import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1800000000000 implements MigrationInterface {
    name = 'Baseline1800000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "billing"."tenant_usage_metrics_periodtype_enum" AS ENUM('daily', 'weekly', 'monthly', 'billing_period')`);
        await queryRunner.query(`CREATE TABLE "billing"."tenant_usage_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "module_id" uuid, "moduleCode" character varying(50), "periodType" "billing"."tenant_usage_metrics_periodtype_enum" NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "metrics" jsonb NOT NULL DEFAULT '{}', "calculatedCost" numeric(12,2), "includedQuantities" jsonb, "overageQuantities" jsonb, "isFinalized" boolean NOT NULL DEFAULT false, "finalizedAt" TIMESTAMP WITH TIME ZONE, "invoiceId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dd8c56c4e71d5eb57c3810a00c9" UNIQUE ("tenant_id", "module_id", "periodStart", "periodType"), CONSTRAINT "PK_5e6101f417f76dcb12d41eb1eea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4dbe830029158ad3f20b653d3b" ON "billing"."tenant_usage_metrics" ("periodType") `);
        await queryRunner.query(`CREATE INDEX "IDX_17e6959d78e4fbd8d9f848fb25" ON "billing"."tenant_usage_metrics" ("periodStart") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e8a92d567203740f6640bf36" ON "billing"."tenant_usage_metrics" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a887174bb6c18e3432139dc82" ON "billing"."tenant_usage_metrics" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "billing"."subscriptions_plan_tier_enum" AS ENUM('starter', 'professional', 'enterprise', 'custom')`);
        await queryRunner.query(`CREATE TYPE "billing"."subscriptions_status_enum" AS ENUM('trial', 'active', 'past_due', 'cancelled', 'suspended', 'expired')`);
        await queryRunner.query(`CREATE TYPE "billing"."subscriptions_billing_cycle_enum" AS ENUM('monthly', 'quarterly', 'semi_annual', 'annual')`);
        await queryRunner.query(`CREATE TABLE "billing"."subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "plan_id" uuid, "plan_tier" "billing"."subscriptions_plan_tier_enum" NOT NULL, "plan_name" character varying NOT NULL, "status" "billing"."subscriptions_status_enum" NOT NULL DEFAULT 'trial', "billing_cycle" "billing"."subscriptions_billing_cycle_enum" NOT NULL, "limits" jsonb NOT NULL, "pricing" jsonb NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE, "current_period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "current_period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "trial_end_date" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" text, "auto_renew" boolean NOT NULL DEFAULT true, "stripe_subscription_id" character varying, "stripe_customer_id" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, "updated_by" character varying, "version" integer NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" character varying, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64a0a41e23d5877dcd27bb919b" ON "billing"."subscriptions" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_383e5a6ce208cdeae91dcdf83c" ON "billing"."subscriptions" ("current_period_end") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "billing"."subscriptions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_subscriptions_tenantId_active" ON "billing"."subscriptions" ("tenant_id") WHERE "isDeleted" = false`);
        await queryRunner.query(`CREATE INDEX "IDX_subscriptions_tenantId" ON "billing"."subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "billing"."subscription_module_items_status_enum" AS ENUM('active', 'suspended', 'cancelled', 'upgraded', 'downgraded')`);
        await queryRunner.query(`CREATE TABLE "billing"."subscription_module_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscription_id" uuid NOT NULL, "module_id" uuid NOT NULL, "module_code" character varying(50) NOT NULL, "module_name" character varying(100) NOT NULL, "quantities" jsonb NOT NULL DEFAULT '{}', "line_items" jsonb NOT NULL DEFAULT '[]', "subtotal" numeric(19,4) NOT NULL, "discount_amount" numeric(19,4) NOT NULL DEFAULT '0', "total" numeric(19,4) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "status" "billing"."subscription_module_items_status_enum" NOT NULL DEFAULT 'active', "activated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "cancelled_at" TIMESTAMP WITH TIME ZONE, "configuration" jsonb, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8002022974aac7bc865b7bf8266" UNIQUE ("subscription_id", "module_id"), CONSTRAINT "PK_ee7d8f7ffd77f67de449709967c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86a74b943baa9a0f02ebbbc461" ON "billing"."subscription_module_items" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_144f8baf910ff8e98dbdaa96b1" ON "billing"."subscription_module_items" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0389c1835f788f85219d57271d" ON "billing"."subscription_module_items" ("subscription_id") `);
        await queryRunner.query(`CREATE TABLE "billing"."stripe_webhook_events" ("event_id" character varying(255) NOT NULL, "event_type" character varying(64) NOT NULL, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "processed_at" TIMESTAMP WITH TIME ZONE, "outcome" character varying(32) NOT NULL DEFAULT 'pending', CONSTRAINT "PK_32411864d51fed6c399f872aec1" PRIMARY KEY ("event_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_stripe_webhook_events_type_received" ON "billing"."stripe_webhook_events" ("event_type", "received_at") `);
        await queryRunner.query(`CREATE TYPE "billing"."scheduled_plan_changes_status_enum" AS ENUM('PENDING', 'APPLIED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "billing"."scheduled_plan_changes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "subscriptionId" uuid NOT NULL, "currentPlanId" uuid NOT NULL, "currentPlanTier" character varying NOT NULL, "newPlanId" uuid NOT NULL, "newPlanTier" character varying NOT NULL, "newPlanName" character varying NOT NULL, "newLimits" jsonb NOT NULL, "newPricing" jsonb NOT NULL, "status" "billing"."scheduled_plan_changes_status_enum" NOT NULL DEFAULT 'PENDING', "effectiveDate" TIMESTAMP WITH TIME ZONE NOT NULL, "reason" text, "scheduledBy" uuid, "appliedAt" TIMESTAMP WITH TIME ZONE, "cancelledAt" TIMESTAMP WITH TIME ZONE, "cancellationReason" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ae77a685a33f775c37eb29dd22d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfdef67ccbf1db49e0c4e19edf" ON "billing"."scheduled_plan_changes" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_774d6143e452e590d9e570f597" ON "billing"."scheduled_plan_changes" ("effectiveDate", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1bb646b48f9bd077f7fb12457" ON "billing"."scheduled_plan_changes" ("tenantId", "status") `);
        await queryRunner.query(`CREATE TYPE "billing"."plans_tier_enum" AS ENUM('starter', 'professional', 'enterprise', 'custom')`);
        await queryRunner.query(`CREATE TYPE "billing"."plans_billing_cycle_enum" AS ENUM('monthly', 'quarterly', 'semi_annual', 'annual')`);
        await queryRunner.query(`CREATE TABLE "billing"."plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "tier" "billing"."plans_tier_enum" NOT NULL, "base_price" numeric(19,4) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "billing_cycle" "billing"."plans_billing_cycle_enum" NOT NULL DEFAULT 'monthly', "limits" jsonb NOT NULL, "pricing" jsonb NOT NULL, "features" jsonb NOT NULL DEFAULT '[]', "is_active" boolean NOT NULL DEFAULT true, "is_public" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, "updated_by" character varying, "version" integer NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" character varying, CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_plan_is_deleted_partial" ON "billing"."plans" ("is_deleted") WHERE "is_deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_253d25dae4c94ee913bc5ec485" ON "billing"."plans" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_7582ab5f01ef13d12f15333400" ON "billing"."plans" ("sort_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_a61665af4701d396e980864dda" ON "billing"."plans" ("is_public") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ac30ab7d4ef974259069a8750" ON "billing"."plans" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f72a20c98ab97e783c5e87ea2" ON "billing"."plans" ("tier") `);
        await queryRunner.query(`CREATE TYPE "billing"."payments_status_enum" AS ENUM('pending', 'processing', 'succeeded', 'failed', 'cancelled', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TYPE "billing"."payments_payment_method_enum" AS ENUM('credit_card', 'debit_card', 'bank_transfer', 'wire_transfer', 'ach', 'sepa', 'paypal', 'check', 'cash', 'other')`);
        await queryRunner.query(`CREATE TABLE "billing"."payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "transaction_id" character varying NOT NULL, "invoice_id" uuid NOT NULL, "amount" numeric(19,4) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "status" "billing"."payments_status_enum" NOT NULL DEFAULT 'pending', "payment_method" "billing"."payments_payment_method_enum" NOT NULL, "payment_method_details" jsonb, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "processed_at" TIMESTAMP WITH TIME ZONE, "failure_reason" text, "stripe_payment_intent_id" character varying, "stripe_charge_id" character varying, "refunds" jsonb, "refunded_amount" numeric(19,4) NOT NULL DEFAULT '0', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, "updated_by" character varying, "version" integer NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" character varying, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_payment_stripe_pi" ON "billing"."payments" ("stripe_payment_intent_id") WHERE "stripe_payment_intent_id" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_00447a5928cae612471fc9ac8a" ON "billing"."payments" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "billing"."payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd69da1be2006cb02d7ed9e439" ON "billing"."payments" ("tenant_id", "payment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_8476231fa87ebf08c399506a87" ON "billing"."payments" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e19270a4fc6a6a300a0e6c738b" ON "billing"."payments" ("tenant_id", "transaction_id") `);
        await queryRunner.query(`CREATE TYPE "billing"."invoices_status_enum" AS ENUM('draft', 'pending', 'sent', 'paid', 'partially_paid', 'overdue', 'void', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "billing"."invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "invoice_number" character varying NOT NULL, "subscription_id" uuid, "status" "billing"."invoices_status_enum" NOT NULL DEFAULT 'draft', "billing_address" jsonb NOT NULL, "line_items" jsonb NOT NULL, "subtotal" numeric(19,4) NOT NULL, "tax" jsonb, "discount" numeric(19,4), "discount_code" character varying, "total" numeric(19,4) NOT NULL, "amount_paid" numeric(19,4) NOT NULL DEFAULT '0', "amount_due" numeric(19,4) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "issue_date" TIMESTAMP WITH TIME ZONE NOT NULL, "due_date" TIMESTAMP WITH TIME ZONE NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "period_start" date NOT NULL, "period_end" date NOT NULL, "notes" text, "stripe_invoice_id" character varying, "pdf_url" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying, "updated_by" character varying, "version" integer NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" character varying, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5c62d838c7338407f3cc562f6" ON "billing"."invoices" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5152c0aa0f851d9b95972b442e" ON "billing"."invoices" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_344c231fafffe51efbd3f17e6d" ON "billing"."invoices" ("tenant_id", "due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7c70191c624dc41d7cbafdc10" ON "billing"."invoices" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2d3ced63b2eb8ae2407b1d3493" ON "billing"."invoices" ("tenant_id", "invoice_number") `);
        await queryRunner.query(`CREATE TABLE "billing"."usage_aggregations" ("id" character varying(255) NOT NULL, "tenant_id" uuid NOT NULL, "period" character varying(20) NOT NULL, "periodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "periodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "meterType" character varying(50) NOT NULL, "dimension" character varying(20), "dimensionValue" character varying(255), "totalUsage" numeric(20,6) NOT NULL DEFAULT '0', "peakUsage" numeric(20,6) NOT NULL DEFAULT '0', "averageUsage" numeric(20,6) NOT NULL DEFAULT '0', "minUsage" numeric(20,6), "maxUsage" numeric(20,6) NOT NULL DEFAULT '0', "eventCount" integer NOT NULL DEFAULT '0', "unit" character varying(50) NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4ffc3a16e83c9d8c0777cb9f4a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3974211db761be071c6467a5be" ON "billing"."usage_aggregations" ("tenant_id", "meterType") `);
        await queryRunner.query(`CREATE INDEX "IDX_d542485f824fb8d672779d0835" ON "billing"."usage_aggregations" ("tenant_id", "period", "periodStart") `);
        await queryRunner.query(`CREATE TABLE "billing"."usage_hourly_data" ("id" character varying(100) NOT NULL, "tenant_id" uuid NOT NULL, "meterType" character varying(50) NOT NULL, "values" jsonb NOT NULL DEFAULT '[]', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_279017e1832b180069d89b9118b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9cd90d8483125e30b6c401dec" ON "billing"."usage_hourly_data" ("tenant_id", "meterType") `);
        await queryRunner.query(`ALTER TABLE "billing"."subscription_module_items" ADD CONSTRAINT "FK_0389c1835f788f85219d57271dd" FOREIGN KEY ("subscription_id") REFERENCES "billing"."subscriptions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."scheduled_plan_changes" ADD CONSTRAINT "FK_2f2a1c8c2635860a28f058a62d1" FOREIGN KEY ("subscriptionId") REFERENCES "billing"."subscriptions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."scheduled_plan_changes" ADD CONSTRAINT "FK_3fd7d6ccbecdb5a2006c4780f92" FOREIGN KEY ("currentPlanId") REFERENCES "billing"."plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."scheduled_plan_changes" ADD CONSTRAINT "FK_b0eae97fe7daa5872cfd3e303a4" FOREIGN KEY ("newPlanId") REFERENCES "billing"."plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "billing"."invoices"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing"."invoices" ADD CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0" FOREIGN KEY ("subscription_id") REFERENCES "billing"."subscriptions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "billing"."invoices" DROP CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0"`);
        await queryRunner.query(`ALTER TABLE "billing"."payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "billing"."scheduled_plan_changes" DROP CONSTRAINT "FK_b0eae97fe7daa5872cfd3e303a4"`);
        await queryRunner.query(`ALTER TABLE "billing"."scheduled_plan_changes" DROP CONSTRAINT "FK_3fd7d6ccbecdb5a2006c4780f92"`);
        await queryRunner.query(`ALTER TABLE "billing"."scheduled_plan_changes" DROP CONSTRAINT "FK_2f2a1c8c2635860a28f058a62d1"`);
        await queryRunner.query(`ALTER TABLE "billing"."subscription_module_items" DROP CONSTRAINT "FK_0389c1835f788f85219d57271dd"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_e9cd90d8483125e30b6c401dec"`);
        await queryRunner.query(`DROP TABLE "billing"."usage_hourly_data"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_d542485f824fb8d672779d0835"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_3974211db761be071c6467a5be"`);
        await queryRunner.query(`DROP TABLE "billing"."usage_aggregations"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_2d3ced63b2eb8ae2407b1d3493"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_c7c70191c624dc41d7cbafdc10"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_344c231fafffe51efbd3f17e6d"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_5152c0aa0f851d9b95972b442e"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_b5c62d838c7338407f3cc562f6"`);
        await queryRunner.query(`DROP TABLE "billing"."invoices"`);
        await queryRunner.query(`DROP TYPE "billing"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_e19270a4fc6a6a300a0e6c738b"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_8476231fa87ebf08c399506a87"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_dd69da1be2006cb02d7ed9e439"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_00447a5928cae612471fc9ac8a"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_payment_stripe_pi"`);
        await queryRunner.query(`DROP TABLE "billing"."payments"`);
        await queryRunner.query(`DROP TYPE "billing"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "billing"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_8f72a20c98ab97e783c5e87ea2"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_8ac30ab7d4ef974259069a8750"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_a61665af4701d396e980864dda"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_7582ab5f01ef13d12f15333400"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_253d25dae4c94ee913bc5ec485"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_plan_is_deleted_partial"`);
        await queryRunner.query(`DROP TABLE "billing"."plans"`);
        await queryRunner.query(`DROP TYPE "billing"."plans_billing_cycle_enum"`);
        await queryRunner.query(`DROP TYPE "billing"."plans_tier_enum"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_c1bb646b48f9bd077f7fb12457"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_774d6143e452e590d9e570f597"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_cfdef67ccbf1db49e0c4e19edf"`);
        await queryRunner.query(`DROP TABLE "billing"."scheduled_plan_changes"`);
        await queryRunner.query(`DROP TYPE "billing"."scheduled_plan_changes_status_enum"`);
        await queryRunner.query(`DROP INDEX "billing"."idx_stripe_webhook_events_type_received"`);
        await queryRunner.query(`DROP TABLE "billing"."stripe_webhook_events"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_0389c1835f788f85219d57271d"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_144f8baf910ff8e98dbdaa96b1"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_86a74b943baa9a0f02ebbbc461"`);
        await queryRunner.query(`DROP TABLE "billing"."subscription_module_items"`);
        await queryRunner.query(`DROP TYPE "billing"."subscription_module_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_subscriptions_tenantId"`);
        await queryRunner.query(`DROP INDEX "billing"."UQ_subscriptions_tenantId_active"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_383e5a6ce208cdeae91dcdf83c"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_64a0a41e23d5877dcd27bb919b"`);
        await queryRunner.query(`DROP TABLE "billing"."subscriptions"`);
        await queryRunner.query(`DROP TYPE "billing"."subscriptions_billing_cycle_enum"`);
        await queryRunner.query(`DROP TYPE "billing"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "billing"."subscriptions_plan_tier_enum"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_9a887174bb6c18e3432139dc82"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_99e8a92d567203740f6640bf36"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_17e6959d78e4fbd8d9f848fb25"`);
        await queryRunner.query(`DROP INDEX "billing"."IDX_4dbe830029158ad3f20b653d3b"`);
        await queryRunner.query(`DROP TABLE "billing"."tenant_usage_metrics"`);
        await queryRunner.query(`DROP TYPE "billing"."tenant_usage_metrics_periodtype_enum"`);
    }

}
