-- GENERATED by tools/scripts/database/generate-database-verification-sql.ts
-- Source of truth: platform/libs/service-catalog/src/topology.ts
-- Regenerate: npx ts-node --project tools/gates/tsconfig.json tools/scripts/database/generate-database-verification-sql.ts generate
-- This collector must run inside a REPEATABLE READ, READ ONLY transaction.

SET LOCAL TIME ZONE 'UTC';
SET LOCAL DateStyle = 'ISO, YMD';
SET LOCAL extra_float_digits = 3;

DO $database_verification$
DECLARE
  canonical_schemas constant text[] := ARRAY['auth', 'farm', 'sensor', 'hr', 'messaging', 'hydroponics', 'alert', 'ai', 'billing', 'notification', 'admin', 'config', 'observability', 'event_store', 'gateway', 'shared', 'compliance']::text[];
  source_schemas constant text[] := ARRAY['auth', 'farm', 'sensor', 'hr', 'messaging', 'hydroponics', 'alert', 'ai', 'billing', 'notification', 'admin', 'config', 'observability', 'event_store']::text[];
  tenant_aware_schemas constant text[] := ARRAY['farm', 'sensor', 'hr', 'messaging', 'hydroponics', 'alert', 'ai']::text[];
  required_schema text;
  source_schema text;
  tenant_schema text;
  malformed_tenant_schemas text;
  tenant_registry_mapping_drift text;
  tenant_registry_collisions text;
  tenant_registry_namespace_drift text;
  release_row record;
  actual_timestamp text;
  actual_name text;
  expected_timestamp text;
  expected_name text;
  ledger_table text;
  sentinel record;
  sentinel_count bigint;
  sentinel_checksum text;
  source_ordinal integer;
  tenant_schema_names jsonb := '[]'::jsonb;
  schema_heads jsonb := '[]'::jsonb;
  tenant_heads jsonb := '[]'::jsonb;
  sentinel_proofs jsonb := '[]'::jsonb;
  verification_payload jsonb;
BEGIN
  FOREACH required_schema IN ARRAY canonical_schemas LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = required_schema) THEN
      RAISE EXCEPTION 'Required schema % is missing from the restored database', required_schema;
    END IF;
  END LOOP;

  IF to_regclass('platform.release_ledger') IS NULL THEN
    RAISE EXCEPTION 'Required relation platform.release_ledger is missing from the restored database';
  END IF;

  SELECT string_agg(nspname, ', ' ORDER BY nspname)
    INTO malformed_tenant_schemas
    FROM pg_namespace
   WHERE nspname LIKE 'tenant\_%' ESCAPE '\'
     AND nspname !~ '^tenant_[a-f0-9]{16}$';
  IF malformed_tenant_schemas IS NOT NULL THEN
    RAISE EXCEPTION 'Malformed tenant schema name(s): %', malformed_tenant_schemas;
  END IF;

  IF to_regclass('admin.tenant_schemas') IS NULL THEN
    RAISE EXCEPTION 'Required tenant schema registry admin.tenant_schemas is missing';
  END IF;
  IF to_regclass('auth.tenants') IS NULL THEN
    RAISE EXCEPTION 'Required tenant owner registry auth.tenants is missing';
  END IF;

  SELECT string_agg(
           format('%s->%s', ts."tenantId", ts."schemaName"),
           ', ' ORDER BY ts."tenantId"::text, ts."schemaName"
         )
    INTO tenant_registry_mapping_drift
    FROM admin.tenant_schemas ts
    LEFT JOIN auth.tenants tenant ON tenant.id = ts."tenantId"
   WHERE COALESCE(ts.status, 'active') <> 'deleted'
     AND (
       tenant.id IS NULL
       OR ts."schemaName" !~ '^tenant_[a-f0-9]{16}$'
       OR ts."schemaName" <>
          'tenant_' || left(replace(lower(ts."tenantId"::text), '-', ''), 16)
     );
  IF tenant_registry_mapping_drift IS NOT NULL THEN
    RAISE EXCEPTION
      'Tenant schema registry mapping disagrees with canonical tenant identity: %',
      tenant_registry_mapping_drift;
  END IF;

  SELECT string_agg(schema_name, ', ' ORDER BY schema_name)
    INTO tenant_registry_collisions
    FROM (
      SELECT ts."schemaName" AS schema_name
        FROM admin.tenant_schemas ts
       WHERE COALESCE(ts.status, 'active') <> 'deleted'
       GROUP BY ts."schemaName"
      HAVING count(DISTINCT ts."tenantId") > 1
    ) AS collisions;
  IF tenant_registry_collisions IS NOT NULL THEN
    RAISE EXCEPTION
      'Tenant schema registry has multiple owners for namespace(s): %',
      tenant_registry_collisions;
  END IF;

  WITH registered AS (
    SELECT DISTINCT ts."schemaName" AS schema_name
      FROM admin.tenant_schemas ts
      JOIN auth.tenants tenant ON tenant.id = ts."tenantId"
     WHERE COALESCE(ts.status, 'active') <> 'deleted'
  ),
  physical AS (
    SELECT nspname AS schema_name
      FROM pg_namespace
     WHERE nspname ~ '^tenant_[a-f0-9]{16}$'
  ),
  namespace_drift AS (
    SELECT 'missing:' || registered.schema_name AS detail
      FROM registered
     WHERE NOT EXISTS (
       SELECT 1 FROM physical WHERE physical.schema_name = registered.schema_name
     )
    UNION ALL
    SELECT 'untracked:' || physical.schema_name AS detail
      FROM physical
     WHERE NOT EXISTS (
       SELECT 1 FROM registered WHERE registered.schema_name = physical.schema_name
     )
  )
  SELECT string_agg(detail, ', ' ORDER BY detail)
    INTO tenant_registry_namespace_drift
    FROM namespace_drift;
  IF tenant_registry_namespace_drift IS NOT NULL THEN
    RAISE EXCEPTION
      'Tenant schema registry and physical namespace sets differ: %',
      tenant_registry_namespace_drift;
  END IF;

  FOR tenant_schema IN
    SELECT nspname
      FROM pg_namespace
     WHERE nspname ~ '^tenant_[a-f0-9]{16}$'
     ORDER BY nspname
  LOOP
    tenant_schema_names := tenant_schema_names || jsonb_build_array(tenant_schema);
  END LOOP;

  SELECT release_id, git_sha, expected_heads, tenant_fanout
    INTO release_row
    FROM platform.release_ledger
   WHERE status IN (
     'db_complete', 'apps_restarting', 'promoted', 'failed',
     'rollback_attempted', 'rollback_verified', 'rollback_failed', 'rolled_back'
   )
     AND expected_heads ? 'schemas'
   ORDER BY updated_at DESC, started_at DESC
   LIMIT 1;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'No DB-complete platform.release_ledger row carries migration heads';
  END IF;
  IF NOT (release_row.expected_heads ? 'tenants') THEN
    RAISE EXCEPTION
      'Release % omits the tenant migration head contract',
      release_row.release_id;
  END IF;

  FOR source_ordinal IN 1..array_length(source_schemas, 1) LOOP
    source_schema := source_schemas[source_ordinal];
    IF to_regclass(format('%I.migrations', source_schema)) IS NULL THEN
      RAISE EXCEPTION 'Source migration ledger %.migrations is missing', source_schema;
    END IF;

    EXECUTE format(
      'SELECT "timestamp"::text, name FROM %I.migrations ORDER BY "timestamp" DESC, id DESC LIMIT 1',
      source_schema
    ) INTO actual_timestamp, actual_name;
    IF actual_timestamp IS NULL OR actual_name IS NULL THEN
      RAISE EXCEPTION 'Source migration ledger %.migrations is empty', source_schema;
    END IF;

    expected_timestamp := release_row.expected_heads #>> ARRAY['schemas', source_schema, 'timestamp'];
    expected_name := release_row.expected_heads #>> ARRAY['schemas', source_schema, 'name'];
    IF expected_timestamp IS NULL OR expected_name IS NULL THEN
      RAISE EXCEPTION 'Release % declares no source migration head for %', release_row.release_id, source_schema;
    END IF;
    IF expected_timestamp <> actual_timestamp OR expected_name <> actual_name THEN
      RAISE EXCEPTION
        'Source migration head mismatch for %: expected=%@%, actual=%@%',
        source_schema, expected_name, expected_timestamp, actual_name, actual_timestamp;
    END IF;

    schema_heads := schema_heads || jsonb_build_array(
      jsonb_build_object(
        'schema', source_schema,
        'timestamp', actual_timestamp,
        'name', actual_name
      )
    );
  END LOOP;

  FOR tenant_schema IN
    SELECT nspname
      FROM pg_namespace
     WHERE nspname ~ '^tenant_[a-f0-9]{16}$'
     ORDER BY nspname
  LOOP
    FOR source_ordinal IN 1..array_length(tenant_aware_schemas, 1) LOOP
      source_schema := tenant_aware_schemas[source_ordinal];
      ledger_table := 'migrations_' || source_schema;
      IF to_regclass(format('%I.%I', tenant_schema, ledger_table)) IS NULL THEN
        RAISE EXCEPTION 'Tenant migration ledger %.% is missing', tenant_schema, ledger_table;
      END IF;

      EXECUTE format(
        'SELECT "timestamp"::text, name FROM %I.%I ORDER BY "timestamp" DESC, id DESC LIMIT 1',
        tenant_schema,
        ledger_table
      ) INTO actual_timestamp, actual_name;
      IF actual_timestamp IS NULL OR actual_name IS NULL THEN
        RAISE EXCEPTION 'Tenant migration ledger %.% is empty', tenant_schema, ledger_table;
      END IF;

      expected_timestamp := release_row.expected_heads #>> ARRAY[
        'tenants', tenant_schema, source_schema, 'timestamp'
      ];
      expected_name := release_row.expected_heads #>> ARRAY[
        'tenants', tenant_schema, source_schema, 'name'
      ];
      IF expected_timestamp IS NULL OR expected_name IS NULL THEN
        expected_timestamp := release_row.expected_heads #>> ARRAY[
          'schemas', source_schema, 'timestamp'
        ];
        expected_name := release_row.expected_heads #>> ARRAY[
          'schemas', source_schema, 'name'
        ];
      ELSIF release_row.tenant_fanout #> ARRAY[
        source_schema, 'tenants', tenant_schema
      ] IS NULL THEN
        RAISE EXCEPTION
          'Release % declares no fan-out evidence for tenant % source %',
          release_row.release_id, tenant_schema, source_schema;
      END IF;

      IF expected_timestamp IS NULL OR expected_name IS NULL THEN
        RAISE EXCEPTION
          'Release % declares no tenant or source migration head for tenant % source %',
          release_row.release_id, tenant_schema, source_schema;
      END IF;
      IF expected_timestamp <> actual_timestamp OR expected_name <> actual_name THEN
        RAISE EXCEPTION
          'Tenant migration head mismatch for % source %: expected=%@%, actual=%@%',
          tenant_schema, source_schema, expected_name, expected_timestamp, actual_name, actual_timestamp;
      END IF;

      tenant_heads := tenant_heads || jsonb_build_array(
        jsonb_build_object(
          'tenant_schema', tenant_schema,
          'source_schema', source_schema,
          'timestamp', actual_timestamp,
          'name', actual_name
        )
      );
    END LOOP;
  END LOOP;

  FOR sentinel IN
    SELECT * FROM (VALUES
        (1, 'auth', 'tenants'),
        (2, 'auth', 'users'),
        (3, 'billing', 'subscriptions')
    ) AS global_sentinels(ordinal, schema_name, table_name)
    ORDER BY ordinal
  LOOP
    IF to_regclass(format('%I.%I', sentinel.schema_name, sentinel.table_name)) IS NULL THEN
      RAISE EXCEPTION
        'Global sentinel relation %.% is missing', sentinel.schema_name, sentinel.table_name;
    END IF;
    EXECUTE format(
      'SELECT COUNT(*)::bigint, COALESCE(md5(string_agg(row_hash, '''' ORDER BY row_hash)), md5('''')) FROM (SELECT md5(to_jsonb(source_row)::text) AS row_hash FROM %I.%I AS source_row) AS hashed_rows',
      sentinel.schema_name,
      sentinel.table_name
    ) INTO sentinel_count, sentinel_checksum;
    sentinel_proofs := sentinel_proofs || jsonb_build_array(
      jsonb_build_object(
        'scope', 'global',
        'schema', sentinel.schema_name,
        'table', sentinel.table_name,
        'row_count', sentinel_count,
        'checksum', sentinel_checksum
      )
    );
  END LOOP;

  FOR tenant_schema IN
    SELECT nspname
      FROM pg_namespace
     WHERE nspname ~ '^tenant_[a-f0-9]{16}$'
     ORDER BY nspname
  LOOP
    FOR sentinel IN
      SELECT * FROM (VALUES
          (1, 'farm', 'farms'),
          (2, 'sensor', 'sensors'),
          (3, 'hr', 'employees'),
          (4, 'messaging', 'channels'),
          (5, 'hydroponics', 'hydroponics_config'),
          (6, 'alert', 'alert_rules'),
          (7, 'ai', 'agent_conversations')
      ) AS tenant_sentinels(ordinal, source_schema, table_name)
      ORDER BY ordinal
    LOOP
      IF to_regclass(format('%I.%I', tenant_schema, sentinel.table_name)) IS NULL THEN
        RAISE EXCEPTION
          'Tenant sentinel relation %.% is missing for source %',
          tenant_schema, sentinel.table_name, sentinel.source_schema;
      END IF;
      EXECUTE format(
        'SELECT COUNT(*)::bigint, COALESCE(md5(string_agg(row_hash, '''' ORDER BY row_hash)), md5('''')) FROM (SELECT md5(to_jsonb(source_row)::text) AS row_hash FROM %I.%I AS source_row) AS hashed_rows',
        tenant_schema,
        sentinel.table_name
      ) INTO sentinel_count, sentinel_checksum;
      sentinel_proofs := sentinel_proofs || jsonb_build_array(
        jsonb_build_object(
          'scope', 'tenant',
          'schema', tenant_schema,
          'table', sentinel.table_name,
          'row_count', sentinel_count,
          'checksum', sentinel_checksum
        )
      );
    END LOOP;
  END LOOP;

  verification_payload := jsonb_build_object(
    'contract_version', 1,
    'canonical_schemas', to_jsonb(canonical_schemas),
    'tenant_schemas', tenant_schema_names,
    'release', jsonb_build_object(
      'release_id', release_row.release_id,
      'git_sha', release_row.git_sha
    ),
    'migration_heads', jsonb_build_object(
      'schemas', schema_heads,
      'tenants', tenant_heads
    ),
    'sentinels', sentinel_proofs
  );
  PERFORM set_config(
    'aqua.restore_verification_payload',
    verification_payload::text,
    true
  );
END
$database_verification$;

SELECT current_setting('aqua.restore_verification_payload', false);
