/**
 * Task Management Types
 */

export type TaskCategory =
  | 'FEEDING'
  | 'WATER_QUALITY'
  | 'HEALTH_CHECK'
  | 'EQUIPMENT_MAINTENANCE'
  | 'STOCK_MANAGEMENT'
  | 'CLEANING'
  | 'REGULATORY'
  | 'HARVEST'
  | 'ENVIRONMENTAL'
  | 'SAFETY'
  | 'GENERAL';

export type TaskPriority = 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW';

export type TaskStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'OVERDUE' | 'CANCELLED';

export type RecurrenceFrequency = 'HOURLY' | 'DAILY' | 'WEEKLY' | 'BIWEEKLY' | 'MONTHLY' | 'CUSTOM';

export type AutoRuleTrigger =
  | 'STOCK_LOW'
  | 'EXPIRY_NEAR'
  | 'MAINTENANCE_DUE'
  | 'SCHEDULE'
  | 'LICENSE_EXPIRY'
  | 'WATER_PARAM_ALERT';

export interface ChecklistItem {
  id: string;
  text: string;
  isCompleted: boolean;
  completedAt?: string;
}

export interface TaskNote {
  id: string;
  text: string;
  createdBy: string;
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  status: TaskStatus;
  assignedTo: string;
  assignedToName: string;
  dueDate: string;
  dueTime?: string;
  createdAt: string;
  completedAt?: string;
  completedBy?: string;
  location?: string;
  estimatedMinutes?: number;
  checklistItems: ChecklistItem[];
  notes: TaskNote[];
  tags: string[];
  isRecurring: boolean;
  recurringTemplateId?: string;
  isAutoGenerated: boolean;
}

export interface RecurringTemplate {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  frequency: RecurrenceFrequency;
  frequencyDetail?: string;
  assignedTo: string;
  assignedToName: string;
  location?: string;
  estimatedMinutes?: number;
  checklistItems: ChecklistItem[];
  isActive: boolean;
  lastGenerated?: string;
  nextGeneration?: string;
  tags: string[];
}

export interface AutoRule {
  id: string;
  name: string;
  description: string;
  trigger: AutoRuleTrigger;
  triggerCondition: string;
  taskTitle: string;
  taskDescription: string;
  taskCategory: TaskCategory;
  taskPriority: TaskPriority;
  assignTo?: string;
  isActive: boolean;
  lastTriggered?: string;
  triggerCount: number;
}

export interface TaskStats {
  totalToday: number;
  completedToday: number;
  overdueCount: number;
  upcomingCount: number;
  completionRate: number;
  avgCompletionMinutes: number;
}

// Category display config
export const CATEGORY_CONFIG: Record<TaskCategory, { label: string; color: string; bg: string }> = {
  FEEDING: { label: 'Yemleme', color: 'text-orange-800', bg: 'bg-orange-100' },
  WATER_QUALITY: { label: 'Su Kalitesi', color: 'text-blue-800', bg: 'bg-blue-100' },
  HEALTH_CHECK: { label: 'Health', color: 'text-red-800', bg: 'bg-red-100' },
  EQUIPMENT_MAINTENANCE: { label: 'Equipment Maintenance', color: 'text-gray-800', bg: 'bg-gray-100' },
  STOCK_MANAGEMENT: { label: 'Stok', color: 'text-purple-800', bg: 'bg-purple-100' },
  CLEANING: { label: 'Temizlik', color: 'text-cyan-800', bg: 'bg-cyan-100' },
  REGULATORY: { label: 'Mevzuat', color: 'text-indigo-800', bg: 'bg-indigo-100' },
  HARVEST: { label: 'Hasat', color: 'text-green-800', bg: 'bg-green-100' },
  ENVIRONMENTAL: { label: 'Environmental', color: 'text-emerald-800', bg: 'bg-emerald-100' },
  SAFETY: { label: 'Safety', color: 'text-yellow-800', bg: 'bg-yellow-100' },
  GENERAL: { label: 'Genel', color: 'text-slate-800', bg: 'bg-slate-100' },
};

export const PRIORITY_CONFIG: Record<TaskPriority, { label: string; color: string; bg: string }> = {
  URGENT: { label: 'Acil', color: 'text-red-800', bg: 'bg-red-100' },
  HIGH: { label: 'High', color: 'text-orange-800', bg: 'bg-orange-100' },
  MEDIUM: { label: 'Orta', color: 'text-blue-800', bg: 'bg-blue-100' },
  LOW: { label: 'Low', color: 'text-gray-800', bg: 'bg-gray-100' },
};

export const STATUS_CONFIG: Record<TaskStatus, { label: string; color: string; bg: string }> = {
  PENDING: { label: 'Bekliyor', color: 'text-yellow-800', bg: 'bg-yellow-100' },
  IN_PROGRESS: { label: 'Devam Ediyor', color: 'text-blue-800', bg: 'bg-blue-100' },
  COMPLETED: { label: 'Completed', color: 'text-green-800', bg: 'bg-green-100' },
  OVERDUE: { label: 'Overdue', color: 'text-red-800', bg: 'bg-red-100' },
  CANCELLED: { label: 'Cancelled', color: 'text-gray-800', bg: 'bg-gray-100' },
};

export const FREQUENCY_CONFIG: Record<RecurrenceFrequency, { label: string; color: string; bg: string }> = {
  HOURLY: { label: 'Saatlik', color: 'text-purple-800', bg: 'bg-purple-100' },
  DAILY: { label: 'Daily', color: 'text-blue-800', bg: 'bg-blue-100' },
  WEEKLY: { label: 'Weekly', color: 'text-green-800', bg: 'bg-green-100' },
  BIWEEKLY: { label: '2 Haftada Bir', color: 'text-teal-800', bg: 'bg-teal-100' },
  MONTHLY: { label: 'Monthly', color: 'text-orange-800', bg: 'bg-orange-100' },
  CUSTOM: { label: 'Custom', color: 'text-gray-800', bg: 'bg-gray-100' },
};

export const TRIGGER_CONFIG: Record<AutoRuleTrigger, { label: string; color: string; bg: string }> = {
  STOCK_LOW: { label: 'Stock Low', color: 'text-red-800', bg: 'bg-red-100' },
  EXPIRY_NEAR: { label: 'Expiry Near', color: 'text-orange-800', bg: 'bg-orange-100' },
  MAINTENANCE_DUE: { label: 'Maintenance Due', color: 'text-blue-800', bg: 'bg-blue-100' },
  SCHEDULE: { label: 'Zamanlama', color: 'text-green-800', bg: 'bg-green-100' },
  LICENSE_EXPIRY: { label: 'License Expiry', color: 'text-purple-800', bg: 'bg-purple-100' },
  WATER_PARAM_ALERT: { label: 'Water Parameter Alert', color: 'text-cyan-800', bg: 'bg-cyan-100' },
};
