/**
 * Task Management Types
 */

export type TaskCategory =
  | 'FEEDING'
  | 'WATER_QUALITY'
  | 'HEALTH_CHECK'
  | 'EQUIPMENT_MAINTENANCE'
  | 'STOCK_MANAGEMENT'
  | 'CLEANING'
  | 'REGULATORY'
  | 'HARVEST'
  | 'ENVIRONMENTAL'
  | 'SAFETY'
  | 'GENERAL';

export type TaskPriority = 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW';

export type TaskStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'OVERDUE' | 'CANCELLED';

export type RecurrenceFrequency = 'HOURLY' | 'DAILY' | 'WEEKLY' | 'BIWEEKLY' | 'MONTHLY' | 'CUSTOM';

export type AutoRuleTrigger =
  | 'STOCK_LOW'
  | 'EXPIRY_NEAR'
  | 'MAINTENANCE_DUE'
  | 'SCHEDULE'
  | 'LICENSE_EXPIRY'
  | 'WATER_PARAM_ALERT';

/** Mirrors the farm-service `TaskChecklistItem` object type (FARM-HIGH-320). */
export interface ChecklistItem {
  id: string;
  text: string;
  isCompleted: boolean;
  completedAt?: string | null;
  completedBy?: string | null;
}

export interface TaskNote {
  id: string;
  text: string;
  createdBy: string;
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  status: TaskStatus;
  assignedTo: string;
  assignedToName: string;
  dueDate: string;
  dueTime?: string;
  createdAt: string;
  completedAt?: string;
  completedBy?: string;
  location?: string;
  estimatedMinutes?: number;
  checklistItems: ChecklistItem[];
  notes: TaskNote[];
  tags: string[];
  isRecurring: boolean;
  recurringTemplateId?: string;
  isAutoGenerated: boolean;
}

export interface RecurringTemplate {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  frequency: RecurrenceFrequency;
  frequencyDetail?: string;
  assignedTo: string;
  assignedToName: string;
  location?: string;
  estimatedMinutes?: number;
  checklistItems: ChecklistItem[];
  isActive: boolean;
  lastGenerated?: string;
  nextGeneration?: string;
  tags: string[];
}

export interface AutoRule {
  id: string;
  name: string;
  description: string;
  trigger: AutoRuleTrigger;
  triggerCondition: string;
  taskTitle: string;
  taskDescription: string;
  taskCategory: TaskCategory;
  taskPriority: TaskPriority;
  assignTo?: string;
  isActive: boolean;
  lastTriggered?: string;
  triggerCount: number;
}

export interface TaskStats {
  totalToday: number;
  completedToday: number;
  overdueCount: number;
  upcomingCount: number;
  completionRate: number;
  avgCompletionMinutes: number;
}

// Category display config
export const CATEGORY_CONFIG: Record<TaskCategory, { label: string; color: string; bg: string }> = {
  FEEDING: {
    label: 'Yemleme',
    color: 'text-accent-800 dark:text-accent-200',
    bg: 'bg-accent-100 dark:bg-accent-900/40',
  },
  WATER_QUALITY: {
    label: 'Su Kalitesi',
    color: 'text-info-800 dark:text-info-200',
    bg: 'bg-info-100 dark:bg-info-900/40',
  },
  HEALTH_CHECK: {
    label: 'Sağlık',
    color: 'text-error-800 dark:text-error-200',
    bg: 'bg-error-100 dark:bg-error-900/40',
  },
  EQUIPMENT_MAINTENANCE: {
    label: 'Ekipman Bakım',
    color: 'text-gray-800 dark:text-gray-200',
    bg: 'bg-gray-100 dark:bg-gray-800',
  },
  STOCK_MANAGEMENT: {
    label: 'Stok',
    color: 'text-accent-800 dark:text-accent-200',
    bg: 'bg-accent-100 dark:bg-accent-900/40',
  },
  CLEANING: {
    label: 'Temizlik',
    color: 'text-info-800 dark:text-info-200',
    bg: 'bg-info-100 dark:bg-info-900/40',
  },
  REGULATORY: {
    label: 'Mevzuat',
    color: 'text-primary-800 dark:text-primary-200',
    bg: 'bg-primary-100 dark:bg-primary-900/40',
  },
  HARVEST: {
    label: 'Hasat',
    color: 'text-success-800 dark:text-success-200',
    bg: 'bg-success-100 dark:bg-success-900/40',
  },
  ENVIRONMENTAL: {
    label: 'Çevre',
    color: 'text-success-800 dark:text-success-200',
    bg: 'bg-success-100 dark:bg-success-900/40',
  },
  SAFETY: {
    label: 'Güvenlik',
    color: 'text-warning-800 dark:text-warning-200',
    bg: 'bg-warning-100 dark:bg-warning-900/40',
  },
  GENERAL: { label: 'Genel', color: 'text-slate-800', bg: 'bg-slate-100' },
};

export const PRIORITY_CONFIG: Record<TaskPriority, { label: string; color: string; bg: string }> = {
  URGENT: {
    label: 'Acil',
    color: 'text-error-800 dark:text-error-200',
    bg: 'bg-error-100 dark:bg-error-900/40',
  },
  HIGH: {
    label: 'Yüksek',
    color: 'text-accent-800 dark:text-accent-200',
    bg: 'bg-accent-100 dark:bg-accent-900/40',
  },
  MEDIUM: {
    label: 'Orta',
    color: 'text-info-800 dark:text-info-200',
    bg: 'bg-info-100 dark:bg-info-900/40',
  },
  LOW: {
    label: 'Düşük',
    color: 'text-gray-800 dark:text-gray-200',
    bg: 'bg-gray-100 dark:bg-gray-800',
  },
};

export const STATUS_CONFIG: Record<TaskStatus, { label: string; color: string; bg: string }> = {
  PENDING: {
    label: 'Bekliyor',
    color: 'text-warning-800 dark:text-warning-200',
    bg: 'bg-warning-100 dark:bg-warning-900/40',
  },
  IN_PROGRESS: {
    label: 'Devam Ediyor',
    color: 'text-info-800 dark:text-info-200',
    bg: 'bg-info-100 dark:bg-info-900/40',
  },
  COMPLETED: {
    label: 'Tamamlandı',
    color: 'text-success-800 dark:text-success-200',
    bg: 'bg-success-100 dark:bg-success-900/40',
  },
  OVERDUE: {
    label: 'Gecikmiş',
    color: 'text-error-800 dark:text-error-200',
    bg: 'bg-error-100 dark:bg-error-900/40',
  },
  CANCELLED: {
    label: 'İptal',
    color: 'text-gray-800 dark:text-gray-200',
    bg: 'bg-gray-100 dark:bg-gray-800',
  },
};

export const FREQUENCY_CONFIG: Record<
  RecurrenceFrequency,
  { label: string; color: string; bg: string }
> = {
  HOURLY: {
    label: 'Saatlik',
    color: 'text-accent-800 dark:text-accent-200',
    bg: 'bg-accent-100 dark:bg-accent-900/40',
  },
  DAILY: {
    label: 'Günlük',
    color: 'text-info-800 dark:text-info-200',
    bg: 'bg-info-100 dark:bg-info-900/40',
  },
  WEEKLY: {
    label: 'Haftalık',
    color: 'text-success-800 dark:text-success-200',
    bg: 'bg-success-100 dark:bg-success-900/40',
  },
  BIWEEKLY: {
    label: '2 Haftada Bir',
    color: 'text-info-800 dark:text-info-200',
    bg: 'bg-info-100 dark:bg-info-900/40',
  },
  MONTHLY: {
    label: 'Aylık',
    color: 'text-accent-800 dark:text-accent-200',
    bg: 'bg-accent-100 dark:bg-accent-900/40',
  },
  CUSTOM: {
    label: 'Özel',
    color: 'text-gray-800 dark:text-gray-200',
    bg: 'bg-gray-100 dark:bg-gray-800',
  },
};

export const TRIGGER_CONFIG: Record<AutoRuleTrigger, { label: string; color: string; bg: string }> =
  {
    STOCK_LOW: {
      label: 'Stok Düşük',
      color: 'text-error-800 dark:text-error-200',
      bg: 'bg-error-100 dark:bg-error-900/40',
    },
    EXPIRY_NEAR: {
      label: 'Son Kullanma Yakın',
      color: 'text-accent-800 dark:text-accent-200',
      bg: 'bg-accent-100 dark:bg-accent-900/40',
    },
    MAINTENANCE_DUE: {
      label: 'Bakım Zamanı',
      color: 'text-info-800 dark:text-info-200',
      bg: 'bg-info-100 dark:bg-info-900/40',
    },
    SCHEDULE: {
      label: 'Zamanlama',
      color: 'text-success-800 dark:text-success-200',
      bg: 'bg-success-100 dark:bg-success-900/40',
    },
    LICENSE_EXPIRY: {
      label: 'Lisans Süresi',
      color: 'text-accent-800 dark:text-accent-200',
      bg: 'bg-accent-100 dark:bg-accent-900/40',
    },
    WATER_PARAM_ALERT: {
      label: 'Su Parametre Uyarısı',
      color: 'text-info-800 dark:text-info-200',
      bg: 'bg-info-100 dark:bg-info-900/40',
    },
  };
