-- ============================================================================
-- DEPRECATED — This file is intentionally empty.
--
-- All schema creation and role provisioning logic has been moved to
-- 00-init-schemas.sh which reads passwords from environment variables
-- instead of using hardcoded CHANGE_ME_* placeholders.
--
-- See: SEC-015 in 00-init-schemas.sh
--
-- This file is kept (empty) to avoid breaking any tooling that expects it.
-- It is safe to delete.
-- ============================================================================
