#!/usr/bin/env ts-node
/**
 * Seed the finding registry with the Phase-0 audit findings that were
 * raised by the 2026-04-16 v2 audit.
 *
 * HISTORICAL CONTEXT:
 * This script used to write findings.jsonl directly — it computed the
 * hash chain locally and called writeFileSync on the registry. That
 * path bypassed the add-time uniqueness check and (later) schema
 * validation in tools/gates/finding-registry.ts, so two seed runs could
 * introduce 39 duplicate ids with byte-identical content (observed
 * 2026-04-22, cleaned up under AUDIT-CRITICAL-003).
 *
 * As of A.3c in the cold-audit remediation plan, this script routes
 * EVERY historical fixed-id append through `finding-registry
 * add-explicit`. The shared mutation authority enforces active-worktree
 * uniqueness, durable high-water reservation, schema validation, hash
 * chaining, and atomic replacement. Writing here directly would be
 * architecturally unsafe and is no longer done.
 *
 * Usage:
 *   npx ts-node --project tools/gates/tsconfig.json \
 *     tools/scripts/seed-finding-registry.ts [--dry-run]
 *
 * Phase reference: /root/.claude/plans/abstract-brewing-mochi.md#Phase-6
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, existsSync, readFileSync, rmSync } from 'node:fs';
import { resolve, join } from 'node:path';

const REPO_ROOT = resolve(__dirname, '..', '..');
const REGISTRY = resolve(REPO_ROOT, 'docs', 'reviews', '_registry', 'findings.jsonl');
const STUB_DIR = resolve(REPO_ROOT, 'tools', 'scripts', '.tmp-seed-stubs');
const REGISTRY_CLI = resolve(REPO_ROOT, 'tools', 'gates', 'finding-registry.ts');
const CLI_TSCONFIG = resolve(REPO_ROOT, 'tools', 'gates', 'tsconfig.json');

const AUDIT_FILE = 'docs/reviews/orchestrator/2026-04-16-v2-audit.md';
const AUDIT_CYCLE = '2026-04-16-v2-audit';

type Severity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
type State = 'OPEN' | 'IN-PROGRESS' | 'RESOLVED' | 'STALE' | 'BLOCKED';

interface SeedEntry {
  id: string;
  severity: Severity;
  state: State;
  title: string;
  layer: 1 | 2 | 3;
  evidence: string[];
  rule_violated: string;
  owner_agent: string;
  raised_in_cycle: string;
  review_file: string;
  created_at: string;
  closed_at: string | null;
  closing_commits: string[];
  deadline: string | null;
  owner_user: string | null;
  override_of: string | null;
  notes: string;
}

const seedEntries: readonly SeedEntry[] = [
  {
    id: 'P0-CRITICAL-001',
    severity: 'CRITICAL',
    state: 'RESOLVED',
    title:
      'createTenantQueryKey signature inverted in layer-1-react.md (would produce cross-tenant cache bleed via TEACHER output)',
    layer: 1,
    evidence: [
      '.claude/knowledge/layer-1-react.md:36',
      'web/shared-ui/src/utils/tenant-query-keys.ts:39',
    ],
    rule_violated: 'SSoT claim must match real code signature (Layer-1 React anchor)',
    owner_agent: 'orchestrator',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-16T14:00:00Z',
    closed_at: '2026-04-16T18:00:00Z',
    closing_commits: ['32839e24'],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      'First RESOLVED finding via the Phase-6 registry bootstrap. Closing commit 32839e24 landed the tenant-query-key inversion fix AND the Phase 0.1 doc corrections.',
  },
  {
    id: 'P0-HIGH-002',
    severity: 'HIGH',
    state: 'RESOLVED',
    title: 'nats-invariants.spec.ts: cert-is-identity contract + services.yaml↔nats.conf sync',
    layer: 3,
    evidence: ['tests/invariants/nats-invariants.spec.ts:1', 'infrastructure/nats/services.yaml:1'],
    rule_violated: 'ADR-015 NATS cert-is-identity SSoT',
    owner_agent: 'orchestrator',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-16T14:00:00Z',
    closed_at: '2026-04-16T18:00:00Z',
    closing_commits: ['2dd09f99'],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      'Closed by 2dd09f99: adds invariants locking services.yaml as SSoT; nats.conf authorization block regenerated by scripts/nats/generate-nats-conf.py.',
  },
  {
    id: 'P0-HIGH-003',
    severity: 'HIGH',
    state: 'RESOLVED',
    title:
      'schema-invariants.spec.ts: SHARED_SCHEMA_TABLES enforcement + entity @schema() inspection',
    layer: 3,
    evidence: [
      'tests/invariants/schema-invariants.spec.ts:1',
      'libs/backend-common/src/database/schema-drift-validator.service.ts:1',
    ],
    rule_violated: 'ADR-011 schema-ownership-model',
    owner_agent: 'orchestrator',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-16T14:00:00Z',
    closed_at: '2026-04-16T18:00:00Z',
    closing_commits: ['2dd09f99'],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      'Closed by 2dd09f99: SHARED_SCHEMA_TABLES set frozen at the 4 canonical cross-tenant tables; new shared-schema additions require ADR + arbiter sign-off.',
  },
  {
    id: 'P0-CRITICAL-004',
    severity: 'CRITICAL',
    state: 'RESOLVED',
    title:
      'Migration runner factory: DATABASE_MIGRATIONS_RUN=false mandatory in prod; double-run prevention via schema_migrations lookahead',
    layer: 2,
    evidence: [
      'libs/backend-common/src/database/migration-runner.factory.ts:1',
      'apps/farm-service/src/app.module.ts:1',
    ],
    rule_violated: 'ADR-011 migration runner single-ownership contract',
    owner_agent: 'orchestrator',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-16T14:00:00Z',
    closed_at: '2026-04-16T18:00:00Z',
    closing_commits: ['32839e24'],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      "Closed by 32839e24: each service's app.module.ts registers createMigrationRunnerService(schema); TypeOrmModule runs migrations:false. Hard-fails on DATABASE_MIGRATIONS_RUN=true in prod.",
  },
  {
    id: 'P0-HIGH-005',
    severity: 'HIGH',
    state: 'RESOLVED',
    title: 'root-cause-auditor + commit-msg-validator + Closes: trailer contract',
    layer: 3,
    evidence: ['tools/gates/commit-msg-validator.ts:1', '.husky/commit-msg:1'],
    rule_violated:
      'CLAUDE.md Review Finding Traceability (every fix commit must Closes: a finding)',
    owner_agent: 'root-cause-auditor',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-16T14:00:00Z',
    closed_at: '2026-04-16T18:00:00Z',
    closing_commits: ['b907c235'],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      'Closed by b907c235: root-cause-auditor inspects every fix commit for a Closes: trailer and rejects when missing. PRE_PHASE6_SHAS allow-list covers commits that landed before the gate existed.',
  },
  {
    id: 'P0-HIGH-006',
    severity: 'HIGH',
    state: 'RESOLVED',
    title:
      'agents-legacy archival: CATCHER-FOUNDATION agent split + Lane-A routing table correctness',
    layer: 3,
    evidence: [
      '.claude/agents/catcher-foundation.md:1',
      '.claude/shared/orchestrator-routing-table.md:1',
    ],
    rule_violated: 'Agent roster coverage — every top-level repo surface has a matching glob',
    owner_agent: 'orchestrator',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-16T14:00:00Z',
    closed_at: '2026-04-16T18:00:00Z',
    closing_commits: ['f931f935'],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      'Closed by f931f935: agents-legacy archived; orchestrator-routing-table.md now authoritative and invariant-tested.',
  },
  {
    id: 'P0-HIGH-007',
    severity: 'HIGH',
    state: 'OPEN',
    title:
      'Registry seeding pipeline hardening — Phase 6 hash-chain + CLI append + close/sweep lifecycle',
    layer: 3,
    evidence: ['docs/reviews/_registry/findings.jsonl:1', 'tools/gates/finding-registry.ts:1'],
    rule_violated: 'CLAUDE.md Review Finding Traceability (registry is the SSoT for finding state)',
    owner_agent: 'orchestrator',
    raised_in_cycle: AUDIT_CYCLE,
    review_file: AUDIT_FILE,
    created_at: '2026-04-17T00:00:00Z',
    closed_at: null,
    closing_commits: [],
    deadline: null,
    owner_user: null,
    override_of: null,
    notes:
      'Phase 6 of /root/.claude/plans/abstract-brewing-mochi.md — seed + verify + add + close + sweep subcommands + schema + invariant test. This script is the bootstrap; future appends go through the allocator-owned tools/gates/finding-registry.ts add command.',
  },
];

function main(): void {
  const dryRun = process.argv.includes('--dry-run');

  if (existsSync(REGISTRY)) {
    const existing = readFileSync(REGISTRY, 'utf8').trim();
    if (existing.length > 0) {
      console.error(`Registry already seeded (${existing.split('\n').length} entries present).`);
      console.error(`Refusing to overwrite. Delete ${REGISTRY} manually to re-seed.`);
      process.exit(1);
    }
  }

  if (dryRun) {
    console.log('[seed-finding-registry] dry-run — printing the stubs that would be added:');
    for (const entry of seedEntries) {
      console.log(
        `  ${entry.id}  ${entry.severity}  ${entry.state}  ${entry.title.slice(0, 60)}...`,
      );
    }
    return;
  }

  // Create a scratch stubs dir, fan out each entry to a JSON stub
  // file, invoke the governed fixed-id import path, and clean up. The
  // bootstrap fixture owns historical IDs, while normal appends must use
  // the allocator-backed `add <DOMAIN> <stub>` command. The CLI validates
  // schema, enforces uniqueness, and stamps the hash chain — we never
  // touch the JSONL directly.
  mkdirSync(STUB_DIR, { recursive: true });
  try {
    for (const entry of seedEntries) {
      const stubPath = join(STUB_DIR, `${entry.id}.json`);
      writeFileSync(stubPath, `${JSON.stringify(entry)}\n`, 'utf8');
      execFileSync(
        'npx',
        ['ts-node', '--project', CLI_TSCONFIG, REGISTRY_CLI, 'add-explicit', stubPath],
        { cwd: REPO_ROOT, stdio: 'inherit' },
      );
    }
    console.log(
      `[seed-finding-registry] seeded ${seedEntries.length} entries through the CLI; registry chain preserved.`,
    );
  } finally {
    rmSync(STUB_DIR, { recursive: true, force: true });
  }
}

main();
