/**
 * AlarmStorageService
 *
 * Handles persistence of active alarms and alarm chronicle (history).
 * Uses TypeORM DataSource with raw SQL for maximum compatibility with
 * the project's existing database layer (TimescaleDB / PostgreSQL).
 *
 * Tables (auto-created on first use if migrations are applied):
 *   scada_alarms           — live active alarm instances (upsert)
 *   scada_alarm_chronicle  — append-only history log
 *
 * Design principles:
 *   - No circular dependencies: this service knows nothing about the engine.
 *   - All DB calls are wrapped in try/catch with structured logging.
 *   - IDs are UUIDs generated by the caller (AlarmEngineService).
 */

import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';

import type {
  AlarmHistoryFilter,
  AlarmInstance,
} from '../../../../../../web/modules/sensor-module/src/types/scada-runtime.types';
import type { ScadaAlarm, ScadaAlarmChronicle } from '../entities/alarm.entity';

/* ------------------------------------------------------------------ */
/*  Internal row shapes returned by raw SQL                            */
/* ------------------------------------------------------------------ */

interface AlarmRow {
  id: string;
  rule_id: string;
  rule_name: string;
  severity: string;
  status: string;
  message: string;
  group_name: string | null;
  current_value: string;
  threshold: string;
  on_time: string;
  off_time: string | null;
  ack_time: string | null;
  ack_user_id: string | null;
  colors_bg: string | null;
  colors_text: string | null;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                             */
/* ------------------------------------------------------------------ */

function rowToInstance(row: AlarmRow): AlarmInstance {
  return {
    id: row.id,
    ruleId: row.rule_id,
    ruleName: row.rule_name,
    severity: row.severity as AlarmInstance['severity'],
    status: row.status as AlarmInstance['status'],
    message: row.message,
    group: row.group_name ?? undefined,
    currentValue: parseFloat(row.current_value),
    threshold: parseFloat(row.threshold),
    onTime: parseInt(row.on_time, 10),
    offTime: row.off_time != null ? parseInt(row.off_time, 10) : undefined,
    ackTime: row.ack_time != null ? parseInt(row.ack_time, 10) : undefined,
    ackUserId: row.ack_user_id ?? undefined,
    colors:
      row.colors_bg != null && row.colors_text != null
        ? { background: row.colors_bg, text: row.colors_text }
        : undefined,
  };
}

/* ------------------------------------------------------------------ */
/*  Service                                                             */
/* ------------------------------------------------------------------ */

@Injectable()
export class AlarmStorageService implements OnModuleInit {
  private readonly logger = new Logger(AlarmStorageService.name);

  constructor(
    @InjectDataSource()
    private readonly dataSource: DataSource,
  ) {}

  /* ---------------------------------------------------------------- */
  /*  Lifecycle                                                         */
  /* ---------------------------------------------------------------- */

  async onModuleInit(): Promise<void> {
    try {
      await this.ensureTablesExist();
      this.logger.log('AlarmStorageService initialised — tables verified');
    } catch (error) {
      this.logger.error(
        `AlarmStorageService: table initialisation failed — ${(error as Error).message}`,
      );
    }
  }

  /**
   * Idempotent DDL: create tables if they do not exist.
   * Uses CREATE TABLE IF NOT EXISTS so it is safe to call on every startup.
   */
  private async ensureTablesExist(): Promise<void> {
    await this.dataSource.query(`
      CREATE TABLE IF NOT EXISTS scada_alarms (
        id            TEXT        PRIMARY KEY,
        rule_id       TEXT        NOT NULL,
        rule_name     TEXT        NOT NULL,
        severity      TEXT        NOT NULL,
        status        TEXT        NOT NULL,
        message       TEXT        NOT NULL,
        group_name    TEXT,
        current_value DOUBLE PRECISION NOT NULL DEFAULT 0,
        threshold     DOUBLE PRECISION NOT NULL DEFAULT 0,
        on_time       BIGINT      NOT NULL,
        off_time      BIGINT,
        ack_time      BIGINT,
        ack_user_id   TEXT,
        colors_bg     TEXT,
        colors_text   TEXT,
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    await this.dataSource.query(`
      CREATE TABLE IF NOT EXISTS scada_alarm_chronicle (
        id            TEXT        PRIMARY KEY,
        rule_id       TEXT        NOT NULL,
        rule_name     TEXT        NOT NULL,
        severity      TEXT        NOT NULL,
        status        TEXT        NOT NULL,
        message       TEXT        NOT NULL,
        group_name    TEXT,
        current_value DOUBLE PRECISION NOT NULL DEFAULT 0,
        threshold     DOUBLE PRECISION NOT NULL DEFAULT 0,
        on_time       BIGINT      NOT NULL,
        off_time      BIGINT,
        ack_time      BIGINT,
        ack_user_id   TEXT,
        recorded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // Index to speed up queries by severity / group / time range
    await this.dataSource.query(`
      CREATE INDEX IF NOT EXISTS idx_scada_alarm_chronicle_on_time
        ON scada_alarm_chronicle (on_time DESC)
    `);
    await this.dataSource.query(`
      CREATE INDEX IF NOT EXISTS idx_scada_alarm_chronicle_severity
        ON scada_alarm_chronicle (severity)
    `);
  }

  /* ---------------------------------------------------------------- */
  /*  Active alarm CRUD                                                 */
  /* ---------------------------------------------------------------- */

  /**
   * Upsert an active alarm.  On conflict (same id) all mutable columns
   * are updated, preserving the original on_time.
   */
  async saveAlarm(alarm: ScadaAlarm): Promise<void> {
    try {
      await this.dataSource.query(
        `
        INSERT INTO scada_alarms
          (id, rule_id, rule_name, severity, status, message, group_name,
           current_value, threshold, on_time, off_time, ack_time, ack_user_id,
           colors_bg, colors_text, updated_at)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15, NOW())
        ON CONFLICT (id) DO UPDATE SET
          severity      = EXCLUDED.severity,
          status        = EXCLUDED.status,
          message       = EXCLUDED.message,
          current_value = EXCLUDED.current_value,
          off_time      = EXCLUDED.off_time,
          ack_time      = EXCLUDED.ack_time,
          ack_user_id   = EXCLUDED.ack_user_id,
          colors_bg     = EXCLUDED.colors_bg,
          colors_text   = EXCLUDED.colors_text,
          updated_at    = NOW()
        `,
        [
          alarm.id,
          alarm.ruleId,
          alarm.ruleName,
          alarm.severity,
          alarm.status,
          alarm.message,
          alarm.group ?? null,
          alarm.currentValue,
          alarm.threshold,
          alarm.onTime,
          alarm.offTime ?? null,
          alarm.ackTime ?? null,
          alarm.ackUserId ?? null,
          alarm.colors?.background ?? null,
          alarm.colors?.text ?? null,
        ],
      );
    } catch (error) {
      this.logger.error(
        `saveAlarm: failed to upsert alarm id=${alarm.id} — ${(error as Error).message}`,
      );
      throw error;
    }
  }

  /**
   * Delete an active alarm by id (called once the alarm resolves).
   */
  async deleteAlarm(alarmId: string): Promise<void> {
    try {
      await this.dataSource.query(`DELETE FROM scada_alarms WHERE id = $1`, [alarmId]);
    } catch (error) {
      this.logger.error(
        `deleteAlarm: failed to delete id=${alarmId} — ${(error as Error).message}`,
      );
    }
  }

  /**
   * Return all rows from scada_alarms ordered by severity then on_time.
   */
  async getActiveAlarms(): Promise<AlarmInstance[]> {
    try {
      const rows: AlarmRow[] = await this.dataSource.query(`
        SELECT * FROM scada_alarms
        ORDER BY
          CASE severity
            WHEN 'critical' THEN 1
            WHEN 'high'     THEN 2
            WHEN 'warning'  THEN 3
            WHEN 'info'     THEN 4
            ELSE 5
          END,
          on_time ASC
      `);
      return rows.map(rowToInstance);
    } catch (error) {
      this.logger.error(`getActiveAlarms: query failed — ${(error as Error).message}`);
      return [];
    }
  }

  /* ---------------------------------------------------------------- */
  /*  Chronicle (history)                                              */
  /* ---------------------------------------------------------------- */

  /**
   * Append a completed alarm to the chronicle table.
   */
  async saveToChronicle(alarm: ScadaAlarmChronicle): Promise<void> {
    try {
      await this.dataSource.query(
        `
        INSERT INTO scada_alarm_chronicle
          (id, rule_id, rule_name, severity, status, message, group_name,
           current_value, threshold, on_time, off_time, ack_time, ack_user_id)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
        ON CONFLICT (id) DO NOTHING
        `,
        [
          alarm.id,
          alarm.ruleId,
          alarm.ruleName,
          alarm.severity,
          alarm.status,
          alarm.message,
          alarm.group ?? null,
          alarm.currentValue,
          alarm.threshold,
          alarm.onTime,
          alarm.offTime ?? null,
          alarm.ackTime ?? null,
          alarm.ackUserId ?? null,
        ],
      );
    } catch (error) {
      this.logger.error(
        `saveToChronicle: failed for alarm id=${alarm.id} — ${(error as Error).message}`,
      );
      throw error;
    }
  }

  /**
   * Query alarm history with optional filtering, pagination, and text search.
   */
  async getAlarmHistory(filter: AlarmHistoryFilter = {}): Promise<AlarmInstance[]> {
    try {
      const conditions: string[] = [];
      const params: unknown[] = [];
      let idx = 1;

      if (filter.severity && filter.severity.length > 0) {
        conditions.push(`severity = ANY($${idx})`);
        params.push(filter.severity);
        idx++;
      }

      if (filter.group) {
        conditions.push(`group_name = $${idx}`);
        params.push(filter.group);
        idx++;
      }

      if (filter.textSearch) {
        conditions.push(`(message ILIKE $${idx} OR rule_name ILIKE $${idx})`);
        params.push(`%${filter.textSearch}%`);
        idx++;
      }

      if (filter.tagIds && filter.tagIds.length > 0) {
        conditions.push(`rule_id = ANY($${idx})`);
        params.push(filter.tagIds);
        idx++;
      }

      if (filter.from != null) {
        conditions.push(`on_time >= $${idx}`);
        params.push(filter.from);
        idx++;
      }

      if (filter.to != null) {
        conditions.push(`on_time <= $${idx}`);
        params.push(filter.to);
        idx++;
      }

      const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
      const limit = filter.limit ?? 500;
      const offset = filter.offset ?? 0;

      const rows: AlarmRow[] = await this.dataSource.query(
        `
        SELECT
          id, rule_id, rule_name, severity, status, message, group_name,
          current_value, threshold, on_time, off_time, ack_time, ack_user_id,
          NULL AS colors_bg, NULL AS colors_text
        FROM scada_alarm_chronicle
        ${where}
        ORDER BY on_time DESC
        LIMIT $${idx} OFFSET $${idx + 1}
        `,
        [...params, limit, offset],
      );

      return rows.map(rowToInstance);
    } catch (error) {
      this.logger.error(`getAlarmHistory: query failed — ${(error as Error).message}`);
      return [];
    }
  }

  /**
   * Delete chronicle records older than retentionDays.
   * Safe to call from a scheduled job.
   */
  async cleanupHistory(retentionDays: number): Promise<number> {
    try {
      const cutoffMs = Date.now() - retentionDays * 24 * 60 * 60 * 1000;
      // pg-driver convention: DataSource.query() returns [rows, rowCount]
      // where rowCount is the number of affected rows for DML statements.
      const [, affectedRows] = await this.dataSource.query(
        `DELETE FROM scada_alarm_chronicle WHERE on_time < $1`,
        [cutoffMs],
      );
      const deleted: number = typeof affectedRows === 'number' ? affectedRows : 0;
      if (deleted > 0) {
        this.logger.log(
          `cleanupHistory: deleted ${deleted} record(s) older than ${retentionDays} days`,
        );
      }
      return deleted;
    } catch (error) {
      this.logger.error(`cleanupHistory: failed — ${(error as Error).message}`);
      return 0;
    }
  }
}
