/**
 * A signal with no IP does not become an attack (ADMIN-HIGH-012).
 *
 * `login_attempts.ipAddress` was `varchar(45) NOT NULL` and the W5 projection
 * filled it with the literal `'unknown'`. Typing it `inet` made the absence
 * real — and revealed that two detectors read the address straight into a
 * TypeORM `where`:
 *
 *     where: { ipAddress, success: false, createdAt: MoreThan(since) }
 *
 * TypeORM DROPS a `where` key whose value is `undefined`. So the first
 * address-less signal would have counted EVERY failed login in the window, not
 * the ones from one address, and raised a critical "distributed brute force"
 * — or a high-severity `api_abuse` — against nobody.
 *
 * That is worse than a missed detection: it is a page, at 3am, generated by
 * the absence of data.
 */
import {
  ScheduledJobRunner,
  type ScheduledJobExecutor,
} from '@aquaculture/backend-common/scheduling';
import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';

import {
  ApiUsageLog,
  LoginAttempt,
  SecurityEvent,
  SecurityIncident,
  ThreatIntelligence,
} from '../../entities/security.entity';
import { SecurityMonitoringService } from '../security-monitoring.service';

const passThroughScheduledJobs: ScheduledJobExecutor = {
  run: async (_job, body) => {
    await body();
    return 'ran';
  },
};

interface Harness {
  service: SecurityMonitoringService;
  loginAttempts: { count: jest.Mock };
  apiUsage: { count: jest.Mock };
  securityEvents: { create: jest.Mock; save: jest.Mock };
}

async function build(): Promise<Harness> {
  // High enough that any count returned here would breach every threshold —
  // so if a detector runs at all, it raises.
  const loginAttempts = { count: jest.fn().mockResolvedValue(9999) };
  const apiUsage = { count: jest.fn().mockResolvedValue(9999) };
  const securityEvents = {
    create: jest.fn((entity: unknown) => entity),
    save: jest.fn(async (entity: unknown) => entity),
  };

  const module: TestingModule = await Test.createTestingModule({
    providers: [
      SecurityMonitoringService,
      { provide: ScheduledJobRunner, useValue: passThroughScheduledJobs },
      { provide: getRepositoryToken(LoginAttempt), useValue: loginAttempts },
      { provide: getRepositoryToken(ApiUsageLog), useValue: apiUsage },
      { provide: getRepositoryToken(SecurityEvent), useValue: securityEvents },
      { provide: getRepositoryToken(SecurityIncident), useValue: {} },
      { provide: getRepositoryToken(ThreatIntelligence), useValue: {} },
    ],
  }).compile();

  return {
    service: module.get(SecurityMonitoringService),
    loginAttempts,
    apiUsage,
    securityEvents,
  };
}

describe('SecurityMonitoringService with no client address', () => {
  it('does not count every failed login in the window as one address', async () => {
    const { service, loginAttempts } = await build();

    await service.analyzeLoginAttempt({
      email: 'operator@example.com',
      ipAddress: undefined,
      success: false,
    });

    // The by-email count still runs — email is present and is a real key.
    // The by-IP count must not: `where: { ipAddress: undefined }` drops the
    // predicate and counts the whole window.
    const byIp = loginAttempts.count.mock.calls.filter(
      (call) => 'ipAddress' in ((call[0] as { where: Record<string, unknown> }).where ?? {}),
    );
    expect(byIp).toEqual([]);
  });

  it('raises no api_abuse event without an address to attribute it to', async () => {
    const { service, apiUsage, securityEvents } = await build();

    await service.checkApiAbuse({
      ipAddress: undefined,
      endpoint: 'login:203.0.113.7',
      rateLimitExceeded: true,
    });

    expect(apiUsage.count).not.toHaveBeenCalled();
    expect(securityEvents.save).not.toHaveBeenCalled();
  });

  it('still detects abuse when an address IS present', async () => {
    // The guard must not be a blanket early return that disables the detector.
    const { service, apiUsage, securityEvents } = await build();

    await service.checkApiAbuse({
      ipAddress: '203.0.113.7',
      endpoint: 'login:203.0.113.7',
      rateLimitExceeded: true,
    });

    expect(apiUsage.count).toHaveBeenCalledTimes(1);
    expect(securityEvents.save).toHaveBeenCalledTimes(1);
  });
});
