/**
 * Shared tenant-schema helpers for real Postgres e2e tests.
 *
 * WHY: Tenant isolation tests must assert physical schema placement without
 * duplicating ad-hoc DDL in every spec. These helpers model the production
 * source-template contract: tenant-owned business tables are copied from the
 * module source schema into each tenant schema; infrastructure tables stay in
 * the source schema.
 */
import { DataSource } from 'typeorm';

export async function createTenantSchemaFromSource(
  dataSource: DataSource,
  schema: string,
  tables: readonly string[],
): Promise<void> {
  await dataSource.query(`CREATE SCHEMA "${schema}"`);
  for (const table of tables) {
    await dataSource.query(`CREATE TABLE "${schema}"."${table}" (LIKE "farm"."${table}" INCLUDING ALL)`);
  }
}

export async function createFarmOutboxTable(dataSource: DataSource): Promise<void> {
  await dataSource.query(`
    CREATE TABLE IF NOT EXISTS "farm"."farm_outbox" (
      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventType" VARCHAR(100) NOT NULL,
      "tenantId" UUID NULL,
      "aggregateId" UUID NULL,
      "payload" JSONB NOT NULL,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "publishedAt" TIMESTAMPTZ NULL,
      "retryCount" INTEGER NOT NULL DEFAULT 0,
      "lastError" TEXT NULL,
      "nextAttemptAt" TIMESTAMPTZ NULL,
      "idempotencyKey" VARCHAR(255) NULL,
      "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
      "leasedAt" TIMESTAMPTZ NULL,
      "leasedBy" VARCHAR(128) NULL
    )
  `);
}

export async function createSourceEquipmentTypesReferenceTable(dataSource: DataSource): Promise<void> {
  // Equipment.equipmentTypeId has a real FK, but EquipmentType is
  // synchronize:false because production owns it through migrations/reference
  // data. Tests that synchronize Equipment must provide the source reference
  // table first.
  await dataSource.query(`
    CREATE TABLE IF NOT EXISTS "farm"."equipment_types" (
      "id" UUID PRIMARY KEY,
      "name" VARCHAR(100) NOT NULL,
      "code" VARCHAR(50) NOT NULL UNIQUE,
      "description" TEXT NULL,
      "category" VARCHAR(50) NOT NULL DEFAULT 'other',
      "icon" VARCHAR(50) NULL,
      "specificationSchema" JSONB NOT NULL DEFAULT '{"fields":[]}'::jsonb,
      "allowedSubEquipmentTypes" TEXT[] NULL,
      "isActive" BOOLEAN NOT NULL DEFAULT true,
      "isSystem" BOOLEAN NOT NULL DEFAULT false,
      "sortOrder" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `);
}
