/**
 * Shared tenant-schema helpers for real Postgres e2e tests.
 *
 * WHY: Tenant isolation tests must assert physical schema placement without
 * duplicating ad-hoc DDL in every spec. These helpers model the production
 * source-template contract: tenant-owned business tables are copied from the
 * module source schema into each tenant schema; infrastructure tables stay in
 * the source schema.
 */
import { DataSource } from 'typeorm';

import { CreateFarmStockReadModel1800400000000 } from '../../../database/migrations/1800400000000-CreateFarmStockReadModel';
import { AssertFarmStockBatchSnapshotMetadata1800500000000 } from '../../../database/migrations/1800500000000-AssertFarmStockBatchSnapshotMetadata';
import { ExtendFarmStockReadModelFanout1800600000000 } from '../../../database/migrations/1800600000000-ExtendFarmStockReadModelFanout';
import { AddFarmStockBatchSnapshotSpecies1805200000000 } from '../../../database/migrations/1805200000000-AddFarmStockBatchSnapshotSpecies';

export async function createTenantSchemaFromSource(
  dataSource: DataSource,
  schema: string,
  tables: readonly string[],
): Promise<void> {
  await dataSource.query(`CREATE SCHEMA "${schema}"`);
  for (const table of tables) {
    await dataSource.query(
      `CREATE TABLE "${schema}"."${table}" (LIKE "farm"."${table}" INCLUDING ALL)`,
    );
  }
}

/**
 * The farm-stock read model, in the SOURCE schema so it can be cloned per tenant.
 *
 * DERIVED, not mirrored: this runs the real migration classes rather than a
 * hand-copy of their DDL. The read model is shaped by FOUR migrations, not one
 * — `AddFarmStockBatchSnapshotSpecies` alone adds a `speciesId` column that
 * `FarmStockProjectionService` writes — so a harness that copies the CREATE
 * TABLE from the first migration is already wrong the day the second lands.
 * That is the drift FARM-HIGH-316 names, reproduced here while writing this
 * helper: the hand-copy failed with `column "speciesId" does not exist`.
 *
 * These tables are not TypeORM entities, so `synchronize: true` never creates
 * them; a suite whose writes go through the real command handlers needs them
 * because `refreshContainers` is part of the allocate/transfer path.
 */
export async function createFarmStockReadModelTables(dataSource: DataSource): Promise<void> {
  // The migrations' DDL is tenant-relative (unqualified) and one default needs
  // uuid-ossp, which db-migrate installs before any migration runs.
  await dataSource.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
  const queryRunner = dataSource.createQueryRunner();
  // One of these migrations arms RLS, which `assertDbMigrateDdlAuthority`
  // reserves for the provisioner. Granting it for the duration of the run and
  // restoring it afterwards is the same scoped grant messaging-service's e2e
  // setup uses (`apps/messaging-service/test/e2e-setup.ts`) — the harness IS
  // standing in for db-migrate here, and the guard must stay armed for the
  // handlers the suite then exercises.
  const previousAuthority = process.env['DB_MIGRATE_DDL_AUTHORITY'];
  process.env['DB_MIGRATE_DDL_AUTHORITY'] = '1';
  try {
    await queryRunner.connect();
    await queryRunner.query('SET search_path TO "farm", public');
    for (const migration of [
      new CreateFarmStockReadModel1800400000000(),
      new AssertFarmStockBatchSnapshotMetadata1800500000000(),
      new ExtendFarmStockReadModelFanout1800600000000(),
      new AddFarmStockBatchSnapshotSpecies1805200000000(),
    ]) {
      await migration.up(queryRunner);
    }
  } finally {
    if (previousAuthority === undefined) {
      Reflect.deleteProperty(process.env, 'DB_MIGRATE_DDL_AUTHORITY');
    } else {
      process.env['DB_MIGRATE_DDL_AUTHORITY'] = previousAuthority;
    }
    await queryRunner.release();
  }
}

export async function createFarmOutboxTable(dataSource: DataSource): Promise<void> {
  await dataSource.query(`
    CREATE TABLE IF NOT EXISTS "farm"."outbox_events" (
      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventType" VARCHAR(100) NOT NULL,
      "tenantId" UUID NULL,
      "aggregateId" UUID NULL,
      "payload" JSONB NOT NULL,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "publishedAt" TIMESTAMPTZ NULL,
      "retryCount" INTEGER NOT NULL DEFAULT 0,
      "lastError" TEXT NULL,
      "nextAttemptAt" TIMESTAMPTZ NULL,
      "idempotencyKey" VARCHAR(255) NULL,
      "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
      "leasedAt" TIMESTAMPTZ NULL,
      "leasedBy" VARCHAR(128) NULL
    )
  `);
}

export async function createSourceEquipmentTypesReferenceTable(
  dataSource: DataSource,
): Promise<void> {
  // Equipment.equipmentTypeId has a real FK, but EquipmentType is
  // synchronize:false because production owns it through migrations/reference
  // data. Tests that synchronize Equipment must provide the source reference
  // table first.
  await dataSource.query(`
    CREATE TABLE IF NOT EXISTS "farm"."equipment_types" (
      "id" UUID PRIMARY KEY,
      "name" VARCHAR(100) NOT NULL,
      "code" VARCHAR(50) NOT NULL UNIQUE,
      "description" TEXT NULL,
      "category" VARCHAR(50) NOT NULL DEFAULT 'other',
      "icon" VARCHAR(50) NULL,
      "specificationSchema" JSONB NOT NULL DEFAULT '{"fields":[]}'::jsonb,
      "allowedSubEquipmentTypes" TEXT[] NULL,
      "isActive" BOOLEAN NOT NULL DEFAULT true,
      "isSystem" BOOLEAN NOT NULL DEFAULT false,
      "sortOrder" INTEGER NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `);
}
