export interface TransactionalOutboxDdlOptions {
  readonly schema: string;
  readonly table: string;
  readonly pollIndexName: string;
  readonly tenantIndexName: string;
  readonly idempotencyIndexName: string;
  readonly notifyFunctionName: string;
  readonly notifyTriggerName: string;
  readonly notifyChannel: string;
}

export interface TenantErasureTargetProofLedgerDdlOptions {
  readonly schema: string;
  readonly table?: string;
  readonly tenantIndexName: string;
  readonly eventIndexName: string;
  readonly targetIndexName: string;
}

export const TENANT_ERASURE_TARGET_PROOF_LEDGER_TABLE =
  'tenant_erasure_target_proofs';

function assertSqlIdentifier(identifier: string, label: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(identifier) || identifier.length > 63) {
    throw new Error(
      `Transactional outbox DDL ${label} must be a safe SQL identifier`,
    );
  }
  return identifier;
}

function quote(identifier: string, label: string): string {
  return `"${assertSqlIdentifier(identifier, label)}"`;
}

export function buildTransactionalOutboxUpSql(
  options: TransactionalOutboxDdlOptions,
): readonly string[] {
  const schema = quote(options.schema, 'schema');
  const table = quote(options.table, 'table');
  const qualified = `${schema}.${table}`;
  const notifyFunction = `${schema}.${quote(options.notifyFunctionName, 'notify function')}`;

  return [
    `CREATE SCHEMA IF NOT EXISTS ${schema}`,
    `
      CREATE TABLE IF NOT EXISTS ${qualified} (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "eventType" VARCHAR(100) NOT NULL,
        "tenantId" UUID NULL,
        "aggregateId" UUID NULL,
        "payload" JSONB NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "publishedAt" TIMESTAMPTZ NULL,
        "retryCount" INTEGER NOT NULL DEFAULT 0,
        "lastError" TEXT NULL,
        "nextAttemptAt" TIMESTAMPTZ NULL,
        "idempotencyKey" VARCHAR(255) NULL,
        "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
        "leasedAt" TIMESTAMPTZ NULL,
        "leasedBy" VARCHAR(128) NULL
      )
    `,
    `
      CREATE INDEX IF NOT EXISTS ${quote(options.pollIndexName, 'poll index')}
        ON ${qualified} ("createdAt")
        WHERE "publishedAt" IS NULL AND "isDeadLettered" = false
    `,
    `
      CREATE INDEX IF NOT EXISTS ${quote(options.tenantIndexName, 'tenant index')}
        ON ${qualified} ("tenantId")
    `,
    `
      CREATE UNIQUE INDEX IF NOT EXISTS ${quote(options.idempotencyIndexName, 'idempotency index')}
        ON ${qualified} ("tenantId", "idempotencyKey")
        WHERE "idempotencyKey" IS NOT NULL
    `,
    `
      CREATE OR REPLACE FUNCTION ${notifyFunction}()
      RETURNS TRIGGER AS $$
      BEGIN
        PERFORM pg_notify('${options.notifyChannel}', '');
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `,
    `
      DROP TRIGGER IF EXISTS ${quote(options.notifyTriggerName, 'notify trigger')}
        ON ${qualified}
    `,
    `
      CREATE TRIGGER ${quote(options.notifyTriggerName, 'notify trigger')}
        AFTER INSERT ON ${qualified}
        FOR EACH ROW
        EXECUTE FUNCTION ${notifyFunction}()
    `,
  ];
}

export function buildTransactionalOutboxDownSql(
  options: TransactionalOutboxDdlOptions,
): readonly string[] {
  const schema = quote(options.schema, 'schema');
  const table = quote(options.table, 'table');
  const qualified = `${schema}.${table}`;

  return [
    `DROP TRIGGER IF EXISTS ${quote(options.notifyTriggerName, 'notify trigger')} ON ${qualified}`,
    `DROP FUNCTION IF EXISTS ${schema}.${quote(options.notifyFunctionName, 'notify function')}()`,
    `DROP TABLE IF EXISTS ${qualified}`,
  ];
}

export function buildTenantErasureTargetProofLedgerUpSql(
  options: TenantErasureTargetProofLedgerDdlOptions,
): readonly string[] {
  const schema = quote(options.schema, 'schema');
  const table = quote(
    options.table ?? TENANT_ERASURE_TARGET_PROOF_LEDGER_TABLE,
    'tenant erasure proof ledger table',
  );
  const qualified = `${schema}.${table}`;

  return [
    `CREATE SCHEMA IF NOT EXISTS ${schema}`,
    `
      CREATE TABLE IF NOT EXISTS ${qualified} (
        "operationId" UUID NOT NULL,
        "tenantId" UUID NOT NULL,
        "targetService" VARCHAR(100) NOT NULL,
        "eventId" UUID NOT NULL,
        "proofHash" VARCHAR(255) NOT NULL,
        "erasedAt" TIMESTAMPTZ NOT NULL,
        "dryRun" BOOLEAN NOT NULL,
        "matchedRecordCount" INTEGER NOT NULL,
        "erasedRecordCount" INTEGER NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "${assertSqlIdentifier(`${options.schema}_tenant_erasure_target_proofs_pk`, 'tenant erasure proof ledger pk')}"
          PRIMARY KEY ("operationId", "targetService")
      )
    `,
    `
      CREATE INDEX IF NOT EXISTS ${quote(options.tenantIndexName, 'tenant erasure proof tenant index')}
        ON ${qualified} ("tenantId")
    `,
    `
      CREATE UNIQUE INDEX IF NOT EXISTS ${quote(options.eventIndexName, 'tenant erasure proof event index')}
        ON ${qualified} ("eventId")
    `,
    `
      CREATE INDEX IF NOT EXISTS ${quote(options.targetIndexName, 'tenant erasure proof target index')}
        ON ${qualified} ("targetService", "createdAt")
    `,
  ];
}

export function buildTenantErasureTargetProofLedgerDownSql(
  options: TenantErasureTargetProofLedgerDdlOptions,
): readonly string[] {
  const schema = quote(options.schema, 'schema');
  const table = quote(
    options.table ?? TENANT_ERASURE_TARGET_PROOF_LEDGER_TABLE,
    'tenant erasure proof ledger table',
  );
  return [`DROP TABLE IF EXISTS ${schema}.${table}`];
}
