/**
 * TasksPage specs (FARM-MEDIUM-120 batch 6).
 *
 * Exercises the real useTasks hook against the routed graphqlClient seam:
 * today's tasks + stats render from the backend, the auto-rules tab fires
 * its own query, and a transport failure does not render fake-empty data.
 */
import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React from 'react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import '@testing-library/jest-dom/vitest';

vi.mock('@aquaculture/shared-ui', async () =>
  (await import('../../../test-utils/sharedUiMock')).createSharedUiMock(),
);

import { requestMock } from '../../../test-utils/sharedUiMock';
import { routeGraphql } from '../../../test-utils/mockGraphqlClient';
import { renderWithProviders } from '../../../test-utils/renderWithProviders';
import TasksPage from '../TasksPage';

const TODAY_ISO = new Date().toISOString().split('T')[0];

const TASKS = [
  {
    id: 'task-1',
    title: 'Morning oxygen check',
    description: null,
    category: 'WATER_QUALITY',
    priority: 'HIGH',
    status: 'PENDING',
    assignedTo: 'user-1',
    assignedToName: 'Ola Nordmann',
    dueDate: TODAY_ISO,
    dueTime: '08:00',
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    completedBy: null,
    location: 'Site A',
    estimatedMinutes: 15,
    checklistItems: [],
    // The backend returns note/tag ARRAYS (never null) — TodayTab reads .length.
    notes: [],
    tags: [],
    isRecurring: false,
    recurringTemplateId: null,
    isAutoGenerated: false,
  },
];

const STATS = {
  totalToday: 1,
  completedToday: 0,
  overdueCount: 0,
  upcomingCount: 1,
  completionRate: 0,
  avgCompletionMinutes: 12,
};

beforeEach(() => {
  requestMock.mockReset();
  routeGraphql([
    { match: 'query Tasks', result: { tasks: { items: TASKS, total: 1 } } },
    { match: 'query TaskStats', result: { taskStats: STATS } },
    { match: 'query RecurringTemplates', result: { recurringTemplates: [] } },
    { match: 'query AutoRules', result: { autoRules: [] } },
  ]);
});

describe('TasksPage', () => {
  it("renders today's tasks and stats from the backend", async () => {
    renderWithProviders(<TasksPage />, { route: '/tasks', path: 'tasks' });

    expect((await screen.findAllByText(/Morning oxygen check/)).length).toBeGreaterThan(0);
    expect(
      requestMock.mock.calls.some(([query]) => (query as string).includes('query TaskStats')),
    ).toBe(true);
  });

  it('loads auto rules when the tab is opened', async () => {
    const user = userEvent.setup();
    renderWithProviders(<TasksPage />, { route: '/tasks', path: 'tasks' });
    await screen.findAllByText(/Morning oxygen check/);

    const autoRulesTab = screen.getByRole('button', { name: /Oto\. Kurallar/ });
    await user.click(autoRulesTab);

    await waitFor(() => {
      expect(
        requestMock.mock.calls.some(([query]) => (query as string).includes('query AutoRules')),
      ).toBe(true);
    });
  });

  it('does not render tasks as an empty success state when the query fails', async () => {
    routeGraphql([]);
    renderWithProviders(<TasksPage />, { route: '/tasks', path: 'tasks' });

    await waitFor(() => expect(requestMock).toHaveBeenCalled());
    await waitFor(() => {
      expect(screen.queryByText(/Morning oxygen check/)).not.toBeInTheDocument();
    });
  });
});
