/**
 * Task hooks for farm-module
 * Handles CRUD operations for tasks via GraphQL API
 */
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { graphqlClient, useAuth, createTenantQueryKey } from '@aquaculture/shared-ui';
import {
  Task,
  TaskStats,
  TaskStatus,
} from '../pages/tasks/types/task.types';

// ============================================================================
// GRAPHQL FIELD FRAGMENTS
// ============================================================================

const TASK_FIELDS = `
  id
  title
  description
  category
  priority
  status
  assignedTo
  assignedToName
  dueDate
  dueTime
  createdAt
  completedAt
  completedBy
  location
  estimatedMinutes
  checklistItems
  notes
  tags
  isRecurring
  recurringTemplateId
  isAutoGenerated
`;

const TASK_STATS_FIELDS = `
  totalToday
  completedToday
  overdueCount
  upcomingCount
  completionRate
  avgCompletionMinutes
`;

// ============================================================================
// INPUT TYPES
// ============================================================================

export interface CreateTaskInput {
  title: string;
  description?: string;
  category: string;
  priority: string;
  assignedTo?: string;
  assignedToName?: string;
  dueDate: string;
  dueTime?: string;
  location?: string;
  estimatedMinutes?: number;
  checklistItems?: { text: string; isCompleted?: boolean }[];
  tags?: string[];
}

export interface UpdateTaskInput {
  id: string;
  title?: string;
  description?: string;
  category?: string;
  priority?: string;
  status?: string;
  assignedTo?: string;
  assignedToName?: string;
  dueDate?: string;
  dueTime?: string;
  location?: string;
  estimatedMinutes?: number;
  checklistItems?: { text: string; isCompleted?: boolean }[];
  tags?: string[];
}

export interface TaskFilterInput {
  status?: TaskStatus[];
  category?: string[];
  priority?: string[];
  assignedTo?: string;
  dateFrom?: string;
  dateTo?: string;
  search?: string;
  limit?: number;
  offset?: number;
}

// ============================================================================
// HOOKS
// ============================================================================

/**
 * Hook to fetch tasks list with optional filter
 */
export function useTasks(filter?: TaskFilterInput) {
  const queryClient = useQueryClient();

  // Tasks query
  const tasksQuery = useQuery({
    queryKey: createTenantQueryKey(tenantId, 'tasks', filter),
    staleTime: 30_000, // 30 saniye - gereksiz refetch önlenir
    queryFn: async () => {
      const query = `
        query Tasks($filter: TaskFilterInput) {
          tasks(filter: $filter) {
            items {
              ${TASK_FIELDS}
            }
            total
          }
        }
      `;

      const result = await graphqlClient.request<{
        tasks: {
          items: Task[];
          total: number;
        };
      }>(query, { filter });

      return result.tasks;
    },
    enabled: !!tenantId,
  });

  // Task stats query
  const statsQuery = useQuery({
    queryKey: createTenantQueryKey(tenantId, 'taskStats'),
    staleTime: 60_000, // 1 dakika - stats sık değişmez
    queryFn: async () => {
      const query = `
        query TaskStats {
          taskStats {
            ${TASK_STATS_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{
        taskStats: TaskStats;
      }>(query);

      return result.taskStats;
    },
    enabled: !!tenantId,
  });

  // --- Mutations ---

  const createTaskMutation = useMutation({
    mutationFn: async (input: CreateTaskInput) => {
      const mutation = `
        mutation CreateTask($input: CreateTaskInput!) {
          createTask(input: $input) {
            ${TASK_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{ createTask: Task }>(
        mutation,
        { input }
      );

      return result.createTask;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'taskStats') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  const updateTaskMutation = useMutation({
    mutationFn: async (input: UpdateTaskInput) => {
      const mutation = `
        mutation UpdateTask($input: UpdateTaskInput!) {
          updateTask(input: $input) {
            ${TASK_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{ updateTask: Task }>(
        mutation,
        { input }
      );

      return result.updateTask;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'taskStats') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  const completeTaskMutation = useMutation({
    mutationFn: async (id: string) => {
      const mutation = `
        mutation CompleteTask($id: String!) {
          completeTask(id: $id) {
            ${TASK_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{ completeTask: Task }>(
        mutation,
        { id }
      );

      return result.completeTask;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'taskStats') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  const startTaskMutation = useMutation({
    mutationFn: async (id: string) => {
      const mutation = `
        mutation StartTask($id: String!) {
          startTask(id: $id) {
            ${TASK_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{ startTask: Task }>(
        mutation,
        { id }
      );

      return result.startTask;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'taskStats') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  const deleteTaskMutation = useMutation({
    mutationFn: async (id: string) => {
      const mutation = `
        mutation DeleteTask($id: String!) {
          deleteTask(id: $id)
        }
      `;

      const result = await graphqlClient.request<{ deleteTask: boolean }>(
        mutation,
        { id }
      );

      return result.deleteTask;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'taskStats') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  const toggleChecklistItemMutation = useMutation({
    mutationFn: async ({ taskId, itemId }: { taskId: string; itemId: string }) => {
      const mutation = `
        mutation ToggleChecklistItem($taskId: String!, $itemId: String!) {
          toggleChecklistItem(taskId: $taskId, itemId: $itemId) {
            ${TASK_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{ toggleChecklistItem: Task }>(
        mutation,
        { taskId, itemId }
      );

      return result.toggleChecklistItem;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  const addTaskNoteMutation = useMutation({
    mutationFn: async ({ taskId, text }: { taskId: string; text: string }) => {
      const mutation = `
        mutation AddTaskNote($taskId: String!, $text: String!) {
          addTaskNote(taskId: $taskId, text: $text) {
            ${TASK_FIELDS}
          }
        }
      `;

      const result = await graphqlClient.request<{ addTaskNote: Task }>(
        mutation,
        { taskId, text }
      );

      return result.addTaskNote;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: createTenantQueryKey(tenantId, 'tasks') });
    },
    onError: (error: Error) => {
      console.error('Mutation failed:', error.message);
    },
  });

  return {
    // Data
    tasks: tasksQuery.data?.items ?? [],
    totalTasks: tasksQuery.data?.total ?? 0,
    stats: statsQuery.data ?? null,
    // Loading / error
    loading: tasksQuery.isLoading,
    error: tasksQuery.error,
    statsLoading: statsQuery.isLoading,
    // Mutations
    createTask: createTaskMutation.mutateAsync,
    updateTask: updateTaskMutation.mutateAsync,
    completeTask: completeTaskMutation.mutateAsync,
    startTask: startTaskMutation.mutateAsync,
    deleteTask: deleteTaskMutation.mutateAsync,
    toggleChecklistItem: toggleChecklistItemMutation.mutateAsync,
    addTaskNote: addTaskNoteMutation.mutateAsync,
    // Mutation loading states
    creating: createTaskMutation.isPending,
    updating: updateTaskMutation.isPending,
    deleting: deleteTaskMutation.isPending,
    // Mutation errors
    createError: createTaskMutation.error,
    updateError: updateTaskMutation.error,
    deleteError: deleteTaskMutation.error,
    // Refetch
    refetch: tasksQuery.refetch,
  };
}
