/**
 * FUXA widget catalog -- a static index of all available community widgets.
 * In production, this is generated by a build-time script from the
 * FUXA-SVG-Widgets repository. For now, we include a representative
 * sample catalog with ~50 entries across categories.
 *
 * The catalog is a lightweight JSON structure -- actual SVG content
 * is loaded on-demand when a widget is added to the canvas.
 * This keeps the initial bundle small even with 1,450+ widgets indexed.
 *
 * Category structure mirrors the FUXA-SVG-Widgets repository layout:
 *   Process Engineering / {Pumps, Valves, Tanks, Heat Exchangers, Compressors}
 *   Electrical / {Logic, Instruments}
 *   Dynamic SVG / {Indicators, Controls, Meters}
 *   Basic / {Shapes, Flowchart}
 */

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface FuxaWidgetCatalogEntry {
  /** Unique identifier matching the SVG file path in the FUXA repository */
  id: string;
  /** Human-readable display name */
  name: string;
  /** Top-level category (e.g. 'Process Engineering') */
  category: string;
  /** Optional subcategory within the main category */
  subcategory?: string;
  /**
   * Tier classification for complexity-based loading:
   * Tier 1 = standard (18 variables, 6 states) -- loads synchronously
   * Tier 2 = complex (>18 variables, animations, custom JS) -- loads lazily
   */
  tier: 1 | 2;
  /** Search tags for fuzzy matching in the browser */
  tags: string[];
  /** Number of exported configurable variables */
  variableCount: number;
  /** Brief description shown in the browser detail panel */
  description: string;
}

/* ------------------------------------------------------------------ */
/*  Catalog data                                                       */
/* ------------------------------------------------------------------ */

export const FUXA_WIDGET_CATALOG: FuxaWidgetCatalogEntry[] = [
  /* ============================================================== */
  /*  Process Engineering > Pumps                                    */
  /* ============================================================== */
  {
    id: 'pe-pump-centrifugal',
    name: 'Centrifugal Pump',
    category: 'Process Engineering',
    subcategory: 'Pumps',
    tier: 1,
    tags: ['pump', 'centrifugal', 'motor', 'rotating'],
    variableCount: 18,
    description: '6-state pump with rotation animation and 3D shading',
  },
  {
    id: 'pe-pump-gear',
    name: 'Gear Pump',
    category: 'Process Engineering',
    subcategory: 'Pumps',
    tier: 1,
    tags: ['pump', 'gear', 'positive-displacement'],
    variableCount: 18,
    description: '6-state gear pump with meshing gear animation',
  },
  {
    id: 'pe-pump-diaphragm',
    name: 'Diaphragm Pump',
    category: 'Process Engineering',
    subcategory: 'Pumps',
    tier: 1,
    tags: ['pump', 'diaphragm', 'membrane'],
    variableCount: 18,
    description: '6-state diaphragm pump with pulse animation',
  },
  {
    id: 'pe-pump-submersible',
    name: 'Submersible Pump',
    category: 'Process Engineering',
    subcategory: 'Pumps',
    tier: 1,
    tags: ['pump', 'submersible', 'underwater', 'well'],
    variableCount: 18,
    description: '6-state submersible pump for submerged installations',
  },
  {
    id: 'pe-pump-vacuum',
    name: 'Vacuum Pump',
    category: 'Process Engineering',
    subcategory: 'Pumps',
    tier: 1,
    tags: ['pump', 'vacuum', 'negative-pressure'],
    variableCount: 18,
    description: '6-state vacuum pump with pressure indication',
  },

  /* ============================================================== */
  /*  Process Engineering > Valves                                   */
  /* ============================================================== */
  {
    id: 'pe-valve-gate',
    name: 'Gate Valve',
    category: 'Process Engineering',
    subcategory: 'Valves',
    tier: 1,
    tags: ['valve', 'gate', 'isolation'],
    variableCount: 18,
    description: '6-state gate valve with open/close position',
  },
  {
    id: 'pe-valve-ball',
    name: 'Ball Valve',
    category: 'Process Engineering',
    subcategory: 'Valves',
    tier: 1,
    tags: ['valve', 'ball', 'quarter-turn'],
    variableCount: 18,
    description: '6-state ball valve with rotation indicator',
  },
  {
    id: 'pe-valve-butterfly',
    name: 'Butterfly Valve',
    category: 'Process Engineering',
    subcategory: 'Valves',
    tier: 1,
    tags: ['valve', 'butterfly', 'throttle'],
    variableCount: 18,
    description: '6-state butterfly valve with disc angle animation',
  },
  {
    id: 'pe-valve-control',
    name: 'Control Valve',
    category: 'Process Engineering',
    subcategory: 'Valves',
    tier: 2,
    tags: ['valve', 'control', 'modulating', 'positioner'],
    variableCount: 22,
    description: 'Modulating control valve with positioner feedback',
  },
  {
    id: 'pe-valve-check',
    name: 'Check Valve',
    category: 'Process Engineering',
    subcategory: 'Valves',
    tier: 1,
    tags: ['valve', 'check', 'non-return'],
    variableCount: 18,
    description: '6-state check valve with flow direction indicator',
  },

  /* ============================================================== */
  /*  Process Engineering > Tanks / Vessels                          */
  /* ============================================================== */
  {
    id: 'pe-tank-vertical',
    name: 'Vertical Tank',
    category: 'Process Engineering',
    subcategory: 'Tanks',
    tier: 1,
    tags: ['tank', 'vertical', 'storage', 'vessel'],
    variableCount: 18,
    description: '6-state vertical tank with level indication',
  },
  {
    id: 'pe-tank-horizontal',
    name: 'Horizontal Tank',
    category: 'Process Engineering',
    subcategory: 'Tanks',
    tier: 1,
    tags: ['tank', 'horizontal', 'storage'],
    variableCount: 18,
    description: '6-state horizontal cylindrical tank',
  },
  {
    id: 'pe-tank-conical',
    name: 'Conical Bottom Tank',
    category: 'Process Engineering',
    subcategory: 'Tanks',
    tier: 1,
    tags: ['tank', 'conical', 'hopper', 'settling'],
    variableCount: 18,
    description: '6-state conical bottom tank for settling',
  },
  {
    id: 'pe-vessel-pressure',
    name: 'Pressure Vessel',
    category: 'Process Engineering',
    subcategory: 'Tanks',
    tier: 2,
    tags: ['vessel', 'pressure', 'reactor', 'autoclave'],
    variableCount: 20,
    description: 'Pressure vessel with safety relief indicator',
  },
  {
    id: 'pe-tank-mixing',
    name: 'Mixing Tank',
    category: 'Process Engineering',
    subcategory: 'Tanks',
    tier: 2,
    tags: ['tank', 'mixer', 'agitator', 'stirred'],
    variableCount: 22,
    description: 'Mixing tank with agitator rotation animation',
  },

  /* ============================================================== */
  /*  Process Engineering > Heat Exchangers                          */
  /* ============================================================== */
  {
    id: 'pe-hx-shell-tube',
    name: 'Shell & Tube HX',
    category: 'Process Engineering',
    subcategory: 'Heat Exchangers',
    tier: 1,
    tags: ['heat-exchanger', 'shell-tube', 'cooling', 'heating'],
    variableCount: 18,
    description: '6-state shell and tube heat exchanger',
  },
  {
    id: 'pe-hx-plate',
    name: 'Plate Heat Exchanger',
    category: 'Process Engineering',
    subcategory: 'Heat Exchangers',
    tier: 1,
    tags: ['heat-exchanger', 'plate', 'compact'],
    variableCount: 18,
    description: '6-state plate heat exchanger with flow paths',
  },
  {
    id: 'pe-hx-air-cooler',
    name: 'Air Cooler',
    category: 'Process Engineering',
    subcategory: 'Heat Exchangers',
    tier: 2,
    tags: ['heat-exchanger', 'air-cooler', 'fan', 'radiator'],
    variableCount: 20,
    description: 'Air cooler with fan rotation animation',
  },

  /* ============================================================== */
  /*  Process Engineering > Compressors                              */
  /* ============================================================== */
  {
    id: 'pe-compressor-centrifugal',
    name: 'Centrifugal Compressor',
    category: 'Process Engineering',
    subcategory: 'Compressors',
    tier: 2,
    tags: ['compressor', 'centrifugal', 'turbo'],
    variableCount: 20,
    description: 'Centrifugal compressor with impeller animation',
  },
  {
    id: 'pe-compressor-reciprocating',
    name: 'Reciprocating Compressor',
    category: 'Process Engineering',
    subcategory: 'Compressors',
    tier: 2,
    tags: ['compressor', 'reciprocating', 'piston'],
    variableCount: 20,
    description: 'Reciprocating compressor with piston stroke',
  },
  {
    id: 'pe-compressor-screw',
    name: 'Screw Compressor',
    category: 'Process Engineering',
    subcategory: 'Compressors',
    tier: 2,
    tags: ['compressor', 'screw', 'rotary'],
    variableCount: 20,
    description: 'Rotary screw compressor with rotation indicator',
  },

  /* ============================================================== */
  /*  Electrical > Logic                                             */
  /* ============================================================== */
  {
    id: 'el-logic-and-gate',
    name: 'AND Gate',
    category: 'Electrical',
    subcategory: 'Logic',
    tier: 1,
    tags: ['logic', 'and', 'gate', 'digital'],
    variableCount: 12,
    description: 'AND logic gate with input/output states',
  },
  {
    id: 'el-logic-or-gate',
    name: 'OR Gate',
    category: 'Electrical',
    subcategory: 'Logic',
    tier: 1,
    tags: ['logic', 'or', 'gate', 'digital'],
    variableCount: 12,
    description: 'OR logic gate with input/output states',
  },
  {
    id: 'el-logic-not-gate',
    name: 'NOT Gate',
    category: 'Electrical',
    subcategory: 'Logic',
    tier: 1,
    tags: ['logic', 'not', 'inverter', 'digital'],
    variableCount: 10,
    description: 'NOT logic gate (inverter)',
  },
  {
    id: 'el-logic-timer',
    name: 'Timer',
    category: 'Electrical',
    subcategory: 'Logic',
    tier: 2,
    tags: ['logic', 'timer', 'delay', 'plc'],
    variableCount: 14,
    description: 'Timer block with elapsed/remaining display',
  },
  {
    id: 'el-logic-counter',
    name: 'Counter',
    category: 'Electrical',
    subcategory: 'Logic',
    tier: 2,
    tags: ['logic', 'counter', 'count', 'plc'],
    variableCount: 14,
    description: 'Up/down counter with preset and current value',
  },

  /* ============================================================== */
  /*  Electrical > Instruments                                       */
  /* ============================================================== */
  {
    id: 'el-inst-motor-starter',
    name: 'Motor Starter',
    category: 'Electrical',
    subcategory: 'Instruments',
    tier: 1,
    tags: ['motor', 'starter', 'contactor', 'drive'],
    variableCount: 18,
    description: '6-state motor starter with overload indication',
  },
  {
    id: 'el-inst-vfd',
    name: 'Variable Frequency Drive',
    category: 'Electrical',
    subcategory: 'Instruments',
    tier: 2,
    tags: ['vfd', 'drive', 'inverter', 'frequency'],
    variableCount: 24,
    description: 'VFD with speed bar and status indicators',
  },
  {
    id: 'el-inst-breaker',
    name: 'Circuit Breaker',
    category: 'Electrical',
    subcategory: 'Instruments',
    tier: 1,
    tags: ['breaker', 'circuit', 'protection', 'switch'],
    variableCount: 14,
    description: '6-state circuit breaker with trip indication',
  },

  /* ============================================================== */
  /*  Dynamic SVG > Indicators                                       */
  /* ============================================================== */
  {
    id: 'dyn-ind-led-round',
    name: 'Round LED',
    category: 'Dynamic SVG',
    subcategory: 'Indicators',
    tier: 1,
    tags: ['led', 'indicator', 'light', 'round'],
    variableCount: 8,
    description: 'Round LED indicator with 6-state color',
  },
  {
    id: 'dyn-ind-led-square',
    name: 'Square LED',
    category: 'Dynamic SVG',
    subcategory: 'Indicators',
    tier: 1,
    tags: ['led', 'indicator', 'light', 'square'],
    variableCount: 8,
    description: 'Square LED indicator with 6-state color',
  },
  {
    id: 'dyn-ind-traffic-light',
    name: 'Traffic Light',
    category: 'Dynamic SVG',
    subcategory: 'Indicators',
    tier: 2,
    tags: ['traffic', 'light', 'signal', 'red-yellow-green'],
    variableCount: 12,
    description: '3-light traffic signal with animation',
  },
  {
    id: 'dyn-ind-bar-graph',
    name: 'Bar Graph',
    category: 'Dynamic SVG',
    subcategory: 'Indicators',
    tier: 2,
    tags: ['bar', 'graph', 'level', 'bargraph'],
    variableCount: 16,
    description: 'Segmented bar graph with color zones',
  },

  /* ============================================================== */
  /*  Dynamic SVG > Controls                                         */
  /* ============================================================== */
  {
    id: 'dyn-ctrl-pushbutton',
    name: 'Push Button',
    category: 'Dynamic SVG',
    subcategory: 'Controls',
    tier: 1,
    tags: ['button', 'push', 'momentary', 'control'],
    variableCount: 10,
    description: 'Momentary push button with pressed state',
  },
  {
    id: 'dyn-ctrl-toggle',
    name: 'Toggle Switch',
    category: 'Dynamic SVG',
    subcategory: 'Controls',
    tier: 1,
    tags: ['switch', 'toggle', 'on-off', 'control'],
    variableCount: 10,
    description: 'Two-position toggle switch with animation',
  },
  {
    id: 'dyn-ctrl-knob',
    name: 'Rotary Knob',
    category: 'Dynamic SVG',
    subcategory: 'Controls',
    tier: 2,
    tags: ['knob', 'rotary', 'dial', 'potentiometer'],
    variableCount: 16,
    description: 'Rotary knob with angle indicator',
  },

  /* ============================================================== */
  /*  Dynamic SVG > Meters                                           */
  /* ============================================================== */
  {
    id: 'dyn-meter-analog',
    name: 'Analog Meter',
    category: 'Dynamic SVG',
    subcategory: 'Meters',
    tier: 2,
    tags: ['meter', 'analog', 'gauge', 'needle'],
    variableCount: 20,
    description: 'Analog meter with needle and graduated scale',
  },

  /* ============================================================== */
  /*  Basic > Shapes                                                 */
  /* ============================================================== */
  {
    id: 'basic-shape-rect',
    name: 'Rectangle',
    category: 'Basic',
    subcategory: 'Shapes',
    tier: 1,
    tags: ['shape', 'rectangle', 'box', 'basic'],
    variableCount: 8,
    description: 'Basic rectangle with configurable fill and border',
  },
  {
    id: 'basic-shape-circle',
    name: 'Circle',
    category: 'Basic',
    subcategory: 'Shapes',
    tier: 1,
    tags: ['shape', 'circle', 'round', 'basic'],
    variableCount: 8,
    description: 'Basic circle with configurable fill and border',
  },
  {
    id: 'basic-shape-arrow',
    name: 'Arrow',
    category: 'Basic',
    subcategory: 'Shapes',
    tier: 1,
    tags: ['shape', 'arrow', 'direction', 'pointer'],
    variableCount: 10,
    description: 'Directional arrow with rotation support',
  },
  {
    id: 'basic-shape-pipe-h',
    name: 'Horizontal Pipe',
    category: 'Basic',
    subcategory: 'Shapes',
    tier: 1,
    tags: ['pipe', 'horizontal', 'connector', 'line'],
    variableCount: 8,
    description: 'Horizontal pipe segment with flow indication',
  },
  {
    id: 'basic-shape-pipe-v',
    name: 'Vertical Pipe',
    category: 'Basic',
    subcategory: 'Shapes',
    tier: 1,
    tags: ['pipe', 'vertical', 'connector', 'line'],
    variableCount: 8,
    description: 'Vertical pipe segment with flow indication',
  },

  /* ============================================================== */
  /*  Basic > Flowchart                                              */
  /* ============================================================== */
  {
    id: 'basic-flow-process',
    name: 'Process Block',
    category: 'Basic',
    subcategory: 'Flowchart',
    tier: 1,
    tags: ['flowchart', 'process', 'block', 'step'],
    variableCount: 8,
    description: 'Rectangular process block for flowcharts',
  },
  {
    id: 'basic-flow-decision',
    name: 'Decision Diamond',
    category: 'Basic',
    subcategory: 'Flowchart',
    tier: 1,
    tags: ['flowchart', 'decision', 'diamond', 'branch'],
    variableCount: 8,
    description: 'Diamond-shaped decision block',
  },
  {
    id: 'basic-flow-terminator',
    name: 'Terminator',
    category: 'Basic',
    subcategory: 'Flowchart',
    tier: 1,
    tags: ['flowchart', 'terminator', 'start', 'end'],
    variableCount: 8,
    description: 'Rounded terminator block (start/end)',
  },
  {
    id: 'basic-flow-data',
    name: 'Data Block',
    category: 'Basic',
    subcategory: 'Flowchart',
    tier: 1,
    tags: ['flowchart', 'data', 'io', 'input-output'],
    variableCount: 8,
    description: 'Parallelogram data I/O block',
  },

  /* ============================================================== */
  /*  Dynamic SVG > Meters (additional)                              */
  /* ============================================================== */
  {
    id: 'dyn-meter-digital',
    name: 'Digital Meter',
    category: 'Dynamic SVG',
    subcategory: 'Meters',
    tier: 1,
    tags: ['meter', 'digital', 'display', 'numeric'],
    variableCount: 12,
    description: 'Digital meter with 7-segment display font',
  },
  {
    id: 'dyn-meter-thermometer',
    name: 'Thermometer',
    category: 'Dynamic SVG',
    subcategory: 'Meters',
    tier: 2,
    tags: ['meter', 'thermometer', 'temperature', 'level'],
    variableCount: 14,
    description: 'Mercury-style thermometer with scale and zone colors',
  },

  /* ============================================================== */
  /*  Process Engineering > Miscellaneous                             */
  /* ============================================================== */
  {
    id: 'pe-misc-conveyor',
    name: 'Belt Conveyor',
    category: 'Process Engineering',
    subcategory: 'Conveyors',
    tier: 2,
    tags: ['conveyor', 'belt', 'transport', 'material'],
    variableCount: 16,
    description: 'Belt conveyor with motion animation and speed control',
  },
  {
    id: 'pe-misc-agitator',
    name: 'Agitator',
    category: 'Process Engineering',
    subcategory: 'Mixers',
    tier: 2,
    tags: ['agitator', 'mixer', 'stirrer', 'impeller'],
    variableCount: 18,
    description: '6-state agitator with rotation speed animation',
  },
];

/* ------------------------------------------------------------------ */
/*  Category tree helpers                                              */
/* ------------------------------------------------------------------ */

export interface CatalogCategoryNode {
  name: string;
  /** Subcategories. Empty array if the category has no subcategories. */
  children: string[];
  /** Number of widgets in this category (including all subcategories) */
  count: number;
}

/**
 * Build a category tree from the flat catalog array.
 * Used by FuxaWidgetBrowser to render the collapsible category sidebar.
 */
export function buildCategoryTree(
  catalog: FuxaWidgetCatalogEntry[],
): CatalogCategoryNode[] {
  const map = new Map<string, Set<string>>();
  const counts = new Map<string, number>();

  for (const entry of catalog) {
    if (!map.has(entry.category)) {
      map.set(entry.category, new Set());
      counts.set(entry.category, 0);
    }
    counts.set(entry.category, (counts.get(entry.category) ?? 0) + 1);

    if (entry.subcategory) {
      map.get(entry.category)!.add(entry.subcategory);
    }
  }

  return Array.from(map.entries()).map(([name, subs]) => ({
    name,
    children: Array.from(subs).sort(),
    count: counts.get(name) ?? 0,
  }));
}

/**
 * Extract all unique categories present in the catalog.
 * Used for "all categories" display in the category filter.
 */
export function getAllCategories(
  catalog: FuxaWidgetCatalogEntry[],
): string[] {
  return [...new Set(catalog.map((e) => e.category))].sort();
}
