import { MigrationInterface, QueryRunner } from 'typeorm';
import { MigrationLogger } from '@aquaculture/backend-common/database';

/**
 * ConvertMessagingOutboxToIdentity1781200000000
 * ============================================================================
 *
 * Converts `messaging_outbox.id` from legacy `BIGSERIAL` to
 * `BIGINT GENERATED BY DEFAULT AS IDENTITY` across EVERY schema that
 * contains a `messaging_outbox` table — i.e. the `messaging` source
 * schema template PLUS every `tenant_<uuid>` schema that was provisioned
 * from it.
 *
 * # Cross-schema dependency model (the bug this revision fixes)
 *
 * messaging-service uses the schema-per-tenant pattern. At tenant
 * provisioning time, `TenantSchemaSyncService` runs:
 *
 *     CREATE TABLE "tenant_<uuid>".messaging_outbox
 *       (LIKE "messaging".messaging_outbox INCLUDING ALL)
 *
 * `INCLUDING ALL` copies the column **default expression** but NOT a
 * new sequence. The source's BIGSERIAL was implemented as:
 *
 *     CREATE SEQUENCE messaging.messaging_outbox_id_seq;
 *     ALTER TABLE messaging.messaging_outbox
 *       ALTER COLUMN id SET DEFAULT nextval('messaging.messaging_outbox_id_seq');
 *     ALTER SEQUENCE messaging.messaging_outbox_id_seq
 *       OWNED BY messaging.messaging_outbox.id;
 *
 * The OWNED BY clause creates a `pg_depend` row of type `'a'` (auto)
 * from the sequence to the source-schema column. The default expression
 * separately creates a `pg_depend` row of type `'n'` (normal) from the
 * column's `pg_attrdef` entry to the sequence.
 *
 * When `LIKE ... INCLUDING ALL` clones the source table to a tenant
 * schema, the **default expression is duplicated literally** — every
 * tenant table ends up with `id DEFAULT nextval('messaging.messaging_outbox_id_seq')`
 * referencing the SOURCE schema's sequence. No new tenant sequence is
 * created. As a result, the source-schema sequence has N+1 normal
 * dependencies on it (one from the source column's default, and one
 * from each tenant column's default), even though only the source
 * column "owns" it via the auto dependency.
 *
 * The original revision of this migration processed schemas in
 * alphabetical order, which made `messaging` (the source) the first
 * schema to be touched. Its DROP SEQUENCE step then failed with:
 *
 *     cannot drop sequence messaging_outbox_id_seq because other
 *     objects depend on it
 *
 * — because all the tenant tables still had normal dependencies on it.
 * Production deploys at 2026-04-07T12:29Z and 13:12Z both crashed
 * messaging-service on this exact step. The migration retried 9 times
 * before TypeORM gave up and the service exited with a fatal startup
 * error.
 *
 * # The fix: tenants first, source last
 *
 * The architectural correction is to process tenant schemas BEFORE the
 * source schema. Each tenant's processing only needs to drop the
 * cross-schema default expression and attach a fresh, per-column
 * IDENTITY — it does NOT touch the source-schema sequence at all.
 * Once every tenant has released its normal dependency, the source
 * schema's processing can drop the sequence safely and replace it
 * with its own IDENTITY.
 *
 * Per-schema logic depends on whether the column **owns** a sequence:
 *
 *   - Owner schema (source): a sequence has an auto-dep on this
 *     column. The classic three-step is correct here:
 *
 *         ALTER COLUMN id DROP DEFAULT
 *         DROP SEQUENCE <owned_sequence>
 *         ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH ?)
 *
 *     The RESTART value comes from the captured `last_value`/`is_called`
 *     of the soon-to-be-dropped sequence so identity allocation
 *     continues exactly where the sequence left off.
 *
 *   - Non-owner schema (tenant): no owned sequence to drop. The
 *     column's default references a sequence in another schema, so
 *     we just clear the default and attach a new per-column IDENTITY
 *     starting one past the highest existing id:
 *
 *         ALTER COLUMN id DROP DEFAULT
 *         ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH MAX(id)+1)
 *
 *     We compute the RESTART value from the actual table data because
 *     the cross-schema sequence is shared across tenants — its
 *     `last_value` reflects the global allocation count, not this
 *     tenant's local maximum, so it would over-allocate gaps if used
 *     directly.
 *
 * # Why classify via pg_depend instead of by schema name
 *
 * Naming a schema `messaging` is convention, not a load-bearing
 * invariant. The deployment script could rename the source schema
 * tomorrow, the test fixtures use a different name, and some
 * environments do not have a tenant-style prefix at all. Pulling the
 * ownership truth from `pg_depend.deptype = 'a'` is the only correct
 * way to identify which column actually owns the sequence.
 *
 * # Idempotency
 *
 * The per-schema attidentity check from the original revision is
 * preserved — schemas already on IDENTITY are skipped. The migration
 * is therefore safe to re-run in any state.
 *
 * # Locking
 *
 * Per-schema ALTER TABLE is metadata-only (no table rewrite). DROP
 * SEQUENCE is also metadata-only. Cumulative lock time scales with
 * the tenant count but each schema's work is sub-millisecond. On a
 * platform with hundreds of tenants, expect total migration time on
 * the order of a few hundred ms — same as the original revision.
 *
 * # Related changes
 *
 * - `init-messaging-schema.sql` template should also use
 *   `BIGINT GENERATED BY DEFAULT AS IDENTITY` so future fresh
 *   deployments skip this migration entirely. That update lives in a
 *   separate commit-level edit because it only affects future fresh
 *   deployments, not existing ones.
 * - `TenantSchemaSyncService.cloneSchemaTables()` already uses
 *   `INCLUDING ALL` which propagates IDENTITY columns correctly to
 *   future tenants. No change needed there once this migration runs.
 */
export class ConvertMessagingOutboxToIdentity1781200000000
  implements MigrationInterface
{
  name = 'ConvertMessagingOutboxToIdentity1781200000000';
  private readonly logger = new MigrationLogger(this.name);

  public async up(queryRunner: QueryRunner): Promise<void> {
    this.logger.log('Discovering schemas containing messaging_outbox table');

    // ── 1. Discover every schema (source + tenant) with the table ──────
    const allSchemas: Array<{ table_schema: string }> = await queryRunner.query(`
      SELECT table_schema
      FROM information_schema.tables
      WHERE table_name = 'messaging_outbox'
        AND table_type = 'BASE TABLE'
      ORDER BY table_schema
    `);

    if (allSchemas.length === 0) {
      this.logger.warn(
        'No schemas with messaging_outbox found — nothing to migrate. ' +
          'This is expected on a fresh environment where TenantSchemaSyncService ' +
          'has not yet provisioned any tenant.',
      );
      return;
    }

    this.logger.log(
      `Found ${allSchemas.length} schemas with messaging_outbox: ${allSchemas.map((s) => s.table_schema).join(', ')}`,
    );

    // ── 2. Classify schemas by sequence ownership ──────────────────────
    // The "owner" schema is the one whose messaging_outbox.id column
    // has an auto (OWNED BY) dependency on a sequence. Any other schema
    // that references the same sequence via the default expression is a
    // tenant clone created via CREATE TABLE LIKE INCLUDING ALL.
    const ownerSchemas: string[] = [];
    const tenantSchemas: string[] = [];

    for (const { table_schema } of allSchemas) {
      if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(table_schema)) {
        this.logger.warn(`Skipping invalid schema name: "${table_schema}"`);
        continue;
      }

      const ownedSequence = await this.findOwnedSequence(
        queryRunner,
        table_schema,
      );

      if (ownedSequence !== null) {
        ownerSchemas.push(table_schema);
      } else {
        tenantSchemas.push(table_schema);
      }
    }

    this.logger.log(
      `Classification complete: ${ownerSchemas.length} owner schema(s) [${ownerSchemas.join(', ') || '∅'}], ` +
        `${tenantSchemas.length} tenant schema(s) [${tenantSchemas.join(', ') || '∅'}]`,
    );

    // ── 3. Process tenants FIRST (release cross-schema dependencies) ───
    // Each tenant only needs to drop its default and attach an IDENTITY.
    // It does not touch the owner sequence — that's the owner's job.
    let convertedTenants = 0;
    let skippedTenants = 0;
    for (const tenantSchema of tenantSchemas) {
      const wasConverted = await this.convertTenantSchema(
        queryRunner,
        tenantSchema,
      );
      if (wasConverted) convertedTenants++;
      else skippedTenants++;
    }

    // ── 4. Process owner schemas LAST (sequence is now droppable) ──────
    // After every tenant has dropped its normal dependency on the
    // owner-schema sequence, the only remaining dependency is the
    // owner column's own auto dependency, which DROP SEQUENCE handles
    // implicitly via OWNED BY.
    let convertedOwners = 0;
    let skippedOwners = 0;
    for (const ownerSchema of ownerSchemas) {
      const wasConverted = await this.convertOwnerSchema(
        queryRunner,
        ownerSchema,
      );
      if (wasConverted) convertedOwners++;
      else skippedOwners++;
    }

    this.logger.log(
      `messaging_outbox IDENTITY migration complete: ` +
        `tenants converted=${convertedTenants}, skipped=${skippedTenants}; ` +
        `owners converted=${convertedOwners}, skipped=${skippedOwners}; ` +
        `total schemas=${allSchemas.length}`,
    );
  }

  // ──────────────────────────────────────────────────────────────────────
  // Owner-schema processing (the source schema with OWNED BY sequence)
  // ──────────────────────────────────────────────────────────────────────

  /**
   * Convert the source-schema column (the one whose sequence has an
   * `auto` dependency on this column). Captures the sequence's
   * `last_value`/`is_called` to preserve allocation continuity, then
   * runs the classic DROP DEFAULT → DROP SEQUENCE → ADD IDENTITY
   * sequence. Returns true on conversion, false if already IDENTITY.
   */
  private async convertOwnerSchema(
    queryRunner: QueryRunner,
    schema: string,
  ): Promise<boolean> {
    if (await this.isAlreadyIdentity(queryRunner, schema)) {
      this.logger.log(`[${schema}] (owner) already IDENTITY — skipping`);
      return false;
    }

    const sequenceName = await this.findOwnedSequence(queryRunner, schema);
    if (!sequenceName) {
      // Should not happen given the classification step, but defensive.
      this.logger.warn(
        `[${schema}] expected to own a sequence but findOwnedSequence ` +
          `returned null — schema may have been re-classified mid-run.`,
      );
      return false;
    }

    // Capture sequence allocation state BEFORE dropping anything.
    const seqState: Array<{ last_value: string; is_called: boolean }> =
      await queryRunner.query(`SELECT last_value, is_called FROM ${sequenceName}`);
    const seqRow = seqState[0];
    if (!seqRow) {
      throw new Error(
        `[${schema}] sequence ${sequenceName} returned no state row — ` +
          `schema corruption suspected.`,
      );
    }
    const lastValue = BigInt(seqRow.last_value);
    const isCalled = seqRow.is_called;
    const nextValue = isCalled ? lastValue + 1n : lastValue;

    this.logger.log(
      `[${schema}] (owner) sequence ${sequenceName}: last_value=${lastValue}, is_called=${isCalled}, next=${nextValue}`,
    );

    // The classic three-step. Order matters — DROP SEQUENCE only
    // succeeds because every tenant has already dropped its default,
    // releasing all normal dependencies on the sequence.
    await queryRunner.query(
      `ALTER TABLE "${schema}"."messaging_outbox" ALTER COLUMN "id" DROP DEFAULT`,
    );
    await queryRunner.query(`DROP SEQUENCE IF EXISTS ${sequenceName}`);
    await queryRunner.query(
      `ALTER TABLE "${schema}"."messaging_outbox" ` +
        `ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH ${nextValue})`,
    );

    this.logger.log(
      `[${schema}] (owner) messaging_outbox.id converted to IDENTITY (RESTART WITH ${nextValue})`,
    );
    return true;
  }

  // ──────────────────────────────────────────────────────────────────────
  // Tenant-schema processing (no owned sequence; default points elsewhere)
  // ──────────────────────────────────────────────────────────────────────

  /**
   * Convert a tenant-schema column whose default expression references
   * a sequence in another schema (the source). Computes the next id
   * from the tenant's actual data via `MAX(id) + 1` because the shared
   * source sequence's `last_value` reflects global allocation across
   * every tenant — not this tenant's local maximum — so reusing it
   * would create gaps and risk conflicts on inserts.
   *
   * Returns true on conversion, false if already IDENTITY.
   */
  private async convertTenantSchema(
    queryRunner: QueryRunner,
    schema: string,
  ): Promise<boolean> {
    if (await this.isAlreadyIdentity(queryRunner, schema)) {
      this.logger.log(`[${schema}] (tenant) already IDENTITY — skipping`);
      return false;
    }

    // Compute the per-tenant restart value from the table data. Empty
    // tenant tables (no rows yet) restart at 1.
    const maxRows: Array<{ next_id: string }> = await queryRunner.query(
      `SELECT COALESCE(MAX(id), 0) + 1 AS next_id FROM "${schema}"."messaging_outbox"`,
    );
    const nextId = BigInt(maxRows[0]?.next_id ?? '1');

    this.logger.log(
      `[${schema}] (tenant) deriving RESTART WITH ${nextId} from MAX(id)+1`,
    );

    // Drop the cross-schema default reference. This is the step that
    // actually fixes the original deploy crash — once every tenant has
    // run this line, the source sequence has no more normal dependencies
    // and DROP SEQUENCE on the owner schema becomes legal.
    await queryRunner.query(
      `ALTER TABLE "${schema}"."messaging_outbox" ALTER COLUMN "id" DROP DEFAULT`,
    );

    // Attach a fresh per-column IDENTITY. Each tenant gets its own
    // implicit sequence under PostgreSQL's IDENTITY machinery.
    await queryRunner.query(
      `ALTER TABLE "${schema}"."messaging_outbox" ` +
        `ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH ${nextId})`,
    );

    this.logger.log(
      `[${schema}] (tenant) messaging_outbox.id converted to IDENTITY (RESTART WITH ${nextId})`,
    );
    return true;
  }

  // ──────────────────────────────────────────────────────────────────────
  // Catalogue helpers
  // ──────────────────────────────────────────────────────────────────────

  /**
   * Returns the schema-qualified name of the sequence whose `auto`
   * (OWNED BY) dependency points at this schema's
   * `messaging_outbox.id` column, or null if no such sequence exists.
   * Used both during classification (owner vs tenant) and during the
   * owner-schema conversion (to find the sequence to drop).
   */
  private async findOwnedSequence(
    queryRunner: QueryRunner,
    schema: string,
  ): Promise<string | null> {
    const rows: Array<{ seq_qualified: string }> = await queryRunner.query(
      `
      SELECT quote_ident(seq_ns.nspname) || '.' || quote_ident(s.relname) AS seq_qualified
      FROM pg_depend d
      JOIN pg_class s         ON s.oid = d.objid    AND s.relkind = 'S'
      JOIN pg_namespace seq_ns ON seq_ns.oid = s.relnamespace
      JOIN pg_class t         ON t.oid = d.refobjid AND t.relkind = 'r'
      JOIN pg_namespace tbl_ns ON tbl_ns.oid = t.relnamespace
      JOIN pg_attribute a     ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
      WHERE d.deptype = 'a'
        AND tbl_ns.nspname = $1
        AND t.relname = 'messaging_outbox'
        AND a.attname = 'id'
      LIMIT 1
      `,
      [schema],
    );

    return rows[0]?.seq_qualified ?? null;
  }

  /**
   * Idempotency check — returns true if `messaging_outbox.id` is
   * already an IDENTITY column in the given schema. Identical to the
   * original revision's check; preserved so re-runs are no-ops.
   */
  private async isAlreadyIdentity(
    queryRunner: QueryRunner,
    schema: string,
  ): Promise<boolean> {
    const rows: Array<{ attidentity: string }> = await queryRunner.query(
      `
      SELECT a.attidentity
      FROM pg_attribute a
      JOIN pg_class c ON a.attrelid = c.oid
      JOIN pg_namespace n ON c.relnamespace = n.oid
      WHERE n.nspname = $1
        AND c.relname = 'messaging_outbox'
        AND a.attname = 'id'
        AND a.attnum > 0
        AND NOT a.attisdropped
      `,
      [schema],
    );

    if (rows.length === 0) {
      // Column not found — let the per-schema converters log the
      // anomaly when they process this schema. Don't treat absence as
      // "already converted".
      return false;
    }

    return (rows[0]?.attidentity ?? '') !== '';
  }

  // ──────────────────────────────────────────────────────────────────────
  // Rollback path
  // ──────────────────────────────────────────────────────────────────────

  /**
   * BREAK-GLASS rollback: convert IDENTITY back to BIGSERIAL across
   * every schema. The order is reversed compared to `up()`: owner
   * schemas first (so the sequence exists), tenants second (so they
   * can attach a default that references the recreated sequence).
   *
   * For tenants, the legacy state is `id DEFAULT nextval('owner.seq')`
   * — a cross-schema reference. We restore that exact shape so the
   * post-rollback world is byte-identical to the pre-up() world.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    this.logger.warn(
      'Rolling back messaging_outbox.id IDENTITY → BIGSERIAL across all schemas. ' +
        'This is a break-glass operation.',
    );

    const allSchemas: Array<{ table_schema: string }> = await queryRunner.query(`
      SELECT table_schema
      FROM information_schema.tables
      WHERE table_name = 'messaging_outbox'
        AND table_type = 'BASE TABLE'
      ORDER BY table_schema
    `);

    if (allSchemas.length === 0) {
      this.logger.warn('No schemas with messaging_outbox — nothing to roll back.');
      return;
    }

    // Re-classify by attidentity rather than pg_depend, because after
    // up() ran the IDENTITY columns no longer have any auto dependency
    // we can use. We pick one schema as the "rollback owner" — the one
    // whose attidentity is set AND that the original up() classified
    // as the owner. To stay in lockstep we just pick the first schema
    // with an IDENTITY column and call it owner; any schema named like
    // a tenant clone (`tenant_*`) we treat as a tenant. This matches
    // the conventional naming used by TenantSchemaSyncService and is
    // a deliberate downgrade in fidelity for the rollback path only.
    const ownerSchemas: string[] = [];
    const tenantSchemas: string[] = [];
    for (const { table_schema } of allSchemas) {
      if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(table_schema)) continue;
      if (table_schema.startsWith('tenant_')) {
        tenantSchemas.push(table_schema);
      } else {
        ownerSchemas.push(table_schema);
      }
    }

    if (ownerSchemas.length !== 1) {
      this.logger.warn(
        `Rollback expected exactly 1 owner schema, found ${ownerSchemas.length}: ` +
          `${ownerSchemas.join(', ')}. Proceeding with the first as the rollback owner.`,
      );
    }
    const ownerSchema = ownerSchemas[0];
    if (!ownerSchema) {
      this.logger.warn(
        'No owner schema identified for rollback (only tenant schemas found). ' +
          'Cannot rebuild the cross-schema sequence reference. Aborting rollback.',
      );
      return;
    }

    // ── Owner first: drop IDENTITY, recreate sequence + default ────────
    const ownerNextValue = await this.captureIdentityNextValue(
      queryRunner,
      ownerSchema,
    );
    await queryRunner.query(
      `ALTER TABLE "${ownerSchema}"."messaging_outbox" ALTER COLUMN "id" DROP IDENTITY IF EXISTS`,
    );
    await queryRunner.query(
      `CREATE SEQUENCE "${ownerSchema}"."messaging_outbox_id_seq" START WITH ${ownerNextValue}`,
    );
    await queryRunner.query(
      `ALTER TABLE "${ownerSchema}"."messaging_outbox" ` +
        `ALTER COLUMN "id" SET DEFAULT nextval('"${ownerSchema}"."messaging_outbox_id_seq"')`,
    );
    await queryRunner.query(
      `ALTER SEQUENCE "${ownerSchema}"."messaging_outbox_id_seq" OWNED BY "${ownerSchema}"."messaging_outbox"."id"`,
    );
    this.logger.warn(
      `[${ownerSchema}] (owner) rolled back to BIGSERIAL`,
    );

    // ── Tenants second: drop IDENTITY, attach cross-schema default ─────
    for (const tenantSchema of tenantSchemas) {
      await queryRunner.query(
        `ALTER TABLE "${tenantSchema}"."messaging_outbox" ALTER COLUMN "id" DROP IDENTITY IF EXISTS`,
      );
      await queryRunner.query(
        `ALTER TABLE "${tenantSchema}"."messaging_outbox" ` +
          `ALTER COLUMN "id" SET DEFAULT nextval('"${ownerSchema}"."messaging_outbox_id_seq"')`,
      );
      this.logger.warn(
        `[${tenantSchema}] (tenant) rolled back to default → ${ownerSchema}.messaging_outbox_id_seq`,
      );
    }
  }

  /**
   * For the rollback path: read the current IDENTITY column's
   * underlying sequence to preserve allocation continuity.
   */
  private async captureIdentityNextValue(
    queryRunner: QueryRunner,
    schema: string,
  ): Promise<bigint> {
    const seqRows: Array<{ seq: string | null }> = await queryRunner.query(
      `SELECT pg_get_serial_sequence($1, 'id') AS seq`,
      [`${schema}.messaging_outbox`],
    );
    const identitySeq = seqRows[0]?.seq;
    if (!identitySeq) return 1n;

    const state: Array<{ last_value: string; is_called: boolean }> =
      await queryRunner.query(
        `SELECT last_value, is_called FROM ${identitySeq}`,
      );
    const stateRow = state[0];
    if (!stateRow) return 1n;

    const lastValue = BigInt(stateRow.last_value);
    return stateRow.is_called ? lastValue + 1n : lastValue;
  }
}
