#!/usr/bin/env python3
"""
CI pre-flight validator for docker-compose files.

Mirrors ADR-016 Phase A2/A4 deploy-time checks into CI so drift is
caught at PR-merge time, not at deploy time. Tier-1 Make-Impossible:
breaking any compose interpolation or dropping a required env var at
the wrong layer fails the PR build BEFORE the deploy pipeline runs.

Approach:
  1. Extract every `${VAR:?...}` required-interpolation reference from
     the target compose file(s).
  2. Emit a throwaway .env file with dummy values for each required var.
  3. Invoke `docker compose -f <file> --env-file <dummy> config --quiet`
     and fail the build if the compose CLI reports an error.

Why a dummy-env approach (instead of a hand-maintained
`infrastructure/deploy/ci-test.env`): the compose file IS the SSoT for
"what prod needs at interpolation time". A hand-maintained env file
would drift. Deriving at CI time keeps the two in lockstep for free.

A static required-secret MANIFEST file (compared against compose's
:? set) is deliberately not built here — that's WS8 scope (deploy
manifest SSoT). This script is the Phase A2 mirror only.

Usage:
  scripts/ci/preflight-validate.py <compose-file> [<compose-file> ...]

Exit codes:
  0  every compose file interpolates cleanly
  1  at least one compose file failed interpolation or YAML schema
  2  invocation error (file missing, docker not available)
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# Matches `${VAR:?optional-message}` — the ADR-014/015 "required secret"
# syntax. Captures just the VAR name. We deliberately DO NOT match
# `${VAR:-default}` (optional with default) because those don't need a
# runtime value.
REQUIRED_VAR_PATTERN = re.compile(r"\$\{([A-Z_][A-Z0-9_]*):\?[^}]*\}")


def extract_required_vars(compose_path: Path) -> set[str]:
    """Return the set of `${VAR:?...}` names referenced in the compose file."""
    text = compose_path.read_text()
    return set(REQUIRED_VAR_PATTERN.findall(text))


def write_dummy_env(env_path: Path, required_vars: set[str]) -> None:
    """Emit a .env file with dummy values sufficient to pass interpolation."""
    lines = [
        "# AUTO-GENERATED by scripts/ci/preflight-validate.py — do not edit.",
        "# These dummy values ONLY unblock `docker compose config --quiet`;",
        "# they are never used at runtime.",
        "",
    ]
    for name in sorted(required_vars):
        # Use a value shape that is semi-plausible for any env var
        # (non-empty, no shell metacharacters, no base64-special chars
        # that might trip downstream consumers parsing the output).
        lines.append(f"{name}=ci-dummy-value")
    env_path.write_text("\n".join(lines) + "\n")


def run_compose_validate(compose_path: Path, env_path: Path) -> int:
    """Invoke `docker compose config --quiet`; return its exit code."""
    cmd = [
        "docker",
        "compose",
        "-f",
        str(compose_path),
        "--env-file",
        str(env_path),
        "config",
        "--quiet",
    ]
    print(f"  running: {' '.join(cmd)}", flush=True)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        # Print both streams so CI log shows the exact compose error.
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
    return result.returncode


def validate_file(compose_path: Path) -> bool:
    """Run the full validation flow for one compose file. True on success."""
    print(f"::group::pre-flight: {compose_path}")
    try:
        if not compose_path.exists():
            print(f"::error::compose file not found: {compose_path}")
            return False

        required = extract_required_vars(compose_path)
        print(
            f"  extracted {len(required)} required-env-var references "
            f"(${{VAR:?...}} pattern)",
        )

        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".env",
            delete=False,
        ) as tmp:
            env_path = Path(tmp.name)

        try:
            write_dummy_env(env_path, required)
            rc = run_compose_validate(compose_path, env_path)
            if rc != 0:
                print(
                    f"::error::docker compose config failed for {compose_path} "
                    f"(exit {rc}). Likely cause: YAML schema error, "
                    f"unknown key, or a ${{VAR:?}} reference that changed "
                    f"shape without updating this validator.",
                )
                return False
            print(f"  OK: {compose_path} interpolates cleanly")
            return True
        finally:
            env_path.unlink(missing_ok=True)
    finally:
        print("::endgroup::")


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(
            "usage: preflight-validate.py <compose-file> [<compose-file> ...]",
            file=sys.stderr,
        )
        return 2

    # Sanity check: docker CLI must be available in the CI image.
    try:
        subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        print(f"::error::docker compose not available: {exc}", file=sys.stderr)
        return 2

    all_ok = True
    for arg in argv[1:]:
        compose_path = Path(arg).resolve()
        if not validate_file(compose_path):
            all_ok = False

    if not all_ok:
        print(
            "::error::pre-flight validation failed. "
            "Fix the compose file(s) or the env-var references above.",
        )
        return 1

    print("All compose files interpolate cleanly.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
