#!/usr/bin/env node
/**
 * WS7 — Signal manifest ↔ compose services SSoT check.
 *
 * Asserts:
 *   1. Every service in `required-signals.yaml` exists in
 *      `docker compose config --services`.
 *   2. Every signal key referenced by a service is defined in
 *      `signal_library`.
 *   3. Levels / windows are within expected bounds.
 *
 * Fails the PR build on drift. Complements
 * `validate-criticality-manifest.ts` — the two manifests (criticality
 * + signals) together define "what a deployed service must do."
 *
 * Exit codes:
 *   0  manifest matches compose + internal references resolve
 *   1  drift detected
 *   2  invocation error
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { writeDummyEnvForCompose } from './lib/compose-dummy-env.ts';

const COMPOSE_FILE =
  process.env['COMPOSE_FILE'] ?? 'docker-compose.droplet.yml';
const MANIFEST_PATH =
  process.env['MANIFEST'] ?? 'infrastructure/deploy/required-signals.yaml';
const REQUIRED_VAR_PATTERN = /\$\{([A-Z_][A-Z0-9_]*):?\?[^}]*\}/g;

interface SignalDef {
  pattern: string;
  description?: string;
  signalSource?: string;
}

interface ServiceReq {
  name: string;
  signals: string[];
  window_seconds?: number;
}

interface Manifest {
  schema_version?: number;
  defaults?: { window_seconds?: number };
  signal_library?: Record<string, SignalDef>;
  services?: ServiceReq[];
}

function loadManifest(path: string): Manifest {
  if (!existsSync(path)) {
    console.error(`::error::manifest not found at ${path}`);
    process.exit(2);
  }
  const data = yaml.load(readFileSync(path, 'utf8')) as Manifest | null;
  if (!data || typeof data !== 'object') {
    console.error(`::error::manifest ${path} is not a YAML mapping`);
    process.exit(2);
  }
  return data;
}

function listComposeServices(composeFile: string): string[] {
  if (!existsSync(composeFile)) {
    console.error(`::error::compose file not found at ${composeFile}`);
    process.exit(2);
  }
  const tmp = mkdtempSync(join(tmpdir(), 'signals-compose-'));
  const envPath = join(tmp, 'dummy.env');
  try {
    writeDummyEnv(envPath, extractRequiredVars(composeFile));
    const out = execFileSync(
      'docker',
      ['compose', '-f', composeFile, '--env-file', envPath, 'config', '--services'],
      { encoding: 'utf8' },
    );
    return out
      .split('\n')
      .map((s) => s.trim())
      .filter(Boolean);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`::error::compose YAML parse failed: ${msg}`);
    process.exit(2);
  } finally {
    cleanup();
  }
  if (
    !parsed ||
    typeof parsed !== 'object' ||
    !('services' in parsed) ||
    typeof (parsed as { services: unknown }).services !== 'object' ||
    (parsed as { services: unknown }).services === null
  ) {
    console.error(
      `::error::compose file ${composeFile} has no \`services\` mapping`,
    );
    process.exit(2);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  return Object.keys(
    (parsed as { services: Record<string, unknown> }).services,
  );
}

function extractRequiredVars(composeFile: string): Set<string> {
  const text = readFileSync(composeFile, 'utf8');
  const vars = new Set<string>();
  for (const match of text.matchAll(REQUIRED_VAR_PATTERN)) {
    vars.add(match[1]);
  }
  return vars;
}

function writeDummyEnv(envPath: string, requiredVars: Set<string>): void {
  const lines = [
    '# AUTO-GENERATED by scripts/ci/validate-signals-manifest.ts.',
    '# Dummy values only unblock docker compose config interpolation in CI.',
    '',
  ];
  for (const name of [...requiredVars].sort()) {
    lines.push(`${name}=ci-dummy-value`);
  }
  writeFileSync(envPath, lines.join('\n') + '\n');
}

function main(): void {
  const manifest = loadManifest(MANIFEST_PATH);
  const signals = manifest.signal_library ?? {};
  const services = manifest.services ?? [];
  const composeSvcs = listComposeServices(COMPOSE_FILE);

  const errors: string[] = [];

  // 1. Signal library self-consistency — each signal has a non-empty
  // pattern string.
  for (const [key, def] of Object.entries(signals)) {
    if (!def || typeof def !== 'object') {
      errors.push(`signal_library.${key} is not an object`);
      continue;
    }
    if (typeof def.pattern !== 'string' || !def.pattern) {
      errors.push(
        `signal_library.${key}.pattern is missing or not a non-empty string`,
      );
    }
  }

  // 2. Service entries — referenced signal keys resolve, services
  // exist in compose, no duplicate service entries.
  const seen = new Set<string>();
  for (const svc of services) {
    if (!svc?.name) {
      errors.push(`service entry missing \`name\`: ${JSON.stringify(svc)}`);
      continue;
    }
    if (seen.has(svc.name)) {
      errors.push(`duplicate service entry: ${svc.name}`);
    }
    seen.add(svc.name);

    if (!composeSvcs.includes(svc.name)) {
      errors.push(
        `service "${svc.name}" not found in ${COMPOSE_FILE}`,
      );
    }
    if (!Array.isArray(svc.signals) || svc.signals.length === 0) {
      errors.push(
        `service "${svc.name}" has no signals — remove the entry or add at least one`,
      );
      continue;
    }
    for (const key of svc.signals) {
      if (!(key in signals)) {
        errors.push(
          `service "${svc.name}" references undefined signal "${key}" ` +
            `(define it in signal_library or remove the reference)`,
        );
      }
    }
    if (
      svc.window_seconds !== undefined &&
      (typeof svc.window_seconds !== 'number' || svc.window_seconds < 1)
    ) {
      errors.push(
        `service "${svc.name}" window_seconds must be a positive integer`,
      );
    }
  }

  if (errors.length > 0) {
    console.error('::error::signal manifest schema / consistency errors:');
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  console.log(
    `OK: ${services.length} services × ${Object.keys(signals).length} signals, ` +
      `all consistent with ${COMPOSE_FILE}.`,
  );
}

main();
