import React, { useState } from 'react';
import { Modal, Button, Input } from '@aquaculture/shared-ui';
import { Task, CATEGORY_CONFIG, PRIORITY_CONFIG, STATUS_CONFIG } from '../types/task.types';

interface TaskDetailModalProps {
  task: Task;
  onClose: () => void;
  onToggleChecklist: (taskId: string, checklistId: string, isCompleted: boolean) => void;
  onAddNote: (taskId: string, note: string) => void;
  onComplete: (taskId: string) => void;
}

export const TaskDetailModal: React.FC<TaskDetailModalProps> = ({
  task,
  onClose,
  onToggleChecklist,
  onAddNote,
  onComplete,
}) => {
  const [noteText, setNoteText] = useState('');

  const cat = CATEGORY_CONFIG[task.category];
  const pri = PRIORITY_CONFIG[task.priority];
  const sts = STATUS_CONFIG[task.status];

  const handleAddNote = () => {
    if (noteText.trim()) {
      onAddNote(task.id, noteText.trim());
      setNoteText('');
    }
  };

  const completedChecklist = task.checklistItems.filter((c) => c.isCompleted).length;
  const totalChecklist = task.checklistItems.length;

  return (
    <Modal
      isOpen
      onClose={onClose}
      title={task.title}
      size="lg"
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>Kapat</Button>
          {task.status !== 'COMPLETED' && task.status !== 'CANCELLED' && (
            <Button variant="primary" onClick={() => onComplete(task.id)}>Tamamlandı</Button>
          )}
        </>
      }
    >
      <div className="space-y-6">
        {/* Badges */}
        <div className="flex items-center gap-2 flex-wrap">
          <span
            className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${cat.bg} ${cat.color}`}
          >
            {cat.label}
          </span>
          <span
            className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${pri.bg} ${pri.color}`}
          >
            {pri.label}
          </span>
          <span
            className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${sts.bg} ${sts.color}`}
          >
            {sts.label}
          </span>
          {task.isRecurring && (
            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800">
              Tekrarlayan
            </span>
          )}
          {task.isAutoGenerated && (
            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-violet-100 text-violet-800">
              Otomatik
            </span>
          )}
        </div>

        {/* Description */}
        <div>
          <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Açıklama</h4>
          <p className="text-sm text-gray-600 dark:text-gray-400">{task.description}</p>
        </div>

        {/* Details Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
          <div>
            <span className="text-gray-500 dark:text-gray-400">Atanan:</span>
            <span className="ml-2 font-medium text-gray-900 dark:text-gray-100">{task.assignedToName}</span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">Bitiş:</span>
            <span className="ml-2 font-medium text-gray-900 dark:text-gray-100">
              {task.dueDate}
              {task.dueTime ? ` ${task.dueTime}` : ''}
            </span>
          </div>
          {task.location && (
            <div>
              <span className="text-gray-500 dark:text-gray-400">Konum:</span>
              <span className="ml-2 font-medium text-gray-900 dark:text-gray-100">{task.location}</span>
            </div>
          )}
          {task.estimatedMinutes && (
            <div>
              <span className="text-gray-500 dark:text-gray-400">Tahmini Süre:</span>
              <span className="ml-2 font-medium text-gray-900 dark:text-gray-100">{task.estimatedMinutes} dk</span>
            </div>
          )}
          {task.completedAt && (
            <div>
              <span className="text-gray-500 dark:text-gray-400">Tamamlanma:</span>
              <span className="ml-2 font-medium text-gray-900 dark:text-gray-100">{task.completedAt}</span>
            </div>
          )}
          {task.completedBy && (
            <div>
              <span className="text-gray-500 dark:text-gray-400">Tamamlayan:</span>
              <span className="ml-2 font-medium text-gray-900 dark:text-gray-100">{task.completedBy}</span>
            </div>
          )}
        </div>

        {/* Tags */}
        {task.tags.length > 0 && (
          <div>
            <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Etiketler</h4>
            <div className="flex flex-wrap gap-1">
              {task.tags.map((tag) => (
                <span
                  key={tag}
                  className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Checklist */}
        {totalChecklist > 0 && (
          <div>
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300">
                Kontrol Listesi ({completedChecklist}/{totalChecklist})
              </h4>
              <div className="w-32 h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                <div
                  className="h-full bg-green-500 rounded-full transition-all"
                  style={{
                    width: `${totalChecklist > 0 ? (completedChecklist / totalChecklist) * 100 : 0}%`,
                  }}
                />
              </div>
            </div>
            <div className="space-y-2">
              {task.checklistItems.map((item) => (
                <label
                  key={item.id}
                  className="flex items-center gap-3 p-2 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={item.isCompleted}
                    onChange={() => onToggleChecklist(task.id, item.id, !item.isCompleted)}
                    className="w-4 h-4 text-blue-600 border-gray-300 dark:border-gray-600 rounded focus:ring-blue-500"
                    disabled={task.status === 'COMPLETED' || task.status === 'CANCELLED'}
                  />
                  <span
                    className={`text-sm ${item.isCompleted ? 'line-through text-gray-400 dark:text-gray-500' : 'text-gray-700 dark:text-gray-300'}`}
                  >
                    {item.text}
                  </span>
                </label>
              ))}
            </div>
          </div>
        )}

        {/* Notes */}
        <div>
          <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Notlar ({task.notes.length})</h4>
          {task.notes.length > 0 && (
            <div className="space-y-3 mb-4">
              {task.notes.map((note) => (
                <div key={note.id} className="bg-gray-50 dark:bg-gray-800 rounded-lg p-3">
                  <p className="text-sm text-gray-700 dark:text-gray-300">{note.text}</p>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-xs text-gray-500 dark:text-gray-400">{note.createdBy}</span>
                    <span className="text-xs text-gray-400 dark:text-gray-500">-</span>
                    <span className="text-xs text-gray-500 dark:text-gray-400">{note.createdAt}</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Add Note */}
          {task.status !== 'COMPLETED' && task.status !== 'CANCELLED' && (
            <div className="flex gap-2">
              <Input type="text" value={noteText} onChange={(e) => setNoteText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleAddNote()} placeholder="Not ekle..." />
              <Button variant="primary" onClick={handleAddNote} disabled={!noteText.trim()}>Ekle</Button>
            </div>
          )}
        </div>
      </div>
    </Modal>
  );
};
