import type {
  ComplianceReport,
  DataRequest,
  LoginAttempt,
  SecurityEvent,
  SecurityIncident,
  ThreatIntelligence,
  UserSession,
} from '../entities/security.entity';
import type {
  ActivityCategory,
  ActivitySeverity,
  ComplianceType,
  ComplianceViolation,
  DataRequestStatus,
  DataRequestType,
  DeviceInfo,
  GeoLocation,
  IncidentSeverity,
  IncidentStatus,
  SecurityEventStatus,
  SecurityEventType,
  ThreatIndicatorType,
  ThreatLevel,
} from '../contracts/security-vocabulary';

export interface ActivityLogDto {
  id: string;
  category: ActivityCategory;
  action: string;
  severity: ActivitySeverity;
  tenantId?: string | null;
  tenantName?: string | null;
  userId?: string | null;
  userName?: string | null;
  userEmail?: string | null;
  ipAddress: string;
  userAgent?: string;
  geoLocation?: GeoLocation | null;
  entityType?: string | null;
  entityId?: string | null;
  entityName?: string | null;
  previousValue?: Record<string, unknown> | null;
  newValue?: Record<string, unknown> | null;
  metadata?: Record<string, unknown> | null;
  duration?: number | null;
  success: boolean;
  errorMessage?: string | null;
  createdAt: Date;
}

export interface RetentionPolicyDto {
  id: string;
  name: string;
  category: ActivityCategory;
  description?: string | null;
  retentionDays: number;
  archiveAfterDays?: number | null;
  deleteAfterArchiveDays?: number | null;
  isGlobal: boolean;
  specificTenants?: string[] | null;
  complianceFrameworks?: ComplianceType[] | null;
  isActive: boolean;
  createdBy: string;
  updatedBy?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface DataRequestDto {
  id: string;
  requestNumber: string;
  requestType: DataRequestType;
  status: DataRequestStatus;
  complianceFramework: ComplianceType;
  tenantId: string;
  tenantName: string;
  requesterId?: string | null;
  requesterName: string;
  requesterEmail: string;
  description: string;
  dataCategories?: string[] | null;
  specificData?: string | null;
  identityVerified: boolean;
  verifiedAt?: Date | null;
  verifiedBy?: string | null;
  verificationMethod?: string | null;
  dueDate: Date;
  assignedTo?: string | null;
  assignedToName?: string | null;
  processingStartedAt?: Date | null;
  completedAt?: Date | null;
  completedBy?: string | null;
  completionNotes?: string | null;
  deliveryFormat?: 'json' | 'csv' | 'pdf' | 'xml' | null;
  downloadUrl?: string | null;
  downloadExpiresAt?: Date | null;
  downloadCount: number;
  rejectionReason?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceReportDto {
  id: string;
  title: string;
  complianceType: ComplianceType;
  reportPeriodStart: Date;
  reportPeriodEnd: Date;
  includedTenants?: string[] | null;
  includesAllTenants: boolean;
  totalDataRequests: number;
  completedDataRequests: number;
  pendingDataRequests: number;
  avgResponseTimeDays?: number | null;
  securityIncidents: number;
  dataBreaches: number;
  complianceScore: number;
  violations?: ComplianceViolation[] | null;
  recommendations?: string[] | null;
  executiveSummary?: string | null;
  detailedFindings?: Record<string, unknown> | null;
  pdfUrl?: string | null;
  csvUrl?: string | null;
  generatedBy: string;
  generatedByName: string;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface SecurityEventDto {
  id: string;
  eventType: SecurityEventType;
  threatLevel: ThreatLevel;
  status: SecurityEventStatus;
  title: string;
  description: string;
  ipAddress: string;
  geoLocation?: GeoLocation | null;
  tenantId?: string | null;
  userId?: string | null;
  userName?: string | null;
  targetResource?: string | null;
  targetEndpoint?: string | null;
  detectionSource: string;
  confidenceScore?: number | null;
  rawData?: Record<string, unknown> | null;
  assignedTo?: string | null;
  assignedToName?: string | null;
  investigationNotes?: string | null;
  resolution?: string | null;
  resolvedAt?: Date | null;
  resolvedBy?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface SecurityIncidentDto {
  id: string;
  incidentNumber: string;
  title: string;
  description: string;
  severity: IncidentSeverity;
  status: IncidentStatus;
  category: string;
  attackVector?: string | null;
  affectedSystems?: string[] | null;
  affectedTenants?: string[] | null;
  dataBreached: boolean;
  affectedUsersCount: number;
  impactDescription?: string | null;
  businessImpact?: string | null;
  detectedAt?: Date | null;
  containedAt?: Date | null;
  eradicatedAt?: Date | null;
  recoveredAt?: Date | null;
  closedAt?: Date | null;
  leadInvestigator?: string | null;
  leadInvestigatorName?: string | null;
  relatedSecurityEvents?: string[] | null;
  rootCauseAnalysis?: string | null;
  remediationSteps?: Array<{
    step: string;
    completed: boolean;
    completedAt?: Date;
  }> | null;
  timeline?: Array<{
    timestamp: string;
    action: string;
    actor: string;
    details?: string;
  }> | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ThreatIntelligenceDto {
  id: string;
  indicatorType: ThreatIndicatorType;
  value: string;
  threatLevel: ThreatLevel;
  source: string;
  description?: string | null;
  threatTypes?: string[] | null;
  tags?: string[] | null;
  confidence: number;
  isActive: boolean;
  validFrom?: Date | null;
  validUntil?: Date | null;
  hitCount: number;
  lastSeenAt?: Date | null;
  firstSeenAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ThreatCheckDto {
  isThreat: boolean;
  threat: ThreatIntelligenceDto | null;
}

export interface OperationSuccessDto {
  success: boolean;
}

export interface TerminatedSessionCountDto {
  terminated: number;
}

export interface ActivityStatsDto {
  totalActivities: number;
  byCategory: Record<ActivityCategory, number>;
  bySeverity: Record<ActivitySeverity, number>;
  bySuccess: { success: number; failure: number };
  topActions: Array<{ action: string; count: number }>;
  topUsers: Array<{ userId: string; userName: string; count: number }>;
  topIPs: Array<{ ip: string; count: number }>;
  activityOverTime: Array<{ date: string; count: number }>;
}

export interface LoginAttemptDto {
  id: string;
  email: string;
  ipAddress: string;
  success: boolean;
  failureReason?: string | null;
  geoLocation?: GeoLocation | null;
  deviceInfo?: DeviceInfo | null;
  tenantId?: string | null;
  userId?: string | null;
  sessionId?: string | null;
  createdAt: Date;
}

/** A deliberately token-free projection of an active session. */
export interface UserSessionDto {
  id: string;
  userId: string;
  userName: string;
  tenantId?: string | null;
  tenantName?: string | null;
  isActive: boolean;
  expiresAt: Date;
  ipAddress: string;
  geoLocation?: GeoLocation | null;
  deviceInfo?: DeviceInfo | null;
  requestCount: number;
  lastActivityAt: Date;
  lastActivityPath?: string | null;
  terminatedAt?: Date | null;
  terminationReason?: 'logout' | 'expired' | 'forced' | 'security' | null;
  terminatedBy?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface AuditSummaryDto {
  totalLogs: number;
  last24Hours: number;
  byAction: Array<{ action: string; count: number }>;
  bySeverity: Array<{ severity: string; count: number }>;
  byEntityType: Array<{ entityType: string; count: number }>;
  topUsers: Array<{ userId: string; email: string; count: number }>;
}

export interface RetentionStatsDto {
  totalLogs: number;
  activeLogs: number;
  archivedLogs: number;
  oldestLog: Date | null;
  newestLog: Date | null;
  storageEstimateMB: number;
  byCategory: Record<string, { active: number; archived: number }>;
}

export interface AuditAlertRuleDto {
  id: string;
  name: string;
  description: string;
  isActive: boolean;
  conditions: {
    category?: ActivityCategory[];
    severity?: ActivitySeverity[];
    actions?: string[];
    entityTypes?: string[];
    successOnly?: boolean;
    failureOnly?: boolean;
    ipPatterns?: string[];
  };
  alertChannels: Array<'email' | 'webhook' | 'slack' | 'sms'>;
  recipients: string[];
  cooldownMinutes: number;
  lastTriggeredAt?: Date;
}

export interface DataRequestStatsDto {
  total: number;
  byStatus: Record<DataRequestStatus, number>;
  byType: Record<DataRequestType, number>;
  avgResponseDays: number;
  overdueCount: number;
  completionRate: number;
}

export interface ComplianceRequirementDto {
  id: string;
  framework: ComplianceType;
  requirement: string;
  description: string;
  category: string;
  isMandatory: boolean;
  verificationMethod: string;
}

export interface ComplianceCheckResultDto {
  requirement: ComplianceRequirementDto;
  status: 'compliant' | 'non_compliant' | 'partial' | 'not_applicable';
  details: string;
  evidence?: string;
  remediation?: string;
}

export interface DataInventoryDto {
  category: string;
  dataTypes: string[];
  sources: string[];
  purposes: string[];
  retentionPeriod: string;
  legalBasis: string;
  thirdPartySharing: boolean;
  crossBorderTransfer: boolean;
}

export interface SecurityEventStatsDto {
  total: number;
  byThreatLevel: Record<string, number>;
  byEventType: Record<string, number>;
  byStatus: Record<string, number>;
}

export interface SecurityIncidentStatsDto {
  total: number;
  byStatus: Record<string, number>;
  bySeverity: Record<string, number>;
}

export interface ThreatIntelligenceStatsDto {
  total: number;
  byIndicatorType: Record<string, number>;
  byThreatLevel: Record<string, number>;
}

export interface AnalyzeLoginResultDto {
  analyzed: boolean;
  message: string;
}

export interface AnomalyDetectionConfigDto {
  failedLoginThreshold: number;
  failedLoginWindowMinutes: number;
  bruteForceThreshold: number;
  geoAnomalyEnabled: boolean;
  apiAbuseThreshold: number;
  apiAbuseWindowMinutes: number;
  rateLimitAbuseEnabled: boolean;
  concurrentSessionLimit: number;
  sessionHijackingDetection: boolean;
  offHoursThreshold: number;
  offHoursStart: number;
  offHoursEnd: number;
}

export interface SecurityDashboardStatsDto {
  totalSecurityEvents: number;
  criticalEvents: number;
  activeIncidents: number;
  threatsBlocked: number;
  eventsLast24h: number;
  eventsLast7d: number;
  eventsLast30d: number;
  eventsTrend: 'increasing' | 'decreasing' | 'stable';
  eventsByType: Record<SecurityEventType, number>;
  eventsBySeverity: Record<ThreatLevel, number>;
  topSourceIPs: Array<{ ip: string; count: number; threatLevel: ThreatLevel }>;
  topTargetedUsers: Array<{ userId: string; userName: string; count: number }>;
  topEventTypes: Array<{ type: SecurityEventType; count: number }>;
  eventsTimeline: Array<{
    date: string;
    critical: number;
    high: number;
    medium: number;
    low: number;
  }>;
}

export interface SecurityHealthScoreDto {
  score: number;
  factors: Array<{
    name: string;
    score: number;
    weight: number;
    description: string;
  }>;
  recommendations: string[];
}

export function toLoginAttemptDto(attempt: LoginAttempt): LoginAttemptDto {
  return {
    id: attempt.id,
    email: attempt.email,
    ipAddress: attempt.ipAddress,
    success: attempt.success,
    failureReason: attempt.failureReason,
    geoLocation: attempt.geoLocation,
    deviceInfo: attempt.deviceInfo,
    tenantId: attempt.tenantId,
    userId: attempt.userId,
    sessionId: attempt.sessionId,
    createdAt: attempt.createdAt,
  };
}

export function toUserSessionDto(session: UserSession): UserSessionDto {
  return {
    id: session.id,
    userId: session.userId,
    userName: session.userName,
    tenantId: session.tenantId,
    tenantName: session.tenantName,
    isActive: session.isActive,
    expiresAt: session.expiresAt,
    ipAddress: session.ipAddress,
    geoLocation: session.geoLocation,
    deviceInfo: session.deviceInfo,
    requestCount: session.requestCount,
    lastActivityAt: session.lastActivityAt,
    lastActivityPath: session.lastActivityPath,
    terminatedAt: session.terminatedAt,
    terminationReason: session.terminationReason,
    terminatedBy: session.terminatedBy,
    createdAt: session.createdAt,
    updatedAt: session.updatedAt,
  };
}

export function toDataRequestDto(request: DataRequest): DataRequestDto {
  return {
    id: request.id,
    requestNumber: request.requestNumber,
    requestType: request.requestType,
    status: request.status,
    complianceFramework: request.complianceFramework,
    tenantId: request.tenantId,
    tenantName: request.tenantName,
    requesterId: request.requesterId,
    requesterName: request.requesterName,
    requesterEmail: request.requesterEmail,
    description: request.description,
    dataCategories: request.dataCategories,
    specificData: request.specificData,
    identityVerified: request.identityVerified,
    verifiedAt: request.verifiedAt,
    verifiedBy: request.verifiedBy,
    verificationMethod: request.verificationMethod,
    dueDate: request.dueDate,
    assignedTo: request.assignedTo,
    assignedToName: request.assignedToName,
    processingStartedAt: request.processingStartedAt,
    completedAt: request.completedAt,
    completedBy: request.completedBy,
    completionNotes: request.completionNotes,
    deliveryFormat: request.deliveryFormat,
    downloadUrl: request.downloadUrl,
    downloadExpiresAt: request.downloadExpiresAt,
    downloadCount: request.downloadCount,
    rejectionReason: request.rejectionReason,
    createdAt: request.createdAt,
    updatedAt: request.updatedAt,
  };
}

export function toComplianceReportDto(report: ComplianceReport): ComplianceReportDto {
  return {
    id: report.id,
    title: report.title,
    complianceType: report.complianceType,
    reportPeriodStart: report.reportPeriodStart,
    reportPeriodEnd: report.reportPeriodEnd,
    includedTenants: report.includedTenants,
    includesAllTenants: report.includesAllTenants,
    totalDataRequests: report.totalDataRequests,
    completedDataRequests: report.completedDataRequests,
    pendingDataRequests: report.pendingDataRequests,
    avgResponseTimeDays: report.avgResponseTimeDays,
    securityIncidents: report.securityIncidents,
    dataBreaches: report.dataBreaches,
    complianceScore: report.complianceScore,
    violations: report.violations,
    recommendations: report.recommendations,
    executiveSummary: report.executiveSummary,
    detailedFindings: report.detailedFindings,
    pdfUrl: report.pdfUrl,
    csvUrl: report.csvUrl,
    generatedBy: report.generatedBy,
    generatedByName: report.generatedByName,
    isAutoGenerated: report.isAutoGenerated,
    createdAt: report.createdAt,
    updatedAt: report.updatedAt,
  };
}

export function toSecurityEventDto(event: SecurityEvent): SecurityEventDto {
  return {
    id: event.id,
    eventType: event.eventType,
    threatLevel: event.threatLevel,
    status: event.status,
    title: event.title,
    description: event.description,
    ipAddress: event.ipAddress,
    geoLocation: event.geoLocation,
    tenantId: event.tenantId,
    userId: event.userId,
    userName: event.userName,
    targetResource: event.targetResource,
    targetEndpoint: event.targetEndpoint,
    detectionSource: event.detectionSource,
    confidenceScore: event.confidenceScore,
    rawData: event.rawData,
    assignedTo: event.assignedTo,
    assignedToName: event.assignedToName,
    investigationNotes: event.investigationNotes,
    resolution: event.resolution,
    resolvedAt: event.resolvedAt,
    resolvedBy: event.resolvedBy,
    createdAt: event.createdAt,
    updatedAt: event.updatedAt,
  };
}

export function toSecurityIncidentDto(incident: SecurityIncident): SecurityIncidentDto {
  return {
    id: incident.id,
    incidentNumber: incident.incidentNumber,
    title: incident.title,
    description: incident.description,
    severity: incident.severity,
    status: incident.status,
    category: incident.category,
    attackVector: incident.attackVector,
    affectedSystems: incident.affectedSystems,
    affectedTenants: incident.affectedTenants,
    dataBreached: incident.dataBreached,
    affectedUsersCount: incident.affectedUsersCount,
    impactDescription: incident.impactDescription,
    businessImpact: incident.businessImpact,
    detectedAt: incident.detectedAt,
    containedAt: incident.containedAt,
    eradicatedAt: incident.eradicatedAt,
    recoveredAt: incident.recoveredAt,
    closedAt: incident.closedAt,
    leadInvestigator: incident.leadInvestigator,
    leadInvestigatorName: incident.leadInvestigatorName,
    relatedSecurityEvents: incident.relatedSecurityEvents,
    rootCauseAnalysis: incident.rootCauseAnalysis,
    remediationSteps: incident.remediationSteps,
    timeline: incident.timeline,
    createdAt: incident.createdAt,
    updatedAt: incident.updatedAt,
  };
}

export function toThreatIntelligenceDto(threat: ThreatIntelligence): ThreatIntelligenceDto {
  return {
    id: threat.id,
    indicatorType: threat.indicatorType,
    value: threat.value,
    threatLevel: threat.threatLevel,
    source: threat.source,
    description: threat.description,
    threatTypes: threat.threatTypes,
    tags: threat.tags,
    confidence: threat.confidence,
    isActive: threat.isActive,
    validFrom: threat.validFrom,
    validUntil: threat.validUntil,
    hitCount: threat.hitCount,
    lastSeenAt: threat.lastSeenAt,
    firstSeenAt: threat.firstSeenAt,
    createdAt: threat.createdAt,
    updatedAt: threat.updatedAt,
  };
}
