import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1800000000000 implements MigrationInterface {
    name = 'Baseline1800000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."audit_logs_severity_enum" AS ENUM('info', 'warning', 'critical'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE "admin"."audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying(100) NOT NULL, "entityType" character varying(50) NOT NULL, "entityId" uuid, "tenantId" uuid, "performedBy" character varying(100) NOT NULL, "performedByEmail" character varying(100), "ipAddress" inet, "userAgent" character varying(500), "details" jsonb, "previousValue" jsonb, "newValue" jsonb, "severity" "admin"."audit_logs_severity_enum" NOT NULL DEFAULT 'info', "requestId" character varying(100), "sessionId" character varying(100), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "legalHold" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3197969cb5ed9b2a00252a3c9e" ON "admin"."audit_logs" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "admin"."audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_889633a4291bcb0bf4680fff23" ON "admin"."audit_logs" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8bd8d95914d6228770fe87b8a" ON "admin"."audit_logs" ("performedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "admin"."audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "admin"."audit_logs" ("action") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "shared"."user_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tenantId" uuid NOT NULL, "permissions" jsonb NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "grantedBy" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_01f4295968ba33d73926684264f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_permissions_user_tenant_unique" ON "shared"."user_permissions" ("userId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_user_permissions_tenant" ON "shared"."user_permissions" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "idx_user_permissions_user" ON "shared"."user_permissions" ("userId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."tenant_activities_activitytype_enum" AS ENUM('created', 'activated', 'suspended', 'deactivated', 'plan_changed', 'limits_updated', 'module_assigned', 'module_removed', 'user_added', 'user_removed', 'settings_updated', 'payment_received', 'payment_failed', 'trial_started', 'trial_expired', 'contact_updated', 'domain_changed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE "admin"."tenant_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "activityType" "admin"."tenant_activities_activitytype_enum" NOT NULL, "title" character varying(255) NOT NULL, "description" text, "metadata" jsonb, "previousValue" jsonb, "newValue" jsonb, "performedBy" character varying(100), "performedByEmail" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4cabd9fc72838a2d744b20170cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63c18b160e36cccb2f656e1373" ON "admin"."tenant_activities" ("activityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_868c21a770df72304f70315a55" ON "admin"."tenant_activities" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."tenant_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "content" text NOT NULL, "category" character varying(50) NOT NULL DEFAULT 'general', "isPinned" boolean NOT NULL DEFAULT false, "createdBy" character varying(100) NOT NULL, "createdByEmail" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2ecbf3569492950f6fcd001048b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d7492898eb27032baddb41559" ON "admin"."tenant_notes" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."tenant_billing_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "billingCycle" character varying(50) NOT NULL, "monthlyAmount" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'USD', "paymentStatus" character varying(50) NOT NULL DEFAULT 'pending', "nextBillingDate" TIMESTAMP WITH TIME ZONE, "lastPaymentDate" TIMESTAMP WITH TIME ZONE, "lastPaymentAmount" numeric(10,2), "stripeCustomerId" character varying(255), "stripeSubscriptionId" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_94bf8f5742c39d367bcf5f4f172" UNIQUE ("tenantId"), CONSTRAINT "PK_3c5682187654bc4d91dce6c82d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94bf8f5742c39d367bcf5f4f17" ON "admin"."tenant_billing_info" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."system_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" character varying(50) NOT NULL, "majorVersion" integer NOT NULL, "minorVersion" integer NOT NULL, "patchVersion" integer NOT NULL, "preReleaseTag" character varying(50), "releaseType" character varying(50) NOT NULL DEFAULT 'patch', "status" character varying(50) NOT NULL DEFAULT 'draft', "title" character varying(255) NOT NULL, "summary" text, "changelog" jsonb, "migrations" jsonb, "breakingChanges" jsonb, "deprecations" jsonb, "newFeatures" jsonb, "dependencies" jsonb, "releaseNotes" text, "upgradeGuide" text, "deployedAt" TIMESTAMP, "deployedBy" character varying, "deploymentDurationSeconds" integer, "deploymentEnvironments" jsonb, "isCurrentVersion" boolean NOT NULL DEFAULT false, "previousVersion" text, "rollbackInfo" jsonb, "metadata" jsonb, "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d20a1738b23637ac0f01ed08b29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c2aec3650bafd17a147de05b9b" ON "admin"."system_versions" ("deployedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6be4daa72cc602cd66bb4a20cb" ON "admin"."system_versions" ("releaseType", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1a1ac1474ad32b265537b01767" ON "admin"."system_versions" ("version") `);
        await queryRunner.query(`CREATE TABLE "admin"."performance_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "metricType" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "value" double precision NOT NULL, "unit" character varying(50), "aggregation" character varying(20) NOT NULL DEFAULT 'avg', "service" character varying(100), "dimensions" jsonb, "percentiles" jsonb, "histogram" jsonb, "sampleCount" integer, "minValue" double precision, "maxValue" double precision, "timestamp" TIMESTAMP NOT NULL, "intervalSeconds" integer NOT NULL DEFAULT '60', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_66237d8c606d64c7bd44a91f74a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38735a10939289547b9d0b8e0b" ON "admin"."performance_metrics" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_d15fbd3d1847c96f7865ad35a1" ON "admin"."performance_metrics" ("service", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_255b3adadd4d505f707c4e131d" ON "admin"."performance_metrics" ("metricType", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "admin"."performance_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "service" character varying(100), "timestamp" TIMESTAMP NOT NULL, "applicationMetrics" jsonb NOT NULL, "databaseMetrics" jsonb NOT NULL, "infrastructureMetrics" jsonb NOT NULL, "alerts" jsonb, "overallHealthScore" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fe51f348099bb6a07df7816727b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eaeadc987378984be1360f7504" ON "admin"."performance_snapshots" ("service") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bc64380eb042b5d7e6b7a6463" ON "admin"."performance_snapshots" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "admin"."maintenance_modes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "scope" character varying(50) NOT NULL DEFAULT 'global', "type" character varying(50) NOT NULL DEFAULT 'scheduled', "status" character varying(50) NOT NULL DEFAULT 'scheduled', "tenantId" uuid, "affectedTenants" jsonb, "affectedServices" jsonb, "affectedRegions" jsonb, "scheduledStart" TIMESTAMP NOT NULL, "scheduledEnd" TIMESTAMP, "actualStart" TIMESTAMP, "actualEnd" TIMESTAMP, "estimatedDurationMinutes" integer NOT NULL DEFAULT '60', "userMessage" text, "internalNotes" text, "notifications" jsonb, "allowReadOnlyAccess" boolean NOT NULL DEFAULT false, "bypassForSuperAdmins" boolean NOT NULL DEFAULT false, "whitelistedIPs" jsonb, "whitelistedUsers" jsonb, "bannerColor" text, "bannerIcon" text, "metadata" jsonb, "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f3e7108f5e087ff8ffc885591a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1a1ce8c991a35199ab72b8d79" ON "admin"."maintenance_modes" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_24594798d636558f63c106f9c7" ON "admin"."maintenance_modes" ("scheduledStart", "scheduledEnd") `);
        await queryRunner.query(`CREATE INDEX "IDX_37ff6ca278f8354a91cfa8e2dc" ON "admin"."maintenance_modes" ("scope", "status") `);
        await queryRunner.query(`CREATE TABLE "admin"."background_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "queueName" character varying(100) NOT NULL, "jobType" character varying(50) NOT NULL DEFAULT 'immediate', "status" character varying(50) NOT NULL DEFAULT 'pending', "priority" integer NOT NULL DEFAULT '5', "payload" jsonb, "result" jsonb, "errorMessage" text, "stackTrace" text, "progress" jsonb, "tenantId" uuid, "userId" uuid, "scheduledAt" TIMESTAMP, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "durationMs" integer, "attempts" integer NOT NULL DEFAULT '0', "maxAttempts" integer NOT NULL DEFAULT '3', "retryPolicy" jsonb, "nextRetryAt" TIMESTAMP, "cronExpression" text, "lastRunAt" TIMESTAMP, "nextRunAt" TIMESTAMP, "timeoutMs" integer NOT NULL DEFAULT '3600000', "dependencies" jsonb, "parentJobId" uuid, "tags" jsonb, "metadata" jsonb, "workerId" character varying(100), "isRecurring" boolean NOT NULL DEFAULT false, "isPaused" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1f31731b1a02806c4aa631acb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b63908dfa5591d40355d7d926a" ON "admin"."background_jobs" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef6af03a7effa02df1779a0e8" ON "admin"."background_jobs" ("jobType", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d5e7a51042582e68ba4a6f9ab" ON "admin"."background_jobs" ("queueName", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9736047b77fb3669502f92f9a" ON "admin"."background_jobs" ("status", "priority", "scheduledAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."job_execution_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jobId" uuid NOT NULL, "attemptNumber" integer NOT NULL, "status" character varying(50) NOT NULL, "startedAt" TIMESTAMP NOT NULL, "completedAt" TIMESTAMP, "durationMs" integer, "errorMessage" text, "stackTrace" text, "result" jsonb, "logs" jsonb, "workerId" character varying(100), "cpuUsage" double precision, "memoryUsage" double precision, "timestamp" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_32e009c848dc4c86c6fe1aa7831" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9886a1e22fa2cd6fe21800d41a" ON "admin"."job_execution_logs" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_edbff5cdb364327758316c3390" ON "admin"."job_execution_logs" ("jobId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "admin"."job_queues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "isPaused" boolean NOT NULL DEFAULT false, "concurrency" integer NOT NULL DEFAULT '10', "maxJobsPerSecond" integer NOT NULL DEFAULT '100', "defaultMaxRetries" integer NOT NULL DEFAULT '3', "defaultTimeoutMs" integer NOT NULL DEFAULT '3600000', "retryPolicy" jsonb, "pendingCount" integer NOT NULL DEFAULT '0', "runningCount" integer NOT NULL DEFAULT '0', "completedCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "avgProcessingTimeMs" double precision, "lastJobAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bd75b9c40cb0cb92fe94712134" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f5d9039d80efa55807e9bc5733" ON "admin"."job_queues" ("name") `);
        await queryRunner.query(`CREATE TABLE "admin"."global_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(200) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "category" character varying(50) NOT NULL DEFAULT 'system', "valueType" character varying(50) NOT NULL DEFAULT 'string', "value" jsonb NOT NULL, "defaultValue" jsonb, "validation" jsonb, "isSecret" boolean NOT NULL DEFAULT false, "isReadOnly" boolean NOT NULL DEFAULT false, "requiresRestart" boolean NOT NULL DEFAULT false, "isEnvironmentSpecific" boolean NOT NULL DEFAULT false, "environmentOverrides" jsonb, "history" jsonb, "maxHistoryEntries" integer NOT NULL DEFAULT '10', "dependsOn" jsonb, "affectedServices" jsonb, "helpText" text, "warningMessage" text, "sortOrder" integer NOT NULL DEFAULT '0', "lastModifiedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_11ee16a4f622cd0417977408703" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40b26ec4ae1e1bd8b46f8b7532" ON "admin"."global_configs" ("isSecret") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d456cabba2f3e3856a113ee2d" ON "admin"."global_configs" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_de954a917c3d76ababc6dcca9e" ON "admin"."global_configs" ("key") `);
        await queryRunner.query(`CREATE TABLE "admin"."feature_toggles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "scope" character varying(50) NOT NULL DEFAULT 'global', "status" character varying(50) NOT NULL DEFAULT 'disabled', "category" character varying(100), "conditions" jsonb, "rolloutPercentage" integer NOT NULL DEFAULT '0', "rolloutSchedule" jsonb, "enabledTenants" jsonb, "disabledTenants" jsonb, "metadata" jsonb, "defaultValue" jsonb, "variants" jsonb, "requiresRestart" boolean NOT NULL DEFAULT false, "isExperimental" boolean NOT NULL DEFAULT false, "deprecatedAt" TIMESTAMP, "deprecationMessage" text, "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6aacfcd59c906d3dc84214df296" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_229fe7feee0c72214f09b4ca57" ON "admin"."feature_toggles" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_2146b3af12d7c699ee461cd091" ON "admin"."feature_toggles" ("scope", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_682ae3334b02dd3f1b7b9823be" ON "admin"."feature_toggles" ("key") `);
        await queryRunner.query(`CREATE TABLE "admin"."error_occurrences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "groupId" uuid NOT NULL, "fingerprint" character varying(64) NOT NULL, "severity" character varying(50) NOT NULL DEFAULT 'error', "message" character varying(500) NOT NULL, "errorType" character varying(255), "stackTrace" text, "stackFrames" jsonb, "context" jsonb, "service" character varying(100), "environment" character varying(100), "release" character varying(50), "tenantId" uuid, "userId" uuid, "ipAddress" inet, "userAgent" text, "metadata" jsonb, "timestamp" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c0799cf38ab89c55ab36c9436d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e49c09acd070928e54f7c4df2b" ON "admin"."error_occurrences" ("service", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7184177974c6f54d1643acf35" ON "admin"."error_occurrences" ("severity", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_8495b7a8f6dadb50a731a6f225" ON "admin"."error_occurrences" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa824faa2275f2114949e652c9" ON "admin"."error_occurrences" ("fingerprint", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "admin"."error_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fingerprint" character varying(64) NOT NULL, "severity" character varying(50) NOT NULL DEFAULT 'error', "status" character varying(50) NOT NULL DEFAULT 'new', "message" character varying(500) NOT NULL, "errorType" character varying(255), "service" character varying(100), "culprit" text, "occurrenceCount" integer NOT NULL DEFAULT '1', "userCount" integer NOT NULL DEFAULT '0', "firstSeenAt" TIMESTAMP NOT NULL, "lastSeenAt" TIMESTAMP NOT NULL, "affectedTenants" jsonb, "affectedReleases" jsonb, "tags" jsonb, "assignedTo" uuid, "notes" text, "resolvedAt" TIMESTAMP, "resolvedBy" uuid, "resolutionNotes" text, "linkedTicketUrl" text, "isRegression" boolean NOT NULL DEFAULT false, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_75f3d2ade79d16975fb3b39352c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_06fe86c67a37a12ddea9682fa8" ON "admin"."error_groups" ("service") `);
        await queryRunner.query(`CREATE INDEX "IDX_39e0d1c4fba46fb536e8203d9b" ON "admin"."error_groups" ("severity", "occurrenceCount") `);
        await queryRunner.query(`CREATE INDEX "IDX_61b83f6089b63ff83d53f1fbee" ON "admin"."error_groups" ("status", "lastSeenAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d8a1adf467f843f858c925bdb8" ON "admin"."error_groups" ("fingerprint") `);
        await queryRunner.query(`CREATE TABLE "admin"."error_alert_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "conditions" jsonb NOT NULL, "actions" jsonb NOT NULL, "cooldownMinutes" integer NOT NULL DEFAULT '15', "lastTriggeredAt" TIMESTAMP, "triggerCount" integer NOT NULL DEFAULT '0', "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c9d3d52cb3277f9c496351f6804" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_02327e60ee0e6571fdfc1f5635" ON "admin"."error_alert_rules" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "admin"."message_threads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "subject" character varying(200) NOT NULL, "lastMessageId" uuid, "messageCount" integer NOT NULL DEFAULT '0', "unreadAdminCount" integer NOT NULL DEFAULT '0', "unreadTenantCount" integer NOT NULL DEFAULT '0', "isArchived" boolean NOT NULL DEFAULT false, "isClosed" boolean NOT NULL DEFAULT false, "lastMessageAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_257a191f664b9470b5d94f98264" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73903d13c2f9512f42fc31ccbb" ON "admin"."message_threads" ("lastMessageAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bccdf9b34dc6b06fc2636856f" ON "admin"."message_threads" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "threadId" uuid NOT NULL, "senderId" uuid NOT NULL, "senderType" character varying(50) NOT NULL, "senderName" character varying(200), "content" text NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'sent', "isInternal" boolean NOT NULL DEFAULT false, "attachments" jsonb, "readAt" TIMESTAMP WITH TIME ZONE, "emailSent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ce6acdb0801254590f8a78c08" ON "admin"."messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2db9cf2b3ca111742793f6c37c" ON "admin"."messages" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_15f9bd2bf472ff12b6ee20012d" ON "admin"."messages" ("threadId") `);
        await queryRunner.query(`CREATE TABLE "admin"."announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "content" text NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'info', "status" character varying(50) NOT NULL DEFAULT 'draft', "isGlobal" boolean NOT NULL DEFAULT false, "targetCriteria" jsonb, "createdBy" uuid, "createdByName" character varying(200), "publishAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "requiresAcknowledgment" boolean NOT NULL DEFAULT false, "viewCount" integer NOT NULL DEFAULT '0', "acknowledgmentCount" integer NOT NULL DEFAULT '0', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c673e84b342a18f9354860e509" ON "admin"."announcements" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fabf411618aba4c3c7790fd31" ON "admin"."announcements" ("publishAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_472dcde086b0881656f29b94af" ON "admin"."announcements" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_c45985989bc600ab871ef1eaf8" ON "admin"."announcements" ("status") `);
        await queryRunner.query(`CREATE TABLE "admin"."announcement_acknowledgments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "announcementId" uuid NOT NULL, "tenantId" uuid NOT NULL, "userId" uuid NOT NULL, "userName" character varying(200), "viewedAt" TIMESTAMP WITH TIME ZONE, "acknowledgedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2210e80b68c3a16b3d5fcb5eec1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba4b92cd3ce9d8fe5fc560661d" ON "admin"."announcement_acknowledgments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_694820afeb2fdb3a6f5f17528a" ON "admin"."announcement_acknowledgments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b31e3f30a25937e045cfba3d6" ON "admin"."announcement_acknowledgments" ("announcementId") `);
        await queryRunner.query(`CREATE TABLE "admin"."support_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketNumber" character varying(20) NOT NULL, "tenantId" uuid NOT NULL, "tenantName" character varying(200), "createdBy" uuid NOT NULL, "createdByName" character varying(200), "createdByEmail" character varying(255), "subject" character varying(200) NOT NULL, "description" text NOT NULL, "category" character varying(50) NOT NULL DEFAULT 'general', "priority" character varying(50) NOT NULL DEFAULT 'medium', "status" character varying(50) NOT NULL DEFAULT 'open', "assignedTo" uuid, "assignedToName" character varying(200), "tags" jsonb, "firstResponseAt" TIMESTAMP WITH TIME ZONE, "resolvedAt" TIMESTAMP WITH TIME ZONE, "closedAt" TIMESTAMP WITH TIME ZONE, "dueAt" TIMESTAMP WITH TIME ZONE, "slaResponseMinutes" integer, "slaResolutionMinutes" integer, "slaBreached" boolean NOT NULL DEFAULT false, "satisfactionRating" integer NOT NULL DEFAULT '0', "satisfactionFeedback" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6e4c71fa5e96520463e92aa02d9" UNIQUE ("ticketNumber"), CONSTRAINT "PK_942e8d8f5df86100471d2324643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b735528ffad34f697758a00d2a" ON "admin"."support_tickets" ("dueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2302659dc5e2f79b1d1288ca7" ON "admin"."support_tickets" ("assignedTo") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d15c3ab16e6b23291cc17f33d" ON "admin"."support_tickets" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_cae81694804986ef32be155d34" ON "admin"."support_tickets" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba7b1a2ed4051fb3b39ff95444" ON "admin"."support_tickets" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f39d4242941c82c75c939c7e0" ON "admin"."support_tickets" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."ticket_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" uuid NOT NULL, "authorId" uuid NOT NULL, "authorType" character varying(50) NOT NULL, "authorName" character varying(200), "content" text NOT NULL, "isInternal" boolean NOT NULL DEFAULT false, "attachments" jsonb, "emailSent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_811ed3b81dd8df6b9a92058d89c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2f0f4740214d1c081ea469882f" ON "admin"."ticket_comments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4497112178bae33622ee27543e" ON "admin"."ticket_comments" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6beba8ae36e1ce20968d7a319" ON "admin"."ticket_comments" ("ticketId") `);
        await queryRunner.query(`CREATE TABLE "admin"."onboarding_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "tenantName" character varying(200), "status" character varying(50) NOT NULL DEFAULT 'not_started', "completionPercent" integer NOT NULL DEFAULT '0', "completedSteps" jsonb NOT NULL DEFAULT '[]', "currentStep" character varying(100), "welcomeEmailSent" boolean NOT NULL DEFAULT false, "welcomeEmailSentAt" TIMESTAMP WITH TIME ZONE, "gettingStartedViewed" boolean NOT NULL DEFAULT false, "viewedTutorials" jsonb, "scheduledTrainings" jsonb, "assignedGuide" uuid, "assignedGuideName" character varying(200), "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d7e40302edaabf40ab5c4b1ed90" UNIQUE ("tenantId"), CONSTRAINT "PK_070eb6e4f3132f9d7f29651aa3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e27193d00cd9c6857b01652a1b" ON "admin"."onboarding_progress" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7e40302edaabf40ab5c4b1ed9" ON "admin"."onboarding_progress" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."tenant_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "userLimits" jsonb NOT NULL DEFAULT '{}', "storageConfig" jsonb NOT NULL DEFAULT '{}', "apiConfig" jsonb NOT NULL DEFAULT '{}', "dataRetention" jsonb NOT NULL DEFAULT '{}', "domainConfig" jsonb NOT NULL DEFAULT '{}', "brandingConfig" jsonb NOT NULL DEFAULT '{}', "securityConfig" jsonb NOT NULL DEFAULT '{}', "notificationConfig" jsonb NOT NULL DEFAULT '{}', "featureFlags" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, CONSTRAINT "UQ_03485c758a380c96574bb380883" UNIQUE ("tenantId"), CONSTRAINT "PK_5b97b6bdabfab3eb07552b3bbed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_03485c758a380c96574bb38088" ON "admin"."tenant_configurations" ("tenantId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."system_settings_valuetype_enum" AS ENUM('string', 'number', 'boolean', 'json', 'encrypted'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."system_settings_category_enum" AS ENUM('general', 'security', 'email', 'sms', 'billing', 'rate_limit', 'storage', 'integration', 'notification', 'feature_flag', 'maintenance'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE "admin"."system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text NOT NULL, "valueType" "admin"."system_settings_valuetype_enum" NOT NULL DEFAULT 'string', "category" "admin"."system_settings_category_enum" NOT NULL, "description" text, "displayName" character varying, "isPublic" boolean NOT NULL DEFAULT false, "isReadOnly" boolean NOT NULL DEFAULT false, "requiresRestart" boolean NOT NULL DEFAULT false, "defaultValue" text, "validationRule" text, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "version" integer NOT NULL, CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_797d199fff9037e5b231dc4ffb" ON "admin"."system_settings" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b1b5bc664526d375c94ce9ad43" ON "admin"."system_settings" ("key") `);
        await queryRunner.query(`CREATE TABLE "admin"."email_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "category" character varying NOT NULL, "subject" character varying NOT NULL, "bodyHtml" text NOT NULL, "bodyText" text, "variables" jsonb NOT NULL DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "isSystem" boolean NOT NULL DEFAULT false, "tenantId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, CONSTRAINT "UQ_e65f590d27b63f71b3d3e01dd33" UNIQUE ("code"), CONSTRAINT "PK_06c564c515d8cdb40b6f3bfbbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_109c25f9c6301dc8a0f9c0f39d" ON "admin"."email_templates" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e65f590d27b63f71b3d3e01dd3" ON "admin"."email_templates" ("code") `);
        await queryRunner.query(`CREATE TABLE "admin"."ip_access_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying, "ipAddress" character varying NOT NULL, "ruleType" character varying(20) NOT NULL, "description" character varying, "isActive" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP WITH TIME ZONE, "hitCount" integer NOT NULL DEFAULT '0', "lastHitAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, CONSTRAINT "PK_806782c054afc4738067a94d94b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ae0dcdff7166137228bb61e0a" ON "admin"."ip_access_rules" ("ruleType") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccc49003f73349d071957fd990" ON "admin"."ip_access_rules" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0026a4e23e66199b0c5053a8c" ON "admin"."ip_access_rules" ("ipAddress") `);
        await queryRunner.query(`CREATE TABLE "admin"."activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying(100), "tenantName" character varying(100), "userId" character varying(100), "userName" character varying(255), "userEmail" character varying(100), "category" character varying(50) NOT NULL, "severity" character varying(20) NOT NULL DEFAULT 'info', "action" character varying(100) NOT NULL, "description" text NOT NULL, "entityType" character varying(100), "entityId" character varying(100), "entityName" character varying(255), "ipAddress" character varying(45) NOT NULL, "geoLocation" jsonb, "deviceInfo" jsonb, "requestInfo" jsonb, "sessionId" character varying(255), "correlationId" character varying(255), "previousValue" jsonb, "newValue" jsonb, "changedFields" jsonb, "metadata" jsonb, "tags" text, "success" boolean NOT NULL DEFAULT true, "errorMessage" text, "errorCode" character varying(100), "duration" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isArchived" boolean NOT NULL DEFAULT false, "archivedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_377463c364326082e86ce68ed3" ON "admin"."activity_logs" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3d5764d4b44970698381dc664" ON "admin"."activity_logs" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_a306e3adc99c4e21fc4a155433" ON "admin"."activity_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_52c7ccae32a5bdc10f1257ee88" ON "admin"."activity_logs" ("ipAddress", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa2f8e99469cc6d494c8612896" ON "admin"."activity_logs" ("severity", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b57258b9301304728fdc0b3c8" ON "admin"."activity_logs" ("category", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_412f03f2a073c89f8918e6ae52" ON "admin"."activity_logs" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a2825dd99a0eb1aeded63709d" ON "admin"."activity_logs" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."security_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventType" character varying(50) NOT NULL, "threatLevel" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'detected', "title" character varying(255) NOT NULL, "description" text NOT NULL, "ipAddress" character varying(45) NOT NULL, "geoLocation" jsonb, "deviceInfo" jsonb, "tenantId" character varying(100), "userId" character varying(100), "userName" character varying(255), "targetResource" character varying(100), "targetEndpoint" character varying(255), "detectionSource" character varying(100) NOT NULL, "confidenceScore" double precision, "anomalyDetails" jsonb, "indicators" jsonb, "rawData" jsonb, "relatedActivityIds" text, "autoMitigated" boolean NOT NULL DEFAULT false, "mitigationActions" text, "investigationNotes" text, "assignedTo" character varying(100), "assignedToName" character varying(255), "assignedAt" TIMESTAMP WITH TIME ZONE, "resolution" text, "resolvedAt" TIMESTAMP WITH TIME ZONE, "resolvedBy" character varying(100), "tags" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6fc100d6700780737348df0d3ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_31ea8d94d66808cbcfb6802996" ON "admin"."security_events" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d52eb18cb798b56183a5ba026" ON "admin"."security_events" ("ipAddress", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb708bf77f760210d747550b91" ON "admin"."security_events" ("threatLevel", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3e3edb95aee90264572beb037" ON "admin"."security_events" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5595f413d4ecb718842f8aab06" ON "admin"."security_events" ("eventType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c2235261ba6518fa4a686f6f5" ON "admin"."security_events" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."security_incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "incidentNumber" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "severity" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'open', "category" character varying(100) NOT NULL, "attackVector" character varying(100), "affectedSystems" text, "affectedTenants" text, "dataBreached" boolean NOT NULL DEFAULT false, "affectedUsersCount" integer NOT NULL DEFAULT '0', "impactDescription" text, "businessImpact" text, "detectedAt" TIMESTAMP WITH TIME ZONE, "containedAt" TIMESTAMP WITH TIME ZONE, "eradicatedAt" TIMESTAMP WITH TIME ZONE, "recoveredAt" TIMESTAMP WITH TIME ZONE, "closedAt" TIMESTAMP WITH TIME ZONE, "leadInvestigator" character varying(100), "leadInvestigatorName" character varying(255), "teamMembers" text, "relatedSecurityEvents" text, "rootCauseAnalysis" text, "lessonsLearned" text, "remediationSteps" jsonb, "reportedToAuthorities" boolean NOT NULL DEFAULT false, "reportedAt" TIMESTAMP WITH TIME ZONE, "reportReference" character varying(255), "timeline" jsonb, "metadata" jsonb, "createdBy" character varying(100) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ae4bb9cdce807edf3f0d3526b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_61f66171aa0c8a1456650aae2e" ON "admin"."security_incidents" ("severity", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_781b94dc7e41d2958b30b4f395" ON "admin"."security_incidents" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."threat_intelligence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "indicatorType" character varying(50) NOT NULL, "value" character varying(500) NOT NULL, "threatLevel" character varying(20) NOT NULL, "source" character varying(100) NOT NULL, "description" character varying(255), "threatTypes" text, "tags" text, "confidence" double precision NOT NULL DEFAULT '0.5', "isActive" boolean NOT NULL DEFAULT true, "validFrom" TIMESTAMP WITH TIME ZONE, "validUntil" TIMESTAMP WITH TIME ZONE, "hitCount" integer NOT NULL DEFAULT '0', "lastSeenAt" TIMESTAMP WITH TIME ZONE, "firstSeenAt" TIMESTAMP WITH TIME ZONE, "relatedIndicators" text, "geoData" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d245e758b5bd93eeeb611a19acb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_236cea9d2fe4ca9079efd9bd46" ON "admin"."threat_intelligence" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_069229793d0509e1311f853e89" ON "admin"."threat_intelligence" ("threatLevel") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6c659e082e916028de28a963e" ON "admin"."threat_intelligence" ("value") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7c014d92e2086de80f60daf27" ON "admin"."threat_intelligence" ("indicatorType") `);
        await queryRunner.query(`CREATE TABLE "admin"."data_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestNumber" character varying(50) NOT NULL, "requestType" character varying(50) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "complianceFramework" character varying(20) NOT NULL, "tenantId" character varying(100) NOT NULL, "tenantName" character varying(255) NOT NULL, "requesterId" character varying(100), "requesterName" character varying(255) NOT NULL, "requesterEmail" character varying(255) NOT NULL, "description" text NOT NULL, "dataCategories" text, "specificData" text, "identityVerified" boolean NOT NULL DEFAULT false, "verifiedAt" TIMESTAMP WITH TIME ZONE, "verifiedBy" character varying(100), "verificationMethod" character varying(100), "dueDate" TIMESTAMP WITH TIME ZONE NOT NULL, "assignedTo" character varying(100), "assignedToName" character varying(255), "processingStartedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "completedBy" character varying(100), "completionNotes" text, "deliveryFormat" character varying(20), "downloadUrl" character varying(500), "downloadExpiresAt" TIMESTAMP WITH TIME ZONE, "downloadCount" integer NOT NULL DEFAULT '0', "rejectionReason" text, "auditTrail" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43e3a8617ed406edce308696264" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b10e5db5fa2e75fd12b9c9f0bc" ON "admin"."data_requests" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_349764678e08e126ab7820adbb" ON "admin"."data_requests" ("requestType", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_98cff932473408b2fd56ab6281" ON "admin"."data_requests" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."compliance_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "complianceType" character varying(20) NOT NULL, "reportPeriodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "reportPeriodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "includedTenants" text, "includesAllTenants" boolean NOT NULL DEFAULT true, "totalDataRequests" integer NOT NULL DEFAULT '0', "completedDataRequests" integer NOT NULL DEFAULT '0', "pendingDataRequests" integer NOT NULL DEFAULT '0', "avgResponseTimeDays" double precision, "securityIncidents" integer NOT NULL DEFAULT '0', "dataBreaches" integer NOT NULL DEFAULT '0', "complianceScore" double precision NOT NULL DEFAULT '100', "violations" jsonb, "recommendations" jsonb, "executiveSummary" text, "detailedFindings" jsonb, "pdfUrl" character varying(500), "csvUrl" character varying(500), "generatedBy" character varying(100) NOT NULL, "generatedByName" character varying(255) NOT NULL, "isAutoGenerated" boolean NOT NULL DEFAULT false, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eb94c451e8b0c8df6e4d64535a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cbb8641e16ba161c4e6135a088" ON "admin"."compliance_reports" ("reportPeriodStart", "reportPeriodEnd") `);
        await queryRunner.query(`CREATE INDEX "IDX_38b7611329ac08db87188a813e" ON "admin"."compliance_reports" ("complianceType", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."retention_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "category" character varying(50) NOT NULL, "description" text, "retentionDays" integer NOT NULL, "archiveAfterDays" integer, "deleteAfterArchiveDays" integer, "isGlobal" boolean NOT NULL DEFAULT true, "specificTenants" text, "complianceFrameworks" text, "isActive" boolean NOT NULL DEFAULT true, "createdBy" character varying(100) NOT NULL, "updatedBy" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cedc8b5aad835580a30405d2e77" UNIQUE ("name"), CONSTRAINT "PK_c0f79bfde72a93e544c780a7470" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cedc8b5aad835580a30405d2e7" ON "admin"."retention_policies" ("name") `);
        await queryRunner.query(`CREATE TABLE "admin"."login_attempts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "ipAddress" character varying(45) NOT NULL, "success" boolean NOT NULL, "failureReason" character varying(100), "geoLocation" jsonb, "deviceInfo" jsonb, "tenantId" character varying(100), "userId" character varying(100), "sessionId" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_070e613c8f768b1a70742705c5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_25bbd36a1c5a95b276d7e6a1df" ON "admin"."login_attempts" ("success", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_46dd77d64eb0ed0d65383ac4ed" ON "admin"."login_attempts" ("email", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c18a6a575dd94177e5d40cee71" ON "admin"."login_attempts" ("ipAddress", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."api_usage_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying(100), "userId" character varying(100), "apiKeyId" character varying(255), "method" character varying(10) NOT NULL, "endpoint" character varying(500) NOT NULL, "path" character varying(500) NOT NULL, "queryParams" jsonb, "requestSize" integer, "statusCode" integer NOT NULL, "responseSize" integer, "responseTimeMs" integer NOT NULL, "ipAddress" character varying(45) NOT NULL, "userAgent" character varying(500), "geoLocation" jsonb, "rateLimitRemaining" integer, "rateLimitExceeded" boolean NOT NULL DEFAULT false, "isError" boolean NOT NULL DEFAULT false, "errorCode" character varying(100), "errorMessage" text, "correlationId" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44911ac00797b4afb1be1cac1a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4520bc5a08a605f3479b93d1de" ON "admin"."api_usage_logs" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_17a1cbf2f3e790d01c2f260a66" ON "admin"."api_usage_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3814d9059774c701215859509b" ON "admin"."api_usage_logs" ("statusCode", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_562cbcb59074b802410ad1c976" ON "admin"."api_usage_logs" ("endpoint", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_167a31500c97a2221aca626f51" ON "admin"."api_usage_logs" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionToken" character varying(255) NOT NULL, "userId" character varying(100) NOT NULL, "userName" character varying(255) NOT NULL, "tenantId" character varying(100), "tenantName" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "ipAddress" character varying(45) NOT NULL, "geoLocation" jsonb, "deviceInfo" jsonb, "requestCount" integer NOT NULL DEFAULT '0', "lastActivityAt" TIMESTAMP WITH TIME ZONE NOT NULL, "lastActivityPath" character varying(500), "terminatedAt" TIMESTAMP WITH TIME ZONE, "terminationReason" character varying(50), "terminatedBy" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cd183bcb9ffe40bd858ed6b6b87" UNIQUE ("sessionToken"), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f04707a77dae48b72dffd2c89" ON "admin"."user_sessions" ("lastActivityAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cd183bcb9ffe40bd858ed6b6b8" ON "admin"."user_sessions" ("sessionToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_9129fe4a216108e1a227b4fee7" ON "admin"."user_sessions" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_36cbbaa23a16cc814fc39f1a7e" ON "admin"."user_sessions" ("userId", "isActive") `);
        await queryRunner.query(`CREATE TABLE "admin"."ingest_backend_policy_state" ("key" character varying(32) NOT NULL, "defaultBackend" character varying(8) NOT NULL, "overrides" jsonb NOT NULL DEFAULT '{}'::jsonb, "updatedBy" character varying(64), "version" integer NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c69a71db0e44d95cfff26287ac2" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "admin"."impersonation_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "superAdminId" uuid NOT NULL, "superAdminEmail" character varying(255), "targetTenantId" uuid NOT NULL, "targetTenantName" character varying(255), "targetUserId" uuid, "targetUserEmail" character varying(255), "status" character varying(50) NOT NULL DEFAULT 'active', "reason" character varying(50) NOT NULL, "reasonDetails" text, "ticketReference" text, "permissions" jsonb, "ipAddress" inet, "userAgent" text, "originalSessionToken" text, "impersonationToken" text, "mfaCompleted" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP NOT NULL, "endedAt" TIMESTAMP, "endReason" text, "actionsPerformed" jsonb, "actionCount" integer NOT NULL DEFAULT '0', "accessedResources" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b735433f13b4dd6f03bd6bf2879" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf24b4c9da8d20c05c970b011e" ON "admin"."impersonation_sessions" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_76c3422b461b26cd5fe1e63adc" ON "admin"."impersonation_sessions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_64bd389e4396a4b4712eb51370" ON "admin"."impersonation_sessions" ("status", "expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_166be7c9132ce5402b4942718a" ON "admin"."impersonation_sessions" ("targetTenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_971d53f5e0415b8c13ffc865fb" ON "admin"."impersonation_sessions" ("superAdminId", "status") `);
        await queryRunner.query(`CREATE TABLE "admin"."impersonation_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "superAdminId" uuid NOT NULL, "superAdminEmail" character varying(255), "canImpersonate" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "allowedTenants" jsonb, "restrictedTenants" jsonb, "defaultPermissions" jsonb, "maxSessionDurationMinutes" integer NOT NULL DEFAULT '60', "maxConcurrentSessions" integer NOT NULL DEFAULT '3', "requireReason" boolean NOT NULL DEFAULT true, "requireTicketReference" boolean NOT NULL DEFAULT false, "notifyTenantAdmin" boolean NOT NULL DEFAULT true, "grantedBy" uuid, "grantedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e16d05be3c8c5de63b93fc05fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef9642299aa2a53c0b00dd6ef5" ON "admin"."impersonation_permissions" ("superAdminId", "isActive") `);
        await queryRunner.query(`CREATE TABLE "admin"."debug_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adminId" uuid NOT NULL, "tenantId" uuid NOT NULL, "sessionType" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "configuration" jsonb, "filters" jsonb, "maxResults" integer NOT NULL DEFAULT '1000', "expiresAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d0af154ed9dd40f4bbd5321391" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6f5d2d9a7a153a0c75504ddfb" ON "admin"."debug_sessions" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f7cfbbb94ff68ad3b54190735" ON "admin"."debug_sessions" ("sessionType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9733c7e1b31fb50eccc3f61fa4" ON "admin"."debug_sessions" ("adminId", "tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."captured_queries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "debugSessionId" uuid, "tenantId" uuid NOT NULL, "userId" uuid, "queryType" character varying(50) NOT NULL, "query" text NOT NULL, "parameters" jsonb, "normalizedQuery" text, "durationMs" double precision NOT NULL, "rowsAffected" integer, "rowsReturned" integer, "tableName" text, "explainPlan" jsonb, "isSlowQuery" boolean NOT NULL DEFAULT false, "hasError" boolean NOT NULL DEFAULT false, "errorMessage" text, "stackTrace" text, "connectionSource" inet, "timestamp" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a83a730617980eb9497edfc490f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e0f03c808443508cf3465c08c" ON "admin"."captured_queries" ("queryType", "durationMs") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a44b8e9ca8a97937ee477e63b" ON "admin"."captured_queries" ("tenantId", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_9730d8fecdf220f12585fc77bb" ON "admin"."captured_queries" ("debugSessionId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "admin"."captured_api_calls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "debugSessionId" uuid, "tenantId" uuid NOT NULL, "userId" uuid, "method" character varying(10) NOT NULL, "endpoint" character varying(500) NOT NULL, "fullUrl" text, "requestHeaders" jsonb, "requestBody" jsonb, "queryParams" jsonb, "responseStatus" integer NOT NULL, "responseHeaders" jsonb, "responseBody" jsonb, "durationMs" double precision NOT NULL, "clientIp" inet, "userAgent" text, "correlationId" text, "hasError" boolean NOT NULL DEFAULT false, "errorMessage" text, "timestamp" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9f08e3723413cdff0edacc9b9f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_61847283d5c2ecd5546d290be9" ON "admin"."captured_api_calls" ("endpoint", "method") `);
        await queryRunner.query(`CREATE INDEX "IDX_246968d4a6a3808233bd3c2655" ON "admin"."captured_api_calls" ("tenantId", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_63550cde464ff4c9c7fb80b5b9" ON "admin"."captured_api_calls" ("debugSessionId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "admin"."cache_entries_snapshot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "debugSessionId" uuid, "tenantId" uuid, "key" character varying(500) NOT NULL, "value" jsonb, "sizeBytes" integer, "ttlSeconds" integer, "expiresAt" TIMESTAMP, "hitCount" integer NOT NULL DEFAULT '0', "lastAccessedAt" TIMESTAMP, "cacheStore" character varying(100), "tags" jsonb, "capturedAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_774d3973fb64a54907bb60af37e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bda2325698a58d92356241f712" ON "admin"."cache_entries_snapshot" ("tenantId", "key") `);
        await queryRunner.query(`CREATE INDEX "IDX_92448890c13ef06876d9c39693" ON "admin"."cache_entries_snapshot" ("debugSessionId", "capturedAt") `);
        await queryRunner.query(`CREATE TABLE "admin"."feature_flag_overrides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "featureKey" character varying(100) NOT NULL, "originalValue" jsonb NOT NULL, "overrideValue" jsonb NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "adminId" uuid NOT NULL, "reason" text, "expiresAt" TIMESTAMP, "appliedAt" TIMESTAMP, "revertedAt" TIMESTAMP, "revertedBy" uuid, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1cf17d8aa221874ceaa1c233315" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfb9d67252c978dc3cf6fae300" ON "admin"."feature_flag_overrides" ("adminId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_103566c810bfac928acbdc7bed" ON "admin"."feature_flag_overrides" ("tenantId", "featureKey") `);
        await queryRunner.query(`CREATE TABLE "admin"."tenant_schemas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "schemaName" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', "currentVersion" character varying(20) NOT NULL DEFAULT '1.0.0', "sizeBytes" bigint NOT NULL DEFAULT '0', "tableCount" integer NOT NULL DEFAULT '0', "connectionCount" integer NOT NULL DEFAULT '0', "maxConnections" integer NOT NULL DEFAULT '10', "metadata" jsonb, "lastMigrationAt" TIMESTAMP WITH TIME ZONE, "lastBackupAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e4ffd3eac852abe428c8944f37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5d9ae5909f33af16811a9ac85" ON "admin"."tenant_schemas" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6eed728a3cf02885b304914243" ON "admin"."tenant_schemas" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."schema_migrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid, "schemaName" character varying(100) NOT NULL, "migrationName" character varying(200) NOT NULL, "version" character varying(20) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "upScript" text, "downScript" text, "errorMessage" text, "executionTimeMs" integer NOT NULL DEFAULT '0', "isDryRun" boolean NOT NULL DEFAULT false, "affectedTables" jsonb, "executedBy" character varying(100), "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_62441bec32630ced9e4cccae336" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_519cd59acf6e054285a27584d6" ON "admin"."schema_migrations" ("version") `);
        await queryRunner.query(`CREATE INDEX "IDX_831d758a811b4de89f8c7b47be" ON "admin"."schema_migrations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1710033a4b7a54967b4669370d" ON "admin"."schema_migrations" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."schema_backups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid, "schemaName" character varying(100) NOT NULL, "backupType" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "filePath" character varying(500), "fileName" character varying(200), "sizeBytes" bigint NOT NULL DEFAULT '0', "checksum" character varying(64), "isEncrypted" boolean NOT NULL DEFAULT false, "isCompressed" boolean NOT NULL DEFAULT false, "retentionDays" integer NOT NULL DEFAULT '0', "errorMessage" text, "metadata" jsonb, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_221dda558c2c6012c20d0b11af9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e2c4f0f0b8ebd490dd2603913c" ON "admin"."schema_backups" ("backupType") `);
        await queryRunner.query(`CREATE INDEX "IDX_334842a6dd63aedadc9682356a" ON "admin"."schema_backups" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c7fdba223e7311e0e1e22b122" ON "admin"."schema_backups" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."schema_restores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "backupId" uuid NOT NULL, "tenantId" uuid, "targetSchemaName" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "isPointInTime" boolean NOT NULL DEFAULT false, "pointInTimeTarget" TIMESTAMP WITH TIME ZONE, "errorMessage" text, "executionTimeMs" integer NOT NULL DEFAULT '0', "executedBy" character varying(100), "restoredTables" jsonb, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f0f2c91713eadc9314cc62d9908" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18cbb3904678e355a4a484063d" ON "admin"."schema_restores" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c11b19e1c85d9c3e542d72d43" ON "admin"."schema_restores" ("backupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b27047ed5b11b4632ebc068fc3" ON "admin"."schema_restores" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."database_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid, "schemaName" character varying(100), "metricType" character varying(50) NOT NULL, "metrics" jsonb NOT NULL, "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0ada6148f805b66374057846e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8cd37a067adefc08eda051d80a" ON "admin"."database_metrics" ("metricType") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa926a4fe28e3521bc1f9d532a" ON "admin"."database_metrics" ("recordedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f066e451596406157ccaf8bc02" ON "admin"."database_metrics" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "admin"."slow_query_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid, "schemaName" character varying(100), "query" text NOT NULL, "normalizedQuery" text, "executionTimeMs" integer NOT NULL, "rowsAffected" integer NOT NULL DEFAULT '0', "rowsExamined" integer NOT NULL DEFAULT '0', "usedIndex" boolean NOT NULL DEFAULT false, "explainPlan" jsonb, "sourceTable" character varying(200), "userId" character varying(100), "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1e60f5b52bf87031fbb03fbf735" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88b82ab74a9724e2f3ad2e2fe5" ON "admin"."slow_query_logs" ("recordedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f59e4a98132110a1b049ef467" ON "admin"."slow_query_logs" ("executionTimeMs") `);
        await queryRunner.query(`CREATE INDEX "IDX_7435d694b2da5de23ac6b3dd21" ON "admin"."slow_query_logs" ("tenantId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."plan_definitions_tier_enum" AS ENUM('free', 'starter', 'professional', 'enterprise', 'custom'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."plan_definitions_visibility_enum" AS ENUM('public', 'private', 'deprecated'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE "admin"."plan_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "shortDescription" text, "tier" "admin"."plan_definitions_tier_enum" NOT NULL, "visibility" "admin"."plan_definitions_visibility_enum" NOT NULL DEFAULT 'public', "isActive" boolean NOT NULL DEFAULT true, "isRecommended" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "limits" jsonb NOT NULL, "pricing" jsonb NOT NULL, "features" jsonb NOT NULL, "trialDays" integer, "gracePeriodDays" integer, "upgradeMessage" text, "downgradeWarning" text, "stripeProductId" character varying, "stripePriceIds" jsonb, "icon" character varying, "color" character varying, "badge" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "UQ_96cc43e16c85d444749ac9aefa3" UNIQUE ("code"), CONSTRAINT "PK_d782695691e25ef94c39abc7b15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d33ff669638a9c36ae663a0ca4" ON "admin"."plan_definitions" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_efb19f72b138b0fd66086d5f3c" ON "admin"."plan_definitions" ("visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3012a24cdebe4be7e6c0a748e" ON "admin"."plan_definitions" ("tier") `);
        await queryRunner.query(`CREATE TABLE "admin"."plan_module_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "planId" uuid NOT NULL, "moduleId" uuid NOT NULL, "moduleCode" character varying(50) NOT NULL, "includedQuantities" jsonb NOT NULL DEFAULT '{}', "isRequired" boolean NOT NULL DEFAULT false, "allowOverage" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "plan_id" uuid, CONSTRAINT "UQ_2abc2ff4874ea413b6813d648d5" UNIQUE ("planId", "moduleId"), CONSTRAINT "PK_33b37c33d49c8de6a0ce1d4090f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_902d9dd7dba1869d6d9882673c" ON "admin"."plan_module_assignments" ("moduleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a16c627c2d4ebf741461872bc" ON "admin"."plan_module_assignments" ("planId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."discount_codes_discounttype_enum" AS ENUM('percentage', 'fixed_amount', 'free_trial_extension', 'free_months'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."discount_codes_appliesto_enum" AS ENUM('all_plans', 'specific_plans', 'upgrades_only', 'new_subscriptions_only'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."discount_codes_duration_enum" AS ENUM('once', 'repeating', 'forever'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE "admin"."discount_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "discountType" "admin"."discount_codes_discounttype_enum" NOT NULL, "discountValue" numeric(10,2) NOT NULL, "appliesTo" "admin"."discount_codes_appliesto_enum" NOT NULL DEFAULT 'all_plans', "applicablePlanIds" jsonb, "duration" "admin"."discount_codes_duration_enum" NOT NULL DEFAULT 'once', "durationInMonths" integer, "isActive" boolean NOT NULL DEFAULT true, "validFrom" TIMESTAMP WITH TIME ZONE, "validUntil" TIMESTAMP WITH TIME ZONE, "maxRedemptions" integer, "currentRedemptions" integer NOT NULL DEFAULT '0', "maxRedemptionsPerTenant" integer, "minimumOrderAmount" numeric(10,2), "campaignId" character varying, "campaignName" character varying, "stripePromotionCodeId" character varying, "stripeCouponId" character varying, "metadata" jsonb, "isReferralCode" boolean NOT NULL DEFAULT false, "referrerId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "UQ_b967edd0d46547d4a92b4a1c6b3" UNIQUE ("code"), CONSTRAINT "PK_c0170a28d937472e9ce50fdce17" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40feeb23f899de94bb29a0be76" ON "admin"."discount_codes" ("campaignId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc9304b48ccb3f0f705c18409e" ON "admin"."discount_codes" ("validFrom", "validUntil") `);
        await queryRunner.query(`CREATE INDEX "IDX_231083bda9d139908a2f18fcec" ON "admin"."discount_codes" ("isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b967edd0d46547d4a92b4a1c6b" ON "admin"."discount_codes" ("code") `);
        await queryRunner.query(`CREATE TABLE "admin"."discount_redemptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "discountCodeId" uuid NOT NULL, "tenantId" uuid NOT NULL, "subscriptionId" character varying, "invoiceId" character varying, "discountAmount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL, "redeemedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "redeemedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2efe685154f7c7deacaf6f0ef63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef8b61a54879ab4fabffce3491" ON "admin"."discount_redemptions" ("redeemedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0cec52f45cde0b2f12eb9b656" ON "admin"."discount_redemptions" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5bb1366b3ce8de8c4f1abcd629" ON "admin"."discount_redemptions" ("discountCodeId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."custom_plans_tier_enum" AS ENUM('free', 'starter', 'professional', 'enterprise', 'custom'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."custom_plans_billingcycle_enum" AS ENUM('monthly', 'quarterly', 'semi_annual', 'annual'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "admin"."custom_plans_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'active', 'expired', 'rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE "admin"."custom_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "basePlanId" uuid, "tier" "admin"."custom_plans_tier_enum" NOT NULL DEFAULT 'custom', "billingCycle" "admin"."custom_plans_billingcycle_enum" NOT NULL DEFAULT 'monthly', "modules" jsonb NOT NULL DEFAULT '[]', "monthlySubtotal" numeric(12,2) NOT NULL DEFAULT '0', "discountPercent" numeric(5,2) NOT NULL DEFAULT '0', "discountAmount" numeric(12,2) NOT NULL DEFAULT '0', "discountReason" character varying(100), "monthlyTotal" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "status" "admin"."custom_plans_status_enum" NOT NULL DEFAULT 'draft', "validFrom" date NOT NULL, "validTo" date, "approvedBy" uuid, "approvedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" text, "notes" text, "subscriptionId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" uuid, "updatedBy" uuid, "base_plan_id" uuid, CONSTRAINT "PK_fe23d575a11629355fca3abfb52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51021e974043b0ca0728b55980" ON "admin"."custom_plans" ("validFrom") `);
        await queryRunner.query(`CREATE INDEX "IDX_49d7e49305b38e8aadacaf064e" ON "admin"."custom_plans" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cd2a32aad93f542e0771bb51f" ON "admin"."custom_plans" ("tenantId") `);
        await queryRunner.query(`ALTER TABLE "admin"."messages" ADD CONSTRAINT "FK_15f9bd2bf472ff12b6ee20012d0" FOREIGN KEY ("threadId") REFERENCES "admin"."message_threads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin"."announcement_acknowledgments" ADD CONSTRAINT "FK_5b31e3f30a25937e045cfba3d6d" FOREIGN KEY ("announcementId") REFERENCES "admin"."announcements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin"."ticket_comments" ADD CONSTRAINT "FK_f6beba8ae36e1ce20968d7a3192" FOREIGN KEY ("ticketId") REFERENCES "admin"."support_tickets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin"."plan_module_assignments" ADD CONSTRAINT "FK_b9030d651d6a352411618af8a03" FOREIGN KEY ("plan_id") REFERENCES "admin"."plan_definitions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin"."custom_plans" ADD CONSTRAINT "FK_07c65d2a248b7234c606436928d" FOREIGN KEY ("base_plan_id") REFERENCES "admin"."plan_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);

        // ── Faz 3.5 hand-author addition — audit immutability triggers ──
        await queryRunner.query(`
            CREATE OR REPLACE FUNCTION "admin".audit_logs_prevent_update_or_delete()
            RETURNS trigger AS $auditguard$
            BEGIN
              RAISE EXCEPTION 'Audit table "admin"."audit_logs" is append-only; UPDATE/DELETE refused (Faz 1.4 protected-tables-guard).';
            END;
            $auditguard$ LANGUAGE plpgsql;
        `);
        await queryRunner.query(`
            CREATE TRIGGER trg_audit_logs_prevent_update
            BEFORE UPDATE OR DELETE ON "admin"."audit_logs"
            FOR EACH ROW EXECUTE FUNCTION "admin".audit_logs_prevent_update_or_delete();
        `);
        await queryRunner.query(`
            REVOKE UPDATE, DELETE ON "admin"."audit_logs" FROM PUBLIC;
        `);
        await queryRunner.query(`
            CREATE OR REPLACE FUNCTION "admin".impersonation_sessions_prevent_update_or_delete()
            RETURNS trigger AS $auditguard$
            BEGIN
              RAISE EXCEPTION 'Audit table "admin"."impersonation_sessions" is append-only; UPDATE/DELETE refused (Faz 1.4 protected-tables-guard).';
            END;
            $auditguard$ LANGUAGE plpgsql;
        `);
        await queryRunner.query(`
            CREATE TRIGGER trg_impersonation_sessions_prevent_update
            BEFORE UPDATE OR DELETE ON "admin"."impersonation_sessions"
            FOR EACH ROW EXECUTE FUNCTION "admin".impersonation_sessions_prevent_update_or_delete();
        `);
        await queryRunner.query(`
            REVOKE UPDATE, DELETE ON "admin"."impersonation_sessions" FROM PUBLIC;
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Reverse Faz 3.5 audit immutability triggers
        await queryRunner.query(`DROP TRIGGER IF EXISTS trg_audit_logs_prevent_update ON "admin"."audit_logs";`);
        await queryRunner.query(`DROP FUNCTION IF EXISTS "admin".audit_logs_prevent_update_or_delete();`);
        await queryRunner.query(`DROP TRIGGER IF EXISTS trg_impersonation_sessions_prevent_update ON "admin"."impersonation_sessions";`);
        await queryRunner.query(`DROP FUNCTION IF EXISTS "admin".impersonation_sessions_prevent_update_or_delete();`);
        await queryRunner.query(`ALTER TABLE "admin"."custom_plans" DROP CONSTRAINT "FK_07c65d2a248b7234c606436928d"`);
        await queryRunner.query(`ALTER TABLE "admin"."plan_module_assignments" DROP CONSTRAINT "FK_b9030d651d6a352411618af8a03"`);
        await queryRunner.query(`ALTER TABLE "admin"."ticket_comments" DROP CONSTRAINT "FK_f6beba8ae36e1ce20968d7a3192"`);
        await queryRunner.query(`ALTER TABLE "admin"."announcement_acknowledgments" DROP CONSTRAINT "FK_5b31e3f30a25937e045cfba3d6d"`);
        await queryRunner.query(`ALTER TABLE "admin"."messages" DROP CONSTRAINT "FK_15f9bd2bf472ff12b6ee20012d0"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_1cd2a32aad93f542e0771bb51f"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_49d7e49305b38e8aadacaf064e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_51021e974043b0ca0728b55980"`);
        await queryRunner.query(`DROP TABLE "admin"."custom_plans"`);
        await queryRunner.query(`DROP TYPE "admin"."custom_plans_status_enum"`);
        await queryRunner.query(`DROP TYPE "admin"."custom_plans_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "admin"."custom_plans_tier_enum"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_5bb1366b3ce8de8c4f1abcd629"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_a0cec52f45cde0b2f12eb9b656"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_ef8b61a54879ab4fabffce3491"`);
        await queryRunner.query(`DROP TABLE "admin"."discount_redemptions"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b967edd0d46547d4a92b4a1c6b"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_231083bda9d139908a2f18fcec"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_bc9304b48ccb3f0f705c18409e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_40feeb23f899de94bb29a0be76"`);
        await queryRunner.query(`DROP TABLE "admin"."discount_codes"`);
        await queryRunner.query(`DROP TYPE "admin"."discount_codes_duration_enum"`);
        await queryRunner.query(`DROP TYPE "admin"."discount_codes_appliesto_enum"`);
        await queryRunner.query(`DROP TYPE "admin"."discount_codes_discounttype_enum"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_1a16c627c2d4ebf741461872bc"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_902d9dd7dba1869d6d9882673c"`);
        await queryRunner.query(`DROP TABLE "admin"."plan_module_assignments"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e3012a24cdebe4be7e6c0a748e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_efb19f72b138b0fd66086d5f3c"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_d33ff669638a9c36ae663a0ca4"`);
        await queryRunner.query(`DROP TABLE "admin"."plan_definitions"`);
        await queryRunner.query(`DROP TYPE "admin"."plan_definitions_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "admin"."plan_definitions_tier_enum"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_7435d694b2da5de23ac6b3dd21"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_7f59e4a98132110a1b049ef467"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_88b82ab74a9724e2f3ad2e2fe5"`);
        await queryRunner.query(`DROP TABLE "admin"."slow_query_logs"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_f066e451596406157ccaf8bc02"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_fa926a4fe28e3521bc1f9d532a"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_8cd37a067adefc08eda051d80a"`);
        await queryRunner.query(`DROP TABLE "admin"."database_metrics"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b27047ed5b11b4632ebc068fc3"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_3c11b19e1c85d9c3e542d72d43"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_18cbb3904678e355a4a484063d"`);
        await queryRunner.query(`DROP TABLE "admin"."schema_restores"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_4c7fdba223e7311e0e1e22b122"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_334842a6dd63aedadc9682356a"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e2c4f0f0b8ebd490dd2603913c"`);
        await queryRunner.query(`DROP TABLE "admin"."schema_backups"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_1710033a4b7a54967b4669370d"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_831d758a811b4de89f8c7b47be"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_519cd59acf6e054285a27584d6"`);
        await queryRunner.query(`DROP TABLE "admin"."schema_migrations"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_6eed728a3cf02885b304914243"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e5d9ae5909f33af16811a9ac85"`);
        await queryRunner.query(`DROP TABLE "admin"."tenant_schemas"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_103566c810bfac928acbdc7bed"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cfb9d67252c978dc3cf6fae300"`);
        await queryRunner.query(`DROP TABLE "admin"."feature_flag_overrides"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_92448890c13ef06876d9c39693"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_bda2325698a58d92356241f712"`);
        await queryRunner.query(`DROP TABLE "admin"."cache_entries_snapshot"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_63550cde464ff4c9c7fb80b5b9"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_246968d4a6a3808233bd3c2655"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_61847283d5c2ecd5546d290be9"`);
        await queryRunner.query(`DROP TABLE "admin"."captured_api_calls"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_9730d8fecdf220f12585fc77bb"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_9a44b8e9ca8a97937ee477e63b"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_4e0f03c808443508cf3465c08c"`);
        await queryRunner.query(`DROP TABLE "admin"."captured_queries"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_9733c7e1b31fb50eccc3f61fa4"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_7f7cfbbb94ff68ad3b54190735"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c6f5d2d9a7a153a0c75504ddfb"`);
        await queryRunner.query(`DROP TABLE "admin"."debug_sessions"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_ef9642299aa2a53c0b00dd6ef5"`);
        await queryRunner.query(`DROP TABLE "admin"."impersonation_permissions"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_971d53f5e0415b8c13ffc865fb"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_166be7c9132ce5402b4942718a"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_64bd389e4396a4b4712eb51370"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_76c3422b461b26cd5fe1e63adc"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cf24b4c9da8d20c05c970b011e"`);
        await queryRunner.query(`DROP TABLE "admin"."impersonation_sessions"`);
        await queryRunner.query(`DROP TABLE "admin"."ingest_backend_policy_state"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_36cbbaa23a16cc814fc39f1a7e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_9129fe4a216108e1a227b4fee7"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cd183bcb9ffe40bd858ed6b6b8"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_1f04707a77dae48b72dffd2c89"`);
        await queryRunner.query(`DROP TABLE "admin"."user_sessions"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_167a31500c97a2221aca626f51"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_562cbcb59074b802410ad1c976"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_3814d9059774c701215859509b"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_17a1cbf2f3e790d01c2f260a66"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_4520bc5a08a605f3479b93d1de"`);
        await queryRunner.query(`DROP TABLE "admin"."api_usage_logs"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c18a6a575dd94177e5d40cee71"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_46dd77d64eb0ed0d65383ac4ed"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_25bbd36a1c5a95b276d7e6a1df"`);
        await queryRunner.query(`DROP TABLE "admin"."login_attempts"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cedc8b5aad835580a30405d2e7"`);
        await queryRunner.query(`DROP TABLE "admin"."retention_policies"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_38b7611329ac08db87188a813e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cbb8641e16ba161c4e6135a088"`);
        await queryRunner.query(`DROP TABLE "admin"."compliance_reports"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_98cff932473408b2fd56ab6281"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_349764678e08e126ab7820adbb"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b10e5db5fa2e75fd12b9c9f0bc"`);
        await queryRunner.query(`DROP TABLE "admin"."data_requests"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b7c014d92e2086de80f60daf27"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_f6c659e082e916028de28a963e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_069229793d0509e1311f853e89"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_236cea9d2fe4ca9079efd9bd46"`);
        await queryRunner.query(`DROP TABLE "admin"."threat_intelligence"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_781b94dc7e41d2958b30b4f395"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_61f66171aa0c8a1456650aae2e"`);
        await queryRunner.query(`DROP TABLE "admin"."security_incidents"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_2c2235261ba6518fa4a686f6f5"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_5595f413d4ecb718842f8aab06"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_f3e3edb95aee90264572beb037"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_eb708bf77f760210d747550b91"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_4d52eb18cb798b56183a5ba026"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_31ea8d94d66808cbcfb6802996"`);
        await queryRunner.query(`DROP TABLE "admin"."security_events"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_1a2825dd99a0eb1aeded63709d"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_412f03f2a073c89f8918e6ae52"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_0b57258b9301304728fdc0b3c8"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_fa2f8e99469cc6d494c8612896"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_52c7ccae32a5bdc10f1257ee88"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_a306e3adc99c4e21fc4a155433"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_a3d5764d4b44970698381dc664"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_377463c364326082e86ce68ed3"`);
        await queryRunner.query(`DROP TABLE "admin"."activity_logs"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e0026a4e23e66199b0c5053a8c"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_ccc49003f73349d071957fd990"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_6ae0dcdff7166137228bb61e0a"`);
        await queryRunner.query(`DROP TABLE "admin"."ip_access_rules"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e65f590d27b63f71b3d3e01dd3"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_109c25f9c6301dc8a0f9c0f39d"`);
        await queryRunner.query(`DROP TABLE "admin"."email_templates"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b1b5bc664526d375c94ce9ad43"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_797d199fff9037e5b231dc4ffb"`);
        await queryRunner.query(`DROP TABLE "admin"."system_settings"`);
        await queryRunner.query(`DROP TYPE "admin"."system_settings_category_enum"`);
        await queryRunner.query(`DROP TYPE "admin"."system_settings_valuetype_enum"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_03485c758a380c96574bb38088"`);
        await queryRunner.query(`DROP TABLE "admin"."tenant_configurations"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_d7e40302edaabf40ab5c4b1ed9"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e27193d00cd9c6857b01652a1b"`);
        await queryRunner.query(`DROP TABLE "admin"."onboarding_progress"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_f6beba8ae36e1ce20968d7a319"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_4497112178bae33622ee27543e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_2f0f4740214d1c081ea469882f"`);
        await queryRunner.query(`DROP TABLE "admin"."ticket_comments"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_7f39d4242941c82c75c939c7e0"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_ba7b1a2ed4051fb3b39ff95444"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cae81694804986ef32be155d34"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_0d15c3ab16e6b23291cc17f33d"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c2302659dc5e2f79b1d1288ca7"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b735528ffad34f697758a00d2a"`);
        await queryRunner.query(`DROP TABLE "admin"."support_tickets"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_5b31e3f30a25937e045cfba3d6"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_694820afeb2fdb3a6f5f17528a"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_ba4b92cd3ce9d8fe5fc560661d"`);
        await queryRunner.query(`DROP TABLE "admin"."announcement_acknowledgments"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c45985989bc600ab871ef1eaf8"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_472dcde086b0881656f29b94af"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_0fabf411618aba4c3c7790fd31"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c673e84b342a18f9354860e509"`);
        await queryRunner.query(`DROP TABLE "admin"."announcements"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_15f9bd2bf472ff12b6ee20012d"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_2db9cf2b3ca111742793f6c37c"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_6ce6acdb0801254590f8a78c08"`);
        await queryRunner.query(`DROP TABLE "admin"."messages"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_8bccdf9b34dc6b06fc2636856f"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_73903d13c2f9512f42fc31ccbb"`);
        await queryRunner.query(`DROP TABLE "admin"."message_threads"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_02327e60ee0e6571fdfc1f5635"`);
        await queryRunner.query(`DROP TABLE "admin"."error_alert_rules"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_d8a1adf467f843f858c925bdb8"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_61b83f6089b63ff83d53f1fbee"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_39e0d1c4fba46fb536e8203d9b"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_06fe86c67a37a12ddea9682fa8"`);
        await queryRunner.query(`DROP TABLE "admin"."error_groups"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_aa824faa2275f2114949e652c9"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_8495b7a8f6dadb50a731a6f225"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_d7184177974c6f54d1643acf35"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_e49c09acd070928e54f7c4df2b"`);
        await queryRunner.query(`DROP TABLE "admin"."error_occurrences"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_682ae3334b02dd3f1b7b9823be"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_2146b3af12d7c699ee461cd091"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_229fe7feee0c72214f09b4ca57"`);
        await queryRunner.query(`DROP TABLE "admin"."feature_toggles"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_de954a917c3d76ababc6dcca9e"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_5d456cabba2f3e3856a113ee2d"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_40b26ec4ae1e1bd8b46f8b7532"`);
        await queryRunner.query(`DROP TABLE "admin"."global_configs"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_f5d9039d80efa55807e9bc5733"`);
        await queryRunner.query(`DROP TABLE "admin"."job_queues"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_edbff5cdb364327758316c3390"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_9886a1e22fa2cd6fe21800d41a"`);
        await queryRunner.query(`DROP TABLE "admin"."job_execution_logs"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b9736047b77fb3669502f92f9a"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_9d5e7a51042582e68ba4a6f9ab"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_aef6af03a7effa02df1779a0e8"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_b63908dfa5591d40355d7d926a"`);
        await queryRunner.query(`DROP TABLE "admin"."background_jobs"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_37ff6ca278f8354a91cfa8e2dc"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_24594798d636558f63c106f9c7"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_f1a1ce8c991a35199ab72b8d79"`);
        await queryRunner.query(`DROP TABLE "admin"."maintenance_modes"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_3bc64380eb042b5d7e6b7a6463"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_eaeadc987378984be1360f7504"`);
        await queryRunner.query(`DROP TABLE "admin"."performance_snapshots"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_255b3adadd4d505f707c4e131d"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_d15fbd3d1847c96f7865ad35a1"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_38735a10939289547b9d0b8e0b"`);
        await queryRunner.query(`DROP TABLE "admin"."performance_metrics"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_1a1ac1474ad32b265537b01767"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_6be4daa72cc602cd66bb4a20cb"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c2aec3650bafd17a147de05b9b"`);
        await queryRunner.query(`DROP TABLE "admin"."system_versions"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_94bf8f5742c39d367bcf5f4f17"`);
        await queryRunner.query(`DROP TABLE "admin"."tenant_billing_info"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_7d7492898eb27032baddb41559"`);
        await queryRunner.query(`DROP TABLE "admin"."tenant_notes"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_868c21a770df72304f70315a55"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_63c18b160e36cccb2f656e1373"`);
        await queryRunner.query(`DROP TABLE "admin"."tenant_activities"`);
        await queryRunner.query(`DROP TYPE "admin"."tenant_activities_activitytype_enum"`);
        await queryRunner.query(`DROP INDEX "shared"."idx_user_permissions_user"`);
        await queryRunner.query(`DROP INDEX "shared"."idx_user_permissions_tenant"`);
        await queryRunner.query(`DROP INDEX "shared"."idx_user_permissions_user_tenant_unique"`);
        await queryRunner.query(`DROP TABLE "shared"."user_permissions"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_a8bd8d95914d6228770fe87b8a"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_889633a4291bcb0bf4680fff23"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "admin"."IDX_3197969cb5ed9b2a00252a3c9e"`);
        await queryRunner.query(`DROP TABLE "admin"."audit_logs"`);
        await queryRunner.query(`DROP TYPE "admin"."audit_logs_severity_enum"`);
    }

}
