import { MigrationInterface, QueryRunner } from 'typeorm';

export class TenantProvisioningWorkflow1800400000000 implements MigrationInterface {
  name = 'TenantProvisioningWorkflow1800400000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "admin"."admin_outbox" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "eventType" VARCHAR(100) NOT NULL,
        "tenantId" UUID NULL,
        "aggregateId" UUID NULL,
        "payload" JSONB NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "publishedAt" TIMESTAMPTZ NULL,
        "retryCount" INTEGER NOT NULL DEFAULT 0,
        "lastError" TEXT NULL,
        "nextAttemptAt" TIMESTAMPTZ NULL,
        "idempotencyKey" VARCHAR(255) NULL,
        "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
        "leasedAt" TIMESTAMPTZ NULL,
        "leasedBy" VARCHAR(128) NULL
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_admin_outbox_poll"
        ON "admin"."admin_outbox" ("createdAt")
        WHERE "publishedAt" IS NULL AND "isDeadLettered" = false
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_admin_outbox_tenant"
        ON "admin"."admin_outbox" ("tenantId")
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "idx_admin_outbox_idempotency"
        ON "admin"."admin_outbox" ("tenantId", "idempotencyKey")
        WHERE "idempotencyKey" IS NOT NULL
    `);

    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION "admin"."notify_admin_outbox_new"()
      RETURNS TRIGGER AS $$
      BEGIN
        PERFORM pg_notify('admin_outbox_notify', '');
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `);
    await queryRunner.query(`
      DROP TRIGGER IF EXISTS "admin_outbox_notify_trigger"
        ON "admin"."admin_outbox"
    `);
    await queryRunner.query(`
      CREATE TRIGGER "admin_outbox_notify_trigger"
        AFTER INSERT ON "admin"."admin_outbox"
        FOR EACH ROW
        EXECUTE FUNCTION "admin"."notify_admin_outbox_new"()
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "admin"."tenant_provisioning_runs" (
        "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        "tenantId" UUID NOT NULL,
        "idempotencyKey" VARCHAR(128) NOT NULL,
        "requestHash" VARCHAR(64) NOT NULL,
        "requestPayload" JSONB NOT NULL DEFAULT '{}',
        "actorUserId" UUID NOT NULL,
        "state" VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
        "currentStep" VARCHAR(100) NULL,
        "lastError" TEXT NULL,
        "attempts" INTEGER NOT NULL DEFAULT 0,
        "nextRetryAt" TIMESTAMPTZ NULL,
        "startedAt" TIMESTAMPTZ NULL,
        "completedAt" TIMESTAMPTZ NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "chk_tenant_provisioning_runs_state"
          CHECK ("state" IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
        CONSTRAINT "fk_tenant_provisioning_runs_tenant"
          FOREIGN KEY ("tenantId") REFERENCES "auth"."tenants"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uk_tenant_provisioning_runs_actor_key"
        ON "admin"."tenant_provisioning_runs" ("actorUserId", "idempotencyKey")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_tenant_provisioning_runs_tenant"
        ON "admin"."tenant_provisioning_runs" ("tenantId", "createdAt" DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_tenant_provisioning_runs_state"
        ON "admin"."tenant_provisioning_runs" ("state", "nextRetryAt", "createdAt")
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "admin"."tenant_provisioning_steps" (
        "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        "runId" UUID NOT NULL,
        "stepName" VARCHAR(100) NOT NULL,
        "state" VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
        "attempts" INTEGER NOT NULL DEFAULT 0,
        "lastError" TEXT NULL,
        "startedAt" TIMESTAMPTZ NULL,
        "completedAt" TIMESTAMPTZ NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "chk_tenant_provisioning_steps_state"
          CHECK ("state" IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
        CONSTRAINT "fk_tenant_provisioning_steps_run"
          FOREIGN KEY ("runId") REFERENCES "admin"."tenant_provisioning_runs"("id") ON DELETE CASCADE,
        CONSTRAINT "uk_tenant_provisioning_steps_run_step" UNIQUE ("runId", "stepName")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_tenant_provisioning_steps_run"
        ON "admin"."tenant_provisioning_steps" ("runId", "createdAt")
    `);

    await queryRunner.query(`
      DO $admin_service_tenant_provisioning_permissions$
      BEGIN
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin_service') THEN
          EXECUTE format('GRANT CREATE ON DATABASE %I TO admin_service', current_database());

          GRANT USAGE ON SCHEMA "auth", "admin", "shared" TO "admin_service";

          GRANT SELECT ON TABLE
            "auth"."tenants",
            "auth"."tenant_modules",
            "auth"."tenant_roles",
            "auth"."users",
            "auth"."invitations",
            "auth"."modules"
          TO "admin_service";

          GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
            "shared"."user_permissions"
          TO "admin_service";

          GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
            "admin"."tenant_configurations",
            "admin"."tenant_schemas",
            "admin"."audit_logs",
            "admin"."admin_outbox",
            "admin"."tenant_provisioning_runs",
            "admin"."tenant_provisioning_steps"
          TO "admin_service";
        END IF;
      END $admin_service_tenant_provisioning_permissions$;
    `);

    await queryRunner.query(`
      COMMENT ON TABLE "admin"."tenant_provisioning_runs" IS
        'grant_admin_service_tenant_provisioning_permissions'
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    // Forward-only operational ledger. Rows are evidence for tenant creation attempts.
  }
}
