[build]
target-dir = "target"

[net]
git-fetch-with-cli = true

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[alias]
xclippy = "clippy --workspace --all-targets --all-features -- -D warnings"
xtest = "test --workspace --all-features"
xfmt = "fmt --all"
xfmt-check = "fmt --all -- --check"
xdeny = "deny check"
