import { MigrationInterface, QueryRunner } from 'typeorm';
import * as crypto from 'crypto';

/**
 * SENSOR-MEDIUM-001: provisioning secrets stored in clear at rest.
 *
 * `edge_devices.provisioning_token` and `tenant_provisioning_keys.key_token`
 * were persisted as the raw 256-bit token, so a database read (backup leak,
 * SQL injection, rogue DBA) yielded a directly replayable credential. Both are
 * high-entropy random values, so a plain SHA-256 digest at rest is sufficient
 * to make a leak non-replayable (pre-image resistance) — no salt/stretching
 * needed. SHA-256 hex is exactly 64 chars, matching the existing `varchar(64)`
 * columns, so no schema change is required.
 *
 * This migration rewrites the existing rows in place to `sha256(value)` (hex).
 * Both columns are per-tenant, so the rewrite fans out across the canonical
 * `sensor` source schema AND every provisioned `tenant_*` schema.
 *
 * DEPLOY ORDERING: run this migration ahead of (or together with) the code that
 * writes/validates hashes. Provisioning tokens are single-use and short-lived
 * (default 24h TTL); any token minted by the previous code version in the brief
 * deploy window can simply be regenerated by the operator. No column is dropped
 * or made NOT NULL — blue-green safe.
 *
 * TENANT_AWARE_SOURCE_SCHEMA_DDL_OK: db-migrate-owned per-tenant data rewrite.
 */
export class HashProvisioningSecretsAtRest1803000000000 implements MigrationInterface {
  name = 'HashProvisioningSecretsAtRest1803000000000';

  private sha256Hex(value: string): string {
    return crypto.createHash('sha256').update(value).digest('hex');
  }

  /**
   * Rewrite `column` on `table` to its SHA-256 hex digest across every schema
   * that physically holds the table (the `sensor` source template + all
   * provisioned tenant schemas). Skips values that are already a 64-char hex
   * digest so a re-run cannot double-hash.
   */
  private async hashColumn(
    queryRunner: QueryRunner,
    table: string,
    column: string,
  ): Promise<void> {
    const schemas: { table_schema: string }[] = await queryRunner.query(
      `SELECT table_schema FROM information_schema.tables
       WHERE table_name = $1
         AND (table_schema = 'sensor' OR table_schema ~ '^tenant_[a-f0-9]{16}$')`,
      [table],
    );

    for (const { table_schema } of schemas) {
      const rows: { id: string; value: string }[] = await queryRunner.query(
        `SELECT id, "${column}" AS value FROM "${table_schema}"."${table}"
         WHERE "${column}" IS NOT NULL`,
      );
      for (const row of rows) {
        const hashed = this.sha256Hex(row.value);
        // Guard on the original value: a row concurrently rewritten by
        // newly-deployed code is left untouched rather than clobbered.
        await queryRunner.query(
          `UPDATE "${table_schema}"."${table}" SET "${column}" = $1
           WHERE id = $2 AND "${column}" = $3`,
          [hashed, row.id, row.value],
        );
      }
    }
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    await this.hashColumn(queryRunner, 'edge_devices', 'provisioning_token');
    await this.hashColumn(queryRunner, 'tenant_provisioning_keys', 'key_token');
  }

  public async down(): Promise<void> {
    // SHA-256 is a one-way function: the plaintext cannot be reconstructed.
    // There is no lossless inverse, so `down` is intentionally a no-op. Rolling
    // the code back must be paired with issuing fresh provisioning credentials.
  }
}
