import { MigrationInterface, QueryRunner } from "typeorm";

import { applyTenantRlsToSchema, removeTenantRlsFromSchema } from '@aquaculture/backend-common/database'; // Faz 3.5 RLS additions: import block
export class Baseline1800000000000 implements MigrationInterface {
    name = 'Baseline1800000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."training_courses_trainingtype_enum" AS ENUM('online', 'in_person', 'blended', 'on_the_job', 'self_paced'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."training_courses_level_enum" AS ENUM('beginner', 'intermediate', 'advanced', 'expert'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "training_courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "code" character varying(30) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "trainingType" "hr"."training_courses_trainingtype_enum" NOT NULL DEFAULT 'in_person', "level" "hr"."training_courses_level_enum" NOT NULL DEFAULT 'beginner', "durationMinutes" integer NOT NULL DEFAULT '60', "cost" numeric(8,2), "isMandatory" boolean NOT NULL DEFAULT false, "requiresAssessment" boolean NOT NULL DEFAULT false, "passingScore" numeric(5,2), "maxAttempts" integer, "validityMonths" integer, "certificationTypeId" character varying, "prerequisites" text, "targetRoles" text, "targetDepartments" text, "isOffshoreRequired" boolean NOT NULL DEFAULT false, "externalUrl" character varying(500), "provider" character varying(200), "displayOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_13bbeecb2ed8a1f45be3c02d68e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64e34988cf6f84917f49bf8044" ON "training_courses" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6e3e7e405046d8e8b98892278" ON "training_courses" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b71df07d8dfaf6edb78948b44" ON "training_courses" ("tenantId", "isMandatory") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_75d8931075f6843da349e54b40" ON "training_courses" ("tenantId", "code") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."payrolls_payperiodtype_enum" AS ENUM('weekly', 'bi_weekly', 'semi_monthly', 'monthly'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."payrolls_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'processing', 'paid', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "payrolls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "payrollNumber" character varying NOT NULL, "payPeriodType" "hr"."payrolls_payperiodtype_enum" NOT NULL, "payPeriodStart" date NOT NULL, "payPeriodEnd" date NOT NULL, "paymentDate" date, "workHours" jsonb NOT NULL, "earningsBaseSalary" numeric(12,2) NOT NULL, "earningsOvertime" numeric(12,2), "earningsBonus" numeric(12,2), "earningsCommission" numeric(12,2), "earningsAllowances" numeric(12,2), "earningsGrossPay" numeric(12,2) NOT NULL, "deductionsTax" numeric(12,2), "deductionsSocialSecurity" numeric(12,2), "deductionsHealthInsurance" numeric(12,2), "deductionsRetirement" numeric(12,2), "deductionsOther" numeric(12,2), "deductionsTotal" numeric(12,2) NOT NULL, "netPay" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "status" "hr"."payrolls_status_enum" NOT NULL DEFAULT 'draft', "approvedBy" character varying, "approvedAt" TIMESTAMP WITH TIME ZONE, "notes" text, "paymentReference" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, CONSTRAINT "PK_4fc19dcf3522661435565b5ecf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2707bcd6c6dbd53414384b515e" ON "payrolls" ("tenantId", "payPeriodStart") `);
        await queryRunner.query(`CREATE INDEX "IDX_26bd770ae67d72656c58eb3e41" ON "payrolls" ("tenantId", "paymentDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_583917de31260b8403cd437483" ON "payrolls" ("tenantId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9bfade608f449383d28e472f22" ON "payrolls" ("tenantId", "payrollNumber") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b5dae33d42bab08b87a931720b" ON "payrolls" ("tenantId", "employeeId", "payPeriodStart", "payPeriodEnd") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "departments_hr" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "siteId" character varying, "parentDepartmentId" character varying, "name" character varying(150) NOT NULL, "code" character varying(20) NOT NULL, "description" text, "managerId" character varying, "budgetCode" character varying(50), "costCenter" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_c38890806b31f7c6b96b85f5033" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5706166cae13216642b941e0ae" ON "departments_hr" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc20c4af22a312e99ceca2fbee" ON "departments_hr" ("tenantId", "siteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_646949e173019eb733a38964c7" ON "departments_hr" ("tenantId", "isDeleted") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dc3b7d261ba9dbcaa814366038" ON "departments_hr" ("tenantId", "code") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."employees_status_enum" AS ENUM('active', 'on_leave', 'terminated', 'suspended'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."employees_employmenttype_enum" AS ENUM('full_time', 'part_time', 'contract', 'seasonal'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."employees_department_enum" AS ENUM('operations', 'maintenance', 'feeding', 'quality_control', 'administration', 'management', 'logistics', 'security'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."employees_personnelcategory_enum" AS ENUM('offshore', 'onshore', 'hybrid'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeNumber" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "contactInfo" jsonb NOT NULL, "address" jsonb NOT NULL, "dateOfBirth" date NOT NULL, "nationalId" text NOT NULL, "status" "hr"."employees_status_enum" NOT NULL DEFAULT 'active', "employmentType" "hr"."employees_employmenttype_enum" NOT NULL, "department" "hr"."employees_department_enum" NOT NULL, "position" character varying NOT NULL, "hireDate" date NOT NULL, "terminationDate" date, "baseSalary" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "bankDetails" text, "farmId" character varying, "supervisorId" character varying, "userId" character varying, "certifications" text, "skills" text, "personnelCategory" "hr"."employees_personnelcategory_enum", "assignedWorkAreas" text, "seaWorthy" boolean NOT NULL DEFAULT false, "positionId" character varying, "departmentHrId" uuid, "emergencyInfo" jsonb, "currentRotationId" uuid, "timezone" character varying(50) DEFAULT 'UTC', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "deletedAt" TIMESTAMP, "isDeleted" boolean NOT NULL DEFAULT false, "isFarmWorker" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a240a705116b09288ddb33881" ON "employees" ("tenantId", "seaWorthy") `);
        await queryRunner.query(`CREATE INDEX "IDX_64e94ad71585bfafc485cd8eb4" ON "employees" ("tenantId", "personnelCategory") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f56de9a9d90cc0d9c54d3d527" ON "employees" ("tenantId", "farmId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8e1c46f48d1080fd7d472c8ac" ON "employees" ("tenantId", "departmentHrId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0e4b9f3e9e82b05072fce2069" ON "employees" ("tenantId", "department") `);
        await queryRunner.query(`CREATE INDEX "idx_employee_status_tenant" ON "employees" ("status", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "idx_employee_department" ON "employees" ("departmentHrId") `);
        await queryRunner.query(`CREATE INDEX "idx_employee_email" ON "employees" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_employee_number_tenant" ON "employees" ("employeeNumber", "tenantId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_employee_email_tenant" ON "employees" ("tenantId", "email") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."certification_types_category_enum" AS ENUM('diving', 'safety', 'vessel', 'equipment', 'first_aid', 'food_handling', 'environmental', 'management', 'technical', 'other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."certification_types_requirement_enum" AS ENUM('mandatory', 'recommended', 'optional'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "certification_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "code" character varying(30) NOT NULL, "name" character varying(150) NOT NULL, "description" text, "category" "hr"."certification_types_category_enum" NOT NULL DEFAULT 'other', "requirement" "hr"."certification_types_requirement_enum" NOT NULL DEFAULT 'optional', "issuingAuthority" character varying(200), "validityMonths" integer, "renewalReminderDays" integer, "requiresRenewal" boolean NOT NULL DEFAULT false, "requiresPhysicalAssessment" boolean NOT NULL DEFAULT false, "isOffshoreRequired" boolean NOT NULL DEFAULT false, "isDivingRequired" boolean NOT NULL DEFAULT false, "isSTCW" boolean NOT NULL DEFAULT false, "applicableWorkAreas" text, "prerequisiteCertifications" text, "colorCode" character varying(7), "displayOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_01821f7de39ed6aafbd5524203c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9330b8069a3ed9755b22bd47dc" ON "certification_types" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa9aca12ef0d70c92e7b744cc0" ON "certification_types" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_0eba2821560680ebf7459f2f71" ON "certification_types" ("tenantId", "category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e762b98622e96f4af4aa34d451" ON "certification_types" ("tenantId", "code") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."employee_certifications_status_enum" AS ENUM('pending', 'active', 'expired', 'expiring_soon', 'revoked', 'suspended'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."employee_certifications_verificationstatus_enum" AS ENUM('unverified', 'pending_verification', 'verified', 'verification_failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "employee_certifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "certificationNumber" character varying(50) NOT NULL, "employeeId" uuid NOT NULL, "certificationTypeId" uuid NOT NULL, "issueDate" date NOT NULL, "expiryDate" date, "status" "hr"."employee_certifications_status_enum" NOT NULL DEFAULT 'pending', "verificationStatus" "hr"."employee_certifications_verificationstatus_enum" NOT NULL DEFAULT 'unverified', "verifiedBy" character varying, "verifiedAt" TIMESTAMP WITH TIME ZONE, "issuingAuthority" character varying(200), "externalCertificationId" character varying(100), "notes" text, "documents" jsonb, "revokedBy" character varying, "revokedAt" TIMESTAMP WITH TIME ZONE, "revocationReason" text, "previousCertificationId" character varying, "isRenewal" boolean NOT NULL DEFAULT false, "reminderSent" boolean NOT NULL DEFAULT false, "reminderSentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_5d7390fbb1abe948ee5efe1dda4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6072db3f67116c5b647d0db02c" ON "employee_certifications" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_db01a87c4eb8b0d4082c144551" ON "employee_certifications" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f72e1b1abcc208d8fe1c115685" ON "employee_certifications" ("tenantId", "verificationStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb1a42113627cd1a74d7102730" ON "employee_certifications" ("tenantId", "expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_d871e267c1760fa77dd9bd3a7a" ON "employee_certifications" ("tenantId", "status", "expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_5934deb3f477db3959ca5bd9ae" ON "employee_certifications" ("tenantId", "employeeId", "certificationTypeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a5037c68c823b943cf7a84cde2" ON "employee_certifications" ("tenantId", "certificationNumber") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."shifts_shifttype_enum" AS ENUM('regular', 'offshore', 'night', 'rotation', 'flexible'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "code" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "description" text, "shiftType" "hr"."shifts_shifttype_enum" NOT NULL DEFAULT 'regular', "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "totalMinutes" integer NOT NULL DEFAULT '480', "breakMinutes" integer NOT NULL DEFAULT '0', "breakPeriods" jsonb, "workDays" text NOT NULL DEFAULT 'monday,tuesday,wednesday,thursday,friday', "crossesMidnight" boolean NOT NULL DEFAULT false, "graceMinutes" integer NOT NULL DEFAULT '0', "earlyClockInMinutes" integer NOT NULL DEFAULT '0', "lateClockOutMinutes" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "colorCode" character varying(7), "displayOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e3e6dd2774dcd657b0fa029d7" ON "shifts" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_596930b4d61c0c886e0349c6d0" ON "shifts" ("tenantId", "shiftType") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdb959654fbf8d3a5b78bb55c4" ON "shifts" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ddceea1d2d0d202d87878b07e3" ON "shifts" ("tenantId", "code") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."leave_types_category_enum" AS ENUM('annual', 'sick', 'parental', 'bereavement', 'personal', 'study', 'sabbatical', 'compensatory', 'shore_leave', 'rotation_break', 'emergency', 'unpaid', 'other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "leave_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "description" text, "category" "hr"."leave_types_category_enum" NOT NULL DEFAULT 'annual', "isPaid" boolean NOT NULL DEFAULT true, "isAccrued" boolean NOT NULL DEFAULT true, "defaultDaysPerYear" numeric(5,2), "maxCarryOverDays" numeric(5,2), "maxConsecutiveDays" integer, "minDaysNotice" integer, "accrualRate" numeric(6,4), "accrualStartAfterMonths" integer NOT NULL DEFAULT '0', "requiresApproval" boolean NOT NULL DEFAULT true, "approvalLevels" integer NOT NULL DEFAULT '1', "isAquacultureSpecific" boolean NOT NULL DEFAULT false, "applicableForOffshore" boolean NOT NULL DEFAULT true, "color" character varying(7), "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_359223e0755d19711813cd07394" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_02e09fb153b8a2928e4b669cc8" ON "leave_types" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_858f406403286b440f291d1066" ON "leave_types" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_63c7a1eba84d364737a2be2565" ON "leave_types" ("tenantId", "category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_503bcc74bb79a5efc073a4e486" ON "leave_types" ("tenantId", "code") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."leave_requests_halfdayperiod_enum" AS ENUM('am', 'pm'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."leave_requests_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'cancelled', 'withdrawn'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "requestNumber" character varying(30) NOT NULL, "employeeId" uuid NOT NULL, "leaveTypeId" uuid NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "totalDays" numeric(5,2) NOT NULL, "isHalfDayStart" boolean NOT NULL DEFAULT false, "isHalfDayEnd" boolean NOT NULL DEFAULT false, "halfDayPeriod" "hr"."leave_requests_halfdayperiod_enum", "reason" text, "contactDuringLeave" character varying(100), "status" "hr"."leave_requests_status_enum" NOT NULL DEFAULT 'draft', "currentApprovalLevel" integer NOT NULL DEFAULT '1', "approvalHistory" jsonb, "approvedBy" character varying, "approvedAt" TIMESTAMP WITH TIME ZONE, "rejectedBy" character varying, "rejectedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" text, "cancelledBy" character varying, "cancelledAt" TIMESTAMP WITH TIME ZONE, "cancellationReason" text, "originalCloseReason" text, "originalClosedAt" TIMESTAMP WITH TIME ZONE, "attachments" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_d3abcf9a16cef1450129e06fa9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_091ffcec318214206f60315f30" ON "leave_requests" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4eda1468756ca831495e308e40" ON "leave_requests" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0957736a6bbc4c9fb7a7c710c" ON "leave_requests" ("tenantId", "approvedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccf6ceef7aa62e38bc49dbc8fb" ON "leave_requests" ("tenantId", "status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7b09c7c3f388959b6de4ee77f" ON "leave_requests" ("tenantId", "startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_8790bfef8297ea1f9f4c37b45e" ON "leave_requests" ("tenantId", "employeeId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_date_range" ON "leave_requests" ("startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_tenant_status" ON "leave_requests" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_tenant_employee" ON "leave_requests" ("tenantId", "employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_leave_request_number" ON "leave_requests" ("tenantId", "requestNumber") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."weekly_plan_entries_dayofweek_enum" AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."weekly_plan_entries_entrytype_enum" AS ENUM('work', 'off', 'leave', 'holiday', 'training'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "weekly_plan_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "weeklyPlanId" uuid NOT NULL, "employeeId" character varying NOT NULL, "date" date NOT NULL, "dayOfWeek" "hr"."weekly_plan_entries_dayofweek_enum" NOT NULL, "shiftId" uuid, "isOffDay" boolean NOT NULL DEFAULT false, "isLeaveDay" boolean NOT NULL DEFAULT false, "leaveRequestId" uuid, "plannedStartTime" TIMESTAMP WITH TIME ZONE, "plannedEndTime" TIMESTAMP WITH TIME ZONE, "plannedMinutes" integer NOT NULL DEFAULT '0', "entryType" "hr"."weekly_plan_entries_entrytype_enum" NOT NULL DEFAULT 'work', "notes" text, "displayOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c79edfb6316c5c3d6b9331e8248" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c49ac3703f520d5039e590bc4b" ON "weekly_plan_entries" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b2ed8f9f4c2fccda0311269f1" ON "weekly_plan_entries" ("tenantId", "date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b1cba7354c832899260822cbc1" ON "weekly_plan_entries" ("tenantId", "employeeId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_6698bfa6d0c2b5d0ae40f53f8c" ON "weekly_plan_entries" ("tenantId", "weeklyPlanId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."weekly_plans_status_enum" AS ENUM('draft', 'published', 'closed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "weekly_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "weekStartDate" date NOT NULL, "weekEndDate" date NOT NULL, "status" "hr"."weekly_plans_status_enum" NOT NULL DEFAULT 'draft', "plannedWorkDays" integer NOT NULL DEFAULT '0', "plannedOffDays" integer NOT NULL DEFAULT '0', "plannedTotalMinutes" integer NOT NULL DEFAULT '0', "standardWeeklyMinutes" integer NOT NULL DEFAULT '2700', "plannedOvertimeMinutes" integer NOT NULL DEFAULT '0', "actualOvertimeMinutes" integer NOT NULL DEFAULT '0', "notifiedAt" TIMESTAMP WITH TIME ZONE, "publishedAt" TIMESTAMP WITH TIME ZONE, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, CONSTRAINT "PK_6c64b331bf3b98025f865282292" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ae68550ec3bf0fe77b0395016" ON "weekly_plans" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_254ddb1198988cb73a79cc6dc9" ON "weekly_plans" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a013ccc24ed6b3568822382d2b" ON "weekly_plans" ("tenantId", "isDeleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c9ab5a09ce9845d39204d5119" ON "weekly_plans" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f820c296561cfc2e51e473fa1" ON "weekly_plans" ("tenantId", "weekEndDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_903a374d10b82abb3e03c835b9" ON "weekly_plans" ("tenantId", "weekStartDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_835db3751ee82271f427c90c0d" ON "weekly_plans" ("tenantId", "employeeId", "weekStartDate") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."scheduling_settings_workweekstartday_enum" AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "scheduling_settings" ("tenantId" uuid NOT NULL, "jurisdictionCode" character varying(10) DEFAULT 'TR', "standardWeeklyMinutes" integer NOT NULL DEFAULT '2700', "maxOvertimeMinutesPerWeek" integer NOT NULL DEFAULT '720', "maxOvertimeMinutesPerMonth" integer NOT NULL DEFAULT '2880', "defaultShiftId" character varying, "workWeekStartDay" "hr"."scheduling_settings_workweekstartday_enum" NOT NULL DEFAULT 'monday', "autoNotifyEmployees" boolean NOT NULL DEFAULT true, "notifyDaysBefore" integer NOT NULL DEFAULT '2', "maxConsecutiveWorkDays" integer NOT NULL DEFAULT '6', "minRestMinutesBetweenShifts" integer NOT NULL DEFAULT '660', "allowOvertimeWithoutApproval" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "version" integer NOT NULL, CONSTRAINT "PK_8e3892ce17b3a09c6172d83423d" PRIMARY KEY ("tenantId"))`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."holidays_type_enum" AS ENUM('national', 'religious', 'regional', 'company'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "name" character varying NOT NULL, "localName" character varying, "date" date NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "type" "hr"."holidays_type_enum" NOT NULL DEFAULT 'national', "isActive" boolean NOT NULL DEFAULT true, "isPaidLeave" boolean NOT NULL DEFAULT false, "affectsScheduling" boolean NOT NULL DEFAULT true, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc93a2743e469f6bd9bec272f6" ON "holidays" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_36744b132722fcf26233d72803" ON "holidays" ("tenantId", "isActive", "affectsScheduling") `);
        await queryRunner.query(`CREATE INDEX "IDX_3dd65e3acf155beab540dae37c" ON "holidays" ("tenantId", "startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_4cfdd1f9e3bacce8359b6608fa" ON "holidays" ("tenantId", "date") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."performance_reviews_periodtype_enum" AS ENUM('ANNUAL', 'SEMI_ANNUAL', 'QUARTERLY', 'PROBATION', 'PROJECT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."performance_reviews_status_enum" AS ENUM('DRAFT', 'SELF_ASSESSMENT', 'MANAGER_REVIEW', 'CALIBRATION', 'FINALIZED', 'ACKNOWLEDGED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "performance_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "reviewerId" uuid NOT NULL, "periodType" "hr"."performance_reviews_periodtype_enum" NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "status" "hr"."performance_reviews_status_enum" NOT NULL DEFAULT 'DRAFT', "selfAssessment" text, "selfRating" numeric(3,2), "managerAssessment" text, "managerRating" numeric(3,2), "finalRating" numeric(3,2), "competencyRatings" jsonb, "strengths" text, "areasForImprovement" text, "developmentPlan" text, "employeeComments" text, "reviewerComments" text, "calibrationNotes" text, "acknowledgedBy" character varying, "acknowledgedAt" TIMESTAMP WITH TIME ZONE, "finalizedBy" character varying, "finalizedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_46f39f620497eb3de4fe6dafdef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32a2f55016eac02f8017d763c2" ON "performance_reviews" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_review_tenant_period" ON "performance_reviews" ("tenantId", "periodType", "periodStart", "periodEnd") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_review_tenant_status" ON "performance_reviews" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_review_tenant_reviewer" ON "performance_reviews" ("tenantId", "reviewerId") `);
        await queryRunner.query(`CREATE INDEX "idx_perf_review_tenant_employee" ON "performance_reviews" ("tenantId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "employee_kpis" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "category" character varying NOT NULL, "targetValue" numeric(12,2) NOT NULL, "currentValue" numeric(12,2) NOT NULL DEFAULT '0', "unit" character varying, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "weight" numeric(5,2) NOT NULL DEFAULT '1', "achievementPercent" numeric(5,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_2992520e9a06ddc7e8482ab8e94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c46cf210f3c393d2864368a6c4" ON "employee_kpis" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "idx_kpi_tenant_period" ON "employee_kpis" ("tenantId", "periodStart", "periodEnd") `);
        await queryRunner.query(`CREATE INDEX "idx_kpi_tenant_category" ON "employee_kpis" ("tenantId", "category") `);
        await queryRunner.query(`CREATE INDEX "idx_kpi_tenant_employee" ON "employee_kpis" ("tenantId", "employeeId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."goals_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."goals_status_enum" AS ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "category" character varying, "priority" "hr"."goals_priority_enum" NOT NULL DEFAULT 'MEDIUM', "status" "hr"."goals_status_enum" NOT NULL DEFAULT 'NOT_STARTED', "startDate" date NOT NULL, "targetDate" date NOT NULL, "completedDate" date, "progressPercent" numeric(5,2) NOT NULL DEFAULT '0', "keyResults" jsonb, "alignedReviewId" character varying, "parentGoalId" uuid, "milestones" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_26e17b251afab35580dff769223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7ede46e8ed1c3c90d79790b52" ON "goals" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "idx_goal_parent" ON "goals" ("parentGoalId") `);
        await queryRunner.query(`CREATE INDEX "idx_goal_tenant_target_date" ON "goals" ("tenantId", "targetDate") `);
        await queryRunner.query(`CREATE INDEX "idx_goal_tenant_priority" ON "goals" ("tenantId", "priority") `);
        await queryRunner.query(`CREATE INDEX "idx_goal_tenant_status" ON "goals" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_goal_tenant_employee" ON "goals" ("tenantId", "employeeId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "leave_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "leaveTypeId" uuid NOT NULL, "year" integer NOT NULL, "openingBalance" numeric(6,2) NOT NULL DEFAULT '0', "accrued" numeric(6,2) NOT NULL DEFAULT '0', "used" numeric(6,2) NOT NULL DEFAULT '0', "pending" numeric(6,2) NOT NULL DEFAULT '0', "adjustment" numeric(6,2) NOT NULL DEFAULT '0', "carriedOver" numeric(6,2) NOT NULL DEFAULT '0', "lastAccrualDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_a1d90dff48fb2bfd23a7163d077" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b454eb605d62e7213ddb1122d" ON "leave_balances" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e0df1791c9344d4bdde694be6" ON "leave_balances" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_24114fc31c43a5f8d69b5642e0" ON "leave_balances" ("tenantId", "leaveTypeId", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3f16ed27f53da3fefa4e537e4" ON "leave_balances" ("tenantId", "employeeId", "year") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d4af2b8c2aa521d8e7790f8aed" ON "leave_balances" ("tenantId", "employeeId", "leaveTypeId", "year") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "hr"."payroll_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "payrollId" character varying NOT NULL, "employeeId" character varying NOT NULL, "action" character varying(30) NOT NULL, "calculationInputs" jsonb, "calculationOutputs" jsonb, "grossPay" numeric(12,2), "netPay" numeric(12,2), "currency" character varying, "performedBy" character varying NOT NULL, "notes" text, "ipAddress" character varying(45), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e14c187d365a51a44e878da2c99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0c515508b5946a8763698a2239" ON "hr"."payroll_audit" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_337203624c27e5d60b443504a2" ON "hr"."payroll_audit" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e7a69d3162369fbb6a595185a0" ON "hr"."payroll_audit" ("tenantId", "action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8e4287bb68d0161280382f24e9" ON "hr"."payroll_audit" ("tenantId", "employeeId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ecf3910335f006d19650e7138c" ON "hr"."payroll_audit" ("tenantId", "payrollId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "hr"."hr_outbox" ("id" BIGSERIAL NOT NULL, "eventType" character varying(100) NOT NULL, "tenantId" uuid, "aggregateId" uuid, "payload" jsonb NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "publishedAt" TIMESTAMP WITH TIME ZONE, "retryCount" integer NOT NULL DEFAULT '0', "lastError" text, "nextAttemptAt" TIMESTAMP WITH TIME ZONE, "idempotencyKey" character varying(255), "isDeadLettered" boolean NOT NULL DEFAULT false, "leasedAt" TIMESTAMP WITH TIME ZONE, "leasedBy" character varying(128), CONSTRAINT "PK_56a95fb9c3872fafc7cb499b69e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."schedules_scheduletype_enum" AS ENUM('fixed', 'rotating', 'flexible', 'offshore_rotation'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."schedules_status_enum" AS ENUM('draft', 'published', 'active', 'completed', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "departmentId" character varying, "shiftId" uuid, "scheduleType" "hr"."schedules_scheduletype_enum" NOT NULL DEFAULT 'fixed', "startDate" date NOT NULL, "endDate" date NOT NULL, "status" "hr"."schedules_status_enum" NOT NULL DEFAULT 'draft', "notes" text, "rotationDaysOn" integer, "rotationDaysOff" integer, "nextRotationDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18016abbbedd8354ee4518cf0e" ON "schedules" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_93cff6e8ed305a333ecd59a5ac" ON "schedules" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6bfd2d77a6bc41b533c27a76a2" ON "schedules" ("tenantId", "employeeId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e83c2630af8f16a955302588e1" ON "schedules" ("tenantId", "departmentId", "startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_63f672c37e2baa58ea078abdbc" ON "schedules" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3de5a796f2da6e5f4e0518a28" ON "schedules" ("tenantId", "employeeId", "startDate", "endDate") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."schedule_entries_status_enum" AS ENUM('scheduled', 'completed', 'absent', 'leave', 'holiday', 'modified'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "schedule_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "scheduleId" uuid NOT NULL, "employeeId" character varying NOT NULL, "date" date NOT NULL, "shiftId" uuid, "plannedStartTime" TIME, "plannedEndTime" TIME, "status" "hr"."schedule_entries_status_enum" NOT NULL DEFAULT 'scheduled', "isOffDay" boolean NOT NULL DEFAULT false, "isOverride" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "PK_bfe848ea36c4b3d8a4b18ec82aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_58c61505823ab74c9bd0fcda37" ON "schedule_entries" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf3134da50d9e3b15dbee3d5b4" ON "schedule_entries" ("scheduleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1c76a05ce3356230e97daad354" ON "schedule_entries" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4644c419fb18633efe761e171" ON "schedule_entries" ("tenantId", "date", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_429e3b11f587cda1dc4e4c6278" ON "schedule_entries" ("tenantId", "employeeId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef2a4baee62e13b2a293a1b3db" ON "schedule_entries" ("tenantId", "scheduleId", "date") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."attendance_records_clockinmethod_enum" AS ENUM('biometric', 'card', 'mobile', 'web', 'manual', 'gps'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."attendance_records_clockoutmethod_enum" AS ENUM('biometric', 'card', 'mobile', 'web', 'manual', 'gps'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."attendance_records_status_enum" AS ENUM('present', 'absent', 'late', 'early_leave', 'half_day', 'on_leave', 'holiday', 'offshore', 'rest_day', 'work_from_home'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."attendance_records_approvalstatus_enum" AS ENUM('auto_approved', 'pending_review', 'manager_approved', 'hr_approved', 'rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "recordNumber" character varying(30) NOT NULL, "employeeId" uuid NOT NULL, "departmentId" character varying, "shiftId" uuid, "date" date NOT NULL, "clockIn" TIMESTAMP WITH TIME ZONE, "clockOut" TIMESTAMP WITH TIME ZONE, "clockInMethod" "hr"."attendance_records_clockinmethod_enum", "clockOutMethod" "hr"."attendance_records_clockoutmethod_enum", "clockInLocation" jsonb, "clockOutLocation" jsonb, "timezone" character varying(50) DEFAULT 'UTC', "breakStartTime" TIMESTAMP WITH TIME ZONE, "breakEndTime" TIMESTAMP WITH TIME ZONE, "status" "hr"."attendance_records_status_enum" NOT NULL DEFAULT 'present', "workedMinutes" integer NOT NULL DEFAULT '0', "overtimeMinutes" integer NOT NULL DEFAULT '0', "lateMinutes" integer NOT NULL DEFAULT '0', "earlyLeaveMinutes" integer NOT NULL DEFAULT '0', "breakMinutes" integer NOT NULL DEFAULT '0', "approvalStatus" "hr"."attendance_records_approvalstatus_enum" NOT NULL DEFAULT 'auto_approved', "approvedBy" character varying, "approvedAt" TIMESTAMP WITH TIME ZONE, "remarks" text, "reason" text, "isManualEntry" boolean NOT NULL DEFAULT false, "isAdjusted" boolean NOT NULL DEFAULT false, "adjustedBy" character varying, "adjustmentReason" text, "workAreaId" character varying, "isOffshore" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94d977ec9616f19e799c7d7f8c" ON "attendance_records" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f86d1ade33d4dbc029e216904" ON "attendance_records" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b353844af7c95c3ecf8c153e9" ON "attendance_records" ("tenantId", "departmentId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_e15a75f8154a0d8cd5b204c5ad" ON "attendance_records" ("tenantId", "approvalStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fc22e3bf3f3927a8639bc37e5" ON "attendance_records" ("tenantId", "date", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_76489e1aa112a99570b251c7d2" ON "attendance_records" ("tenantId", "employeeId", "date") `);
        await queryRunner.query(`CREATE INDEX "idx_attendance_status_tenant" ON "attendance_records" ("status", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "idx_attendance_tenant_date" ON "attendance_records" ("tenantId", "date") `);
        await queryRunner.query(`CREATE INDEX "idx_attendance_tenant_employee" ON "attendance_records" ("tenantId", "employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_attendance_record_number" ON "attendance_records" ("tenantId", "recordNumber") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."work_areas_workareatype_enum" AS ENUM('shore_facility', 'sea_cage', 'floating_platform', 'vessel', 'feed_barge', 'processing_plant', 'hatchery', 'laboratory', 'office', 'warehouse', 'workshop', 'other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."work_areas_risklevel_enum" AS ENUM('low', 'medium', 'high', 'critical'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "work_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "code" character varying(30) NOT NULL, "name" character varying(150) NOT NULL, "description" text, "workAreaType" "hr"."work_areas_workareatype_enum" NOT NULL, "riskLevel" "hr"."work_areas_risklevel_enum" NOT NULL DEFAULT 'low', "siteId" character varying, "coordinates" jsonb, "isOffshore" boolean NOT NULL DEFAULT false, "geofenceRadiusMeters" integer DEFAULT '500', "maxCapacity" integer, "requiredCertifications" text, "requiredPPE" text, "requiresDivingCertification" boolean NOT NULL DEFAULT false, "requiresVesselCertification" boolean NOT NULL DEFAULT false, "requiresSeaWorthy" boolean NOT NULL DEFAULT false, "emergencyContact" character varying, "emergencyProcedure" character varying, "colorCode" character varying(7), "displayOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_50b32ea86ee7096cc58345f887e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81e2df8e932fd81effea6b9f9f" ON "work_areas" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9382319a23e87c2095f9d2874a" ON "work_areas" ("tenantId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_daf82681dc577d462e47ebf77a" ON "work_areas" ("tenantId", "siteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b59d6cf6c322a8a681bf737f19" ON "work_areas" ("tenantId", "workAreaType") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_176351a94a141764daa9952f63" ON "work_areas" ("tenantId", "code") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."work_rotations_rotationtype_enum" AS ENUM('offshore', 'onshore', 'field', 'vessel', 'mixed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."work_rotations_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'extended'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "work_rotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "workAreaId" uuid NOT NULL, "rotationType" "hr"."work_rotations_rotationtype_enum" NOT NULL, "status" "hr"."work_rotations_status_enum" NOT NULL DEFAULT 'scheduled', "startDate" date NOT NULL, "endDate" date NOT NULL, "daysOn" integer NOT NULL, "daysOff" integer NOT NULL, "actualStartTime" TIMESTAMP WITH TIME ZONE, "actualEndTime" TIMESTAMP WITH TIME ZONE, "outboundTransport" jsonb, "inboundTransport" jsonb, "accommodationInfo" character varying, "supervisorId" character varying, "reliefEmployeeId" character varying, "notes" text, "isExtended" boolean NOT NULL DEFAULT false, "extensionDays" integer, "extensionReason" text, "lastCheckInTime" TIMESTAMP WITH TIME ZONE, "checkInHistory" jsonb DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" character varying, CONSTRAINT "PK_4b3cfeb2b63c05594b559c27d97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51e5ae0f79a18e70e6a54012c6" ON "work_rotations" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f8d0da9c491cdbbbd1d4ce6e1" ON "work_rotations" ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_80da5718978b6f53ff0d94aa4b" ON "work_rotations" ("tenantId", "employeeId", "startDate", "endDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebc058057b8d953c166e0fc034" ON "work_rotations" ("tenantId", "rotationType") `);
        await queryRunner.query(`CREATE INDEX "IDX_fff4faceaa5779c6f27f2d8eb9" ON "work_rotations" ("tenantId", "workAreaId", "startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e3c0360217a06bd14a7989379" ON "work_rotations" ("tenantId", "status", "startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_257f26cbd55e49c6f1f9c27907" ON "work_rotations" ("tenantId", "employeeId", "startDate") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."training_enrollments_status_enum" AS ENUM('enrolled', 'in_progress', 'completed', 'passed', 'failed', 'withdrawn', 'expired'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "training_enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "trainingCourseId" uuid NOT NULL, "status" "hr"."training_enrollments_status_enum" NOT NULL DEFAULT 'enrolled', "enrollmentDate" date NOT NULL, "dueDate" date, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "progressPercent" numeric(5,2) NOT NULL DEFAULT '0', "finalScore" numeric(5,2), "attemptCount" integer NOT NULL DEFAULT '0', "assessmentAttempts" jsonb, "certificateId" character varying, "sessionId" character varying, "instructor" character varying(200), "location" character varying(200), "feedback" text, "feedbackRating" integer, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_61c7ba1db08ad1c4aae4ab05217" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b198d0e8cc675aa07deda6985e" ON "training_enrollments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_26321e476485f2a4cc9435089d" ON "training_enrollments" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_672f2843aadbaca6a40a208024" ON "training_enrollments" ("tenantId", "completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c64437233dc8b6ad517a650482" ON "training_enrollments" ("tenantId", "enrollmentDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_d27f8ee19e5c4a65851a59acde" ON "training_enrollments" ("tenantId", "employeeId", "trainingCourseId") `);
        await queryRunner.query(`CREATE INDEX "idx_enrollment_course" ON "training_enrollments" ("trainingCourseId") `);
        await queryRunner.query(`CREATE INDEX "idx_enrollment_tenant_status" ON "training_enrollments" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_enrollment_tenant_employee" ON "training_enrollments" ("tenantId", "employeeId") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."safety_training_records_trainingtype_enum" AS ENUM('induction', 'fire_safety', 'sea_survival', 'first_aid', 'helicopter_safety', 'vessel_safety', 'diving_safety', 'chemical_handling', 'fall_protection', 'confined_space', 'emergency_response', 'biosecurity'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "hr"."safety_training_records_status_enum" AS ENUM('not_started', 'in_progress', 'completed', 'expired', 'overdue'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "safety_training_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "employeeId" uuid NOT NULL, "trainingType" "hr"."safety_training_records_trainingtype_enum" NOT NULL, "status" "hr"."safety_training_records_status_enum" NOT NULL DEFAULT 'not_started', "completedDate" date, "expiryDate" date, "nextDueDate" date, "instructor" character varying(200), "location" character varying(200), "certificateNumber" character varying(100), "notes" text, "isMandatoryForOffshore" boolean NOT NULL DEFAULT false, "reminderSent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, "version" integer NOT NULL, CONSTRAINT "PK_4e1da2d9a037916980ae40360e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72a63d24bc82accf15186c868f" ON "safety_training_records" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_90c3be823ebf2dc92caced1b81" ON "safety_training_records" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcca6dbb555811211a86bf6420" ON "safety_training_records" ("tenantId", "expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_179b64be8d9883a0b6293bc338" ON "safety_training_records" ("tenantId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a71fa6f873632363fdfb34444f" ON "safety_training_records" ("tenantId", "employeeId", "trainingType") `);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD CONSTRAINT "FK_eeffbd86fba74517d4dacc8ab37" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_f0a8343162ed3ecd2760ae2163f" FOREIGN KEY ("departmentHrId") REFERENCES "departments_hr"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_certifications" ADD CONSTRAINT "FK_db01a87c4eb8b0d4082c1445518" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_certifications" ADD CONSTRAINT "FK_842cee08e0adea42ae825406d95" FOREIGN KEY ("certificationTypeId") REFERENCES "certification_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_4eda1468756ca831495e308e407" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_1a15bd6c14a42bb91c53712a5f4" FOREIGN KEY ("leaveTypeId") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_plan_entries" ADD CONSTRAINT "FK_96191c5adfd596faebc2b5bf142" FOREIGN KEY ("weeklyPlanId") REFERENCES "weekly_plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_plan_entries" ADD CONSTRAINT "FK_6fc6dfcbe0579a05770d1ee8453" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_plan_entries" ADD CONSTRAINT "FK_18d5b96780bd8ddf5b83eb862b4" FOREIGN KEY ("leaveRequestId") REFERENCES "leave_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_plans" ADD CONSTRAINT "FK_254ddb1198988cb73a79cc6dc9b" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ADD CONSTRAINT "FK_89c1585d31979b8f709928bd2bf" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" ADD CONSTRAINT "FK_a3c7d2780b0f68ada057ee17cf1" FOREIGN KEY ("reviewerId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_kpis" ADD CONSTRAINT "FK_23b6f3fd6a327381fac8ef28463" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_c3dba9d57c38067e0b34366acfd" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_45db60741e56aa6941b7cf77fde" FOREIGN KEY ("parentGoalId") REFERENCES "goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_1e0df1791c9344d4bdde694be60" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_98f067848742e213d1a55445379" FOREIGN KEY ("leaveTypeId") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_93cff6e8ed305a333ecd59a5acd" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_9f473001b5432ed29c44b898d0a" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_entries" ADD CONSTRAINT "FK_bf3134da50d9e3b15dbee3d5b4a" FOREIGN KEY ("scheduleId") REFERENCES "schedules"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_entries" ADD CONSTRAINT "FK_7c960b7cf8997e304659dda34c9" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_2f86d1ade33d4dbc029e216904a" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_6fe9e80bee61d5ac47a27d40f2c" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_rotations" ADD CONSTRAINT "FK_0f8d0da9c491cdbbbd1d4ce6e1d" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_rotations" ADD CONSTRAINT "FK_1ae5f9a9d4c6896a53420a784fe" FOREIGN KEY ("workAreaId") REFERENCES "work_areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ADD CONSTRAINT "FK_26321e476485f2a4cc9435089da" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ADD CONSTRAINT "FK_4f261472a35957d9cf48638553c" FOREIGN KEY ("trainingCourseId") REFERENCES "training_courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "safety_training_records" ADD CONSTRAINT "FK_90c3be823ebf2dc92caced1b81f" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);

        // ── Faz 3.5 hand-author addition — RLS canonical predicate ──
        await applyTenantRlsToSchema(queryRunner, {
            tenantIdColumns: ['tenant_id', 'tenantId'],
            excludeTables: [],
        });

        // ── Faz 3.5 hand-author addition — audit immutability triggers ──
        await queryRunner.query(`
            CREATE OR REPLACE FUNCTION "hr".payroll_audit_prevent_update_or_delete()
            RETURNS trigger AS $auditguard$
            BEGIN
              RAISE EXCEPTION 'Audit table "hr"."payroll_audit" is append-only; UPDATE/DELETE refused (Faz 1.4 protected-tables-guard).';
            END;
            $auditguard$ LANGUAGE plpgsql;
        `);
        await queryRunner.query(`
            CREATE OR REPLACE TRIGGER trg_payroll_audit_prevent_update
            BEFORE UPDATE OR DELETE ON "hr"."payroll_audit"
            FOR EACH ROW EXECUTE FUNCTION "hr".payroll_audit_prevent_update_or_delete();
        `);
        await queryRunner.query(`
            REVOKE UPDATE, DELETE ON "hr"."payroll_audit" FROM PUBLIC;
        `);
    }

    // ── GENERATED postCondition (DATA-CRITICAL-010) — do not hand-edit ──
    public async postCondition(queryRunner: QueryRunner): Promise<boolean> {
        const rows: Array<{ missing: string }> = await queryRunner.query(`
            SELECT expected.table_name AS missing
              FROM (VALUES ('attendance_records'), ('certification_types'), ('departments_hr'), ('employee_certifications'), ('employee_kpis'), ('employees'), ('goals'), ('holidays'), ('leave_balances'), ('leave_requests'), ('leave_types'), ('payrolls'), ('performance_reviews'), ('safety_training_records'), ('schedule_entries'), ('schedules'), ('scheduling_settings'), ('shifts'), ('training_courses'), ('training_enrollments'), ('weekly_plan_entries'), ('weekly_plans'), ('work_areas'), ('work_rotations')) AS expected(table_name)
             WHERE NOT EXISTS (
               SELECT 1
                 FROM information_schema.tables
                WHERE table_schema = current_schema()
                  AND table_name = expected.table_name
             )
        `);
        return rows.length === 0;
    }
    // ── END GENERATED postCondition ──

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Reverse Faz 3.5 audit immutability triggers
        await queryRunner.query(`DROP TRIGGER IF EXISTS trg_payroll_audit_prevent_update ON "hr"."payroll_audit";`);
        await queryRunner.query(`DROP FUNCTION IF EXISTS "hr".payroll_audit_prevent_update_or_delete();`);
        // Reverse Faz 3.5 RLS install first (avoids policy-on-missing-table errors).
        await removeTenantRlsFromSchema(queryRunner, {
            tenantIdColumns: ['tenant_id', 'tenantId'],
            excludeTables: [],
        });
        await queryRunner.query(`ALTER TABLE "safety_training_records" DROP CONSTRAINT "FK_90c3be823ebf2dc92caced1b81f"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" DROP CONSTRAINT "FK_4f261472a35957d9cf48638553c"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" DROP CONSTRAINT "FK_26321e476485f2a4cc9435089da"`);
        await queryRunner.query(`ALTER TABLE "work_rotations" DROP CONSTRAINT "FK_1ae5f9a9d4c6896a53420a784fe"`);
        await queryRunner.query(`ALTER TABLE "work_rotations" DROP CONSTRAINT "FK_0f8d0da9c491cdbbbd1d4ce6e1d"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_6fe9e80bee61d5ac47a27d40f2c"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_2f86d1ade33d4dbc029e216904a"`);
        await queryRunner.query(`ALTER TABLE "schedule_entries" DROP CONSTRAINT "FK_7c960b7cf8997e304659dda34c9"`);
        await queryRunner.query(`ALTER TABLE "schedule_entries" DROP CONSTRAINT "FK_bf3134da50d9e3b15dbee3d5b4a"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_9f473001b5432ed29c44b898d0a"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_93cff6e8ed305a333ecd59a5acd"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_98f067848742e213d1a55445379"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_1e0df1791c9344d4bdde694be60"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_45db60741e56aa6941b7cf77fde"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_c3dba9d57c38067e0b34366acfd"`);
        await queryRunner.query(`ALTER TABLE "employee_kpis" DROP CONSTRAINT "FK_23b6f3fd6a327381fac8ef28463"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" DROP CONSTRAINT "FK_a3c7d2780b0f68ada057ee17cf1"`);
        await queryRunner.query(`ALTER TABLE "performance_reviews" DROP CONSTRAINT "FK_89c1585d31979b8f709928bd2bf"`);
        await queryRunner.query(`ALTER TABLE "weekly_plans" DROP CONSTRAINT "FK_254ddb1198988cb73a79cc6dc9b"`);
        await queryRunner.query(`ALTER TABLE "weekly_plan_entries" DROP CONSTRAINT "FK_18d5b96780bd8ddf5b83eb862b4"`);
        await queryRunner.query(`ALTER TABLE "weekly_plan_entries" DROP CONSTRAINT "FK_6fc6dfcbe0579a05770d1ee8453"`);
        await queryRunner.query(`ALTER TABLE "weekly_plan_entries" DROP CONSTRAINT "FK_96191c5adfd596faebc2b5bf142"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_1a15bd6c14a42bb91c53712a5f4"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_4eda1468756ca831495e308e407"`);
        await queryRunner.query(`ALTER TABLE "employee_certifications" DROP CONSTRAINT "FK_842cee08e0adea42ae825406d95"`);
        await queryRunner.query(`ALTER TABLE "employee_certifications" DROP CONSTRAINT "FK_db01a87c4eb8b0d4082c1445518"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_f0a8343162ed3ecd2760ae2163f"`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP CONSTRAINT "FK_eeffbd86fba74517d4dacc8ab37"`);
        await queryRunner.query(`DROP INDEX "IDX_a71fa6f873632363fdfb34444f"`);
        await queryRunner.query(`DROP INDEX "IDX_179b64be8d9883a0b6293bc338"`);
        await queryRunner.query(`DROP INDEX "IDX_fcca6dbb555811211a86bf6420"`);
        await queryRunner.query(`DROP INDEX "IDX_90c3be823ebf2dc92caced1b81"`);
        await queryRunner.query(`DROP INDEX "IDX_72a63d24bc82accf15186c868f"`);
        await queryRunner.query(`DROP TABLE "safety_training_records"`);
        await queryRunner.query(`DROP TYPE "hr"."safety_training_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."safety_training_records_trainingtype_enum"`);
        await queryRunner.query(`DROP INDEX "idx_enrollment_tenant_employee"`);
        await queryRunner.query(`DROP INDEX "idx_enrollment_tenant_status"`);
        await queryRunner.query(`DROP INDEX "idx_enrollment_course"`);
        await queryRunner.query(`DROP INDEX "IDX_d27f8ee19e5c4a65851a59acde"`);
        await queryRunner.query(`DROP INDEX "IDX_c64437233dc8b6ad517a650482"`);
        await queryRunner.query(`DROP INDEX "IDX_672f2843aadbaca6a40a208024"`);
        await queryRunner.query(`DROP INDEX "IDX_26321e476485f2a4cc9435089d"`);
        await queryRunner.query(`DROP INDEX "IDX_b198d0e8cc675aa07deda6985e"`);
        await queryRunner.query(`DROP TABLE "training_enrollments"`);
        await queryRunner.query(`DROP TYPE "hr"."training_enrollments_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_257f26cbd55e49c6f1f9c27907"`);
        await queryRunner.query(`DROP INDEX "IDX_0e3c0360217a06bd14a7989379"`);
        await queryRunner.query(`DROP INDEX "IDX_fff4faceaa5779c6f27f2d8eb9"`);
        await queryRunner.query(`DROP INDEX "IDX_ebc058057b8d953c166e0fc034"`);
        await queryRunner.query(`DROP INDEX "IDX_80da5718978b6f53ff0d94aa4b"`);
        await queryRunner.query(`DROP INDEX "IDX_0f8d0da9c491cdbbbd1d4ce6e1"`);
        await queryRunner.query(`DROP INDEX "IDX_51e5ae0f79a18e70e6a54012c6"`);
        await queryRunner.query(`DROP TABLE "work_rotations"`);
        await queryRunner.query(`DROP TYPE "hr"."work_rotations_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."work_rotations_rotationtype_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_176351a94a141764daa9952f63"`);
        await queryRunner.query(`DROP INDEX "IDX_b59d6cf6c322a8a681bf737f19"`);
        await queryRunner.query(`DROP INDEX "IDX_daf82681dc577d462e47ebf77a"`);
        await queryRunner.query(`DROP INDEX "IDX_9382319a23e87c2095f9d2874a"`);
        await queryRunner.query(`DROP INDEX "IDX_81e2df8e932fd81effea6b9f9f"`);
        await queryRunner.query(`DROP TABLE "work_areas"`);
        await queryRunner.query(`DROP TYPE "hr"."work_areas_risklevel_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."work_areas_workareatype_enum"`);
        await queryRunner.query(`DROP INDEX "idx_attendance_record_number"`);
        await queryRunner.query(`DROP INDEX "idx_attendance_tenant_employee"`);
        await queryRunner.query(`DROP INDEX "idx_attendance_tenant_date"`);
        await queryRunner.query(`DROP INDEX "idx_attendance_status_tenant"`);
        await queryRunner.query(`DROP INDEX "IDX_76489e1aa112a99570b251c7d2"`);
        await queryRunner.query(`DROP INDEX "IDX_8fc22e3bf3f3927a8639bc37e5"`);
        await queryRunner.query(`DROP INDEX "IDX_e15a75f8154a0d8cd5b204c5ad"`);
        await queryRunner.query(`DROP INDEX "IDX_3b353844af7c95c3ecf8c153e9"`);
        await queryRunner.query(`DROP INDEX "IDX_2f86d1ade33d4dbc029e216904"`);
        await queryRunner.query(`DROP INDEX "IDX_94d977ec9616f19e799c7d7f8c"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "hr"."attendance_records_approvalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."attendance_records_clockoutmethod_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."attendance_records_clockinmethod_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_ef2a4baee62e13b2a293a1b3db"`);
        await queryRunner.query(`DROP INDEX "IDX_429e3b11f587cda1dc4e4c6278"`);
        await queryRunner.query(`DROP INDEX "IDX_e4644c419fb18633efe761e171"`);
        await queryRunner.query(`DROP INDEX "IDX_1c76a05ce3356230e97daad354"`);
        await queryRunner.query(`DROP INDEX "IDX_bf3134da50d9e3b15dbee3d5b4"`);
        await queryRunner.query(`DROP INDEX "IDX_58c61505823ab74c9bd0fcda37"`);
        await queryRunner.query(`DROP TABLE "schedule_entries"`);
        await queryRunner.query(`DROP TYPE "hr"."schedule_entries_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_c3de5a796f2da6e5f4e0518a28"`);
        await queryRunner.query(`DROP INDEX "IDX_63f672c37e2baa58ea078abdbc"`);
        await queryRunner.query(`DROP INDEX "IDX_e83c2630af8f16a955302588e1"`);
        await queryRunner.query(`DROP INDEX "IDX_6bfd2d77a6bc41b533c27a76a2"`);
        await queryRunner.query(`DROP INDEX "IDX_93cff6e8ed305a333ecd59a5ac"`);
        await queryRunner.query(`DROP INDEX "IDX_18016abbbedd8354ee4518cf0e"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "hr"."schedules_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."schedules_scheduletype_enum"`);
        await queryRunner.query(`DROP TABLE "hr"."hr_outbox"`);
        await queryRunner.query(`DROP INDEX "hr"."IDX_ecf3910335f006d19650e7138c"`);
        await queryRunner.query(`DROP INDEX "hr"."IDX_8e4287bb68d0161280382f24e9"`);
        await queryRunner.query(`DROP INDEX "hr"."IDX_e7a69d3162369fbb6a595185a0"`);
        await queryRunner.query(`DROP INDEX "hr"."IDX_337203624c27e5d60b443504a2"`);
        await queryRunner.query(`DROP INDEX "hr"."IDX_0c515508b5946a8763698a2239"`);
        await queryRunner.query(`DROP TABLE "hr"."payroll_audit"`);
        await queryRunner.query(`DROP INDEX "IDX_d4af2b8c2aa521d8e7790f8aed"`);
        await queryRunner.query(`DROP INDEX "IDX_d3f16ed27f53da3fefa4e537e4"`);
        await queryRunner.query(`DROP INDEX "IDX_24114fc31c43a5f8d69b5642e0"`);
        await queryRunner.query(`DROP INDEX "IDX_1e0df1791c9344d4bdde694be6"`);
        await queryRunner.query(`DROP INDEX "IDX_4b454eb605d62e7213ddb1122d"`);
        await queryRunner.query(`DROP TABLE "leave_balances"`);
        await queryRunner.query(`DROP INDEX "idx_goal_tenant_employee"`);
        await queryRunner.query(`DROP INDEX "idx_goal_tenant_status"`);
        await queryRunner.query(`DROP INDEX "idx_goal_tenant_priority"`);
        await queryRunner.query(`DROP INDEX "idx_goal_tenant_target_date"`);
        await queryRunner.query(`DROP INDEX "idx_goal_parent"`);
        await queryRunner.query(`DROP INDEX "IDX_d7ede46e8ed1c3c90d79790b52"`);
        await queryRunner.query(`DROP TABLE "goals"`);
        await queryRunner.query(`DROP TYPE "hr"."goals_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."goals_priority_enum"`);
        await queryRunner.query(`DROP INDEX "idx_kpi_tenant_employee"`);
        await queryRunner.query(`DROP INDEX "idx_kpi_tenant_category"`);
        await queryRunner.query(`DROP INDEX "idx_kpi_tenant_period"`);
        await queryRunner.query(`DROP INDEX "IDX_c46cf210f3c393d2864368a6c4"`);
        await queryRunner.query(`DROP TABLE "employee_kpis"`);
        await queryRunner.query(`DROP INDEX "idx_perf_review_tenant_employee"`);
        await queryRunner.query(`DROP INDEX "idx_perf_review_tenant_reviewer"`);
        await queryRunner.query(`DROP INDEX "idx_perf_review_tenant_status"`);
        await queryRunner.query(`DROP INDEX "idx_perf_review_tenant_period"`);
        await queryRunner.query(`DROP INDEX "IDX_32a2f55016eac02f8017d763c2"`);
        await queryRunner.query(`DROP TABLE "performance_reviews"`);
        await queryRunner.query(`DROP TYPE "hr"."performance_reviews_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."performance_reviews_periodtype_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_4cfdd1f9e3bacce8359b6608fa"`);
        await queryRunner.query(`DROP INDEX "IDX_3dd65e3acf155beab540dae37c"`);
        await queryRunner.query(`DROP INDEX "IDX_36744b132722fcf26233d72803"`);
        await queryRunner.query(`DROP INDEX "IDX_cc93a2743e469f6bd9bec272f6"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP TYPE "hr"."holidays_type_enum"`);
        await queryRunner.query(`DROP TABLE "scheduling_settings"`);
        await queryRunner.query(`DROP TYPE "hr"."scheduling_settings_workweekstartday_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_835db3751ee82271f427c90c0d"`);
        await queryRunner.query(`DROP INDEX "IDX_903a374d10b82abb3e03c835b9"`);
        await queryRunner.query(`DROP INDEX "IDX_5f820c296561cfc2e51e473fa1"`);
        await queryRunner.query(`DROP INDEX "IDX_4c9ab5a09ce9845d39204d5119"`);
        await queryRunner.query(`DROP INDEX "IDX_a013ccc24ed6b3568822382d2b"`);
        await queryRunner.query(`DROP INDEX "IDX_254ddb1198988cb73a79cc6dc9"`);
        await queryRunner.query(`DROP INDEX "IDX_3ae68550ec3bf0fe77b0395016"`);
        await queryRunner.query(`DROP TABLE "weekly_plans"`);
        await queryRunner.query(`DROP TYPE "hr"."weekly_plans_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_6698bfa6d0c2b5d0ae40f53f8c"`);
        await queryRunner.query(`DROP INDEX "IDX_b1cba7354c832899260822cbc1"`);
        await queryRunner.query(`DROP INDEX "IDX_8b2ed8f9f4c2fccda0311269f1"`);
        await queryRunner.query(`DROP INDEX "IDX_c49ac3703f520d5039e590bc4b"`);
        await queryRunner.query(`DROP TABLE "weekly_plan_entries"`);
        await queryRunner.query(`DROP TYPE "hr"."weekly_plan_entries_entrytype_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."weekly_plan_entries_dayofweek_enum"`);
        await queryRunner.query(`DROP INDEX "idx_leave_request_number"`);
        await queryRunner.query(`DROP INDEX "idx_leave_tenant_employee"`);
        await queryRunner.query(`DROP INDEX "idx_leave_tenant_status"`);
        await queryRunner.query(`DROP INDEX "idx_leave_date_range"`);
        await queryRunner.query(`DROP INDEX "IDX_8790bfef8297ea1f9f4c37b45e"`);
        await queryRunner.query(`DROP INDEX "IDX_e7b09c7c3f388959b6de4ee77f"`);
        await queryRunner.query(`DROP INDEX "IDX_ccf6ceef7aa62e38bc49dbc8fb"`);
        await queryRunner.query(`DROP INDEX "IDX_b0957736a6bbc4c9fb7a7c710c"`);
        await queryRunner.query(`DROP INDEX "IDX_4eda1468756ca831495e308e40"`);
        await queryRunner.query(`DROP INDEX "IDX_091ffcec318214206f60315f30"`);
        await queryRunner.query(`DROP TABLE "leave_requests"`);
        await queryRunner.query(`DROP TYPE "hr"."leave_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."leave_requests_halfdayperiod_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_503bcc74bb79a5efc073a4e486"`);
        await queryRunner.query(`DROP INDEX "IDX_63c7a1eba84d364737a2be2565"`);
        await queryRunner.query(`DROP INDEX "IDX_858f406403286b440f291d1066"`);
        await queryRunner.query(`DROP INDEX "IDX_02e09fb153b8a2928e4b669cc8"`);
        await queryRunner.query(`DROP TABLE "leave_types"`);
        await queryRunner.query(`DROP TYPE "hr"."leave_types_category_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_ddceea1d2d0d202d87878b07e3"`);
        await queryRunner.query(`DROP INDEX "IDX_bdb959654fbf8d3a5b78bb55c4"`);
        await queryRunner.query(`DROP INDEX "IDX_596930b4d61c0c886e0349c6d0"`);
        await queryRunner.query(`DROP INDEX "IDX_4e3e6dd2774dcd657b0fa029d7"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "hr"."shifts_shifttype_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_a5037c68c823b943cf7a84cde2"`);
        await queryRunner.query(`DROP INDEX "IDX_5934deb3f477db3959ca5bd9ae"`);
        await queryRunner.query(`DROP INDEX "IDX_d871e267c1760fa77dd9bd3a7a"`);
        await queryRunner.query(`DROP INDEX "IDX_bb1a42113627cd1a74d7102730"`);
        await queryRunner.query(`DROP INDEX "IDX_f72e1b1abcc208d8fe1c115685"`);
        await queryRunner.query(`DROP INDEX "IDX_db01a87c4eb8b0d4082c144551"`);
        await queryRunner.query(`DROP INDEX "IDX_6072db3f67116c5b647d0db02c"`);
        await queryRunner.query(`DROP TABLE "employee_certifications"`);
        await queryRunner.query(`DROP TYPE "hr"."employee_certifications_verificationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."employee_certifications_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_e762b98622e96f4af4aa34d451"`);
        await queryRunner.query(`DROP INDEX "IDX_0eba2821560680ebf7459f2f71"`);
        await queryRunner.query(`DROP INDEX "IDX_fa9aca12ef0d70c92e7b744cc0"`);
        await queryRunner.query(`DROP INDEX "IDX_9330b8069a3ed9755b22bd47dc"`);
        await queryRunner.query(`DROP TABLE "certification_types"`);
        await queryRunner.query(`DROP TYPE "hr"."certification_types_requirement_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."certification_types_category_enum"`);
        await queryRunner.query(`DROP INDEX "idx_employee_email_tenant"`);
        await queryRunner.query(`DROP INDEX "idx_employee_number_tenant"`);
        await queryRunner.query(`DROP INDEX "idx_employee_email"`);
        await queryRunner.query(`DROP INDEX "idx_employee_department"`);
        await queryRunner.query(`DROP INDEX "idx_employee_status_tenant"`);
        await queryRunner.query(`DROP INDEX "IDX_c0e4b9f3e9e82b05072fce2069"`);
        await queryRunner.query(`DROP INDEX "IDX_d8e1c46f48d1080fd7d472c8ac"`);
        await queryRunner.query(`DROP INDEX "IDX_1f56de9a9d90cc0d9c54d3d527"`);
        await queryRunner.query(`DROP INDEX "IDX_64e94ad71585bfafc485cd8eb4"`);
        await queryRunner.query(`DROP INDEX "IDX_2a240a705116b09288ddb33881"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "hr"."employees_personnelcategory_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."employees_department_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."employees_employmenttype_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."employees_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_dc3b7d261ba9dbcaa814366038"`);
        await queryRunner.query(`DROP INDEX "IDX_646949e173019eb733a38964c7"`);
        await queryRunner.query(`DROP INDEX "IDX_bc20c4af22a312e99ceca2fbee"`);
        await queryRunner.query(`DROP INDEX "IDX_5706166cae13216642b941e0ae"`);
        await queryRunner.query(`DROP TABLE "departments_hr"`);
        await queryRunner.query(`DROP INDEX "IDX_b5dae33d42bab08b87a931720b"`);
        await queryRunner.query(`DROP INDEX "IDX_9bfade608f449383d28e472f22"`);
        await queryRunner.query(`DROP INDEX "IDX_583917de31260b8403cd437483"`);
        await queryRunner.query(`DROP INDEX "IDX_26bd770ae67d72656c58eb3e41"`);
        await queryRunner.query(`DROP INDEX "IDX_2707bcd6c6dbd53414384b515e"`);
        await queryRunner.query(`DROP TABLE "payrolls"`);
        await queryRunner.query(`DROP TYPE "hr"."payrolls_status_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."payrolls_payperiodtype_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_75d8931075f6843da349e54b40"`);
        await queryRunner.query(`DROP INDEX "IDX_1b71df07d8dfaf6edb78948b44"`);
        await queryRunner.query(`DROP INDEX "IDX_c6e3e7e405046d8e8b98892278"`);
        await queryRunner.query(`DROP INDEX "IDX_64e34988cf6f84917f49bf8044"`);
        await queryRunner.query(`DROP TABLE "training_courses"`);
        await queryRunner.query(`DROP TYPE "hr"."training_courses_level_enum"`);
        await queryRunner.query(`DROP TYPE "hr"."training_courses_trainingtype_enum"`);
    }

}
