/**
 * RowEditor Component
 *
 * Enhanced modal for creating and editing database rows.
 * Features smart input types, validation, FK lookups, and grouped field layout.
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Modal, Button, Input, Alert, Badge, Spinner } from '@aquaculture/shared-ui';
import { getAccessToken } from '@platform/shared-ui/utils/api-client';

// ============================================================================
// Types
// ============================================================================

export interface ColumnInfo {
  columnName: string;
  dataType: string;
  isNullable: boolean;
  columnDefault: string | null;
  isPrimaryKey: boolean;
  isForeignKey: boolean;
  foreignKeyTable?: string;
  foreignKeyColumn?: string;
}

export interface RowEditorProps {
  isOpen: boolean;
  onClose: () => void;
  schema: string;
  table: string;
  columns: ColumnInfo[];
  row?: Record<string, unknown>; // undefined for create mode
  onSave: (data: Record<string, unknown>) => Promise<void>;
}

interface ForeignKeyOption {
  value: string;
  label: string;
}

interface ValidationError {
  field: string;
  message: string;
}

// ============================================================================
// API Functions
// ============================================================================

const API_BASE = '/api/database/explorer';

const getAuthHeader = (): Record<string, string> => {
  const token = getAccessToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
};

async function fetchForeignKeyValues(
  schema: string,
  table: string,
  column: string,
  search?: string
): Promise<ForeignKeyOption[]> {
  const params = new URLSearchParams({
    limit: '100',
  });
  if (search) {
    params.set('search', search);
  }

  const response = await fetch(
    `${API_BASE}/schemas/${schema}/tables/${table}/columns/${column}/values?${params}`,
    { credentials: 'include', headers: { ...getAuthHeader() } }
  );

  if (!response.ok) {
    // Fallback: try to get data directly from the table
    const dataResponse = await fetch(
      `${API_BASE}/schemas/${schema}/tables/${table}/data?limit=100`,
      { credentials: 'include', headers: { ...getAuthHeader() } }
    );
    if (!dataResponse.ok) return [];

    const data = await dataResponse.json();
    return data.rows.map((row: Record<string, unknown>) => ({
      value: String(row[column] ?? ''),
      label: String(row[column] ?? ''),
    }));
  }

  const json = await response.json();
  return json && json.data ? json.data : json;
}

// ============================================================================
// Utilities
// ============================================================================

const formatValue = (value: unknown): string => {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') {
    if (value instanceof Date) return value.toISOString();
    return JSON.stringify(value, null, 2);
  }
  return String(value);
};

const formatDateTimeLocal = (value: unknown): string => {
  if (!value) return '';
  const date = new Date(String(value));
  if (isNaN(date.getTime())) return '';
  // Format: YYYY-MM-DDTHH:mm
  return date.toISOString().slice(0, 16);
};

const formatDateValue = (value: unknown): string => {
  if (!value) return '';
  const date = new Date(String(value));
  if (isNaN(date.getTime())) return '';
  // Format: YYYY-MM-DD
  return date.toISOString().slice(0, 10);
};

const isAutoGenerated = (column: ColumnInfo): boolean => {
  const defaultVal = column.columnDefault?.toLowerCase() || '';
  return (
    defaultVal.includes('gen_random_uuid') ||
    defaultVal.includes('uuid_generate') ||
    defaultVal.includes('nextval') ||
    (column.isPrimaryKey && column.dataType.includes('serial'))
  );
};

const isJsonType = (dataType: string): boolean => {
  const type = dataType.toLowerCase();
  return type.includes('json') || type.includes('jsonb');
};

const isNumericType = (dataType: string): boolean => {
  const type = dataType.toLowerCase();
  return (
    type.includes('int') ||
    type.includes('numeric') ||
    type.includes('decimal') ||
    type.includes('float') ||
    type.includes('double') ||
    type.includes('real')
  );
};

const isBooleanType = (dataType: string): boolean => {
  return dataType.toLowerCase().includes('bool');
};

const isDateTimeType = (dataType: string): boolean => {
  const type = dataType.toLowerCase();
  return type.includes('timestamp') || type === 'timestamptz';
};

const isDateType = (dataType: string): boolean => {
  const type = dataType.toLowerCase();
  return type === 'date';
};

const isTextAreaType = (dataType: string): boolean => {
  const type = dataType.toLowerCase();
  return type === 'text' || isJsonType(dataType);
};

const validateJson = (value: string): string | null => {
  if (!value.trim()) return null;
  try {
    JSON.parse(value);
    return null;
  } catch (e) {
    return 'Invalid JSON syntax';
  }
};

const validateNumber = (value: string, dataType: string): string | null => {
  if (!value.trim()) return null;
  const num = Number(value);
  if (isNaN(num)) return 'Must be a valid number';
  if (dataType.toLowerCase().includes('int') && !Number.isInteger(num)) {
    return 'Must be an integer';
  }
  return null;
};

// ============================================================================
// Sub-components
// ============================================================================

interface FieldInputProps {
  column: ColumnInfo;
  value: string;
  onChange: (value: string) => void;
  disabled: boolean;
  error?: string;
  fkOptions: ForeignKeyOption[];
  fkLoading: boolean;
  fkSearch: string;
  onFkSearch: (search: string) => void;
}

const FieldInput: React.FC<FieldInputProps> = ({
  column,
  value,
  onChange,
  disabled,
  error,
  fkOptions,
  fkLoading,
  fkSearch,
  onFkSearch,
}) => {
  const inputClassName = `w-full px-3 py-2 border rounded-lg transition-colors text-sm
    ${error ? 'border-red-500 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}
    ${disabled ? 'bg-gray-100 cursor-not-allowed text-gray-500' : 'bg-white'}
    focus:outline-none focus:ring-2`;

  // Foreign Key Select
  if (column.isForeignKey && !disabled) {
    return (
      <div className="relative">
        <div className="flex gap-2">
          <input
            type="text"
            value={fkSearch}
            onChange={(e) => onFkSearch(e.target.value)}
            placeholder="Search..."
            className="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <select
          value={value}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          className={`${inputClassName} mt-2`}
        >
          <option value="">-- Select --</option>
          {fkLoading ? (
            <option disabled>Loading...</option>
          ) : (
            fkOptions.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))
          )}
        </select>
        <div className="text-xs text-gray-500 mt-1">
          FK: {column.foreignKeyTable}.{column.foreignKeyColumn}
        </div>
      </div>
    );
  }

  // Boolean Checkbox
  if (isBooleanType(column.dataType)) {
    return (
      <label className="flex items-center gap-3 cursor-pointer">
        <input
          type="checkbox"
          checked={value === 'true' || value === '1'}
          onChange={(e) => onChange(e.target.checked ? 'true' : 'false')}
          disabled={disabled}
          className="w-5 h-5 rounded border-gray-300 text-blue-600 focus:ring-blue-500 cursor-pointer disabled:cursor-not-allowed"
        />
        <span className="text-sm text-gray-600">
          {value === 'true' || value === '1' ? 'True' : 'False'}
        </span>
      </label>
    );
  }

  // DateTime Local
  if (isDateTimeType(column.dataType)) {
    return (
      <input
        type="datetime-local"
        value={formatDateTimeLocal(value) || value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        className={inputClassName}
      />
    );
  }

  // Date
  if (isDateType(column.dataType)) {
    return (
      <input
        type="date"
        value={formatDateValue(value) || value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        className={inputClassName}
      />
    );
  }

  // Number
  if (isNumericType(column.dataType)) {
    return (
      <input
        type="number"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        step={column.dataType.toLowerCase().includes('int') ? '1' : 'any'}
        className={inputClassName}
      />
    );
  }

  // Textarea (JSON or text)
  if (isTextAreaType(column.dataType)) {
    return (
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        rows={isJsonType(column.dataType) ? 5 : 3}
        className={`${inputClassName} font-mono`}
        placeholder={isJsonType(column.dataType) ? '{ }' : ''}
      />
    );
  }

  // Default: Text input
  return (
    <input
      type="text"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      className={inputClassName}
      placeholder={column.columnDefault || ''}
    />
  );
};

// ============================================================================
// Main Component
// ============================================================================

export const RowEditor: React.FC<RowEditorProps> = ({
  isOpen,
  onClose,
  schema,
  table,
  columns,
  row,
  onSave,
}) => {
  const isEditMode = row !== undefined;

  // Form state
  const [formData, setFormData] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);

  // FK state
  const [fkOptions, setFkOptions] = useState<Record<string, ForeignKeyOption[]>>({});
  const [fkLoading, setFkLoading] = useState<Record<string, boolean>>({});
  const [fkSearch, setFkSearch] = useState<Record<string, string>>({});

  // Group columns
  const { primaryKeyColumns, requiredColumns, optionalColumns } = useMemo(() => {
    const pkCols: ColumnInfo[] = [];
    const reqCols: ColumnInfo[] = [];
    const optCols: ColumnInfo[] = [];

    columns.forEach((col) => {
      if (col.isPrimaryKey) {
        pkCols.push(col);
      } else if (!col.isNullable && !col.columnDefault) {
        reqCols.push(col);
      } else {
        optCols.push(col);
      }
    });

    return {
      primaryKeyColumns: pkCols,
      requiredColumns: reqCols,
      optionalColumns: optCols,
    };
  }, [columns]);

  // Initialize form data
  useEffect(() => {
    if (isOpen) {
      const initialData: Record<string, string> = {};
      columns.forEach((col) => {
        if (row && row[col.columnName] !== undefined && row[col.columnName] !== null) {
          if (isBooleanType(col.dataType)) {
            initialData[col.columnName] = row[col.columnName] ? 'true' : 'false';
          } else if (isDateTimeType(col.dataType)) {
            initialData[col.columnName] = formatDateTimeLocal(row[col.columnName]);
          } else if (isDateType(col.dataType)) {
            initialData[col.columnName] = formatDateValue(row[col.columnName]);
          } else {
            initialData[col.columnName] = formatValue(row[col.columnName]);
          }
        } else {
          initialData[col.columnName] = '';
        }
      });
      setFormData(initialData);
      setError(null);
      setValidationErrors([]);
      setFkSearch({});
    }
  }, [isOpen, columns, row]);

  // Load FK options
  useEffect(() => {
    if (!isOpen) return;

    const fkColumns = columns.filter((col) => col.isForeignKey && col.foreignKeyTable && col.foreignKeyColumn);

    fkColumns.forEach((col) => {
      loadFkOptions(col.columnName, col.foreignKeyTable!, col.foreignKeyColumn!, '');
    });
  }, [isOpen, columns, schema]);

  const loadFkOptions = useCallback(
    async (columnName: string, fkTable: string, fkColumn: string, search: string) => {
      setFkLoading((prev) => ({ ...prev, [columnName]: true }));

      try {
        const options = await fetchForeignKeyValues(schema, fkTable, fkColumn, search);
        setFkOptions((prev) => ({ ...prev, [columnName]: options }));
      } catch {
        setFkOptions((prev) => ({ ...prev, [columnName]: [] }));
      } finally {
        setFkLoading((prev) => ({ ...prev, [columnName]: false }));
      }
    },
    [schema]
  );

  const handleFkSearch = useCallback(
    (columnName: string, col: ColumnInfo, search: string) => {
      setFkSearch((prev) => ({ ...prev, [columnName]: search }));

      // Debounce search
      const timeoutId = setTimeout(() => {
        if (col.foreignKeyTable && col.foreignKeyColumn) {
          loadFkOptions(columnName, col.foreignKeyTable, col.foreignKeyColumn, search);
        }
      }, 300);

      return () => clearTimeout(timeoutId);
    },
    [loadFkOptions]
  );

  const handleFieldChange = useCallback((columnName: string, value: string) => {
    setFormData((prev) => ({ ...prev, [columnName]: value }));
    // Clear validation error for this field
    setValidationErrors((prev) => prev.filter((e) => e.field !== columnName));
  }, []);

  const validateForm = useCallback((): boolean => {
    const errors: ValidationError[] = [];

    columns.forEach((col) => {
      const value = formData[col.columnName]?.trim() || '';
      const isAutoGen = isAutoGenerated(col);

      // Skip auto-generated fields in create mode
      if (!isEditMode && isAutoGen) return;

      // Required field validation
      if (!col.isNullable && !col.columnDefault && !isAutoGen && !value) {
        errors.push({ field: col.columnName, message: 'This field is required' });
        return;
      }

      if (!value) return;

      // Type-specific validation
      if (isJsonType(col.dataType)) {
        const jsonError = validateJson(value);
        if (jsonError) {
          errors.push({ field: col.columnName, message: jsonError });
        }
      }

      if (isNumericType(col.dataType)) {
        const numError = validateNumber(value, col.dataType);
        if (numError) {
          errors.push({ field: col.columnName, message: numError });
        }
      }
    });

    setValidationErrors(errors);
    return errors.length === 0;
  }, [columns, formData, isEditMode]);

  const handleSave = async () => {
    if (!validateForm()) return;

    setSaving(true);
    setError(null);

    try {
      const parsedData: Record<string, unknown> = {};

      columns.forEach((col) => {
        const value = formData[col.columnName];
        const isAutoGen = isAutoGenerated(col);

        // Skip auto-generated fields in create mode
        if (!isEditMode && isAutoGen) return;

        // Skip primary key in edit mode if auto-generated
        if (isEditMode && col.isPrimaryKey && isAutoGen) return;

        if (value === '' || value === undefined) {
          if (col.isNullable) {
            parsedData[col.columnName] = null;
          }
          return;
        }

        // Parse based on data type
        if (isBooleanType(col.dataType)) {
          parsedData[col.columnName] = value === 'true' || value === '1';
        } else if (isNumericType(col.dataType)) {
          parsedData[col.columnName] = col.dataType.toLowerCase().includes('int')
            ? parseInt(value, 10)
            : parseFloat(value);
        } else if (isJsonType(col.dataType)) {
          try {
            parsedData[col.columnName] = JSON.parse(value);
          } catch {
            parsedData[col.columnName] = value;
          }
        } else if (isDateTimeType(col.dataType) || isDateType(col.dataType)) {
          parsedData[col.columnName] = value ? new Date(value).toISOString() : null;
        } else {
          parsedData[col.columnName] = value;
        }
      });

      await onSave(parsedData);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save');
    } finally {
      setSaving(false);
    }
  };

  const handleReset = () => {
    const initialData: Record<string, string> = {};
    columns.forEach((col) => {
      if (row && row[col.columnName] !== undefined && row[col.columnName] !== null) {
        if (isBooleanType(col.dataType)) {
          initialData[col.columnName] = row[col.columnName] ? 'true' : 'false';
        } else if (isDateTimeType(col.dataType)) {
          initialData[col.columnName] = formatDateTimeLocal(row[col.columnName]);
        } else if (isDateType(col.dataType)) {
          initialData[col.columnName] = formatDateValue(row[col.columnName]);
        } else {
          initialData[col.columnName] = formatValue(row[col.columnName]);
        }
      } else {
        initialData[col.columnName] = '';
      }
    });
    setFormData(initialData);
    setValidationErrors([]);
    setError(null);
  };

  const getFieldError = (columnName: string): string | undefined => {
    return validationErrors.find((e) => e.field === columnName)?.message;
  };

  const renderColumnField = (col: ColumnInfo) => {
    const isAutoGen = isAutoGenerated(col);
    const isDisabled = isAutoGen && (isEditMode || !isEditMode); // Disabled in both modes for auto-gen
    const fieldError = getFieldError(col.columnName);
    const isRequired = !col.isNullable && !col.columnDefault && !isAutoGen;

    return (
      <div key={col.columnName} className="space-y-1">
        {/* Label */}
        <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
          <span>{col.columnName}</span>
          {col.isPrimaryKey && (
            <Badge variant="info" className="text-xs">
              PK
            </Badge>
          )}
          {col.isForeignKey && (
            <Badge variant="warning" className="text-xs">
              FK
            </Badge>
          )}
          {isRequired && <span className="text-red-500">*</span>}
        </label>

        {/* Input */}
        <FieldInput
          column={col}
          value={formData[col.columnName] || ''}
          onChange={(value) => handleFieldChange(col.columnName, value)}
          disabled={isDisabled}
          error={fieldError}
          fkOptions={fkOptions[col.columnName] || []}
          fkLoading={fkLoading[col.columnName] || false}
          fkSearch={fkSearch[col.columnName] || ''}
          onFkSearch={(search) => handleFkSearch(col.columnName, col, search)}
        />

        {/* Field info & error */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Badge
              variant={
                isNumericType(col.dataType)
                  ? 'info'
                  : isBooleanType(col.dataType)
                  ? 'error'
                  : isDateTimeType(col.dataType) || isDateType(col.dataType)
                  ? 'warning'
                  : 'default'
              }
              className="text-xs"
            >
              {col.dataType}
            </Badge>
            {col.isNullable && (
              <span className="text-xs text-gray-400">nullable</span>
            )}
            {isAutoGen && (
              <span className="text-xs text-gray-400">auto-generated</span>
            )}
          </div>
          {fieldError && (
            <span className="text-xs text-red-500">{fieldError}</span>
          )}
        </div>
      </div>
    );
  };

  const renderFieldGroup = (
    title: string,
    cols: ColumnInfo[],
    variant: 'primary' | 'required' | 'optional'
  ) => {
    if (cols.length === 0) return null;

    const bgColor =
      variant === 'primary'
        ? 'bg-blue-50 border-blue-200'
        : variant === 'required'
        ? 'bg-yellow-50 border-yellow-200'
        : 'bg-gray-50 border-gray-200';

    return (
      <div className={`p-4 rounded-lg border ${bgColor}`}>
        <h4 className="text-sm font-semibold text-gray-700 mb-4">{title}</h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {cols.map(renderColumnField)}
        </div>
      </div>
    );
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={isEditMode ? `Edit Row - ${table}` : `Add New Row - ${table}`}
      description={`Schema: ${schema}`}
      size="xl"
    >
      {/* Error Alert */}
      {error && (
        <Alert type="error" className="mb-4" dismissible onDismiss={() => setError(null)}>
          {error}
        </Alert>
      )}

      {/* Validation Errors Summary */}
      {validationErrors.length > 0 && (
        <Alert type="warning" className="mb-4">
          <span className="font-medium">Please fix the following errors:</span>
          <ul className="mt-2 list-disc list-inside">
            {validationErrors.map((err) => (
              <li key={err.field}>
                <span className="font-medium">{err.field}:</span> {err.message}
              </li>
            ))}
          </ul>
        </Alert>
      )}

      {/* Scrollable Content */}
      <div className="space-y-6 max-h-[60vh] overflow-y-auto pr-2">
        {/* Primary Keys */}
        {renderFieldGroup('Primary Keys', primaryKeyColumns, 'primary')}

        {/* Required Fields */}
        {renderFieldGroup('Required Fields', requiredColumns, 'required')}

        {/* Optional Fields */}
        {renderFieldGroup('Optional Fields', optionalColumns, 'optional')}
      </div>

      {/* Actions */}
      <div className="flex items-center justify-between mt-6 pt-4 border-t border-gray-200">
        <Button
          variant="ghost"
          onClick={handleReset}
          disabled={saving}
        >
          Reset Form
        </Button>

        <div className="flex gap-3">
          <Button
            variant="outline"
            onClick={onClose}
            disabled={saving}
          >
            Cancel
          </Button>
          <Button
            onClick={handleSave}
            disabled={saving}
          >
            {saving ? (
              <>
                <Spinner size="sm" className="mr-2" />
                Saving...
              </>
            ) : isEditMode ? (
              'Save Changes'
            ) : (
              'Create Row'
            )}
          </Button>
        </div>
      </div>
    </Modal>
  );
};

export default RowEditor;
