#!/usr/bin/env sh
# Minimal husky.sh bootstrap — regenerated by Batch 82 when
# node_modules/husky was absent. Sets errexit + ignores hook
# paths outside the git repo root.
if [ -z "$husky_skip_init" ]; then
  readonly hook_name="$(basename "$0")"
  debug () {
    [ "$HUSKY_DEBUG" = "1" ] && echo "husky (debug) - $1"
  }
  debug "starting $hook_name..."
  export readonly husky_skip_init=1
  sh -e "$0" "$@"
  exitCode="$?"
  if [ $exitCode != 0 ]; then
    echo "husky - $hook_name hook exited with code $exitCode (error)"
  fi
  exit $exitCode
fi
