import type { QueryRunner } from 'typeorm';
import { ConvertFarmOutboxToIdentity1781200000000 } from './1781200000000-ConvertFarmOutboxToIdentity';

/**
 * ConvertFarmOutboxToIdentity.spec.ts
 * ============================================================================
 *
 * Behavioural tests for the BIGSERIAL → IDENTITY conversion. The non-
 * trivial parts are:
 *
 *   1. Idempotency — attidentity check must short-circuit when the
 *      column is already IDENTITY ('a' or 'd'), without issuing any
 *      DDL.
 *   2. Missing column — a fresh environment where CreateFarmOutboxTable
 *      has not run yet must warn + return, not throw.
 *   3. Sequence state capture — `is_called` semantics differ between
 *      "sequence never used" (`last_value + 0`) and "sequence used"
 *      (`last_value + 1`). Getting this wrong silently duplicates PKs.
 *   4. RESTART WITH value — must be computed correctly from the
 *      captured sequence state, and must appear verbatim in the
 *      CREATE IDENTITY statement.
 */

function makeMockRunner(replies: ReadonlyArray<unknown>): {
  runner: QueryRunner;
  calls: Array<{ sql: string; params?: unknown[] }>;
} {
  const calls: Array<{ sql: string; params?: unknown[] }> = [];
  let idx = 0;
  const runner = {
    query: async (sql: string, params?: unknown[]): Promise<unknown> => {
      calls.push({ sql, params });
      if (idx >= replies.length) {
        throw new Error(
          `mock runner exhausted at call ${idx}: unexpected SQL "${sql.slice(
            0,
            80,
          )}..."`,
        );
      }
      return replies[idx++];
    },
  } as unknown as QueryRunner;
  return { runner, calls };
}

describe('ConvertFarmOutboxToIdentity1781200000000', () => {
  let migration: ConvertFarmOutboxToIdentity1781200000000;

  beforeEach(() => {
    migration = new ConvertFarmOutboxToIdentity1781200000000();
  });

  describe('up() — happy path', () => {
    it('converts BIGSERIAL → IDENTITY preserving sequence state (is_called=true)', async () => {
      const replies = [
        [{ current_schema: 'farm' }],          // 0: current_schema
        [{ attidentity: '' }],                 // 1: identity check — empty = BIGSERIAL
        [{ seq: 'farm.farm_outbox_id_seq' }],  // 2: pg_get_serial_sequence
        [{ last_value: '42', is_called: true }], // 3: sequence state
        undefined,                             // 4: DROP DEFAULT
        undefined,                             // 5: DROP SEQUENCE
        undefined,                             // 6: ALTER COLUMN ... ADD IDENTITY
      ];
      const { runner, calls } = makeMockRunner(replies);

      await migration.up(runner);

      expect(calls.length).toBe(7);

      // Critical: the RESTART WITH value must be 43 (last_value + 1)
      // because is_called=true means nextval() has already been
      // invoked and the next call will return 43.
      expect(calls[6]?.sql).toContain('RESTART WITH 43');
      expect(calls[6]?.sql).toContain('GENERATED BY DEFAULT AS IDENTITY');
      expect(calls[6]?.sql).toContain('"farm"."farm_outbox"');
    });

    it('converts preserving sequence state (is_called=false, fresh sequence)', async () => {
      // A sequence that has never had nextval() called has
      // is_called=false, and the next call will return last_value
      // (NOT last_value + 1). This branch is easy to get wrong.
      const replies = [
        [{ current_schema: 'farm' }],
        [{ attidentity: '' }],
        [{ seq: 'farm.farm_outbox_id_seq' }],
        [{ last_value: '1', is_called: false }], // fresh sequence
        undefined, undefined, undefined,
      ];
      const { runner, calls } = makeMockRunner(replies);

      await migration.up(runner);

      // RESTART WITH = last_value (1), not last_value + 1 (2).
      // The new IDENTITY must still produce 1 on the first nextval.
      expect(calls[6]?.sql).toContain('RESTART WITH 1');
    });
  });

  describe('up() — idempotency', () => {
    it('short-circuits when column is already IDENTITY (attidentity="d")', async () => {
      const replies = [
        [{ current_schema: 'farm' }],
        [{ attidentity: 'd' }], // already GENERATED BY DEFAULT AS IDENTITY
      ];
      const { runner, calls } = makeMockRunner(replies);

      await migration.up(runner);

      // Only the two introspection queries fire. No DDL, no sequence
      // capture. Re-running the migration is free.
      expect(calls.length).toBe(2);
    });

    it('short-circuits when column is already ALWAYS IDENTITY (attidentity="a")', async () => {
      const replies = [
        [{ current_schema: 'farm' }],
        [{ attidentity: 'a' }],
      ];
      const { runner, calls } = makeMockRunner(replies);

      await migration.up(runner);
      expect(calls.length).toBe(2);
    });
  });

  describe('up() — environment resilience', () => {
    it('warns and returns when farm_outbox column does not exist', async () => {
      const replies = [
        [{ current_schema: 'farm' }],
        [], // empty result — column not found
      ];
      const { runner, calls } = makeMockRunner(replies);

      // Must NOT throw — production bootstrap order can run this
      // migration before CreateFarmOutboxTable on a fresh environment.
      await expect(migration.up(runner)).resolves.toBeUndefined();

      // Only the introspection queries ran.
      expect(calls.length).toBe(2);
    });

    it('throws loud when column exists but has no associated sequence', async () => {
      // Corrupted schema — column exists with attidentity='' but
      // pg_get_serial_sequence returns NULL. Indicates manual DDL
      // surgery; migration should refuse to proceed.
      const replies = [
        [{ current_schema: 'farm' }],
        [{ attidentity: '' }],
        [{ seq: null }],
      ];
      const { runner } = makeMockRunner(replies);

      await expect(migration.up(runner)).rejects.toThrow(
        /has no associated sequence/,
      );
    });
  });

  describe('up() — SQL shape', () => {
    it('issues DROP DEFAULT, DROP SEQUENCE, ADD IDENTITY in the documented order', async () => {
      const replies = [
        [{ current_schema: 'farm' }],
        [{ attidentity: '' }],
        [{ seq: 'farm.farm_outbox_id_seq' }],
        [{ last_value: '10', is_called: true }],
        undefined, undefined, undefined,
      ];
      const { runner, calls } = makeMockRunner(replies);

      await migration.up(runner);

      // Order is load-bearing: DROP DEFAULT before DROP SEQUENCE
      // (otherwise DROP SEQUENCE fails with "cannot drop sequence
      // because other objects depend on it"). ADD IDENTITY last.
      expect(calls[4]?.sql).toContain('DROP DEFAULT');
      expect(calls[5]?.sql).toContain('DROP SEQUENCE IF EXISTS');
      expect(calls[6]?.sql).toContain('ADD GENERATED BY DEFAULT AS IDENTITY');
    });
  });
});
