import { MigrationInterface, QueryRunner } from 'typeorm';
import { MigrationLogger } from '@aquaculture/backend-common';

/**
 * ConvertFarmOutboxToIdentity1781200000000
 * ============================================================================
 *
 * Converts `farm_outbox.id` from legacy `BIGSERIAL` to
 * `BIGINT GENERATED BY DEFAULT AS IDENTITY`.
 *
 * # Why
 *
 * `BIGSERIAL` is a backwards-compat macro from pre-PG10 days: it creates a
 * detached sequence, sets the column default to `nextval('seq')`, and links
 * the sequence ownership via `ALTER SEQUENCE ... OWNED BY`. The modern
 * replacement is `GENERATED ... AS IDENTITY` (SQL standard, introduced in
 * PG10), which:
 *
 * 1. Keeps the sequence **integrated** with the column so `pg_dump`,
 *    `CREATE TABLE LIKE`, and table renames preserve the link without
 *    extra ALTER statements.
 * 2. Prevents accidental manual INSERTs into the `id` column when declared
 *    `GENERATED ALWAYS` (we use `BY DEFAULT` to preserve existing
 *    application code that can still override the value if needed).
 * 3. Plays nicely with logical replication and partitioning features added
 *    after PG10.
 * 4. Is the single documented "correct" choice per the PostgreSQL project
 *    and our internal `database-design:postgresql` skill.
 *
 * The `CreateFarmOutboxTable1780300000000` migration shipped the legacy
 * `BIGSERIAL` because the helper at the time wasn't aware of the rule. We
 * cannot edit that migration in place — TypeORM tracks applied migrations
 * by class name, so editing an already-applied migration would be a
 * silent no-op on existing environments. A forward migration is the
 * correct fix.
 *
 * # Conversion semantics — preserving sequence state
 *
 * The most dangerous part of a SERIAL → IDENTITY conversion is losing the
 * current sequence value. If the new IDENTITY restarts from 1, the next
 * INSERT will collide with an existing row and fail with a primary key
 * violation.
 *
 * The conversion is therefore:
 *
 * 1. Capture the sequence's `last_value` and `is_called` state. A sequence
 *    that has never been used has `is_called = false` and `last_value = 1`
 *    — we must respect that difference to avoid double-consuming the
 *    first number.
 * 2. Drop the column default (removes the `nextval('seq')` expression).
 * 3. Drop the sequence (which is now unowned because its column default
 *    is gone).
 * 4. Attach a new IDENTITY sequence via
 *    `ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH <next>)`
 *    where `<next>` is `last_value + 1` when `is_called` is true, and
 *    `last_value` otherwise. The `RESTART WITH` clause is the ONLY way to
 *    avoid losing the sequence state.
 * 5. Verify: `SELECT nextval(pg_get_serial_sequence('farm_outbox', 'id'))`
 *    should now come from the new IDENTITY sequence; the row count and
 *    max(id) are unchanged.
 *
 * # Idempotency
 *
 * Before touching anything, the migration checks
 * `pg_attribute.attidentity` — if it is already `'a'` (ALWAYS) or `'d'`
 * (BY DEFAULT), the column is an IDENTITY and the migration logs + exits.
 * This lets the migration run safely on environments that were manually
 * converted (staging, dev) and in any case where it is re-applied.
 *
 * # Locking
 *
 * `ALTER TABLE ... ALTER COLUMN ... DROP DEFAULT` and the subsequent
 * IDENTITY attach are metadata-only changes on the column — PostgreSQL
 * does not rewrite the table. The operation takes an ACCESS EXCLUSIVE lock
 * but releases it immediately. Outbox tables are tiny (unpublished events
 * only), so the impact is negligible.
 */
export class ConvertFarmOutboxToIdentity1781200000000
  implements MigrationInterface
{
  name = 'ConvertFarmOutboxToIdentity1781200000000';
  private readonly logger = new MigrationLogger(this.name);

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Read current_schema via standard row access so TS's noUncheckedIndexedAccess
    // (which types arr[0] as T | undefined) is satisfied with an explicit check.
    const schemaRows: Array<{ current_schema: string }> = await queryRunner.query(
      `SELECT current_schema()`,
    );
    const schema = schemaRows[0]?.current_schema;
    if (!schema) {
      throw new Error(
        'SELECT current_schema() returned no rows — cannot proceed with migration',
      );
    }
    this.logger.log(`Converting farm_outbox.id to IDENTITY in schema "${schema}"`);

    // Idempotency guard — skip if already IDENTITY.
    // pg_attribute.attidentity: '' = not identity, 'a' = ALWAYS, 'd' = DEFAULT
    const identityCheck: Array<{ attidentity: string }> = await queryRunner.query(
      `
      SELECT a.attidentity
      FROM pg_attribute a
      JOIN pg_class c ON a.attrelid = c.oid
      JOIN pg_namespace n ON c.relnamespace = n.oid
      WHERE n.nspname = $1
        AND c.relname = 'farm_outbox'
        AND a.attname = 'id'
        AND a.attnum > 0
        AND NOT a.attisdropped
      `,
      [schema],
    );

    if (identityCheck.length === 0) {
      this.logger.warn(
        `farm_outbox.id column not found in schema "${schema}" — skipping. ` +
          `This is expected on environments that have not yet run ` +
          `CreateFarmOutboxTable1780300000000.`,
      );
      return;
    }

    // First row is guaranteed present by the length check above, but TS
    // can't prove it under noUncheckedIndexedAccess — re-access via const.
    const existingIdentity = identityCheck[0]?.attidentity ?? '';
    if (existingIdentity !== '') {
      this.logger.log(
        `farm_outbox.id is already IDENTITY (attidentity='${existingIdentity}') — skipping`,
      );
      return;
    }

    // ── Step 1: Capture existing sequence state ────────────────────────
    // pg_get_serial_sequence is the portable way to find the sequence name
    // regardless of whether it was created via SERIAL, BIGSERIAL, or an
    // explicit CREATE SEQUENCE OWNED BY.
    const seqRows: Array<{ seq: string | null }> = await queryRunner.query(
      `SELECT pg_get_serial_sequence($1, 'id') AS seq`,
      [`${schema}.farm_outbox`],
    );
    const sequenceName = seqRows[0]?.seq;

    if (!sequenceName) {
      // Edge case: column has no associated sequence. This should never
      // happen for a BIGSERIAL column, but we guard against it so a
      // corrupted schema fails loudly instead of silently.
      throw new Error(
        `farm_outbox.id has no associated sequence — schema is in an ` +
          `inconsistent state. Investigate before retrying migration.`,
      );
    }

    // Read last_value and is_called. is_called indicates whether nextval()
    // has been invoked at least once; if false, the next call will return
    // last_value itself, not last_value + 1.
    const seqState: Array<{ last_value: string; is_called: boolean }> =
      await queryRunner.query(`SELECT last_value, is_called FROM ${sequenceName}`);
    const seqRow = seqState[0];
    if (!seqRow) {
      throw new Error(
        `Sequence ${sequenceName} exists but returned no state row — ` +
          `schema corruption suspected.`,
      );
    }
    const lastValue = BigInt(seqRow.last_value);
    const isCalled = seqRow.is_called;

    // Compute the value the next nextval() would produce. This becomes the
    // IDENTITY's RESTART WITH value so post-conversion INSERTs continue
    // the numbering from exactly where the old sequence left off.
    const nextValue = isCalled ? lastValue + 1n : lastValue;

    this.logger.log(
      `Existing sequence ${sequenceName}: last_value=${lastValue}, is_called=${isCalled}, next=${nextValue}`,
    );

    // ── Step 2: Drop the column default ────────────────────────────────
    // This removes the `nextval('seq')` expression so the sequence is no
    // longer tied to the column. Necessary before dropping the sequence.
    await queryRunner.query(
      `ALTER TABLE "${schema}"."farm_outbox" ALTER COLUMN "id" DROP DEFAULT`,
    );

    // ── Step 3: Drop the now-unowned sequence ──────────────────────────
    // At this point the sequence is no longer used by any column and can
    // be dropped without cascading effects.
    await queryRunner.query(`DROP SEQUENCE IF EXISTS ${sequenceName}`);

    // ── Step 4: Attach a new IDENTITY sequence ─────────────────────────
    // `GENERATED BY DEFAULT` (not ALWAYS) so existing application code
    // that explicitly sets id on INSERT (e.g. for idempotency keys) still
    // works. `RESTART WITH` continues the numbering.
    //
    // SAFETY: The RESTART WITH value is computed from a trusted
    // pg_sequence read and does not involve user input — SQL injection is
    // impossible here. Interpolation is required because RESTART WITH
    // does not accept parameters.
    await queryRunner.query(
      `ALTER TABLE "${schema}"."farm_outbox" ` +
        `ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH ${nextValue})`,
    );

    this.logger.log(
      `farm_outbox.id converted to IDENTITY with RESTART WITH ${nextValue}`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Reverting IDENTITY → SERIAL is possible but pointless: the old style
    // is deprecated for a reason and the application behaviour is
    // unchanged either way. This down() exists solely to satisfy the
    // TypeORM MigrationInterface contract — calling it is a "break glass"
    // operation that should only happen as part of a full rollback.
    const schemaRows: Array<{ current_schema: string }> = await queryRunner.query(
      `SELECT current_schema()`,
    );
    const schema = schemaRows[0]?.current_schema;
    if (!schema) {
      throw new Error('SELECT current_schema() returned no rows');
    }
    this.logger.warn(
      `Rolling back farm_outbox.id IDENTITY → BIGSERIAL in schema "${schema}". ` +
        `This is a break-glass operation.`,
    );

    // Capture the current IDENTITY sequence state so we can recreate a
    // detached sequence at the same position.
    const seqRows: Array<{ seq: string | null }> = await queryRunner.query(
      `SELECT pg_get_serial_sequence($1, 'id') AS seq`,
      [`${schema}.farm_outbox`],
    );
    const identitySeq = seqRows[0]?.seq;

    let nextValue = 1n;
    if (identitySeq) {
      const state: Array<{ last_value: string; is_called: boolean }> =
        await queryRunner.query(
          `SELECT last_value, is_called FROM ${identitySeq}`,
        );
      const stateRow = state[0];
      if (stateRow) {
        const lastValue = BigInt(stateRow.last_value);
        nextValue = stateRow.is_called ? lastValue + 1n : lastValue;
      }
    }

    // Drop the IDENTITY (implicitly drops its sequence).
    await queryRunner.query(
      `ALTER TABLE "${schema}"."farm_outbox" ALTER COLUMN "id" DROP IDENTITY IF EXISTS`,
    );

    // Create a detached sequence at the captured position.
    await queryRunner.query(
      `CREATE SEQUENCE "${schema}"."farm_outbox_id_seq" START WITH ${nextValue}`,
    );

    // Link the sequence back to the column via nextval() default.
    await queryRunner.query(
      `ALTER TABLE "${schema}"."farm_outbox" ` +
        `ALTER COLUMN "id" SET DEFAULT nextval('"${schema}"."farm_outbox_id_seq"')`,
    );

    // Restore ownership so DROP TABLE cascades to the sequence.
    await queryRunner.query(
      `ALTER SEQUENCE "${schema}"."farm_outbox_id_seq" OWNED BY "${schema}"."farm_outbox"."id"`,
    );

    this.logger.warn(`Rollback complete — farm_outbox.id back on BIGSERIAL`);
  }
}
