import {
  buildTenantErasureTargetProofLedgerDownSql,
  buildTenantErasureTargetProofLedgerUpSql,
} from '@platform/outbox';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCanonicalOutboxInbox1800700000000 implements MigrationInterface {
  name = 'CreateCanonicalOutboxInbox1800700000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS farm`);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS farm.outbox_events (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "eventType" VARCHAR(100) NOT NULL,
        "tenantId" UUID NULL,
        "aggregateId" UUID NULL,
        "payload" JSONB NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "publishedAt" TIMESTAMPTZ NULL,
        "retryCount" INTEGER NOT NULL DEFAULT 0,
        "lastError" TEXT NULL,
        "nextAttemptAt" TIMESTAMPTZ NULL,
        "idempotencyKey" VARCHAR(255) NULL,
        "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
        "leasedAt" TIMESTAMPTZ NULL,
        "leasedBy" VARCHAR(128) NULL
      )
    `);

    await queryRunner.query(`
      INSERT INTO farm.outbox_events (
        "id", "eventType", "tenantId", "aggregateId", "payload", "createdAt",
        "publishedAt", "retryCount", "lastError", "nextAttemptAt", "idempotencyKey",
        "isDeadLettered", "leasedAt", "leasedBy"
      )
      SELECT
        "id", "eventType", "tenantId", "aggregateId", "payload", "createdAt",
        "publishedAt", "retryCount", "lastError", "nextAttemptAt", "idempotencyKey",
        "isDeadLettered", "leasedAt", "leasedBy"
      FROM farm.farm_outbox
      ON CONFLICT ("id") DO NOTHING
    `);

    await queryRunner.query(`
      SELECT setval(
        pg_get_serial_sequence('farm.outbox_events', 'id'),
        GREATEST(
          COALESCE((SELECT MAX("id") FROM farm.outbox_events), 0),
          COALESCE((SELECT MAX("id") FROM farm.farm_outbox), 0),
          1
        ),
        true
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_outbox_events_poll"
        ON farm.outbox_events ("createdAt")
        WHERE "publishedAt" IS NULL AND "isDeadLettered" = false
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_outbox_events_tenant"
        ON farm.outbox_events ("tenantId")
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "idx_outbox_events_idempotency"
        ON farm.outbox_events ("tenantId", "idempotencyKey")
        WHERE "idempotencyKey" IS NOT NULL
    `);
    for (const sql of buildTenantErasureTargetProofLedgerUpSql({
      schema: 'farm',
      tenantIndexName: 'idx_farm_erasure_proofs_tenant',
      eventIndexName: 'idx_farm_erasure_proofs_event',
      targetIndexName: 'idx_farm_erasure_proofs_target',
    })) {
      await queryRunner.query(sql);
    }

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS farm.inbox_messages (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "consumerName" VARCHAR(128) NOT NULL,
        "tenantId" UUID NOT NULL,
        "eventId" UUID NOT NULL,
        "eventType" VARCHAR(100) NOT NULL,
        "payload" JSONB NOT NULL,
        "receivedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "processedAt" TIMESTAMPTZ NULL,
        "retryCount" INTEGER NOT NULL DEFAULT 0,
        "lastError" TEXT NULL
      )
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "idx_inbox_messages_dedupe"
        ON farm.inbox_messages ("consumerName", "tenantId", "eventId")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_inbox_messages_pending"
        ON farm.inbox_messages ("receivedAt")
        WHERE "processedAt" IS NULL
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS farm.event_dlq (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "source" VARCHAR(64) NOT NULL,
        "tenantId" UUID NULL,
        "eventId" UUID NULL,
        "eventType" VARCHAR(100) NOT NULL,
        "payload" JSONB NOT NULL,
        "error" TEXT NOT NULL,
        "failedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "retryCount" INTEGER NOT NULL DEFAULT 0,
        "metadata" JSONB NULL
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_event_dlq_failed_at"
        ON farm.event_dlq ("failedAt" DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_event_dlq_tenant"
        ON farm.event_dlq ("tenantId")
    `);

    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION farm.bridge_farm_outbox_to_outbox_events()
      RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        INSERT INTO farm.outbox_events (
          "id", "eventType", "tenantId", "aggregateId", "payload", "createdAt",
          "publishedAt", "retryCount", "lastError", "nextAttemptAt", "idempotencyKey",
          "isDeadLettered", "leasedAt", "leasedBy"
        ) VALUES (
          NEW."id", NEW."eventType", NEW."tenantId", NEW."aggregateId", NEW."payload", NEW."createdAt",
          NEW."publishedAt", NEW."retryCount", NEW."lastError", NEW."nextAttemptAt", NEW."idempotencyKey",
          NEW."isDeadLettered", NEW."leasedAt", NEW."leasedBy"
        ) ON CONFLICT ("id") DO NOTHING;
        RETURN NEW;
      END;
      $$
    `);
    await queryRunner.query(`DROP TRIGGER IF EXISTS "farm_outbox_bridge_to_outbox_events" ON farm.farm_outbox`);
    await queryRunner.query(`
      CREATE TRIGGER "farm_outbox_bridge_to_outbox_events"
        AFTER INSERT ON farm.farm_outbox
        FOR EACH ROW EXECUTE FUNCTION farm.bridge_farm_outbox_to_outbox_events()
    `);

    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION farm.notify_outbox_events_new()
      RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        PERFORM pg_notify('outbox_events_notify', '');
        RETURN NEW;
      END;
      $$
    `);
    await queryRunner.query(`DROP TRIGGER IF EXISTS "outbox_events_notify_trigger" ON farm.outbox_events`);
    await queryRunner.query(`
      CREATE TRIGGER "outbox_events_notify_trigger"
        AFTER INSERT ON farm.outbox_events
        FOR EACH ROW EXECUTE FUNCTION farm.notify_outbox_events_new()
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TRIGGER IF EXISTS "outbox_events_notify_trigger" ON farm.outbox_events`);
    await queryRunner.query(`DROP FUNCTION IF EXISTS farm.notify_outbox_events_new()`);
    await queryRunner.query(`DROP TRIGGER IF EXISTS "farm_outbox_bridge_to_outbox_events" ON farm.farm_outbox`);
    await queryRunner.query(`DROP FUNCTION IF EXISTS farm.bridge_farm_outbox_to_outbox_events()`);
    for (const sql of buildTenantErasureTargetProofLedgerDownSql({
      schema: 'farm',
      tenantIndexName: 'idx_farm_erasure_proofs_tenant',
      eventIndexName: 'idx_farm_erasure_proofs_event',
      targetIndexName: 'idx_farm_erasure_proofs_target',
    })) {
      await queryRunner.query(sql);
    }
    await queryRunner.query(`DROP TABLE IF EXISTS farm.event_dlq`);
    await queryRunner.query(`DROP TABLE IF EXISTS farm.inbox_messages`);
    await queryRunner.query(`DROP TABLE IF EXISTS farm.outbox_events`);
  }
}
