import { SourceOnlyMigration } from '@aquaculture/backend-common/database';
import { MigrationInterface, QueryRunner } from 'typeorm';

@SourceOnlyMigration({
  reason:
    'farm_outbox is source-owned infrastructure and must never be cloned into tenant schemas — it is in MODULE_SCHEMAS.farm.infrastructureTables, whose own comment says so, and a per-tenant copy of an outbox silently swallows platform-wide events',
})
export class CreateFarmOutboxTable1800200000000 implements MigrationInterface {
  name = 'CreateFarmOutboxTable1800200000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Source-relative DDL: db-migrate pins search_path to `farm`, and the
    // @SourceOnlyMigration above keeps a tenant pass from running this at all.
    // Without it the unqualified CREATE TABLE resolved into `tenant_<id>` and
    // gave every newly provisioned tenant its own farm_outbox — caught by
    // tenant-provisioning-replay.spec.ts the first time a real tenant was
    // provisioned in CI.
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS farm_outbox (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "eventType" VARCHAR(100) NOT NULL,
        "tenantId" UUID NULL,
        "aggregateId" UUID NULL,
        "payload" JSONB NOT NULL,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "publishedAt" TIMESTAMPTZ NULL,
        "retryCount" INTEGER NOT NULL DEFAULT 0,
        "lastError" TEXT NULL,
        "nextAttemptAt" TIMESTAMPTZ NULL,
        "idempotencyKey" VARCHAR(255) NULL,
        "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
        "leasedAt" TIMESTAMPTZ NULL,
        "leasedBy" VARCHAR(128) NULL
      )
    `);

    await queryRunner.query(`
      ALTER TABLE farm_outbox
        ADD COLUMN IF NOT EXISTS "tenantId" UUID,
        ADD COLUMN IF NOT EXISTS "aggregateId" UUID,
        ADD COLUMN IF NOT EXISTS "nextAttemptAt" TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS "idempotencyKey" VARCHAR(255),
        ADD COLUMN IF NOT EXISTS "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
        ADD COLUMN IF NOT EXISTS "leasedAt" TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS "leasedBy" VARCHAR(128)
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_farm_outbox_poll_entity"
        ON farm_outbox ("createdAt")
        WHERE "publishedAt" IS NULL
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_farm_outbox_tenant"
        ON farm_outbox ("tenantId")
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "idx_farm_outbox_idempotency"
        ON farm_outbox ("tenantId", "idempotencyKey")
        WHERE "idempotencyKey" IS NOT NULL
    `);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    // Forward-only repair: this table may already exist in deployed databases.
  }
}
