import { ExpandContract } from '@aquaculture/backend-common/database';
import { Logger } from '@nestjs/common';
import { MigrationInterface, QueryRunner } from 'typeorm';

import { PARAMETER_CODES, parameterQuantity } from '../../water-quality/data/parameter-quantities';

const MAPPINGS = 'water_quality_param_equipment';
const CONFIGS = 'water_quality_parameter_configs';
const MEASUREMENTS = 'water_quality_measurements';
const LEDGER = 'parameter_quantity_declarations';
const STAMP_FUNCTION = 'wqpc_stamp_quantity_configured_at';
const STAMP_TRIGGER = 'trg_wqpc_quantity_configured_at';
/** The unique (tenant, parameter, equipment) over every row; it forbids history and a backup. */
const LEGACY_MAPPING_UNIQUE = 'IDX_3283cafd2982b3e394ac021307';

const MAPPING_CHECKS: ReadonlyArray<readonly [string, string]> = [
  // One measurement point per row. Legacy rows name equipmentId only, which
  // already satisfies it.
  ['CHK_wqpe_one_point', `num_nonnulls("siteId", "systemId", "tankId", "equipmentId") = 1`],
  ['CHK_wqpe_position', `"position" IN ('representative', 'inlet', 'outlet')`],
  ['CHK_wqpe_depth', `"depthM" IS NULL OR "depthM" >= 0`],
  // A channel source names its channel by (sensorId, channelKey) and a
  // priority. A row without a channel key is a manual source; until the
  // contract release it may still carry a legacy sensorId written by the
  // previous release (read by nothing).
  [
    'CHK_wqpe_channel_source',
    `("channelKey" IS NULL AND "priority" IS NULL)
     OR ("channelKey" IS NOT NULL AND "sensorId" IS NOT NULL
         AND "priority" IN ('primary', 'backup'))`,
  ],
  // Manual cadence and alert switch belong to manual sources; a channel
  // reports continuously and alerts through the sensor service. A channel
  // source ends by being unbound, never by isActive.
  [
    'CHK_wqpe_source_settings',
    `("channelKey" IS NULL AND "monitoringFrequency" IS NOT NULL AND "alertEnabled" IS NOT NULL)
     OR ("channelKey" IS NOT NULL AND "monitoringFrequency" IS NULL
         AND "alertEnabled" IS NULL AND "isActive")`,
  ],
  [
    'CHK_wqpe_unbound',
    `("unboundAt" IS NULL AND "unboundBy" IS NULL)
     OR ("unboundAt" IS NOT NULL AND "unboundBy" IS NOT NULL AND "unboundAt" >= "boundAt")`,
  ],
];

/**
 * The parameter-equipment mapping becomes the one owner of where each
 * water-chemistry parameter is sourced (FARM-HIGH-373); parameter configs
 * carry what they measure (FARM-MEDIUM-374); a measurement names at most one
 * point (FARM-MEDIUM-375). Expand phase of plan rev2 PR-3.1 (Release B).
 *
 * # Mapping rows: sources at a measurement point
 *
 * - Point: exactly one of `siteId` | `systemId` | `tankId` | `equipmentId`
 *   (non-tank water equipment), qualified by `position` (representative,
 *   inlet, outlet) and `depthM`. Legacy rows whose `equipmentId` names a tank
 *   (a `tanks` row, or an `equipment` row flagged `isTank`, as the
 *   measurement-unit classifier decides) move to `tankId`.
 * - Source: a manual source has no channel key; a channel source names its
 *   channel by its stable natural key (`sensorId`, `channelKey`) and a
 *   `priority` (primary | backup). Nothing about the channel is copied.
 * - Temporal: `boundAt`/`boundBy`, `unboundAt`/`unboundBy`. A source ends by
 *   being unbound, so what fed a parameter at a point on a past date stays
 *   answerable after the audit log is purged. Legacy rows take
 *   `boundAt = createdAt`.
 * - `pointKey` is generated by the database from the point columns, the
 *   position and the depth, so every uniqueness rule is a plain-column partial
 *   unique index (mirrored in the entity's `@Index`) and no writer can spell a
 *   point two ways. A nil-uuid COALESCE would have put point-less rows on one
 *   key; the one-point CHECK leaves no such row.
 * - Uniques over live rows (`unboundAt IS NULL`): one manual source per
 *   parameter and point; one primary and one backup channel per parameter and
 *   point; a channel once per parameter and point. They replace the unique
 *   (tenant, parameter, equipment) over every row, which forbade both a
 *   backup and history.
 * - The previous release still writes `sensorId` on manual rows; no reader
 *   ever read it. It is cleared here and the cleared pairs are logged for the
 *   operator, and the channel-source CHECK admits that legacy shape until the
 *   contract release.
 *
 * # Parameter configs: the quantity a parameter records
 *
 * - `declaredQuantity`: what an operator declared (a registry quantity id),
 *   needed for codes that name a family (ammonia, nitrite, nitrate).
 * - `effectiveQuantity`: declared, else the code's own; persisted so the
 *   database keeps one ACTIVE config per quantity in a tenant (partial unique)
 *   instead of an advisory lock. Written by the entity from
 *   `parameterQuantity()`; backfilled here from the same function. A change to
 *   what a code means (PARAMETER_CODES) needs a migration re-deriving it —
 *   parameter-quantities.spec.ts pins the table to say so.
 * - `quantityConfiguredAt`: stamped by a trigger whenever code, unit or
 *   declared quantity change (and on insert), so a reader never pairs a value
 *   with a later meaning. NULL for existing rows: not changed since tracking
 *   began.
 * - `parameter_quantity_declarations`: append-only history of declarations,
 *   written in the declaring transaction (as sensor's
 *   channel_quantity_declarations). Per-tenant: listed in MODULE_SCHEMAS farm
 *   tables.
 *
 * # Measurements: one point
 *
 * `systemId` joins the point vocabulary and at most one of tankId,
 * equipmentId, systemId is set. Old writers filed one id in both unit columns:
 * an equal pair keeps the column of the unit's kind (classifier rule); a
 * differing pair keeps `tankId`, which is what every reader already resolved
 * (COALESCE(tankId, equipmentId)). Both counts are logged.
 *
 * # Routing and safety
 *
 * Per-tenant tables: run once per schema with the search_path pinned,
 * unqualified, each table guarded by to_regclass. Blue-green: every new column
 * is nullable or defaulted, and the entity relaxed `equipmentId`,
 * `monitoringFrequency` and `alertEnabled` one release earlier (Release A),
 * because the drift validator fails a boot whose entity says NOT NULL over a
 * nullable column (DATA-MEDIUM-020). `down` reverts only while nothing uses
 * the new shape, and refuses otherwise rather than drop sources.
 */
@ExpandContract({
  phase: 'expand',
  reason: 'Measurement points, channel sources and parameter quantities beside the legacy shape',
})
export class ExtendParamEquipmentToChannelSources1822000000000 implements MigrationInterface {
  name = 'ExtendParamEquipmentToChannelSources1822000000000';

  private readonly logger = new Logger(ExtendParamEquipmentToChannelSources1822000000000.name);

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`SET LOCAL lock_timeout = '5s'`);
    await queryRunner.query(`SET LOCAL statement_timeout = '120s'`);
    const schema = await currentSchema(queryRunner);

    if (await tablesExist(queryRunner, [CONFIGS])) {
      await this.extendConfigs(queryRunner);
    }
    if (await tablesExist(queryRunner, [MAPPINGS, 'tanks', 'equipment'])) {
      await this.extendMappings(queryRunner, schema);
    }
    if (await tablesExist(queryRunner, [MEASUREMENTS, 'equipment'])) {
      await this.extendMeasurements(queryRunner, schema);
    }
  }

  private async extendConfigs(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "${CONFIGS}"
         ADD COLUMN IF NOT EXISTS "declaredQuantity" varchar(32),
         ADD COLUMN IF NOT EXISTS "effectiveQuantity" varchar(32),
         ADD COLUMN IF NOT EXISTS "quantityConfiguredAt" timestamptz`,
    );
    const derived = Object.keys(PARAMETER_CODES).flatMap((code) => {
      const quantity = parameterQuantity(code, null);
      return quantity === null ? [] : [[code, quantity] as const];
    });
    await queryRunner.query(
      `UPDATE "${CONFIGS}" c
          SET "effectiveQuantity" = m.quantity
         FROM unnest($1::text[], $2::text[]) AS m(code, quantity)
        WHERE c."code" = m.code
          AND c."declaredQuantity" IS NULL
          AND c."effectiveQuantity" IS NULL`,
      [derived.map(([code]) => code), derived.map(([, quantity]) => quantity)],
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_wqpc_tenant_effective_quantity"
         ON "${CONFIGS}" ("tenantId", "effectiveQuantity")
       WHERE "isActive" AND "effectiveQuantity" IS NOT NULL`,
    );
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION ${STAMP_FUNCTION}()
      RETURNS TRIGGER AS $fn$
      BEGIN
        IF TG_OP = 'INSERT' THEN
          NEW."quantityConfiguredAt" := now();
        ELSIF NEW."code" IS DISTINCT FROM OLD."code"
           OR NEW."unit" IS DISTINCT FROM OLD."unit"
           OR NEW."declaredQuantity" IS DISTINCT FROM OLD."declaredQuantity" THEN
          NEW."quantityConfiguredAt" := now();
        ELSE
          NEW."quantityConfiguredAt" := OLD."quantityConfiguredAt";
        END IF;
        RETURN NEW;
      END;
      $fn$ LANGUAGE plpgsql`);
    await queryRunner.query(`DROP TRIGGER IF EXISTS ${STAMP_TRIGGER} ON "${CONFIGS}"`);
    await queryRunner.query(
      `CREATE TRIGGER ${STAMP_TRIGGER}
         BEFORE INSERT OR UPDATE ON "${CONFIGS}"
         FOR EACH ROW EXECUTE FUNCTION ${STAMP_FUNCTION}()`,
    );
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "${LEDGER}" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "tenantId" uuid NOT NULL,
        "parameterConfigId" uuid NOT NULL,
        "code" varchar(50) NOT NULL,
        "quantity" varchar(32),
        "unit" varchar(30) NOT NULL,
        "reason" varchar(32) NOT NULL,
        "declaredBy" varchar(255) NOT NULL,
        "declaredAt" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_${LEDGER}" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_pqd_reason" CHECK ("reason" IN ('declared', 'cleared'))
      )`);
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_pqd_tenant_config_declared_at"
         ON "${LEDGER}" ("tenantId", "parameterConfigId", "declaredAt")`,
    );
  }

  private async extendMappings(queryRunner: QueryRunner, schema: string): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "${MAPPINGS}"
         ADD COLUMN IF NOT EXISTS "siteId" uuid,
         ADD COLUMN IF NOT EXISTS "systemId" uuid,
         ADD COLUMN IF NOT EXISTS "tankId" uuid,
         ADD COLUMN IF NOT EXISTS "position" varchar(16) NOT NULL DEFAULT 'representative',
         ADD COLUMN IF NOT EXISTS "depthM" numeric(5,2),
         ADD COLUMN IF NOT EXISTS "channelKey" varchar(100),
         ADD COLUMN IF NOT EXISTS "priority" varchar(16),
         ADD COLUMN IF NOT EXISTS "boundAt" timestamptz,
         ADD COLUMN IF NOT EXISTS "boundBy" varchar(255),
         ADD COLUMN IF NOT EXISTS "unboundAt" timestamptz,
         ADD COLUMN IF NOT EXISTS "unboundBy" varchar(255)`,
    );
    await queryRunner.query(`
      DO $$
      DECLARE
        relaxed text;
      BEGIN
        FOREACH relaxed IN ARRAY ARRAY['equipmentId', 'monitoringFrequency', 'alertEnabled'] LOOP
          IF EXISTS (
            SELECT 1 FROM information_schema.columns
             WHERE table_schema = current_schema()
               AND table_name = '${MAPPINGS}'
               AND column_name = relaxed
               AND is_nullable = 'NO'
          ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP NOT NULL', '${MAPPINGS}', relaxed);
          END IF;
        END LOOP;
      END $$`);

    await queryRunner.query(
      `UPDATE "${MAPPINGS}" SET "boundAt" = "createdAt" WHERE "boundAt" IS NULL`,
    );
    await queryRunner.query(`ALTER TABLE "${MAPPINGS}" ALTER COLUMN "boundAt" SET DEFAULT now()`);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = '${MAPPINGS}'
             AND column_name = 'boundAt'
             AND is_nullable = 'YES'
        ) THEN
          ALTER TABLE "${MAPPINGS}" ALTER COLUMN "boundAt" SET NOT NULL;
        END IF;
      END $$`);

    // A tank presented as equipment is a tank point (measurement-unit.ts:
    // an equipment row first, tank when flagged isTank; else a tanks row).
    const moved = await updateReturning<{ id: string }>(
      queryRunner,

      `UPDATE "${MAPPINGS}" m
          SET "tankId" = m."equipmentId", "equipmentId" = NULL
        WHERE m."equipmentId" IS NOT NULL
          AND m."tankId" IS NULL AND m."systemId" IS NULL AND m."siteId" IS NULL
          AND (
            EXISTS (SELECT 1 FROM "equipment" e WHERE e."id" = m."equipmentId" AND e."isTank")
            OR (
              NOT EXISTS (SELECT 1 FROM "equipment" e WHERE e."id" = m."equipmentId")
              AND EXISTS (SELECT 1 FROM "tanks" t WHERE t."id" = m."equipmentId")
            )
          )
      RETURNING m."id"`,
    );
    const cleared = await updateReturning<{ id: string; sensorId: string }>(
      queryRunner,

      `WITH legacy AS (
         SELECT "id", "sensorId" FROM "${MAPPINGS}"
          WHERE "channelKey" IS NULL AND "sensorId" IS NOT NULL
          FOR UPDATE
       )
       UPDATE "${MAPPINGS}" m
          SET "sensorId" = NULL
         FROM legacy
        WHERE m."id" = legacy."id"
      RETURNING m."id", legacy."sensorId"`,
    );
    this.report(schema, 'param_equipment_legacy', {
      movedToTankPoint: moved.length,
      clearedSensorLinks: cleared.map((row) => ({ mappingId: row.id, sensorId: row.sensorId })),
    });

    await queryRunner.query(
      `ALTER TABLE "${MAPPINGS}"
         ADD COLUMN IF NOT EXISTS "pointKey" text GENERATED ALWAYS AS (
           COALESCE(
             'site:' || "siteId"::text,
             'system:' || "systemId"::text,
             'tank:' || "tankId"::text,
             'equipment:' || "equipmentId"::text
           ) || '|' || "position" || '|' || COALESCE("depthM"::text, '')
         ) STORED`,
    );
    for (const [constraint, predicate] of MAPPING_CHECKS) {
      await addCheck(queryRunner, MAPPINGS, constraint, predicate);
    }
    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = '${MAPPINGS}'
             AND column_name = 'pointKey'
             AND is_nullable = 'YES'
        ) THEN
          ALTER TABLE "${MAPPINGS}" ALTER COLUMN "pointKey" SET NOT NULL;
        END IF;
      END $$`);

    await queryRunner.query(`DROP INDEX IF EXISTS "${LEGACY_MAPPING_UNIQUE}"`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_wqpe_manual_source"
         ON "${MAPPINGS}" ("tenantId", "parameterConfigId", "pointKey")
       WHERE "channelKey" IS NULL AND "unboundAt" IS NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_wqpe_channel_priority"
         ON "${MAPPINGS}" ("tenantId", "parameterConfigId", "pointKey", "priority")
       WHERE "channelKey" IS NOT NULL AND "unboundAt" IS NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "UQ_wqpe_channel_key"
         ON "${MAPPINGS}" ("tenantId", "parameterConfigId", "pointKey", "sensorId", "channelKey")
       WHERE "channelKey" IS NOT NULL AND "unboundAt" IS NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_wqpe_live_channel"
         ON "${MAPPINGS}" ("tenantId", "sensorId", "channelKey")
       WHERE "channelKey" IS NOT NULL AND "unboundAt" IS NULL`,
    );
    for (const point of ['siteId', 'systemId', 'tankId'] as const) {
      await queryRunner.query(
        `CREATE INDEX IF NOT EXISTS "IDX_wqpe_tenant_${point}"
           ON "${MAPPINGS}" ("tenantId", "${point}")
         WHERE "${point}" IS NOT NULL`,
      );
    }
  }

  private async extendMeasurements(queryRunner: QueryRunner, schema: string): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "${MEASUREMENTS}" ADD COLUMN IF NOT EXISTS "systemId" uuid`,
    );
    // An equal pair is one unit filed twice: keep the column of its kind
    // (an equipment row not flagged isTank is equipment; anything else is a tank).
    const equipmentPairs = await updateReturning<{ id: string }>(
      queryRunner,

      `UPDATE "${MEASUREMENTS}" w
          SET "tankId" = NULL
        WHERE w."tankId" IS NOT NULL AND w."tankId" = w."equipmentId"
          AND EXISTS (SELECT 1 FROM "equipment" e WHERE e."id" = w."equipmentId" AND NOT e."isTank")
      RETURNING w."id"`,
    );
    const tankPairs = await updateReturning<{ id: string }>(
      queryRunner,

      `UPDATE "${MEASUREMENTS}" w
          SET "equipmentId" = NULL
        WHERE w."tankId" IS NOT NULL AND w."tankId" = w."equipmentId"
      RETURNING w."id"`,
    );
    // A differing pair: readers resolved it to tankId (COALESCE(tankId, equipmentId)).
    const differing = await updateReturning<{ id: string; equipmentId: string }>(
      queryRunner,

      `WITH pair AS (
         SELECT "id", "equipmentId" FROM "${MEASUREMENTS}"
          WHERE "tankId" IS NOT NULL AND "equipmentId" IS NOT NULL
          FOR UPDATE
       )
       UPDATE "${MEASUREMENTS}" w
          SET "equipmentId" = NULL
         FROM pair
        WHERE w."id" = pair."id"
      RETURNING w."id", pair."equipmentId"`,
    );
    this.report(schema, 'measurement_one_point', {
      equalPairsKeptAsEquipment: equipmentPairs.length,
      equalPairsKeptAsTank: tankPairs.length,
      differingPairsKeptAsTank: differing.map((row) => ({
        measurementId: row.id,
        clearedEquipmentId: row.equipmentId,
      })),
    });
    await addCheck(
      queryRunner,
      MEASUREMENTS,
      'CHK_wqm_one_point',
      `num_nonnulls("tankId", "equipmentId", "systemId") <= 1`,
    );
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_wqm_tenant_system_measured_at"
         ON "${MEASUREMENTS}" ("tenantId", "systemId", "measuredAt")
       WHERE "systemId" IS NOT NULL`,
    );
  }

  /**
   * Every table present in the pinned schema carries its new shape: the
   * mapping checks, uniques and generated point key; the config quantity
   * index and trigger; the ledger; the measurement one-point check.
   */
  public async postCondition(queryRunner: QueryRunner): Promise<boolean> {
    const rows: Array<{ ok: boolean }> = await queryRunner.query(
      `SELECT (
         (to_regclass('${CONFIGS}') IS NULL OR (
           to_regclass('${LEDGER}') IS NOT NULL
           AND EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = current_schema()
                        AND indexname = 'UQ_wqpc_tenant_effective_quantity')
           AND EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
                        WHERE c.oid = to_regclass('${CONFIGS}') AND t.tgname = '${STAMP_TRIGGER}')
         ))
         AND (to_regclass('${MAPPINGS}') IS NULL OR (
           (SELECT count(*) FROM pg_constraint
             WHERE conrelid = to_regclass('${MAPPINGS}')
               AND conname = ANY($1::text[])) = ${MAPPING_CHECKS.length}
           AND (SELECT count(*) FROM pg_indexes WHERE schemaname = current_schema()
                 AND tablename = '${MAPPINGS}'
                 AND indexname IN ('UQ_wqpe_manual_source', 'UQ_wqpe_channel_priority',
                                   'UQ_wqpe_channel_key')) = 3
           AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = current_schema()
                            AND indexname = '${LEGACY_MAPPING_UNIQUE}')
           AND EXISTS (SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema() AND table_name = '${MAPPINGS}'
                          AND column_name = 'pointKey' AND is_generated = 'ALWAYS'
                          AND is_nullable = 'NO')
         ))
         AND (to_regclass('${MEASUREMENTS}') IS NULL OR EXISTS (
           SELECT 1 FROM pg_constraint
            WHERE conrelid = to_regclass('${MEASUREMENTS}') AND conname = 'CHK_wqm_one_point'
         ))
       ) AS ok`,
      [MAPPING_CHECKS.map(([constraint]) => constraint)],
    );
    return rows[0]?.ok === true;
  }

  /**
   * Reverts the expand only while nothing relies on it: no source at a site,
   * system or tank point, no channel source, no unbound history, no declared
   * quantity, no declaration, no measurement at a system. Otherwise it refuses
   * rather than drop sources and history (the previous release cannot hold
   * them).
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`SET LOCAL lock_timeout = '5s'`);
    await queryRunner.query(`SET LOCAL statement_timeout = '120s'`);
    const usage = await expandUsage(queryRunner);
    if (usage.length > 0) {
      throw new Error(
        `${this.name}.down refused: the expanded shape is in use (${usage.join(', ')}); ` +
          'reverting would drop sources or history the previous release cannot hold',
      );
    }
    if (await tablesExist(queryRunner, [MEASUREMENTS])) {
      await queryRunner.query(`DROP INDEX IF EXISTS "IDX_wqm_tenant_system_measured_at"`);
      await queryRunner.query(
        `ALTER TABLE "${MEASUREMENTS}" DROP CONSTRAINT IF EXISTS "CHK_wqm_one_point"`,
      );
      // -- DESTRUCTIVE: empty column (down refuses while any row sets it); rollback = re-run up
      await queryRunner.query(`ALTER TABLE "${MEASUREMENTS}" DROP COLUMN IF EXISTS "systemId"`);
    }
    if (await tablesExist(queryRunner, [MAPPINGS])) {
      for (const index of [
        'UQ_wqpe_manual_source',
        'UQ_wqpe_channel_priority',
        'UQ_wqpe_channel_key',
        'IDX_wqpe_live_channel',
        'IDX_wqpe_tenant_siteId',
        'IDX_wqpe_tenant_systemId',
        'IDX_wqpe_tenant_tankId',
      ]) {
        await queryRunner.query(`DROP INDEX IF EXISTS "${index}"`);
      }
      for (const [constraint] of MAPPING_CHECKS) {
        await queryRunner.query(
          `ALTER TABLE "${MAPPINGS}" DROP CONSTRAINT IF EXISTS "${constraint}"`,
        );
      }
      // -- DESTRUCTIVE: columns unused by every row (down refuses otherwise); rollback = re-run up
      await queryRunner.query(
        `ALTER TABLE "${MAPPINGS}"
           DROP COLUMN IF EXISTS "pointKey",
           DROP COLUMN IF EXISTS "siteId",
           DROP COLUMN IF EXISTS "systemId",
           DROP COLUMN IF EXISTS "tankId",
           DROP COLUMN IF EXISTS "position",
           DROP COLUMN IF EXISTS "depthM",
           DROP COLUMN IF EXISTS "channelKey",
           DROP COLUMN IF EXISTS "priority",
           DROP COLUMN IF EXISTS "boundAt",
           DROP COLUMN IF EXISTS "boundBy",
           DROP COLUMN IF EXISTS "unboundAt",
           DROP COLUMN IF EXISTS "unboundBy"`,
      );
      await queryRunner.query(`
        DO $$
        DECLARE
          restored text;
        BEGIN
          FOREACH restored IN ARRAY ARRAY['equipmentId', 'monitoringFrequency', 'alertEnabled'] LOOP
            IF EXISTS (
              SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema()
                 AND table_name = '${MAPPINGS}'
                 AND column_name = restored
                 AND is_nullable = 'YES'
            ) THEN
              EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET NOT NULL', '${MAPPINGS}', restored);
            END IF;
          END LOOP;
        END $$`);
      await queryRunner.query(
        `CREATE UNIQUE INDEX IF NOT EXISTS "${LEGACY_MAPPING_UNIQUE}"
           ON "${MAPPINGS}" ("tenantId", "parameterConfigId", "equipmentId")`,
      );
    }
    if (await tablesExist(queryRunner, [CONFIGS])) {
      // -- DESTRUCTIVE: empty ledger (down refuses while it has rows); rollback = re-run up
      await queryRunner.query(`DROP TABLE IF EXISTS "${LEDGER}"`);
      await queryRunner.query(`DROP TRIGGER IF EXISTS ${STAMP_TRIGGER} ON "${CONFIGS}"`);
      await queryRunner.query(`DROP FUNCTION IF EXISTS ${STAMP_FUNCTION}()`);
      await queryRunner.query(`DROP INDEX IF EXISTS "UQ_wqpc_tenant_effective_quantity"`);
      // -- DESTRUCTIVE: derived or undeclared columns (down refuses while any is declared); rollback = re-run up
      await queryRunner.query(
        `ALTER TABLE "${CONFIGS}"
           DROP COLUMN IF EXISTS "declaredQuantity",
           DROP COLUMN IF EXISTS "effectiveQuantity",
           DROP COLUMN IF EXISTS "quantityConfiguredAt"`,
      );
    }
  }

  private report(schema: string, event: string, detail: Record<string, unknown>): void {
    this.logger.warn(JSON.stringify({ event: `migration_${event}`, schema, ...detail }));
  }
}

async function currentSchema(queryRunner: QueryRunner): Promise<string> {
  const rows: Array<{ schema: string }> = await queryRunner.query(
    `SELECT current_schema() AS schema`,
  );
  return rows[0]?.schema ?? '';
}

async function tablesExist(queryRunner: QueryRunner, tables: readonly string[]): Promise<boolean> {
  const rows: Array<{ ready: boolean }> = await queryRunner.query(
    `SELECT bool_and(to_regclass(name) IS NOT NULL) AS ready FROM unnest($1::text[]) AS name`,
    [tables],
  );
  return rows[0]?.ready === true;
}

async function addCheck(
  queryRunner: QueryRunner,
  table: string,
  constraint: string,
  predicate: string,
): Promise<void> {
  await queryRunner.query(`
    DO $$
    BEGIN
      ALTER TABLE "${table}" ADD CONSTRAINT "${constraint}" CHECK (${predicate});
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$`);
}

/** What in the pinned schema relies on the expanded shape (empty: down may revert). */
async function expandUsage(queryRunner: QueryRunner): Promise<string[]> {
  const usage: string[] = [];
  const count = async (label: string, tables: readonly string[], sql: string): Promise<void> => {
    if (!(await tablesExist(queryRunner, tables))) {
      return;
    }
    const rows: Array<{ n: string }> = await queryRunner.query(sql);
    const n = Number(rows[0]?.n ?? 0);
    if (n > 0) {
      usage.push(`${n} ${label}`);
    }
  };
  await count(
    'mapping rows past the legacy shape',
    [MAPPINGS],
    `SELECT count(*) AS n FROM "${MAPPINGS}"
      WHERE "equipmentId" IS NULL OR "channelKey" IS NOT NULL OR "unboundAt" IS NOT NULL
         OR "position" <> 'representative' OR "depthM" IS NOT NULL`,
  );
  await count(
    'declared parameter quantities',
    [CONFIGS],
    `SELECT count(*) AS n FROM "${CONFIGS}" WHERE "declaredQuantity" IS NOT NULL`,
  );
  await count('quantity declarations', [LEDGER], `SELECT count(*) AS n FROM "${LEDGER}"`);
  await count(
    'measurements at a system',
    [MEASUREMENTS],
    `SELECT count(*) AS n FROM "${MEASUREMENTS}" WHERE "systemId" IS NOT NULL`,
  );
  return usage;
}

/**
 * Rows of an UPDATE … RETURNING. TypeORM's Postgres runner returns an UPDATE
 * as [rows, affected count], unlike a SELECT.
 */
async function updateReturning<T>(queryRunner: QueryRunner, sql: string): Promise<T[]> {
  const [rows]: [T[], number] = await queryRunner.query(sql);
  return rows;
}
