import { MigrationInterface, QueryRunner } from 'typeorm';
import { MigrationLogger } from '@aquaculture/backend-common';

/**
 * ConvertMessagingOutboxToIdentity1781200000000
 * ============================================================================
 *
 * Converts `messaging_outbox.id` from legacy `BIGSERIAL` to
 * `BIGINT GENERATED BY DEFAULT AS IDENTITY` across EVERY schema that
 * contains a `messaging_outbox` table — i.e. the `messaging` source
 * schema template PLUS every `tenant_<uuid>` schema that was provisioned
 * from it.
 *
 * # Why dynamic schema discovery?
 *
 * messaging-service uses the schema-per-tenant pattern. At tenant
 * provisioning time, `TenantSchemaSyncService` copies the table
 * definitions from the `messaging` source schema into `tenant_<uuid>`
 * via `CREATE TABLE ... (LIKE source.messaging_outbox INCLUDING ALL)`.
 *
 * Because `BIGSERIAL` creates a **detached** sequence with `OWNED BY`, the
 * `LIKE ... INCLUDING ALL` clause clones the default expression but
 * creates a NEW per-tenant sequence. That's correct, but it means
 * fixing the source schema alone doesn't fix the tenants' existing
 * sequences — those are already on the old style and must each be
 * migrated in place.
 *
 * The migration therefore:
 *
 * 1. Discovers every schema that owns a `messaging_outbox` base table
 *    via `information_schema.tables`.
 * 2. Runs the standard IDENTITY conversion sequence on each schema
 *    (capture → drop default → drop sequence → add IDENTITY
 *    RESTART WITH <next>).
 * 3. Skips any schema where the column is already IDENTITY (idempotent).
 *
 * This is the same approach as farm-service's
 * `ConvertFarmOutboxToIdentity1781200000000` but extended to iterate
 * schemas — the per-schema logic is identical.
 *
 * # Why not also update init-messaging-schema.sql?
 *
 * That update (replacing BIGSERIAL with IDENTITY in the template SQL)
 * **is** a necessary companion change, but lives in a separate commit-
 * level edit because it only affects future fresh deployments, not
 * existing ones. The SQL update alone would leave all current
 * environments broken; this migration alone would leave all future
 * clean installs on the legacy style. Both are required.
 *
 * # Locking
 *
 * Per-schema ALTER TABLE is metadata-only (no table rewrite). The
 * cumulative lock time scales with the tenant count but each schema's
 * work is sub-millisecond. On a platform with ~hundreds of tenants,
 * expect total migration time on the order of a few hundred ms.
 */
export class ConvertMessagingOutboxToIdentity1781200000000
  implements MigrationInterface
{
  name = 'ConvertMessagingOutboxToIdentity1781200000000';
  private readonly logger = new MigrationLogger(this.name);

  public async up(queryRunner: QueryRunner): Promise<void> {
    this.logger.log('Discovering schemas containing messaging_outbox table');

    // Find every schema (source + tenant) that has a `messaging_outbox`
    // base table. We filter on BASE TABLE to skip views/partitions.
    const schemas: Array<{ table_schema: string }> = await queryRunner.query(`
      SELECT table_schema
      FROM information_schema.tables
      WHERE table_name = 'messaging_outbox'
        AND table_type = 'BASE TABLE'
      ORDER BY table_schema
    `);

    if (schemas.length === 0) {
      this.logger.warn(
        'No schemas with messaging_outbox found — nothing to migrate. ' +
          'This is expected on a fresh environment where TenantSchemaSyncService ' +
          'has not yet provisioned any tenant.',
      );
      return;
    }

    this.logger.log(
      `Found ${schemas.length} schemas with messaging_outbox: ${schemas.map((s) => s.table_schema).join(', ')}`,
    );

    let converted = 0;
    let skipped = 0;

    for (const { table_schema } of schemas) {
      const wasConverted = await this.convertSchema(queryRunner, table_schema);
      if (wasConverted) {
        converted++;
      } else {
        skipped++;
      }
    }

    this.logger.log(
      `messaging_outbox IDENTITY migration: converted=${converted}, skipped=${skipped}, total=${schemas.length}`,
    );
  }

  /**
   * Convert a single schema's `messaging_outbox.id` from BIGSERIAL to
   * IDENTITY. Returns true if a conversion happened, false if the
   * schema was already on IDENTITY and skipped.
   */
  private async convertSchema(
    queryRunner: QueryRunner,
    schema: string,
  ): Promise<boolean> {
    // Safety: validate the schema name before interpolation. The only
    // source is information_schema which is trusted, but the defensive
    // check is cheap and makes the code auditable.
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(schema)) {
      this.logger.warn(`Skipping invalid schema name: "${schema}"`);
      return false;
    }

    // Idempotency guard — check pg_attribute.attidentity.
    const identityCheck: Array<{ attidentity: string }> = await queryRunner.query(
      `
      SELECT a.attidentity
      FROM pg_attribute a
      JOIN pg_class c ON a.attrelid = c.oid
      JOIN pg_namespace n ON c.relnamespace = n.oid
      WHERE n.nspname = $1
        AND c.relname = 'messaging_outbox'
        AND a.attname = 'id'
        AND a.attnum > 0
        AND NOT a.attisdropped
      `,
      [schema],
    );

    if (identityCheck.length === 0) {
      this.logger.warn(
        `messaging_outbox.id column not found in schema "${schema}"`,
      );
      return false;
    }

    const existingIdentity = identityCheck[0]?.attidentity ?? '';
    if (existingIdentity !== '') {
      this.logger.log(
        `[${schema}] already IDENTITY (attidentity='${existingIdentity}') — skipping`,
      );
      return false;
    }

    // ── Capture sequence state ─────────────────────────────────────────
    const seqRows: Array<{ seq: string | null }> = await queryRunner.query(
      `SELECT pg_get_serial_sequence($1, 'id') AS seq`,
      [`${schema}.messaging_outbox`],
    );
    const sequenceName = seqRows[0]?.seq;

    if (!sequenceName) {
      throw new Error(
        `[${schema}] messaging_outbox.id has no associated sequence — ` +
          `schema is in an inconsistent state.`,
      );
    }

    const seqState: Array<{ last_value: string; is_called: boolean }> =
      await queryRunner.query(`SELECT last_value, is_called FROM ${sequenceName}`);
    const seqRow = seqState[0];
    if (!seqRow) {
      throw new Error(
        `[${schema}] sequence ${sequenceName} returned no state row — ` +
          `schema corruption suspected.`,
      );
    }
    const lastValue = BigInt(seqRow.last_value);
    const isCalled = seqRow.is_called;
    const nextValue = isCalled ? lastValue + 1n : lastValue;

    this.logger.log(
      `[${schema}] sequence ${sequenceName}: last_value=${lastValue}, is_called=${isCalled}, next=${nextValue}`,
    );

    // ── Drop default → drop sequence → add IDENTITY ───────────────────
    await queryRunner.query(
      `ALTER TABLE "${schema}"."messaging_outbox" ALTER COLUMN "id" DROP DEFAULT`,
    );
    await queryRunner.query(`DROP SEQUENCE IF EXISTS ${sequenceName}`);
    await queryRunner.query(
      `ALTER TABLE "${schema}"."messaging_outbox" ` +
        `ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH ${nextValue})`,
    );

    this.logger.log(
      `[${schema}] messaging_outbox.id converted to IDENTITY (RESTART WITH ${nextValue})`,
    );
    return true;
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    this.logger.warn(
      'Rolling back messaging_outbox.id IDENTITY → BIGSERIAL across all schemas. ' +
        'This is a break-glass operation.',
    );

    const schemas: Array<{ table_schema: string }> = await queryRunner.query(`
      SELECT table_schema
      FROM information_schema.tables
      WHERE table_name = 'messaging_outbox'
        AND table_type = 'BASE TABLE'
      ORDER BY table_schema
    `);

    for (const { table_schema: schema } of schemas) {
      if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(schema)) continue;

      // Capture current IDENTITY position to preserve sequence state on
      // rollback. The same is_called/last_value semantics apply.
      const seqRows: Array<{ seq: string | null }> = await queryRunner.query(
        `SELECT pg_get_serial_sequence($1, 'id') AS seq`,
        [`${schema}.messaging_outbox`],
      );
      const identitySeq = seqRows[0]?.seq;

      let nextValue = 1n;
      if (identitySeq) {
        const state: Array<{ last_value: string; is_called: boolean }> =
          await queryRunner.query(
            `SELECT last_value, is_called FROM ${identitySeq}`,
          );
        const stateRow = state[0];
        if (stateRow) {
          const lastValue = BigInt(stateRow.last_value);
          nextValue = stateRow.is_called ? lastValue + 1n : lastValue;
        }
      }

      await queryRunner.query(
        `ALTER TABLE "${schema}"."messaging_outbox" ALTER COLUMN "id" DROP IDENTITY IF EXISTS`,
      );
      await queryRunner.query(
        `CREATE SEQUENCE "${schema}"."messaging_outbox_id_seq" START WITH ${nextValue}`,
      );
      await queryRunner.query(
        `ALTER TABLE "${schema}"."messaging_outbox" ` +
          `ALTER COLUMN "id" SET DEFAULT nextval('"${schema}"."messaging_outbox_id_seq"')`,
      );
      await queryRunner.query(
        `ALTER SEQUENCE "${schema}"."messaging_outbox_id_seq" OWNED BY "${schema}"."messaging_outbox"."id"`,
      );

      this.logger.warn(
        `[${schema}] messaging_outbox.id rolled back to BIGSERIAL`,
      );
    }
  }
}
