/** Stable, secret-free failure codes safe for metrics and sanitized boundaries. */
export const CREDENTIAL_CIPHER_ERROR_CODES = {
  KEYRING_FILE_REQUIRED: 'CREDENTIAL_CIPHER_KEYRING_FILE_REQUIRED',
  ACTIVE_KEY_ID_REQUIRED: 'CREDENTIAL_CIPHER_ACTIVE_KEY_ID_REQUIRED',
  KEYRING_FILE_UNREADABLE: 'CREDENTIAL_CIPHER_KEYRING_FILE_UNREADABLE',
  KEYRING_FILE_TOO_LARGE: 'CREDENTIAL_CIPHER_KEYRING_FILE_TOO_LARGE',
  KEYRING_MALFORMED: 'CREDENTIAL_CIPHER_KEYRING_MALFORMED',
  KEYRING_VERSION_UNSUPPORTED: 'CREDENTIAL_CIPHER_KEYRING_VERSION_UNSUPPORTED',
  KEYRING_EMPTY: 'CREDENTIAL_CIPHER_KEYRING_EMPTY',
  KEYRING_TOO_MANY_KEYS: 'CREDENTIAL_CIPHER_KEYRING_TOO_MANY_KEYS',
  KEY_ID_INVALID: 'CREDENTIAL_CIPHER_KEY_ID_INVALID',
  KEY_ID_DUPLICATE: 'CREDENTIAL_CIPHER_KEY_ID_DUPLICATE',
  KEY_MATERIAL_INVALID: 'CREDENTIAL_CIPHER_KEY_MATERIAL_INVALID',
  KEY_MATERIAL_WEAK: 'CREDENTIAL_CIPHER_KEY_MATERIAL_WEAK',
  KEY_MATERIAL_DUPLICATE: 'CREDENTIAL_CIPHER_KEY_MATERIAL_DUPLICATE',
  ACTIVE_KEY_NOT_FOUND: 'CREDENTIAL_CIPHER_ACTIVE_KEY_NOT_FOUND',
  NOT_INITIALIZED: 'CREDENTIAL_CIPHER_NOT_INITIALIZED',
  PLAINTEXT_INVALID: 'CREDENTIAL_CIPHER_PLAINTEXT_INVALID',
  PLAINTEXT_TOO_LARGE: 'CREDENTIAL_CIPHER_PLAINTEXT_TOO_LARGE',
  AAD_INVALID: 'CREDENTIAL_CIPHER_AAD_INVALID',
  ENVELOPE_MALFORMED: 'CREDENTIAL_CIPHER_ENVELOPE_MALFORMED',
  ENVELOPE_VERSION_UNSUPPORTED: 'CREDENTIAL_CIPHER_ENVELOPE_VERSION_UNSUPPORTED',
  KEY_NOT_FOUND: 'CREDENTIAL_CIPHER_KEY_NOT_FOUND',
  ENCRYPTION_FAILED: 'CREDENTIAL_CIPHER_ENCRYPTION_FAILED',
  AUTHENTICATION_FAILED: 'CREDENTIAL_CIPHER_AUTHENTICATION_FAILED',
} as const;

export type CredentialCipherErrorCode =
  (typeof CREDENTIAL_CIPHER_ERROR_CODES)[keyof typeof CREDENTIAL_CIPHER_ERROR_CODES];

/**
 * A hard credential-cipher failure whose text never incorporates caught error
 * messages, key identifiers, paths, AAD values, plaintext, or ciphertext.
 */
export class CredentialCipherError extends Error {
  constructor(public readonly code: CredentialCipherErrorCode) {
    super(`Credential cipher operation failed (${code})`);
    this.name = 'CredentialCipherError';
  }
}

export function isCredentialCipherError(value: unknown): value is CredentialCipherError {
  return value instanceof CredentialCipherError;
}
