/**
 * The attention column makes two claims a cabin board must never get wrong:
 * what is alarming and what is planned. Both come from queries that fail on a
 * site with a flaky uplink, and a wall display showing "No open alarms" while it
 * cannot reach the alert engine is an all-clear nobody checked — the defect this
 * app has now found seven times. Most of what follows holds that line.
 *
 * The rest pins the pane's other contract: it WATCHES. An alarm may fill the
 * detail column, and only when the board actually holds that unit; nothing here
 * acknowledges, starts or completes anything, because that happens on the
 * handheld at the pen.
 */
import { render, screen, cleanup, fireEvent } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { AttentionPane } from '../AttentionPane';

import type { MobileAlert } from '@/hooks/useAlerts';
import type { Tank, Task } from '@/types';

const mockUseAlerts = vi.fn();
vi.mock('@/hooks/useAlerts', () => ({ useAlerts: (): unknown => mockUseAlerts() }));

const mockUseMyTasks = vi.fn();
vi.mock('@/hooks/useMyTasks', () => ({ useMyTasks: (): unknown => mockUseMyTasks() }));

const mockUseTanks = vi.fn();
vi.mock('@/hooks/useTanks', () => ({ useTanks: (): unknown => mockUseTanks() }));

const mockCanReach = vi.fn<(feature: string) => boolean>();
vi.mock('@/utils/feature-access', () => ({
  useFeatureAccess: (): unknown => ({
    canReach: (feature: string): boolean => mockCanReach(feature),
  }),
}));

function alarm(overrides: Partial<MobileAlert> = {}): MobileAlert {
  return {
    id: 'alert-1',
    ruleId: 'rule-1',
    ruleName: 'Oxygen low',
    farmId: 'farm-1',
    pondId: 'tank-7',
    sensorId: 'sensor-1',
    severity: 'CRITICAL',
    message: 'DO 4.1 mg/L',
    triggeredAt: '2026-08-07T06:12:00.000Z',
    acknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementNote: null,
    resolved: false,
    resolvedAt: null,
    createdAt: '2026-08-07T06:12:00.000Z',
    ...overrides,
  };
}

function unit(id: string, name: string): Tank {
  return {
    id,
    name,
    code: name,
    volume: 0,
    status: 'ACTIVE',
    siteId: 'site-a',
    currentQuantity: 0,
    currentBiomass: 0,
    maxBiomass: 0,
    batchMetrics: null,
  };
}

function task(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-1',
    title: 'Net inspection',
    description: '',
    category: 'EQUIPMENT_MAINTENANCE',
    priority: 'HIGH',
    status: 'PENDING',
    assignedTo: 'user-1',
    assignedToName: 'Ola Nordvik',
    dueDate: '2026-08-07',
    dueTime: '10:30',
    location: 'Pen 7',
    checklistItems: [],
    notes: [],
    tags: [],
    isRecurring: false,
    isAutoGenerated: false,
    createdAt: '2026-08-07T05:00:00.000Z',
    ...overrides,
  };
}

const refetchAlerts = vi.fn();
const refetchTasks = vi.fn();

beforeEach(() => {
  vi.clearAllMocks();
  mockUseAlerts.mockReturnValue({
    alerts: [],
    isLoading: false,
    error: null,
    refetch: refetchAlerts,
  });
  mockUseMyTasks.mockReturnValue({
    tasks: [],
    loading: false,
    error: null,
    refetch: refetchTasks,
  });
  mockUseTanks.mockReturnValue({ data: [], isLoading: false, isError: false, refetch: vi.fn() });
  mockCanReach.mockReturnValue(true);
});

afterEach(cleanup);

describe('AttentionPane — alarms', () => {
  it('shows the open alarms and names the unit each one is raised on', () => {
    mockUseAlerts.mockReturnValue({
      alerts: [alarm()],
      isLoading: false,
      error: null,
      refetch: refetchAlerts,
    });
    mockUseTanks.mockReturnValue({
      data: [unit('tank-7', 'Pen 7')],
      isLoading: false,
      isError: false,
    });

    render(<AttentionPane />);

    expect(screen.getByText('Oxygen low')).toBeTruthy();
    expect(screen.getByText('Pen 7 · DO 4.1 mg/L')).toBeTruthy();
  });

  it('leaves acknowledged alarms to the alarm history', () => {
    mockUseAlerts.mockReturnValue({
      alerts: [alarm({ id: 'alert-2', ruleName: 'Handled yesterday', acknowledged: true })],
      isLoading: false,
      error: null,
      refetch: refetchAlerts,
    });

    render(<AttentionPane />);

    expect(screen.queryByText('Handled yesterday')).toBeNull();
    // The fetch SUCCEEDED and nothing is open — that is the empty state, not the
    // error state below.
    expect(screen.getByText('No open alarms')).toBeTruthy();
  });

  it('selects the alarm’s unit instead of navigating away from the board', () => {
    const onSelectUnit = vi.fn();
    mockUseAlerts.mockReturnValue({
      alerts: [alarm()],
      isLoading: false,
      error: null,
      refetch: refetchAlerts,
    });
    mockUseTanks.mockReturnValue({
      data: [unit('tank-7', 'Pen 7')],
      isLoading: false,
      isError: false,
    });

    render(<AttentionPane onSelectUnit={onSelectUnit} />);
    fireEvent.click(screen.getByRole('button', { name: /Oxygen low/ }));

    expect(onSelectUnit).toHaveBeenCalledWith('tank-7');
  });

  it('does not offer a tap that the detail column could not resolve', () => {
    // The alarm names a pond this board never loaded (or names none at all).
    // A tappable row would hand the detail pane an id it cannot show, and the
    // unit name in the subtitle would be a guess.
    const onSelectUnit = vi.fn();
    mockUseAlerts.mockReturnValue({
      alerts: [alarm({ pondId: 'tank-99' }), alarm({ id: 'alert-3', pondId: null })],
      isLoading: false,
      error: null,
      refetch: refetchAlerts,
    });
    mockUseTanks.mockReturnValue({
      data: [unit('tank-7', 'Pen 7')],
      isLoading: false,
      isError: false,
    });

    render(<AttentionPane onSelectUnit={onSelectUnit} />);

    expect(screen.queryByRole('button', { name: /Oxygen low/ })).toBeNull();
    // …but the alarm itself is still on the board, unit name omitted.
    expect(screen.getAllByText('DO 4.1 mg/L').length).toBe(2);
  });

  it('says the alarms are UNAVAILABLE rather than rendering an all-clear', () => {
    mockUseAlerts.mockReturnValue({
      alerts: [],
      isLoading: false,
      error: 'Network request failed',
      refetch: refetchAlerts,
    });

    render(<AttentionPane />);

    expect(screen.getByText('Could not load alarms')).toBeTruthy();
    expect(screen.queryByText('No open alarms')).toBeNull();
    // No count beside the heading either — a number is a claim.
    expect(screen.queryByText(/open$/)).toBeNull();
  });

  it('retries the real query from the error state', () => {
    mockUseAlerts.mockReturnValue({
      alerts: [],
      isLoading: false,
      error: 'Network request failed',
      refetch: refetchAlerts,
    });

    render(<AttentionPane />);
    fireEvent.click(screen.getByRole('button', { name: 'Try again' }));

    expect(refetchAlerts).toHaveBeenCalled();
  });

  it('shows placeholders while the first fetch is in flight, not an empty list', () => {
    mockUseAlerts.mockReturnValue({
      alerts: [],
      isLoading: true,
      error: null,
      refetch: refetchAlerts,
    });

    render(<AttentionPane />);

    expect(screen.getAllByTestId('skeleton').length).toBeGreaterThan(0);
    expect(screen.queryByText('No open alarms')).toBeNull();
  });

  it('carries no acknowledge control and says where the acknowledge happens', () => {
    mockUseAlerts.mockReturnValue({
      alerts: [alarm()],
      isLoading: false,
      error: null,
      refetch: refetchAlerts,
    });

    render(<AttentionPane />);

    expect(screen.queryByRole('button', { name: /acknowledge/i })).toBeNull();
    expect(screen.getByText('Acknowledge on the handheld, standing at the pen.')).toBeTruthy();
  });
});

describe('AttentionPane — tasks', () => {
  it('shows today’s tasks with their due time', () => {
    mockUseMyTasks.mockReturnValue({
      tasks: [task()],
      loading: false,
      error: null,
      refetch: refetchTasks,
    });

    render(<AttentionPane />);

    expect(screen.getByText('Net inspection')).toBeTruthy();
    expect(screen.getByText('10:30')).toBeTruthy();
  });

  it('keeps task rows read-only — a task is finished at the pen, not at the board', () => {
    mockUseMyTasks.mockReturnValue({
      tasks: [task()],
      loading: false,
      error: null,
      refetch: refetchTasks,
    });

    render(<AttentionPane />);

    expect(screen.queryByRole('button', { name: /Net inspection/ })).toBeNull();
    expect(
      screen.getByText(
        'Assigned to this account, for today. Start and finish them on the handheld.',
      ),
    ).toBeTruthy();
  });

  it('says the task list is UNAVAILABLE rather than "nothing scheduled"', () => {
    mockUseMyTasks.mockReturnValue({
      tasks: [],
      loading: false,
      error: 'Network request failed',
      refetch: refetchTasks,
    });

    render(<AttentionPane />);

    expect(screen.getByText("Could not load today's tasks")).toBeTruthy();
    expect(screen.queryByText('Nothing scheduled')).toBeNull();
  });

  it('keeps an empty day distinct from an unreachable one', () => {
    render(<AttentionPane />);
    expect(screen.getByText('Nothing scheduled')).toBeTruthy();
  });

  it('hides the whole section from a role the phone hides it from', () => {
    // Same gate as <FeatureRoute feature="tasks"> in App.tsx and Today's task
    // section: the board must not expose a surface the handheld does not.
    mockCanReach.mockImplementation((feature: string) => feature !== 'tasks');
    mockUseMyTasks.mockReturnValue({
      tasks: [task()],
      loading: false,
      error: null,
      refetch: refetchTasks,
    });

    render(<AttentionPane />);

    expect(screen.queryByText('Tasks')).toBeNull();
    expect(screen.queryByText('Net inspection')).toBeNull();
    // The alarms half is unaffected.
    expect(screen.getByText('Alarms')).toBeTruthy();
  });
});
