import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { IncomingMessage } from 'node:http';
import { createServer, Socket } from 'node:net';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import { loadConfig } from '../src/config.ts';
import { createCase, uploadDocument } from '../src/legal-intake.ts';
import { loadOrCreateSigner } from '../src/ledger.ts';
import { prepareLegalInventory, resolveLegalRun } from '../src/legal-runs.ts';
import { runLegalWorker } from '../src/legal-worker.ts';

const workspace = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
test('production sandbox exposes only the selected snapshot and no host authority or network', async t => {
  const root = await mkdtemp(join(tmpdir(), 'legal-isolation-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const server = createServer(socket => socket.end());
  await new Promise<void>(done => server.listen(0, '127.0.0.1', done));
  t.after(() => new Promise<void>((done, reject) => server.close(error => error === undefined ? done() : reject(error))));
  const address = server.address(); assert.ok(address !== null && typeof address !== 'string');
  const hidden = ['other-case.txt', 'principals.json', 'ledger-key.pem'].map(name => join(root, name));
  for (const file of hidden) await writeFile(file, 'private fixture');
  const snapshotDir = join(root, 'snapshot'); await mkdir(snapshotDir);
  await writeFile(join(snapshotDir, 'own.txt'), 'allowed fixture');
  const inputFile = join(root, 'input.json'); await writeFile(inputFile, '{}');
  const probe = join(root, 'probe.py');
  await writeFile(probe, `#!/usr/bin/python3\nimport sys,json,os,socket\nfrom pathlib import Path\nif 'register' in sys.argv:\n print('{}');sys.exit(0)\np=Path('/work/data/legal-cases/case-probe/archive/own.txt')\nresult={'own':p.read_text()=='allowed fixture','hidden':all(not Path(x).exists() for x in ${JSON.stringify(hidden)}),'environment':'ARIA_ISOLATION_TEST_SECRET' not in os.environ}\nfor name,path in [('source_readonly',p),('input_readonly',Path('/input.json'))]:\n try:\n  with path.open('ab') as f:f.write(b'forbidden')\n  result[name]=False\n except OSError:result[name]=True\ns=socket.socket();s.settimeout(1)\nresult['network']=s.connect_ex(('127.0.0.1',${address.port}))!=0\ns.close()\nprint(json.dumps(result))\n`, { mode: 0o700 });
  const previous = process.env['ARIA_ISOLATION_TEST_SECRET'];
  process.env['ARIA_ISOLATION_TEST_SECRET'] = 'must remain in service';
  t.after(() => { if (previous === undefined) delete process.env['ARIA_ISOLATION_TEST_SECRET']; else process.env['ARIA_ISOLATION_TEST_SECRET'] = previous; });
  const config = loadConfig({ ARIA_UI_TOKEN: 'test-token-long-enough', ARIA_TOOLS_DIR: join(root, 'live-tools'), ARIA_WORKSPACE_ROOT: workspace, ARIA_KERNEL_BIN: probe });
  const toolsDir = join(root, 'job-tools');
  await runLegalWorker(config, { caseId: 'case-probe', runKey: 'run-probe', snapshotDir, toolsDir, inputFile });
  assert.deepEqual(JSON.parse(await readFile(join(toolsDir, 'kernel-result.json'), 'utf8')), { own: true, hidden: true, environment: true, source_readonly: true, input_readonly: true, network: true });
  for (const file of hidden) assert.equal(await readFile(file, 'utf8'), 'private fixture');
  assert.equal(await readFile(join(snapshotDir, 'own.txt'), 'utf8'), 'allowed fixture');
});

test('real isolated kernel registers, inventories snapshot bytes, and publishes signed run', async t => {
  const root = await mkdtemp(join(tmpdir(), 'legal-worker-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const config = loadConfig({ ARIA_UI_TOKEN: 'test-token-long-enough', ARIA_TOOLS_DIR: join(root, 'tools'), ARIA_LEGAL_CASES_DIR: join(root, 'cases'), ARIA_WORKSPACE_BASE: join(root, 'jobs'), ARIA_WORKSPACE_ROOT: workspace, ARIA_KERNEL_BIN: join(workspace, 'bin/aria'), ARIA_INSTANCE_MANIFEST: join(workspace, 'arias/legal/aria.manifest.json'), ARIA_UI_PRINCIPALS_FILE: join(root, 'principals.json') });
  const signer = loadOrCreateSigner(join(root, 'key.pem'));
  const caseId = 'case-real';
  await createCase(config.legalCasesDir, { caseId, title: 'Real inventory', custodian: 'Counsel', createdBy: 'operator', jurisdiction: null, courtReference: null }, '2026-09-05T00:00:00Z');
  const req = new IncomingMessage(new Socket()); req.push(Buffer.from('Fra: Nordbygg AS\nTil: Eksempel AS\nInvoice dated 2024-01-01.\nTotal: NOK 1000.\n')); req.push(null);
  await uploadDocument(req, { casesDir: config.legalCasesDir, caseId, signer, now: '2026-09-05T00:00:00Z', fileName: 'invoice.txt', receivedBy: 'operator', sourceNote: null, maxBytes: 4096 });
  const excluded = new IncomingMessage(new Socket()); excluded.push(Buffer.from('excluded private bytes')); excluded.push(null);
  await uploadDocument(excluded, { casesDir: config.legalCasesDir, caseId, signer, now: '2026-09-05T00:00:00Z', fileName: 'Ikke laste opp/private.txt', receivedBy: 'operator', sourceNote: null, maxBytes: 4096 });
  const prepared = await prepareLegalInventory(config, caseId, 'Real inventory', signer, () => {});
  await prepared.execute();
  const run = await resolveLegalRun(config.toolsDir, caseId, signer);
  const docs = JSON.parse(await readFile(join(run.dir, 'documents.json'), 'utf8'));
  assert.equal(run.runKey, prepared.runKey);
  assert.equal(docs.length, 1);
  assert.equal(docs[0].relativePath, 'invoice.txt');
  assert.equal(docs[0].extraction, 'text');
  assert.equal(docs[0].modifiedAt, (await stat(join(config.legalCasesDir, caseId, 'archive/invoice.txt'))).mtime.toISOString());
  await assert.rejects(readFile(join(config.workspaceBase, 'legal-jobs', prepared.runKey, 'snapshot/Ikke laste opp/private.txt')), { code: 'ENOENT' });
  const coverage = JSON.parse(await readFile(join(run.dir, 'coverage.json'), 'utf8'));
  assert.equal(coverage.complete, false);
  assert.deepEqual(coverage.reconciliation, { receipts: 2, matched: 1, documentsWithoutReceipt: [], receiptsWithoutDocument: ['Ikke laste opp/private.txt'], hashMismatches: [] });
  const links = JSON.parse(await readFile(join(run.dir, 'links.json'), 'utf8'));
  assert.ok(links.some((link: { kind: string }) => link.kind === 'PARTY_IN'));
  const kernel = JSON.parse(await readFile(join(run.dir, 'kernel-result.json'), 'utf8'));
  assert.equal(kernel.envelope.status, 'ok');
  assert.equal(kernel.envelope.evidence_validation.valid, true);
  await writeFile(join(config.toolsDir, 'runtime-profile.json'), JSON.stringify({ active_profile: 'frozen' }));
  const frozen = await prepareLegalInventory(config, caseId, null, signer, () => {});
  await assert.rejects(frozen.execute(), { code: 'legal_worker_failed' });
  assert.equal((await resolveLegalRun(config.toolsDir, caseId, signer)).runKey, prepared.runKey);
});
