/**
 * Writes the design tokens into the edge gateway's two embedded surfaces
 * (FE-MEDIUM-093).
 *
 * WHY generated rather than imported: `sens-api-gateway` is a Rust binary that
 * embeds its SCADA page with `include_str!` and serves it to a panel that is
 * usually offline. It cannot import a TypeScript module, and giving it a second
 * stylesheet would add a same-origin asset the service worker must precache —
 * the PWA install is all-or-nothing, so a missed entry costs the offline
 * guarantee. So the tokens are spliced into the page's own `<style>` block and
 * into a small Rust module, between BEGIN/END GENERATED sentinels, the same
 * convention `infrastructure/docker/nats/nats.conf` uses.
 *
 * The source of truth stays `libs/shared-contracts/src/design/color-tokens.ts`,
 * which `web/shared-ui` mirrors into `theme.css`. Drift is a failing build:
 * `tests/invariants/edge-theme-generated.spec.ts` regenerates and diffs.
 *
 *   npx tsx tools/design/generate-edge-theme.ts [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  chartChrome,
  chartPalette,
  colorTokenEntries,
} from '../../libs/shared-contracts/src/design/color-tokens';

const REPO_ROOT = resolve(__dirname, '..', '..');

export const HTML_PATH = 'sens-api-gateway/static/scada-edge.html';
export const RUST_PATH = 'sens-api-gateway/src/theme_tokens.rs';

const CSS_BEGIN = '    /* BEGIN GENERATED TOKENS */';
const CSS_END = '    /* END GENERATED TOKENS */';

/**
 * The channels of a token, for the places that need it at an opacity: a tinted
 * panel, a focus ring, an alarm glow. `rgb(var(--rgb-error-500) / 0.15)` keeps
 * that tint following the token, where a written-out `rgba(239, 68, 68, 0.15)`
 * silently stops at the value it was typed with.
 */
function channels(hex: string): string {
  const value = hex.replace('#', '');
  const full =
    value.length === 3
      ? value
          .split('')
          .map((c) => c + c)
          .join('')
      : value;
  const r = parseInt(full.slice(0, 2), 16);
  const g = parseInt(full.slice(2, 4), 16);
  const b = parseInt(full.slice(4, 6), 16);
  return `${r} ${g} ${b}`;
}

/** The scales the edge page paints from. `gray` is a single step, kept as one. */
function customProperties(): string[] {
  const lines: string[] = ['    :root {'];
  for (const [name, hex] of colorTokenEntries) {
    lines.push(`      --color-${name}: ${hex};`);
    lines.push(`      --rgb-${name}: ${channels(hex)};`);
  }
  chartPalette.forEach((hex, index) => {
    lines.push(`      --chart-${index + 1}: ${hex};`);
  });
  for (const [key, hex] of Object.entries(chartChrome)) {
    lines.push(`      --chart-${key}: ${hex};`);
  }
  lines.push('    }');
  return lines;
}

export function renderCssBlock(): string {
  return [CSS_BEGIN, ...customProperties(), CSS_END].join('\n');
}

function constName(tokenName: string): string {
  return tokenName.replace(/-/g, '_').toUpperCase();
}

export function renderRustModule(): string {
  const lines: string[] = [
    '// GENERATED by tools/design/generate-edge-theme.ts — do not edit by hand.',
    '//',
    '// The design tokens the gateway needs outside the SCADA page: the PWA',
    '// manifest colours and the launcher icon. The source of truth is',
    '// libs/shared-contracts/src/design/color-tokens.ts, the same file',
    '// web/shared-ui mirrors into theme.css (FE-MEDIUM-093).',
    '',
    '#![allow(dead_code)]',
    '',
  ];
  for (const [name, hex] of colorTokenEntries) {
    lines.push(`pub const ${constName(name)}: &str = "${hex}";`);
  }
  lines.push('');
  return lines.join('\n');
}

export function spliceCssBlock(html: string, block: string): string {
  const begin = html.indexOf(CSS_BEGIN);
  const end = html.indexOf(CSS_END);
  if (begin === -1 || end === -1) {
    throw new Error(
      `${HTML_PATH} is missing the BEGIN/END GENERATED TOKENS sentinels; the ` +
        `token block cannot be placed without them.`,
    );
  }
  return html.slice(0, begin) + block + html.slice(end + CSS_END.length);
}

function main(): void {
  const check = process.argv.includes('--check');
  const htmlFile = resolve(REPO_ROOT, HTML_PATH);
  const rustFile = resolve(REPO_ROOT, RUST_PATH);

  const html = readFileSync(htmlFile, 'utf8');
  const nextHtml = spliceCssBlock(html, renderCssBlock());
  const nextRust = renderRustModule();
  const currentRust = readFileSync(rustFile, 'utf8');

  const stale: string[] = [];
  if (nextHtml !== html) stale.push(HTML_PATH);
  if (nextRust !== currentRust) stale.push(RUST_PATH);

  if (check) {
    if (stale.length > 0) {
      process.stderr.write(
        `Edge theme is stale — run \`npx tsx tools/design/generate-edge-theme.ts\`:\n` +
          stale.map((s) => `  ${s}\n`).join(''),
      );
      process.exit(1);
    }
    process.stdout.write('Edge theme is up to date.\n');
    return;
  }

  if (nextHtml !== html) writeFileSync(htmlFile, nextHtml);
  if (nextRust !== currentRust) writeFileSync(rustFile, nextRust);
  process.stdout.write(
    stale.length === 0 ? 'Edge theme unchanged.\n' : `Edge theme written: ${stale.join(', ')}\n`,
  );
}

if (require.main === module) {
  main();
}
