/**
 * Shared helper for CI scripts that need to invoke
 * `docker compose ... config ...` against compose files containing
 * `${VAR:?required}` references.
 *
 * Without an env file, every `${VAR:?...}` raises an interpolation
 * error and the compose call fails — regardless of whether the script
 * actually cares about the env values themselves. This helper extracts
 * the required-var names from the compose file, writes a throwaway
 * dummy .env beside them, and returns the path so callers can pass
 * `--env-file <dummy>` to docker compose.
 *
 * The dummy values are NEVER used at runtime — they only unblock
 * compose's interpolation pass at CI time. The compose file remains
 * the SSoT for "what prod needs"; deriving the dummy at call time
 * keeps the two in lockstep without a hand-maintained ci-test.env.
 *
 * Used by:
 *   - scripts/ci/preflight-validate.ts (WS3 / ADR-016 Phase A2)
 *   - scripts/ci/validate-criticality-manifest.ts (WS6)
 *
 * Both scripts run on Node 22+ with built-in TypeScript type-stripping.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const REQUIRED_VAR_PATTERN = /\$\{([A-Z_][A-Z0-9_]*):\?[^}]*\}/g;

/** Names of every `${VAR:?...}` reference in a compose file. */
export function extractRequiredVars(composePath: string): Set<string> {
  const text = readFileSync(composePath, 'utf8');
  const vars = new Set<string>();
  for (const match of text.matchAll(REQUIRED_VAR_PATTERN)) {
    vars.add(match[1]!);
  }
  return vars;
}

/**
 * Write a throwaway env file with dummy values for every required
 * var in the compose file. Returns `{ envPath, cleanup }`. Callers
 * MUST invoke `cleanup()` when done (even on error paths).
 */
export function writeDummyEnvForCompose(composePath: string): {
  envPath: string;
  cleanup: () => void;
} {
  const tmp = mkdtempSync(join(tmpdir(), 'compose-dummy-env-'));
  const envPath = join(tmp, 'dummy.env');

  const required = extractRequiredVars(composePath);
  const lines = [
    '# AUTO-GENERATED by scripts/ci/lib/compose-dummy-env.ts — do not edit.',
    '# Dummy values ONLY unblock `docker compose config`; never used at runtime.',
    '',
  ];
  for (const name of [...required].sort()) {
    lines.push(`${name}=ci-dummy-value`);
  }
  writeFileSync(envPath, lines.join('\n') + '\n');

  return {
    envPath,
    cleanup: () => rmSync(tmp, { recursive: true, force: true }),
  };
}
