/**
 * WaterQualityParamEquipment — where a water-quality parameter is sourced.
 *
 * The one owner of "parameter P is monitored at point X, from source S"
 * (FARM-HIGH-373). A row is one source of one parameter at one measurement
 * point:
 *
 * - Point: exactly one of `siteId` | `systemId` | `tankId` | `equipmentId`
 *   (non-tank water equipment; a tank is `tankId`, as the measurement-unit
 *   classifier decides), qualified by `position` and `depthM`.
 * - Source: a manual source (no channel key) is a line of the unit's manual
 *   entry plan; a channel source names its sensor channel by its stable
 *   natural key (`sensorId`, `channelKey`) with a `priority` (one primary, one
 *   backup). Nothing about the channel — unit, quantity, id, name, value — is
 *   copied here: the sensor service answers those (SensorChannelDirectory).
 * - Temporal: a source ends by being unbound (`unboundAt`/`unboundBy`), so what
 *   fed a parameter at a point on a past date stays answerable.
 *
 * `pointKey` is generated by the database from the point, position and depth;
 * every uniqueness rule is a plain-column partial unique over it (live rows
 * only), mirrored below. Migration 1822000000000 owns the DDL.
 *
 * @module WaterQuality
 */
import { DecimalTransformer } from '@aquaculture/backend-common/database';
import { Field, Float, ID, ObjectType, registerEnumType } from '@nestjs/graphql';
import {
  Check,
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { WaterQualityParameterConfig } from './water-quality-parameter-config.entity';

/**
 * Lightweight GraphQL type for equipment references.
 * Avoids circular import of the full Equipment entity.
 */
@ObjectType('EquipmentRef')
class EquipmentRef {
  @Field(() => ID)
  id!: string;

  @Field()
  name!: string;

  @Field()
  code!: string;

  @Field({ nullable: true })
  description?: string;
}

// ============================================================================
// ENUMS
// ============================================================================

/** How frequently a manual source is sampled. */
export enum MonitoringFrequency {
  CONTINUOUS = 'continuous',
  HOURLY = 'hourly',
  DAILY = 'daily',
  WEEKLY = 'weekly',
  ON_DEMAND = 'on_demand',
}

registerEnumType(MonitoringFrequency, {
  name: 'MonitoringFrequency',
  description: 'Frequency at which a water quality parameter is monitored on equipment',
});

/** Where at a point the sample is taken: the point as a whole, or a flow end of it. */
export enum MeasurementPosition {
  REPRESENTATIVE = 'representative',
  INLET = 'inlet',
  OUTLET = 'outlet',
}

registerEnumType(MeasurementPosition, {
  name: 'MeasurementPosition',
  description: 'Where at a measurement point a source samples: representative, inlet or outlet',
});

/** Which of a point's channel sources feeds the parameter first. */
export enum ChannelSourcePriority {
  PRIMARY = 'primary',
  BACKUP = 'backup',
}

registerEnumType(ChannelSourcePriority, {
  name: 'ChannelSourcePriority',
  description: 'A channel source is the primary of its parameter at its point, or the backup',
});

// ============================================================================
// ENTITY
// ============================================================================

/** The generated point key (migration 1822000000000 holds the DDL; this mirrors it). */
const POINT_KEY_EXPRESSION = `COALESCE(
  'site:' || "siteId"::text,
  'system:' || "systemId"::text,
  'tank:' || "tankId"::text,
  'equipment:' || "equipmentId"::text
) || '|' || "position" || '|' || COALESCE("depthM"::text, '')`;

const LIVE_MANUAL = '"channelKey" IS NULL AND "unboundAt" IS NULL';
const LIVE_CHANNEL = '"channelKey" IS NOT NULL AND "unboundAt" IS NULL';

@ObjectType()
@Entity('water_quality_param_equipment')
@Index('UQ_wqpe_manual_source', ['tenantId', 'parameterConfigId', 'pointKey'], {
  unique: true,
  where: LIVE_MANUAL,
})
@Index('UQ_wqpe_channel_priority', ['tenantId', 'parameterConfigId', 'pointKey', 'priority'], {
  unique: true,
  where: LIVE_CHANNEL,
})
@Index(
  'UQ_wqpe_channel_key',
  ['tenantId', 'parameterConfigId', 'pointKey', 'sensorId', 'channelKey'],
  { unique: true, where: LIVE_CHANNEL },
)
@Index('IDX_wqpe_live_channel', ['tenantId', 'sensorId', 'channelKey'], { where: LIVE_CHANNEL })
@Index('IDX_wqpe_tenant_siteId', ['tenantId', 'siteId'], { where: '"siteId" IS NOT NULL' })
@Index('IDX_wqpe_tenant_systemId', ['tenantId', 'systemId'], { where: '"systemId" IS NOT NULL' })
@Index('IDX_wqpe_tenant_tankId', ['tenantId', 'tankId'], { where: '"tankId" IS NOT NULL' })
@Index(['tenantId', 'equipmentId'])
@Index(['tenantId', 'parameterConfigId'])
@Check('CHK_wqpe_one_point', `num_nonnulls("siteId", "systemId", "tankId", "equipmentId") = 1`)
@Check('CHK_wqpe_position', `"position" IN ('representative', 'inlet', 'outlet')`)
@Check('CHK_wqpe_depth', `"depthM" IS NULL OR "depthM" >= 0`)
@Check(
  'CHK_wqpe_channel_source',
  `("channelKey" IS NULL AND "priority" IS NULL) OR ("channelKey" IS NOT NULL AND "sensorId" IS NOT NULL AND "priority" IN ('primary', 'backup'))`,
)
@Check(
  'CHK_wqpe_source_settings',
  `("channelKey" IS NULL AND "monitoringFrequency" IS NOT NULL AND "alertEnabled" IS NOT NULL) OR ("channelKey" IS NOT NULL AND "monitoringFrequency" IS NULL AND "alertEnabled" IS NULL AND "isActive")`,
)
@Check(
  'CHK_wqpe_unbound',
  `("unboundAt" IS NULL AND "unboundBy" IS NULL) OR ("unboundAt" IS NOT NULL AND "unboundBy" IS NOT NULL AND "unboundAt" >= "boundAt")`,
)
export class WaterQualityParamEquipment {
  @Field(() => ID)
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Field()
  @Column('uuid')
  @Index()
  tenantId!: string;

  @Field()
  @Column('uuid')
  parameterConfigId!: string;

  // -------------------------------------------------------------------------
  // MEASUREMENT POINT (exactly one of the four)
  // -------------------------------------------------------------------------

  @Field(() => ID, { nullable: true, description: 'Site point' })
  @Column({ type: 'uuid', nullable: true })
  siteId!: string | null;

  @Field(() => ID, { nullable: true, description: 'System (loop) point' })
  @Column({ type: 'uuid', nullable: true })
  systemId!: string | null;

  @Field(() => ID, { nullable: true, description: 'Tank point' })
  @Column({ type: 'uuid', nullable: true })
  tankId!: string | null;

  /** Non-tank water equipment point (a biofilter, a sump); a tank is `tankId`. */
  @Field(() => String, { nullable: true, description: 'Non-tank water equipment point' })
  @Column({ type: 'uuid', nullable: true })
  equipmentId!: string | null;

  @Field(() => MeasurementPosition, { description: 'Where at the point the source samples' })
  @Column({ type: 'varchar', length: 16, default: MeasurementPosition.REPRESENTATIVE })
  position!: MeasurementPosition;

  @Field(() => Float, { nullable: true, description: 'Sampling depth in metres' })
  @Column({
    type: 'decimal',
    precision: 5,
    scale: 2,
    nullable: true,
    transformer: new DecimalTransformer(),
  })
  depthM!: number | null;

  /** Generated by the database (point, position, depth); the uniques key on it. Never written. */
  @Column({
    type: 'text',
    generatedType: 'STORED',
    asExpression: POINT_KEY_EXPRESSION,
    insert: false,
    update: false,
  })
  pointKey!: string;

  // -------------------------------------------------------------------------
  // SOURCE
  // -------------------------------------------------------------------------

  @Field(() => String, { nullable: true, description: 'Sensor of a channel source' })
  @Column({ type: 'uuid', nullable: true })
  sensorId!: string | null;

  @Field(() => String, { nullable: true, description: 'Channel key of a channel source' })
  @Column({ type: 'varchar', length: 100, nullable: true })
  channelKey!: string | null;

  @Field(() => ChannelSourcePriority, { nullable: true, description: 'Null for a manual source' })
  @Column({ type: 'varchar', length: 16, nullable: true })
  priority!: ChannelSourcePriority | null;

  @Field({ description: 'Whether this manual source is in the entry plan' })
  @Column({ default: true })
  isActive!: boolean;

  /** Manual-entry cadence; null on a channel source, which reports continuously (plan D14). */
  @Field(() => MonitoringFrequency, {
    nullable: true,
    description: 'How often this parameter is monitored on the equipment; null for a sensor channel',
  })
  @Column({
    type: 'enum',
    enum: MonitoringFrequency,
    default: MonitoringFrequency.ON_DEMAND,
    nullable: true,
  })
  monitoringFrequency!: MonitoringFrequency | null;

  /** Null on a channel source: its alerts are the sensor channel's (plan D14). */
  @Field(() => Boolean, {
    nullable: true,
    description: 'Whether alerts are enabled for this mapping; null for a sensor channel',
  })
  @Column({ type: 'boolean', default: true, nullable: true })
  alertEnabled!: boolean | null;

  @Field(() => String, { nullable: true, description: 'Free-text notes for this mapping' })
  @Column({ type: 'text', nullable: true })
  notes!: string | null;

  // -------------------------------------------------------------------------
  // VALIDITY
  // -------------------------------------------------------------------------

  @Field({ description: 'When the source started feeding the parameter at the point' })
  @Column({ type: 'timestamptz', default: () => 'now()' })
  boundAt!: Date;

  @Field(() => String, { nullable: true, description: 'Who bound it; null before tracking' })
  @Column({ type: 'varchar', length: 255, nullable: true })
  boundBy!: string | null;

  @Field(() => Date, { nullable: true, description: 'When it stopped; null while live' })
  @Column({ type: 'timestamptz', nullable: true })
  unboundAt!: Date | null;

  @Field(() => String, { nullable: true, description: 'Who or what unbound it' })
  @Column({ type: 'varchar', length: 255, nullable: true })
  unboundBy!: string | null;

  // -------------------------------------------------------------------------
  // RELATIONS
  // -------------------------------------------------------------------------

  @Field(() => WaterQualityParameterConfig)
  @ManyToOne(() => WaterQualityParameterConfig)
  @JoinColumn({ name: 'parameterConfigId' })
  parameterConfig!: WaterQualityParameterConfig;

  @Field(() => EquipmentRef, { nullable: true })
  @ManyToOne('Equipment')
  @JoinColumn({ name: 'equipmentId' })
  equipment?: EquipmentRef;

  // -------------------------------------------------------------------------
  // AUDIT FIELDS
  // -------------------------------------------------------------------------

  @Field()
  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;

  @Field()
  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt!: Date;
}
