/**
 * AutoRule Trigger Engine
 *
 * Event-driven service that listens to domain events and automatically
 * creates tasks when conditions match active AutoRules.
 *
 * Supported trigger types:
 * - STOCK_LOW: inventory.lowStock events
 * - MAINTENANCE_DUE: maintenance.schedule.due events
 * - WATER_PARAM_ALERT: alert.waterQuality events
 * - EXPIRY_NEAR: feeding.expiryWarning events
 * - SCHEDULE: cron-based (hourly check)
 * - LICENSE_EXPIRY: reserved for future implementation
 *
 * @module Task/Services
 */
import {
  Injectable,
  Logger,
  OnModuleInit,
  Inject,
  Optional,
} from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { NatsEventBus, IEventHandler } from '@platform/event-bus';
import { createBaseEvent } from '@platform/event-contracts';
import { AutoRule, AutoRuleTrigger } from '../entities/auto-rule.entity';
import { Task, TaskStatus } from '../entities/task.entity';

// Map trigger types to the NATS event subjects they listen for
const TRIGGER_EVENT_MAP: Record<string, AutoRuleTrigger> = {
  'inventory.lowStock': AutoRuleTrigger.STOCK_LOW,
  'maintenance.schedule.due': AutoRuleTrigger.MAINTENANCE_DUE,
  'alert.waterQuality': AutoRuleTrigger.WATER_PARAM_ALERT,
  'feeding.expiryWarning': AutoRuleTrigger.EXPIRY_NEAR,
};

@Injectable()
export class AutoRuleTriggerService implements OnModuleInit {
  private readonly logger = new Logger(AutoRuleTriggerService.name);

  constructor(
    @InjectRepository(AutoRule)
    private readonly autoRuleRepository: Repository<AutoRule>,
    @InjectRepository(Task)
    private readonly taskRepository: Repository<Task>,
    @Optional() @Inject('EVENT_BUS')
    private readonly eventBus?: NatsEventBus,
  ) {}

  async onModuleInit(): Promise<void> {
    if (!this.eventBus) {
      this.logger.warn(
        'EVENT_BUS not available — AutoRule triggers will not fire from events',
      );
      return;
    }

    // Subscribe to all relevant events
    for (const eventName of Object.keys(TRIGGER_EVENT_MAP)) {
      try {
        await this.eventBus.subscribe(eventName, {
          getEventType: () => eventName,
          handle: (event: any) => this.handleEvent(eventName, event),
        } as IEventHandler<any>);
        this.logger.log(`Subscribed to ${eventName} for AutoRule triggers`);
      } catch (err) {
        this.logger.warn(
          `Failed to subscribe to ${eventName}: ${(err as Error).message}`,
        );
      }
    }
  }

  /**
   * Handle an incoming domain event and check for matching AutoRules
   */
  async handleEvent(eventName: string, event: any): Promise<void> {
    const tenantId = event?.tenantId;
    if (!tenantId) {
      this.logger.warn(`Event ${eventName} has no tenantId, skipping`);
      return;
    }

    const triggerType = TRIGGER_EVENT_MAP[eventName];
    if (!triggerType) return;

    this.logger.debug(`Processing ${eventName} for tenant ${tenantId}`);

    // Find active rules matching this trigger type for this tenant
    const matchingRules = await this.autoRuleRepository.find({
      where: {
        tenantId,
        trigger: triggerType,
        isActive: true,
      },
    });

    if (matchingRules.length === 0) return;

    for (const rule of matchingRules) {
      try {
        await this.executeRule(rule, event);
      } catch (err) {
        this.logger.error(
          `Failed to execute AutoRule ${rule.id}: ${(err as Error).message}`,
        );
      }
    }
  }

  /**
   * Execute a single AutoRule by creating a task
   */
  private async executeRule(rule: AutoRule, triggerEvent: any): Promise<void> {
    // Build task title with context from trigger event
    const taskTitle = this.interpolateTitle(rule.taskTitle, triggerEvent);

    const task = this.taskRepository.create({
      tenantId: rule.tenantId,
      title: taskTitle,
      description: rule.taskDescription || undefined,
      category: rule.taskCategory,
      priority: rule.taskPriority,
      status: TaskStatus.PENDING,
      assignedTo:
        rule.assignTo || triggerEvent.userId || triggerEvent.assignedTo,
      assignedToName: 'Otomatik Atama',
      createdBy:
        rule.assignTo || triggerEvent.userId || 'system',
      dueDate: new Date(), // Due today
      checklistItems: [],
      notes: [],
      isAutoGenerated: true,
      isRecurring: false,
    });

    const saved = await this.taskRepository.save(task);

    // Update rule stats
    rule.lastTriggered = new Date();
    rule.triggerCount += 1;
    await this.autoRuleRepository.save(rule);

    // Publish TaskCreated event for notification
    if (this.eventBus && saved.assignedTo) {
      try {
        await this.eventBus.publish({
          ...createBaseEvent('TaskCreated', rule.tenantId),
          taskId: saved.id,
          title: saved.title,
          assignedTo: saved.assignedTo,
          assignedToName: saved.assignedToName,
          category: saved.category,
          priority: saved.priority,
          dueDate: saved.dueDate?.toISOString(),
          createdBy: 'auto-rule',
        });
      } catch (eventError) {
        this.logger.warn(
          `Failed to publish TaskCreated event for auto-rule task: ${(eventError as Error).message}`,
        );
      }
    }

    this.logger.log(
      `AutoRule "${rule.name}" triggered — created task "${saved.title}" (${saved.id})`,
    );
  }

  /**
   * Interpolate trigger event data into task title
   * Supports {eventField} placeholders
   */
  private interpolateTitle(template: string, event: any): string {
    return template.replace(/\{(\w+)\}/g, (_, key) => {
      return event[key]?.toString() ?? key;
    });
  }

  /**
   * SCHEDULE trigger type — runs every hour and checks for SCHEDULE-type rules.
   * These are simple time-based rules without external event triggers.
   */
  @Cron('0 0 * * * *')
  async processScheduleRules(): Promise<void> {
    this.logger.debug('Checking SCHEDULE-type AutoRules...');

    const scheduleRules = await this.autoRuleRepository.find({
      where: {
        trigger: AutoRuleTrigger.SCHEDULE,
        isActive: true,
      },
    });

    if (scheduleRules.length === 0) return;

    const now = new Date();

    for (const rule of scheduleRules) {
      try {
        // Check if enough time has passed since last trigger
        // triggerCondition for SCHEDULE type contains interval in hours (e.g., "24", "48")
        const intervalHours = parseInt(rule.triggerCondition, 10);
        if (isNaN(intervalHours) || intervalHours <= 0) {
          this.logger.warn(
            `Invalid SCHEDULE interval for rule ${rule.id}: "${rule.triggerCondition}"`,
          );
          continue;
        }

        if (rule.lastTriggered) {
          const elapsed =
            (now.getTime() - new Date(rule.lastTriggered).getTime()) / 3600000;
          if (elapsed < intervalHours) continue;
        }

        await this.executeRule(rule, { tenantId: rule.tenantId });
      } catch (err) {
        this.logger.error(
          `Failed to process SCHEDULE rule ${rule.id}: ${(err as Error).message}`,
        );
      }
    }
  }
}
