/**
 * Recurring Task Service
 *
 * Tekrarlayan görev şablon yönetimi ve otomatik görev oluşturma.
 *
 * @module Task/Services
 */
import {
  Injectable,
  NotFoundException,
  Logger,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, LessThanOrEqual } from 'typeorm';
import { RecurringTemplate, RecurrenceFrequency } from '../entities/recurring-template.entity';
import { Task, TaskStatus } from '../entities/task.entity';

@Injectable()
export class RecurringTaskService {
  private readonly logger = new Logger(RecurringTaskService.name);

  constructor(
    @InjectRepository(RecurringTemplate)
    private readonly templateRepository: Repository<RecurringTemplate>,
    @InjectRepository(Task)
    private readonly taskRepository: Repository<Task>,
  ) {}

  // -------------------------------------------------------------------------
  // CRUD OPERATIONS
  // -------------------------------------------------------------------------

  /**
   * Tüm tekrarlayan şablonları listeler
   */
  async findAll(tenantId: string): Promise<RecurringTemplate[]> {
    return this.templateRepository.find({
      where: { tenantId },
      order: { createdAt: 'DESC' },
    });
  }

  /**
   * ID ile şablon bulur
   */
  async findById(tenantId: string, id: string): Promise<RecurringTemplate> {
    const template = await this.templateRepository.findOne({
      where: { id, tenantId },
    });

    if (!template) {
      throw new NotFoundException(`Tekrarlayan şablon bulunamadı: ${id}`);
    }

    return template;
  }

  /**
   * Yeni tekrarlayan şablon oluşturur
   */
  async create(
    tenantId: string,
    input: Partial<RecurringTemplate>,
  ): Promise<RecurringTemplate> {
    this.logger.log(`Creating recurring template "${input.title}" for tenant ${tenantId}`);

    const template = this.templateRepository.create({
      ...input,
      tenantId,
      isActive: true,
      nextGeneration: this.calculateNextGeneration(
        input.frequency!,
        input.frequencyDetail,
      ),
    });

    return this.templateRepository.save(template);
  }

  /**
   * Şablonu günceller
   */
  async update(
    tenantId: string,
    id: string,
    input: Partial<RecurringTemplate>,
  ): Promise<RecurringTemplate> {
    const template = await this.findById(tenantId, id);

    Object.assign(template, input);

    // Recalculate next generation if frequency changed
    if (input.frequency) {
      template.nextGeneration = this.calculateNextGeneration(
        input.frequency,
        input.frequencyDetail || template.frequencyDetail,
      );
    }

    return this.templateRepository.save(template);
  }

  /**
   * Şablonu aktif/pasif yapar
   */
  async toggleActive(tenantId: string, id: string): Promise<RecurringTemplate> {
    const template = await this.findById(tenantId, id);
    template.isActive = !template.isActive;

    if (template.isActive && !template.nextGeneration) {
      template.nextGeneration = this.calculateNextGeneration(
        template.frequency,
        template.frequencyDetail,
      );
    }

    return this.templateRepository.save(template);
  }

  /**
   * Şablonu siler
   */
  async delete(tenantId: string, id: string): Promise<boolean> {
    const template = await this.findById(tenantId, id);
    await this.templateRepository.remove(template);
    return true;
  }

  // -------------------------------------------------------------------------
  // TASK GENERATION
  // -------------------------------------------------------------------------

  /**
   * Zamanı gelen şablonlardan görev oluşturur
   */
  async generateDueTasks(): Promise<Task[]> {
    const now = new Date();

    const dueTemplates = await this.templateRepository.find({
      where: {
        isActive: true,
        nextGeneration: LessThanOrEqual(now),
      },
    });

    if (dueTemplates.length === 0) {
      this.logger.debug('No recurring templates due for generation');
      return [];
    }

    const generatedTasks: Task[] = [];

    for (const template of dueTemplates) {
      try {
        const task = this.taskRepository.create({
          tenantId: template.tenantId,
          title: template.title,
          description: template.description,
          category: template.category,
          priority: template.priority,
          status: TaskStatus.PENDING,
          assignedTo: template.assignedTo,
          assignedToName: template.assignedToName,
          createdBy: template.assignedTo, // Auto-generated by system
          dueDate: now,
          location: template.location,
          estimatedMinutes: template.estimatedMinutes,
          checklistItems: template.checklistItems ? [...template.checklistItems] : [],
          notes: [],
          tags: template.tags,
          isRecurring: true,
          recurringTemplateId: template.id,
          isAutoGenerated: true,
        });

        const saved = await this.taskRepository.save(task);
        generatedTasks.push(saved);

        // Update template
        template.lastGenerated = now;
        template.nextGeneration = this.calculateNextGeneration(
          template.frequency,
          template.frequencyDetail,
        );
        await this.templateRepository.save(template);

        this.logger.log(
          `Generated task "${saved.title}" from template ${template.id}`,
        );
      } catch (error) {
        this.logger.error(
          `Failed to generate task from template ${template.id}: ${(error as Error).message}`,
        );
      }
    }

    return generatedTasks;
  }

  // -------------------------------------------------------------------------
  // HELPER METHODS
  // -------------------------------------------------------------------------

  /**
   * Sonraki üretim zamanını hesaplar
   */
  private calculateNextGeneration(
    frequency: RecurrenceFrequency,
    frequencyDetail?: string | null,
  ): Date {
    const now = new Date();

    switch (frequency) {
      case RecurrenceFrequency.HOURLY:
        return new Date(now.getTime() + 60 * 60 * 1000);
      case RecurrenceFrequency.DAILY:
        return new Date(now.getTime() + 24 * 60 * 60 * 1000);
      case RecurrenceFrequency.WEEKLY:
        return new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
      case RecurrenceFrequency.BIWEEKLY:
        return new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);
      case RecurrenceFrequency.MONTHLY:
        const nextMonth = new Date(now);
        nextMonth.setMonth(nextMonth.getMonth() + 1);
        return nextMonth;
      case RecurrenceFrequency.CUSTOM:
        // frequencyDetail should contain interval in hours
        const hours = parseInt(frequencyDetail || '24', 10);
        return new Date(now.getTime() + hours * 60 * 60 * 1000);
      default:
        return new Date(now.getTime() + 24 * 60 * 60 * 1000);
    }
  }
}
