import { MigrationInterface, QueryRunner } from 'typeorm';
import { applyTenantRlsToSchema, removeTenantRlsFromSchema } from '@aquaculture/backend-common/database';

/**
 * Day-one baseline for hydroponics-service. Faz 3 of the day-one
 * baseline reset (`docs/plans/peppy-crafting-waterfall.md`).
 *
 * Generated by `scripts/migration/baseline-generator.ts` against the
 * disposable Postgres 16 + TimescaleDB container (sealed from
 * production). Hand-author additions appended in Faz 3.5:
 *
 *   - Row-Level Security via the canonical helper
 *     `applyTenantRlsToSchema` (Faz 1.7 RLS predicate invariant).
 */
export class Baseline1800000000000 implements MigrationInterface {
    name = 'Baseline1800000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "hydroponics_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "config_name" character varying(255) NOT NULL DEFAULT 'Default', "settings" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8f76b7cbf6ee0aee15412c44e2b" UNIQUE ("tenant_id", "config_name"), CONSTRAINT "PK_fb61a2e995a67c89204a89a725b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00dd22c917aa1ce6578bc9d7c7" ON "hydroponics_config" ("tenant_id") `);

        // ── Faz 3.5 hand-author addition — RLS canonical predicate ──
        await applyTenantRlsToSchema(queryRunner, {
            tenantIdColumns: ['tenant_id', 'tenantId'],
            excludeTables: [],
        });
    }

    // ── GENERATED postCondition (DATA-CRITICAL-010) — do not hand-edit ──
    public async postCondition(queryRunner: QueryRunner): Promise<boolean> {
        const rows: Array<{ missing: string }> = await queryRunner.query(`
            SELECT expected.table_name AS missing
              FROM (VALUES ('hydroponics_config')) AS expected(table_name)
             WHERE NOT EXISTS (
               SELECT 1
                 FROM information_schema.tables
                WHERE table_schema = current_schema()
                  AND table_name = expected.table_name
             )
        `);
        return rows.length === 0;
    }
    // ── END GENERATED postCondition ──

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Reverse Faz 3.5 RLS install first (avoids policy-on-missing-table).
        await removeTenantRlsFromSchema(queryRunner, {
            tenantIdColumns: ['tenant_id', 'tenantId'],
            excludeTables: [],
        });
        await queryRunner.query(`DROP INDEX "IDX_00dd22c917aa1ce6578bc9d7c7"`);
        await queryRunner.query(`DROP TABLE "hydroponics_config"`);
    }

}
