/**
 * Centralized GraphQL query and mutation definitions.
 * Every query/mutation used in tenant-admin is exported from here.
 */

export {
  MY_TENANT_QUERY,
  TENANT_STATS_QUERY,
  TENANT_DATABASE_QUERY,
  TABLE_SCHEMA_QUERY,
  TABLE_DATA_QUERY,
  UPDATE_TENANT_MUTATION,
  UPDATE_TENANT_SETTINGS_MUTATION,
  MY_TENANT_LOCALIZATION_QUERY,
  UPDATE_TENANT_LOCALIZATION_MUTATION,
} from './tenant-queries';

export {
  TENANT_USERS_QUERY,
  CREATE_TENANT_USER_MUTATION,
  UPDATE_USER_MUTATION,
  DELETE_USER_MUTATION,
  DEACTIVATE_TENANT_USER_MUTATION,
  ACTIVE_SITE_ACCESS_CATALOG_QUERY,
  USER_ASSIGNED_SITE_IDS_QUERY,
  ASSIGN_USER_TO_SITE_MUTATION,
  UNASSIGN_USER_FROM_SITE_MUTATION,
} from './user-queries';

export {
  TENANT_ROLES_QUERY,
  TENANT_ROLE_QUERY,
  DEFAULT_TENANT_ROLE_QUERY,
  PERMISSION_CATEGORIES_QUERY,
  CREATE_TENANT_ROLE_MUTATION,
  UPDATE_TENANT_ROLE_MUTATION,
  DELETE_TENANT_ROLE_MUTATION,
  SEED_TENANT_ROLES_MUTATION,
} from './role-queries';

export {
  MY_MODULES_QUERY,
  MY_TENANT_MODULES_QUERY,
  MY_MODULES_ID_QUERY,
  MODULE_USAGE_STATS_QUERY,
  ASSIGN_MODULE_MANAGER_MUTATION,
  REMOVE_MODULE_MANAGER_MUTATION,
} from './module-queries';

export {
  EDGE_DEVICES_QUERY,
  EDGE_DEVICE_QUERY,
  DEVICE_EVENTS_QUERY,
  APPROVE_DEVICE_MUTATION,
  PING_DEVICE_MUTATION,
  REBOOT_DEVICE_MUTATION,
  MAINTENANCE_DEVICE_MUTATION,
  DECOMMISSION_DEVICE_MUTATION,
  CREATE_PROVISIONING_KEY_MUTATION,
  LIST_PROVISIONING_KEYS_QUERY,
  REVOKE_PROVISIONING_KEY_MUTATION,
} from './device-queries';

export {
  TENANT_BILLING_QUERY,
  MY_SUBSCRIPTION_QUERY,
  TENANT_ACTIVITY_QUERY,
  TENANT_AUDIT_LOGS_QUERY,
  GET_NOTIFICATION_PREFERENCES_QUERY,
  UPDATE_NOTIFICATION_PREFERENCES_MUTATION,
  GET_MOBILE_USERS_SETTINGS_QUERY,
  UPDATE_MOBILE_USER_SETTINGS_MUTATION,
} from './billing-queries';

export { AI_PROVIDER_SETTINGS_QUERY, UPDATE_AI_PROVIDER_SETTINGS_MUTATION } from './ai-queries';

export {
  // Messaging
  MY_THREADS_QUERY,
  THREAD_QUERY,
  THREAD_MESSAGES_QUERY,
  MESSAGING_STATS_QUERY,
  CREATE_THREAD_MUTATION,
  SEND_MESSAGE_MUTATION,
  CLOSE_THREAD_MUTATION,
  REOPEN_THREAD_MUTATION,
  // Support
  MY_TICKETS_QUERY,
  TICKET_QUERY,
  TICKET_COMMENTS_QUERY,
  SUPPORT_STATS_QUERY,
  CREATE_TICKET_MUTATION,
  ADD_TICKET_COMMENT_MUTATION,
  RATE_TICKET_MUTATION,
  // Announcements
  MY_ANNOUNCEMENTS_QUERY,
  ANNOUNCEMENT_QUERY,
  ANNOUNCEMENT_STATS_QUERY,
  CREATE_TENANT_ANNOUNCEMENT_MUTATION,
  PUBLISH_ANNOUNCEMENT_MUTATION,
  CANCEL_ANNOUNCEMENT_MUTATION,
  DELETE_ANNOUNCEMENT_MUTATION,
  VIEW_ANNOUNCEMENT_MUTATION,
  ACKNOWLEDGE_ANNOUNCEMENT_MUTATION,
} from './communication-queries';
