import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { GenericContainer, type StartedTestContainer, Wait } from 'testcontainers';

/**
 * MQTT broker test harness — a real Mosquitto + mosquitto-go-auth container
 * whose auth/acl decisions delegate over HTTP to a sensor-service
 * MqttAuthController under test.
 *
 * Canonical pattern from `docs/patterns/jest-testcontainers.md` (same model
 * as `@platform/migration-harness`): one shared container per spec file,
 * boot in `beforeAll`, `stop()` in `afterAll`.
 *
 * # Why a real broker at all
 *
 * The SENSOR-HIGH-118 class of bug lives BETWEEN three components: the
 * listener's filter list, the go-auth HTTP bridge semantics (acc=4 =
 * MOSQ_ACL_SUBSCRIBE on wildcard filters), and the broker's SUBACK handling
 * (0x80 for a denied filter). Mock-based unit tests proved each component in
 * isolation and still shipped a listener subscribed to NOTHING. Only a real
 * Mosquitto exercising the real go-auth plugin against the real
 * `checkTopicAccess` decision path reproduces that contract.
 *
 * # Image
 *
 * Default image is the platform's own hardened broker
 * (`ghcr.io/okan-wqm/aquaculture_platform/mosquitto` — mosquitto + go-auth
 * .so, no TLS listener; production terminates TLS at nginx). Override via
 * `image` or MQTT_TEST_BROKER_IMAGE.
 *
 * # Config
 *
 * The image's baked config points at `sensor-service:3000` with a
 * __MQTT_AUTH_SECRET__ placeholder that production compose seds at start.
 * The harness instead writes its own config (same plugin settings) pointing
 * at the jest process's auth backend via the `host-gateway`, bind-mounts it
 * over /mosquitto/config/mosquitto.conf, and runs the same command the image
 * declares.
 */

export interface MqttHarnessOptions {
  /** Broker image; defaults to the platform mosquitto (go-auth baked in). */
  image?: string;
  /**
   * Hostname the broker resolves for the auth HTTP calls. Defaults to
   * `sensor-service` pinned to the Docker host gateway, so an HTTP server
   * in the jest process (listen on 0.0.0.0) is reachable.
   */
  authBackendHost?: string;
  authBackendHostIp?: string;
  /** Port the auth endpoints listen on (the jest process's server). */
  authBackendPort: number;
  /** Value the broker sends as X-Mosquitto-Auth (must match the backend). */
  authSecret: string;
  startTimeoutMs?: number;
}

export interface MqttHarness {
  container: StartedTestContainer;
  /** Host to connect an MQTT client to. */
  host: string;
  port: number;
  /** Broker log lines captured since boot (for failure diagnostics). */
  capturedLogs(): string[];
  stop(): Promise<void>;
}

const PLATFORM_MOSQUITTO_IMAGE =
  'ghcr.io/okan-wqm/aquaculture_platform/mosquitto:9b44390f98e16c4de759bfbc4d524e4312d2a81b';

function writeBrokerConfig(options: MqttHarnessOptions): string {
  const host = options.authBackendHost ?? 'sensor-service';
  const conf = `# Generated by @platform/mqtt-test-harness — mirrors the image's
# baked mosquitto-production.conf (go-auth http backend) with the auth
# endpoint and secret pinned to this test run.
listener 1883
allow_anonymous false

auth_plugin /usr/lib/go-auth.so
auth_opt_backends http
auth_opt_cache false

auth_opt_http_host ${host}
auth_opt_http_port ${options.authBackendPort}
auth_opt_http_getuser_uri /mqtt/auth
auth_opt_http_superuser_uri /mqtt/superuser
auth_opt_http_aclcheck_uri /mqtt/acl
auth_opt_http_with_tls false
auth_opt_http_verify_peer false
auth_opt_http_response_mode status
auth_opt_http_timeout 5
auth_opt_http_params_mode form
auth_opt_http_headers X-Mosquitto-Auth: ${options.authSecret}

persistence false
log_dest stdout
log_type error
log_type warning
log_type notice
`;
  const dir = mkdtempSync(join(tmpdir(), 'mqtt-acl-test-'));
  const file = join(dir, 'mosquitto.conf');
  writeFileSync(file, conf, { encoding: 'utf8' });
  return file;
}

export async function bootMosquittoContainer(options: MqttHarnessOptions): Promise<MqttHarness> {
  const image = options.image ?? process.env['MQTT_TEST_BROKER_IMAGE'] ?? PLATFORM_MOSQUITTO_IMAGE;
  const confFile = writeBrokerConfig(options);
  const backendHostIp = options.authBackendHostIp ?? 'host-gateway';

  try {
    const container = new GenericContainer(image)
      .withBindMounts([
        { source: confFile, target: '/mosquitto/config/mosquitto.conf', mode: 'ro' },
      ])
      .withCommand(['mosquitto', '-c', '/mosquitto/config/mosquitto.conf'])
      .withExtraHosts([
        { host: options.authBackendHost ?? 'sensor-service', ipAddress: backendHostIp },
      ])
      .withExposedPorts(1883)
      .withWaitStrategy(
        Wait.forSuccessfulCommand('nc -z localhost 1883').withStartupTimeout(
          options.startTimeoutMs ?? 60_000,
        ),
      );

    const logs: string[] = [];
    container.withLogConsumer((stream) => {
      stream.on('data', (line) => logs.push(line.trim()));
    });

    const started = await container.start();

    return {
      container: started,
      host: started.getHost(),
      port: started.getMappedPort(1883),
      capturedLogs: () => [...logs],
      async stop() {
        await started.stop({ remove: true, timeout: 10_000 });
      },
    };
  } finally {
    rmSync(dirname(confFile), { recursive: true, force: true });
  }
}
