import {
  bootPostgresContainer,
  type HarnessContext,
  shutdownHarness,
} from '@platform/migration-harness';
import type { QueryRunner } from 'typeorm';

import { EnforceTenantOnboardingAckMonotonicity1808300000000 } from '../1808300000000-EnforceTenantOnboardingAckMonotonicity';

const ACTIVE_OPERATION = '11111111-1111-4111-8111-111111111111';
const TERMINAL_OPERATION = '22222222-2222-4222-8222-222222222222';
const QUALIFIED_OPERATION = '33333333-3333-4333-8333-333333333333';
const TENANT_ID = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const DIGEST = 'a'.repeat(64);
const PUBLICATION_EVENT_ID = '44444444-4444-4444-8444-444444444444';

function onboardingRequestPayload(overrides: Readonly<Record<string, unknown>> = {}): object {
  return {
    eventId: PUBLICATION_EVENT_ID,
    eventType: 'TenantOnboardingRequested',
    tenantId: TENANT_ID,
    aggregateId: TENANT_ID,
    aggregateType: 'Tenant',
    operationId: QUALIFIED_OPERATION,
    generation: 1,
    timestamp: new Date().toISOString(),
    version: 1,
    slug: 'qualified-tenant',
    name: 'Qualified Tenant',
    moduleIds: ['farm-core'],
    ...overrides,
  };
}

interface BaselineDrift {
  readonly unexpectedColumn?: boolean;
  readonly wrongRequestHashType?: boolean;
  readonly wrongStateConstraint?: boolean;
}

async function installBaseline(queryRunner: QueryRunner, drift: BaselineDrift = {}): Promise<void> {
  await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
  await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "pgcrypto"');
  await queryRunner.query('DROP SCHEMA IF EXISTS "admin" CASCADE');
  await queryRunner.query('CREATE SCHEMA "admin"');
  await queryRunner.query(`
    CREATE TABLE "admin"."tenant_provisioning_runs" (
      "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      "tenantId" UUID NOT NULL,
      "idempotencyKey" VARCHAR(128) NOT NULL,
      "requestHash" VARCHAR(${drift.wrongRequestHashType ? 63 : 64}) NOT NULL,
      "requestPayload" JSONB NOT NULL DEFAULT '{}',
      "actorUserId" UUID NOT NULL,
      "state" VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
      "currentStep" VARCHAR(100) NULL,
      "lastError" TEXT NULL,
      "attempts" INTEGER NOT NULL DEFAULT 0,
      "nextRetryAt" TIMESTAMPTZ NULL,
      "leaseToken" UUID NULL,
      "leasedBy" VARCHAR(128) NULL,
      "heartbeatAt" TIMESTAMPTZ NULL,
      "leaseExpiresAt" TIMESTAMPTZ NULL,
      "startedAt" TIMESTAMPTZ NULL,
      "completedAt" TIMESTAMPTZ NULL,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT "chk_tenant_provisioning_runs_state"
        CHECK ("state" IN (
          'QUEUED', 'RESERVING', 'RUNNING', 'SUCCEEDED', 'FAILED'
          ${drift.wrongStateConstraint ? ", 'WAITING_ONBOARDING'" : ''}
        ))
    )
  `);
  if (drift.unexpectedColumn) {
    await queryRunner.query(
      'ALTER TABLE "admin"."tenant_provisioning_runs" ADD COLUMN "unexpected" TEXT NULL',
    );
  }
  await queryRunner.query(`
    CREATE TABLE "admin"."tenant_provisioning_steps" (
      "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      "runId" UUID NOT NULL,
      "stepName" VARCHAR(100) NOT NULL,
      "stepOrder" INTEGER NOT NULL DEFAULT 999,
      "state" VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
      "attempts" INTEGER NOT NULL DEFAULT 0,
      "lastError" TEXT NULL,
      "startedAt" TIMESTAMPTZ NULL,
      "completedAt" TIMESTAMPTZ NULL,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT "chk_tenant_provisioning_steps_state"
        CHECK ("state" IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
      CONSTRAINT "fk_tenant_provisioning_steps_run"
        FOREIGN KEY ("runId") REFERENCES "admin"."tenant_provisioning_runs"("id")
        ON DELETE CASCADE,
      CONSTRAINT "uk_tenant_provisioning_steps_run_step" UNIQUE ("runId", "stepName")
    )
  `);
  await queryRunner.query(`
    CREATE TABLE "admin"."tenant_onboarding_acks" (
      "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      "operationId" UUID NOT NULL,
      "tenantId" UUID NOT NULL,
      "service" VARCHAR(128) NOT NULL,
      "status" VARCHAR(20) NOT NULL,
      "error" TEXT NULL,
      "acknowledgedAt" TIMESTAMPTZ NULL,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT "chk_tenant_onboarding_acks_status" CHECK ("status" IN ('ACK', 'FAILED')),
      CONSTRAINT "uk_tenant_onboarding_acks_operation_service"
        UNIQUE ("operationId", "service")
    )
  `);
  await queryRunner.query(`
    CREATE TABLE "admin"."admin_outbox" (
      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "eventType" VARCHAR(100) NOT NULL,
      "tenantId" UUID NULL,
      "aggregateId" UUID NULL,
      "payload" JSONB NOT NULL,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
      "publishedAt" TIMESTAMPTZ NULL,
      "retryCount" INTEGER NOT NULL DEFAULT 0,
      "lastError" TEXT NULL,
      "nextAttemptAt" TIMESTAMPTZ NULL,
      "idempotencyKey" VARCHAR(255) NULL,
      "isDeadLettered" BOOLEAN NOT NULL DEFAULT false,
      "leasedAt" TIMESTAMPTZ NULL,
      "leasedBy" VARCHAR(128) NULL
    );
    CREATE UNIQUE INDEX "idx_admin_outbox_idempotency"
      ON "admin"."admin_outbox" ("tenantId", "idempotencyKey")
      WHERE "idempotencyKey" IS NOT NULL
  `);
}

async function migrate(queryRunner: QueryRunner): Promise<void> {
  const migration = new EnforceTenantOnboardingAckMonotonicity1808300000000();
  await queryRunner.startTransaction();
  try {
    await migration.up(queryRunner);
    await queryRunner.commitTransaction();
  } catch (error) {
    await queryRunner.rollbackTransaction();
    throw error;
  }
}

async function seedLegacyRows(queryRunner: QueryRunner): Promise<void> {
  await queryRunner.query(
    `INSERT INTO admin.tenant_provisioning_runs (
       id, "tenantId", "idempotencyKey", "requestHash", "requestPayload",
       "actorUserId", state, "leaseToken"
     ) VALUES
       ($1, $3, 'legacy-active', $4, '{}', $3, 'RUNNING', $3),
       ($2, $3, 'legacy-terminal', $4, '{}', $3, 'SUCCEEDED', NULL)`,
    [ACTIVE_OPERATION, TERMINAL_OPERATION, TENANT_ID, 'b'.repeat(64)],
  );
  await queryRunner.query(
    `INSERT INTO admin.tenant_onboarding_acks (
       "operationId", "tenantId", service, status, "acknowledgedAt"
     ) VALUES ($1, $2, 'legacy-owner', 'ACK', now())`,
    [ACTIVE_OPERATION, TENANT_ID],
  );
}

async function seedQualifiedGeneration(queryRunner: QueryRunner): Promise<void> {
  const snapshot = {
    schemaVersion: 'tenant-onboarding-requirement-snapshot.v1',
    sourceProfileDigest: 'b'.repeat(64),
    requiredServices: ['farm-service'],
    ackDeadlineMs: 60_000,
    retryIntervalMs: 10_000,
    snapshotDigest: DIGEST,
  };
  await queryRunner.query(
    `INSERT INTO admin.tenant_provisioning_runs (
       id, "tenantId", "idempotencyKey", "requestHash", "requestPayload",
       "actorUserId", state, "onboardingQualification", "onboardingGeneration",
       "onboardingRequirements", "onboardingRequirementsDigest"
     ) VALUES (
       $1, $2, 'qualified-operation', $3, '{}', $2, 'WAITING_ONBOARDING',
       'QUALIFIED', 1, $4::jsonb, $5
     )`,
    [QUALIFIED_OPERATION, TENANT_ID, 'c'.repeat(64), JSON.stringify(snapshot), DIGEST],
  );
  await queryRunner.query(
    `INSERT INTO admin.tenant_onboarding_requirements (
       "operationId", "tenantId", generation, service, "requirementsDigest"
     ) VALUES ($1, $2, 1, 'farm-service', $3)`,
    [QUALIFIED_OPERATION, TENANT_ID, DIGEST],
  );
}

async function publishQualifiedGeneration(queryRunner: QueryRunner): Promise<{
  outboxId: string;
  eventId: string;
  publicationDigest: string;
  requestedAt: Date;
  deadlineAt: Date;
}> {
  const rows = (await queryRunner.query(
    `SELECT "outboxId", "eventId", "publicationDigest", "requestedAt", "deadlineAt"
       FROM admin.publish_tenant_onboarding_request($1, $2, 1, $3::jsonb)`,
    [QUALIFIED_OPERATION, TENANT_ID, JSON.stringify(onboardingRequestPayload())],
  )) as Array<{
    outboxId: string;
    eventId: string;
    publicationDigest: string;
    requestedAt: Date;
    deadlineAt: Date;
  }>;
  const proof = rows[0];
  if (!proof) throw new Error('tenant onboarding publication proof is missing');
  return proof;
}

interface ActivationProof {
  readonly sealToken: string;
  readonly evidenceRoot: string;
  readonly publicationDigest: string;
}

async function seedReadyActivation(queryRunner: QueryRunner): Promise<ActivationProof> {
  await seedQualifiedGeneration(queryRunner);
  await publishQualifiedGeneration(queryRunner);
  await queryRunner.query(
    `INSERT INTO admin.tenant_provisioning_steps (
       "runId", "stepName", "stepOrder", state
     ) VALUES
       ($1, 'publish_onboarding_requested', 9, 'SUCCEEDED'),
       ($1, 'wait_for_onboarding_ack', 10, 'SUCCEEDED')`,
    [QUALIFIED_OPERATION],
  );
  await queryRunner.query(
    `SELECT admin.admit_tenant_onboarding_outcome(
       $1, $2, 1, 'farm-service', 'ACK', NULL, clock_timestamp()
     )`,
    [QUALIFIED_OPERATION, TENANT_ID],
  );
  const rows = (await queryRunner.query(
    `SELECT "sealToken", "evidenceRoot", "publicationDigest"
       FROM admin.seal_tenant_onboarding_activation($1, $2, 1)`,
    [QUALIFIED_OPERATION, TENANT_ID],
  )) as ActivationProof[];
  const proof = rows[0];
  if (!proof) throw new Error('activation seal proof is missing');
  return proof;
}

describe('tenant onboarding generation authority — real PostgreSQL contract', () => {
  let harness: HarnessContext | undefined;
  let queryRunner: QueryRunner;

  beforeAll(async () => {
    harness = await bootPostgresContainer({
      startTimeoutMs: 120_000,
      labels: { 'com.aqua-saas.test.role': 'tenant-onboarding-generation-contract' },
    });
    queryRunner = harness.dataSource.createQueryRunner();
    await queryRunner.connect();
    await queryRunner.query(`
      DO $roles$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin_service') THEN
          CREATE ROLE admin_service NOLOGIN;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'auth_service') THEN
          CREATE ROLE auth_service NOLOGIN;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'onboarding_unauthorized') THEN
          CREATE ROLE onboarding_unauthorized NOLOGIN;
        END IF;
      END
      $roles$
    `);
  }, 150_000);

  afterAll(async () => {
    await queryRunner?.release();
    await shutdownHarness(harness);
  }, 60_000);

  it('preserves legacy evidence without fabricating a catalog snapshot', async () => {
    await installBaseline(queryRunner);
    await seedLegacyRows(queryRunner);
    await migrate(queryRunner);

    const runs = (await queryRunner.query(
      `SELECT id, state, "onboardingQualification", "onboardingGeneration",
              "onboardingRequirements", "onboardingRequirementsDigest", "lastError"
         FROM admin.tenant_provisioning_runs ORDER BY id`,
    )) as Array<Record<string, unknown>>;
    expect(runs).toHaveLength(2);
    expect(runs).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: ACTIVE_OPERATION,
          state: 'FAILED',
          onboardingQualification: 'LEGACY_UNQUALIFIED',
          onboardingGeneration: null,
          onboardingRequirements: null,
          onboardingRequirementsDigest: null,
          lastError: 'Legacy onboarding run requires an explicit catalog-qualified retry',
        }),
        expect.objectContaining({
          id: TERMINAL_OPERATION,
          state: 'SUCCEEDED',
          onboardingQualification: 'LEGACY_UNQUALIFIED',
          onboardingRequirements: null,
        }),
      ]),
    );
    const counts = (await queryRunner.query(`
      SELECT
        (SELECT count(*)::int FROM admin.tenant_onboarding_requirements) AS "requirementCount",
        (SELECT count(*)::int FROM admin.tenant_onboarding_acks) AS "liveAckCount",
        (SELECT count(*)::int FROM admin.tenant_onboarding_acks_legacy) AS "legacyAckCount"
    `)) as Array<{ requirementCount: number; liveAckCount: number; legacyAckCount: number }>;
    const countProof = counts[0];
    if (!countProof) throw new Error('legacy convergence count proof is missing');
    const { requirementCount, liveAckCount, legacyAckCount } = countProof;
    expect({ requirementCount, liveAckCount, legacyAckCount }).toEqual({
      requirementCount: 0,
      liveAckCount: 0,
      legacyAckCount: 1,
    });
  });

  it('fails closed before mutation when the deployed baseline has an unknown column', async () => {
    await installBaseline(queryRunner, { unexpectedColumn: true });

    await expect(migrate(queryRunner)).rejects.toThrow('descriptor differs from governed baseline');
    const archiveRows = (await queryRunner.query(
      `SELECT to_regclass('admin.tenant_onboarding_acks_legacy') AS archive`,
    )) as Array<{ archive: string | null }>;
    const archiveProof = archiveRows[0];
    if (!archiveProof) throw new Error('baseline failure proof is missing');
    const { archive } = archiveProof;
    expect(archive).toBeNull();
  });

  it.each([
    [{ wrongRequestHashType: true }, 'tenant_provisioning_runs descriptor'],
    [{ wrongStateConstraint: true }, 'state constraint differs'],
  ] as const)('fails before mutation for canonical baseline drift %#', async (drift, message) => {
    await installBaseline(queryRunner, drift);

    await expect(migrate(queryRunner)).rejects.toThrow(message);
    const rows = (await queryRunner.query(
      `SELECT to_regclass('admin.tenant_onboarding_acks_legacy') AS archive`,
    )) as Array<{ archive: string | null }>;
    expect(rows[0]?.archive).toBeNull();
  });

  it('revokes SECURITY DEFINER execution from PUBLIC and enforces exact role surfaces', async () => {
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    await queryRunner.query(
      'GRANT USAGE ON SCHEMA admin TO admin_service, auth_service, onboarding_unauthorized',
    );

    try {
      await queryRunner.query('SET ROLE onboarding_unauthorized');
      await expect(
        queryRunner.query(`SELECT * FROM admin.assert_tenant_onboarding_publication($1, $2, 1)`, [
          QUALIFIED_OPERATION,
          TENANT_ID,
        ]),
      ).rejects.toThrow('permission denied');
    } finally {
      await queryRunner.query('RESET ROLE');
    }
    try {
      await queryRunner.query('SET ROLE admin_service');
      await expect(
        queryRunner.query(
          `SELECT * FROM admin.consume_tenant_onboarding_activation(
             $1, $2, 1, $3, $4, $5
           )`,
          [QUALIFIED_OPERATION, TENANT_ID, PUBLICATION_EVENT_ID, DIGEST, DIGEST],
        ),
      ).rejects.toThrow('permission denied');
    } finally {
      await queryRunner.query('RESET ROLE');
    }
    try {
      await queryRunner.query('SET ROLE auth_service');
      await expect(
        queryRunner.query(`SELECT * FROM admin.seal_tenant_onboarding_activation($1, $2, 1)`, [
          QUALIFIED_OPERATION,
          TENANT_ID,
        ]),
      ).rejects.toThrow('permission denied');
    } finally {
      await queryRunner.query('RESET ROLE');
    }
  });

  it('rejects pre-request/stale outcomes and safety-fails FAILED-to-ACK contradiction', async () => {
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    await seedQualifiedGeneration(queryRunner);
    await publishQualifiedGeneration(queryRunner);

    await expect(
      queryRunner.query(
        `SELECT admin.admit_tenant_onboarding_outcome(
           $1, $2, 1, 'farm-service', 'ACK', NULL, now() - interval '2 seconds'
         )`,
        [QUALIFIED_OPERATION, TENANT_ID],
      ),
    ).rejects.toThrow('outside its request window');
    await expect(
      queryRunner.query(
        `SELECT admin.admit_tenant_onboarding_outcome(
           $1, $2, 2, 'farm-service', 'ACK', NULL, now()
         )`,
        [QUALIFIED_OPERATION, TENANT_ID],
      ),
    ).rejects.toThrow('stale or unqualified generation');

    const failedRows = (await queryRunner.query(
      `SELECT admin.admit_tenant_onboarding_outcome(
         $1, $2, 1, 'farm-service', 'FAILED', 'owner failed', now()
       ) AS disposition`,
      [QUALIFIED_OPERATION, TENANT_ID],
    )) as Array<{ disposition: string }>;
    const failedDisposition = failedRows[0]?.disposition;
    expect(failedDisposition).toBe('ADMITTED');
    const contradictionRows = (await queryRunner.query(
      `SELECT admin.admit_tenant_onboarding_outcome(
         $1, $2, 1, 'farm-service', 'ACK', NULL, now()
       ) AS disposition`,
      [QUALIFIED_OPERATION, TENANT_ID],
    )) as Array<{ disposition: string }>;
    const contradictionDisposition = contradictionRows[0]?.disposition;
    expect(contradictionDisposition).toBe('SAFETY_FAILED');

    const proofRows = (await queryRunner.query(
      `SELECT acknowledgement.status, run.state,
              run."onboardingSafetyFailure" ->> 'code' AS "safetyCode"
         FROM admin.tenant_onboarding_acks acknowledgement
         JOIN admin.tenant_provisioning_runs run ON run.id = acknowledgement."operationId"
        WHERE acknowledgement."operationId" = $1`,
      [QUALIFIED_OPERATION],
    )) as Array<{ status: string; state: string; safetyCode: string }>;
    const proof = proofRows[0];
    if (!proof) throw new Error('contradictory outcome safety proof is missing');
    expect(proof).toEqual({
      status: 'FAILED',
      state: 'FAILED',
      safetyCode: 'CONTRADICTORY_TERMINAL_OUTCOME',
    });
  });

  it('makes request-window arming and outbox insertion rollback-indivisible', async () => {
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    await seedQualifiedGeneration(queryRunner);

    await queryRunner.startTransaction();
    try {
      await publishQualifiedGeneration(queryRunner);
      throw new Error('simulated process crash before commit');
    } catch {
      await queryRunner.rollbackTransaction();
    }

    const atomicProofRows = (await queryRunner.query(
      `SELECT run."onboardingRequestedAt", run."onboardingDeadlineAt",
              run."onboardingPublicationDigest",
              (SELECT count(*)::int FROM admin.admin_outbox) AS "outboxCount"
         FROM admin.tenant_provisioning_runs run WHERE run.id = $1`,
      [QUALIFIED_OPERATION],
    )) as Array<{
      onboardingRequestedAt: Date | null;
      onboardingDeadlineAt: Date | null;
      onboardingPublicationDigest: string | null;
      outboxCount: number;
    }>;
    const proof = atomicProofRows[0];
    if (!proof) throw new Error('atomic rollback proof is missing');
    expect(proof).toEqual({
      onboardingRequestedAt: null,
      onboardingDeadlineAt: null,
      onboardingPublicationDigest: null,
      outboxCount: 0,
    });
  });

  it('rejects wrong/duplicate publication minting and detects replay outbox tampering', async () => {
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    await seedQualifiedGeneration(queryRunner);
    await expect(
      queryRunner.query(
        `SELECT * FROM admin.publish_tenant_onboarding_request($1, $2, 1, $3::jsonb)`,
        [
          QUALIFIED_OPERATION,
          TENANT_ID,
          JSON.stringify(onboardingRequestPayload({ generation: 2 })),
        ],
      ),
    ).rejects.toThrow('payload violates its governed identity');

    const publication = await publishQualifiedGeneration(queryRunner);
    await expect(
      queryRunner.query(
        `SELECT * FROM admin.publish_tenant_onboarding_request($1, $2, 1, $3::jsonb)`,
        [QUALIFIED_OPERATION, TENANT_ID, JSON.stringify(onboardingRequestPayload())],
      ),
    ).rejects.toThrow('already sealed or unavailable');
    const replayRows = (await queryRunner.query(
      `SELECT "publicationDigest"
         FROM admin.assert_tenant_onboarding_publication($1, $2, 1)`,
      [QUALIFIED_OPERATION, TENANT_ID],
    )) as Array<{ publicationDigest: string }>;
    expect(replayRows[0]?.publicationDigest).toBe(publication.publicationDigest);

    await queryRunner.query(
      `UPDATE admin.admin_outbox
          SET payload = jsonb_set(payload, '{generation}', '9'::jsonb)
        WHERE id = $1`,
      [publication.outboxId],
    );
    await expect(
      queryRunner.query(`SELECT * FROM admin.assert_tenant_onboarding_publication($1, $2, 1)`, [
        QUALIFIED_OPERATION,
        TENANT_ID,
      ]),
    ).rejects.toThrow('outbox identity is inconsistent');
  });

  it('allows only auth_service to consume an exact activation proof idempotently', async () => {
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    const activationProof = await seedReadyActivation(queryRunner);

    await queryRunner.query('SET ROLE auth_service');
    try {
      const consume = (): Promise<unknown> =>
        queryRunner.query(
          `SELECT * FROM admin.consume_tenant_onboarding_activation($1, $2, 1, $3, $4, $5)`,
          [
            QUALIFIED_OPERATION,
            TENANT_ID,
            activationProof.sealToken,
            activationProof.evidenceRoot,
            activationProof.publicationDigest,
          ],
        );
      await expect(consume()).resolves.toEqual([
        {
          evidenceRoot: activationProof.evidenceRoot,
          publicationDigest: activationProof.publicationDigest,
        },
      ]);
      await expect(consume()).resolves.toEqual([
        {
          evidenceRoot: activationProof.evidenceRoot,
          publicationDigest: activationProof.publicationDigest,
        },
      ]);
    } finally {
      await queryRunner.query('RESET ROLE');
    }
    const consumedRows = (await queryRunner.query(
      `SELECT "onboardingActivationConsumedAt" AS consumed
         FROM admin.tenant_provisioning_runs WHERE id = $1`,
      [QUALIFIED_OPERATION],
    )) as Array<{ consumed: Date | null }>;
    expect(consumedRows[0]?.consumed).toBeInstanceOf(Date);
  });

  it('invalidates a minted activation seal when a late contradictory outcome arrives', async () => {
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    const activationProof = await seedReadyActivation(queryRunner);

    const contradictionRows = (await queryRunner.query(
      `SELECT admin.admit_tenant_onboarding_outcome(
         $1, $2, 1, 'farm-service', 'FAILED', 'late owner failure', now()
       ) AS disposition`,
      [QUALIFIED_OPERATION, TENANT_ID],
    )) as Array<{ disposition: string }>;
    expect(contradictionRows[0]?.disposition).toBe('SAFETY_FAILED');
    await expect(
      queryRunner.query(
        `SELECT * FROM admin.consume_tenant_onboarding_activation($1, $2, 1, $3, $4, $5)`,
        [
          QUALIFIED_OPERATION,
          TENANT_ID,
          activationProof.sealToken,
          activationProof.evidenceRoot,
          activationProof.publicationDigest,
        ],
      ),
    ).rejects.toThrow('stale, unsafe, or inconsistent');
  });

  it('linearizes the real PostgreSQL late-failure/auth-consume race with failure winning', async () => {
    if (!harness) throw new Error('PostgreSQL harness is unavailable');
    await installBaseline(queryRunner);
    await migrate(queryRunner);
    const activationProof = await seedReadyActivation(queryRunner);
    const failureRunner = harness.dataSource.createQueryRunner();
    const authRunner = harness.dataSource.createQueryRunner();
    await Promise.all([failureRunner.connect(), authRunner.connect()]);
    try {
      await failureRunner.startTransaction('SERIALIZABLE');
      const failureRows = (await failureRunner.query(
        `SELECT admin.admit_tenant_onboarding_outcome(
           $1, $2, 1, 'farm-service', 'FAILED', 'concurrent late failure', clock_timestamp()
         ) AS disposition`,
        [QUALIFIED_OPERATION, TENANT_ID],
      )) as Array<{ disposition: string }>;
      expect(failureRows[0]?.disposition).toBe('SAFETY_FAILED');

      await authRunner.startTransaction('SERIALIZABLE');
      const consumeResult = authRunner
        .query(`SELECT * FROM admin.consume_tenant_onboarding_activation($1, $2, 1, $3, $4, $5)`, [
          QUALIFIED_OPERATION,
          TENANT_ID,
          activationProof.sealToken,
          activationProof.evidenceRoot,
          activationProof.publicationDigest,
        ])
        .then(
          (rows: unknown) => ({ rows, error: null }),
          (error: unknown) => ({ rows: null, error }),
        );
      await new Promise<void>((resolve) => setTimeout(resolve, 25));
      await failureRunner.commitTransaction();

      const result = await consumeResult;
      expect(result.rows).toBeNull();
      expect(result.error).toBeInstanceOf(Error);
      expect((result.error as Error).message).toMatch(
        /stale, unsafe, or inconsistent|could not serialize access/,
      );
      await authRunner.rollbackTransaction();
    } finally {
      if (failureRunner.isTransactionActive) await failureRunner.rollbackTransaction();
      if (authRunner.isTransactionActive) await authRunner.rollbackTransaction();
      await Promise.all([failureRunner.release(), authRunner.release()]);
    }
  });
});
